🚀 2단계 - 문자열 계산기
next-step/kotlin-racingcar pull request #1018
Opened 2023-06-06 20:37 UTC by rladowl92

문자열 계산기 기능 추가했습니다.
(kotest로도 추가하고 싶었는데 어렵네요ㅠ)

2023-06-07 03:43 UTC, D000L requested changes
리뷰드린 부분 수정 후 "리뷰 요청" 주시면 확인 후 진행하도록 하겠습니다.~!

2023-06-07 03:43 UTC, D000L commented on src/test/kotlin/calculator/StringCalculatorTest.kt
> +    }
과제 요구사항에는 별도로 없는 내용이지만, 수식의 입력이 String 으로 열려있습니다.
그래서 `1    + 2 = 3` , `One + Two + NotNumber` 과 같은 케이스에 대한 예외처리도 한번 고민해보시면 좋을것 같습니다.

2023-06-07 03:43 UTC, D000L commented on src/main/kotlin/calculator/StringCalculator.kt
> +}
수식을 분석하는 함수와 계산하는 함수로 잘 분리해주셨습니다.

추가적으로 calculate 같은 경우 현재 요구사항에서는 외부에 노출될 필요가 없는 함수입니다.
`calculateFromString` 와 `calculate` 를 하나의 class or object 로 관리하는 형태로 변경해보시고, 외부에 불필요한 함수의 노출을 최소화 할 수 있도록 해보세요.

2023-06-07 03:43 UTC, D000L commented on src/main/kotlin/calculator/Operator.kt
> +            }
operator 와 비교를 위해서 when 부문을 사용하여 잘 정리해주셨습니다.

요구사항 상으로 4개의 연산자만 존재하지만, 더 많은 가상의 연산자가 존재한다면 when 으로 하나씩 처리하는 것은 보기 힘든 코드가 될 수 있습니다. `find` or `first` 와 같은 함수를 한번 사용해서 수정해보면 좋을 것 같습니다.

2023-06-07 03:43 UTC, D000L commented on src/main/kotlin/calculator/Operator.kt
> +                else -> throw IllegalArgumentException("Invalid operator: $operator")
값이 없는 경우 적절한 예외가 발생하고 있습니다. 

다만, 이 정보를 외부에서는 모르는 상태입니다.
`valueOf` 와 같이 kotlin 기본 함수들은 어떤 예외가 발생할지 다른 사람들도 인지한 상태에서 개발을 할 수 있지만, 새로 만들어주신 `valueOfString` 의 경우 어떤 예외가 발생할지 함수를 열어보지 않으면 알기 어렵습니다.

그래서 `@Throws` 등을 이용해 함수를 열지 않고도 예의를 확인할 수 있도록 하는것도 좋을 것 같습니다.

2023-06-07 03:43 UTC, D000L commented on src/test/kotlin/calculator/StringCalculatorTest.kt
> +        delimiter = '='
"/" 에 대한 추가적인 테스트가 필요해보입니다.
"5 / 2 = 2.5" 와 같은 소수점이 나오는 케이스에 대한 대응도 한번 추가해보세요.

2023-06-07 03:43 UTC, D000L commented on src/main/kotlin/calculator/StringCalculator.kt
> +            return operator.execute(answer, num2)
뒤에서 부터 계산해서 최종적인 결과를 내는 형식으로 보입니다.
다만, 이 과정을 위해서 copy 와 size 확인이 계속되고 있습니다. 

`1 + 2 + 3  + 4` 라는 수식이 있을 때,
`1 + 2` -> `3 + 3` -> `6 + 4` 순으로 계산할 수 있는 방법을 고민해보시면 좋을 것 같습니다.
( `fold` 와 `windowed`  같은 kotlin 함수가 있습니다. )

이 부분은 시간이 여유가 있다면 진행해주시고, 아니면 다른 코멘트만 확인 후 진행해주셔도 무방합니다.
( 그래도 고민은 한번.. )

2023-06-07 03:43 UTC, D000L commented on build.gradle.kts
> +    testImplementation("io.kotest", "kotest-framework-datatest", "5.5.0")
문법이 다를 뿐 kotest 도 junit 테스트와 크게 다르지 않습니다.

그래서 시간적 여유가 있다면 두 개 하는것도 추천드리지만, 
여유가 없다면 하나만 사용해서 여러 테스트케이스를 더 만들어 보는게 더 중요할 것 같습니다.

kotest 를 적용하실 예정이라면 테스트 패턴도 같이 적용해보시길 바랍니다.
대표적인 패턴으로 BDD 와 DCI 패턴이 있는데, kotest 에서는 해당 함수를 제공해주고 있어서 도움이 될겁니다.

https://johngrib.github.io/wiki/junit5-nested/
테스트 패턴중 dci 패턴에 대한 글입니다.

2023-06-07 03:43 UTC, D000L requested changes
리뷰드린 부분 수정 후 "리뷰 요청" 주시면 확인 후 진행하도록 하겠습니다.~!

2023-06-08 03:23 UTC, rladowl92 commented on src/main/kotlin/calculator/Operator.kt
> +                else -> throw IllegalArgumentException("Invalid operator: $operator")
valueOfString 뿐만 아니라 valueOfString을 사용하는 상위 함수들에서도 모두 throw가 발생할텐데요, 모두 @Throws를 표시해주는게 좋을까요? java의 throws를 생각하면 그게 맞는것같은데 코틀린의 경우 @Throws로 명시해주지 않아도 컴파일 과정에서 에러가 발생하지않으니 놓칠수도 있겠네요. java처럼 의무적으로 명시해주는게 좋은건지.. 코틀린에서는 어떤 기준으로 명시해주는게 좋을지 고민되네요.

2023-06-08 04:04 UTC, D000L commented on src/main/kotlin/calculator/Operator.kt
> +                else -> throw IllegalArgumentException("Invalid operator: $operator")
완벽한 기준은 없을거 같습니다. 
여기서는 상위함수는 `calculate` 가 되겠네요. `calculate` 에서 throw 에 대한 처리를 진행한다면 상위함수들 전부에 굳이 표시하지 않아도 될거 같습니다. 발생을 외부에서 알아야할 정도의 범위까지만 명시하는 정도면 충분할거라고 생각합니다.
아니면 orNull 과 같은 kotlin 스러운 접근법을 사용하는 것도 좋은 방법이 될것 같습니다.

2023-06-08 05:07 UTC, rladowl92 commented on src/main/kotlin/calculator/Operator.kt
> +                else -> throw IllegalArgumentException("Invalid operator: $operator")
여기서는 에러를 발생시키는게 목적이라 모두 표시해주는게 좋겠군요!
그런데 null을 리턴하는게 코틀린스러운 방법인가요?

2023-06-08 06:17 UTC, D000L commented on src/main/kotlin/calculator/Operator.kt
> +                else -> throw IllegalArgumentException("Invalid operator: $operator")
관점에 따라 다르겠지만, 저는 문제 발생시 에러를 던지는 것 보단 `null` 을 리턴하는 방식을 더 선호하고 있습니다.
( 개인적으로 오히려 kotlin 에서 예외가 필요한 함수에 @throws 와 같은 문법을 강제하지 않기 때문에 `null` 이 더 자연스럽게 느껴지는 것 같습니다. )

1. 예외를 발생시키는 경우
여러 곳에서 처리해야할 예외 사항 전달을 한곳에서 던질 수 있습니다. 에러에 대한 핸들링을 한곳에서 처리하는 형태를 많이 사용하는 서버같은 경우에는 하나의 예외에 대해 한번의 처리로 가능할 수 있지만, 안드로이드같은 클라이언트 입장에서는 에러에 대한 처리를 한곳에서 처리하기 힘든 구조를 가지고 있습니다. 그래서 만일을 대비한 try catch 문이 여러곳에서 사용되어야합니다.

2. null 을 발생시키는 경우
예외에 대한 처리는 사용하는 곳에서 신경쓰지 않아도 되지만, 대신 모든 사용하는 곳에서 null 에 대한 핸들링을 해야하는 문제가 있습니다. 화면에 노출하는 것이 중요한 클라이언트 입장에서는 예외를 던지는 것보단 `null` 이나 `Result.fail( ~ )` 같은 형태를 받는 것이 처리하기 용이합니다.

제가 안드로이드 쪽이다보니 기준도 안드로이드 기준의 생가이니 참고만 해주시면 좋을것 같습니다.

2023-06-08 06:36 UTC, rladowl92 commented on src/main/kotlin/calculator/Operator.kt
> +                else -> throw IllegalArgumentException("Invalid operator: $operator")
오오 안드는 그렇군요?!
저는 서버개발이라 null 보다는 에러코드로 응답해야하는 일이 많아서 throw로 넘기는 편입니다.
과제 요구사항에 맞춰 이번에는 throw로 구현해보겠습니다!
코틀린이 null 관리를 잘 할수있도록 만들어진것같던데,, 앞으로 과제하면서 잘 사용할수있도록 많은 지적 부탁드립니다ㅎㅎ

2023-06-08 13:10 UTC, rladowl92 commented on src/main/kotlin/calculator/StringCalculator.kt
> +            return operator.execute(answer, num2)
fold와 windowed를 활용해서 이것저것해보다가 결국 dropLast를 사용해서 수정했습니다ㅠ
그래도 말씀해주신덕에 두 함수 사용법은 익힐수있었네요!ㅎㅎ
코드를 읽는 순서는 역순이지만 실제 스택에서 실행되는 순서는 정방향이라 계산 결과는 동일합니다ㅎㅎ

2023-06-08 13:31 UTC, D000L approved these changes
전체적으로 리뷰 잘반영해주셨습니다.~!
다음 단계인 "자동차 경주" 진행 해주시면 되겠습니다.

2023-06-08 13:31 UTC, D000L commented on src/main/kotlin/calculator/Operator.kt
> +                throw IllegalArgumentException("Invalid operator: $operator")
first 사용해서 잘 수정해주셨습니다.~!

추가적으로 `firstOrNull` 과 elvis 연산자를 이용하면 try catch 없이도 동일한 동작이 가능합니다.
```
Operator.values().firstOrNull { it.operator == operator } 
    ?: throw IllegalArgumentException("Invalid operator: $operator")
```

2023-06-08 13:31 UTC, D000L commented on src/main/kotlin/calculator/StringCalculator.kt
> +            return operator.execute(answer, num2)
List 의 사용과 `dropLast` 통해서 잘 변경해주셨습니다.~!

`fold` 와 `windowed` 를 이용한 방법은 아래 코드 처럼 작성하실 수 있습니다.
```
val result = inputList.first().toDouble()

return inputList.drop(1)
    .windowed(2, 2)
    .fold(result) { acc, (operator, number) ->
        Operator.valueOfString(operator).execute(acc, number.toDouble())
    }
```

2023-06-08 13:32 UTC, merged