[step2] 문자열 계산기
next-step/kotlin-racingcar pull request #1022
Opened 2023-06-07 05:56 UTC by graygreat

안녕하세요 :)
첫 PR 올립니다.

일을 하면서 객체지향에 대한 많은 생각을 하지 못했는데,, 오랜만에 객체지향 생각하면서 짜니 쉽지 않네요.
리뷰 잘 부탁드립니다!

2023-06-08 12:46 UTC, Hyeon9mak requested changes
안녕하세요 준형님! 문자열 계산기 잘 구현해주셨어요.
간단한 코멘트 남겼으니 확인해주세요 😄 
궁금하신 점 코멘트, DM 남겨주세요.

2023-06-08 12:46 UTC, Hyeon9mak commented on build.gradle.kts
> +    testImplementation("io.kotest", "kotest-runner-junit5", "5.5.0")
5.5.0 버전을 선택하신 이유가 있을까요?

2023-06-08 12:46 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Input.kt
> +    }
- companion object 와 java static 의 차이는 무엇일까요?
- 싱글턴으로 모든 행위가 수행되므로, class 대신 object 로 만들어보아도 좋겠네요.

2023-06-08 12:46 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Operator.kt
> +    });
- enum, BiFunction 활용 👍 👍 사칙연산 기호와 로직을 확인할 땐 `Operator` 클래스만 열어보면 되겠네요.
- `symbol` 은 내부에서만 사용되므로 private 하게 숨겨줄 수 있겠네요.

2023-06-08 12:46 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Operator.kt
> +    }
자세한 예외 메세지도 전달해주면 어떨까요?

2023-06-08 12:46 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Operator.kt
> +    fun operate(op1: Int, op2: Int) = operation.apply(op1, op2)
보통 동반 객체보다 메서드를 더 위에 두는 것 같아요 😄

2023-06-08 12:46 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/TokenizedExpression.kt
> +}
class 와 data class 의 차이는 무엇일까요?

2023-06-08 12:46 UTC, Hyeon9mak commented on src/test/kotlin/step2/calculator/CalculatorTest.kt
> +    }
string spec 과 forAll 연산 활용 👍 👍

2023-06-08 12:46 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Calculator.kt
> +        }
`A` 와 같은 문자열이 전달되면 로직이 수행되지 못하겠네요 😱 
사용자에게 적합한 예외를 던져주면 좋겠어요.

2023-06-09 00:30 UTC, graygreat commented on build.gradle.kts
> +    testImplementation("io.kotest", "kotest-runner-junit5", "5.5.0")
라이브 세션할 때, 뭐가 안됐는데 (뭐가 뭐였는지 기억이 잘 안남) 5.5.0으로 버전을 바꾸면 된다고 했어서 바꿨었습니다.

2023-06-09 00:46 UTC, graygreat commented on src/main/kotlin/step2/calculator/Input.kt
> +    }
> companion object 와 java static 의 차이는 무엇일까요?
* companion object는 클래스가 메모리에 적재되면서 함께 생성되는 객체인데, static은 독립된 객체로 여길 수 없습니다.
* companion object는 이름을 지정할 수 있지만, static은 속한 클래스의 이름 사용합니다.
* companion object는 처음 접근될 때까지 초기화 되지 않지만 static은 클래스가 로드될 때 즉시 초기화 됩니다.

이 정도의 차이점을 알고 있는데, 혹시 더 중요한 것들이 있을까요?

2023-06-09 00:46 UTC, graygreat commented on src/main/kotlin/step2/calculator/Input.kt
> +    }
> 싱글턴으로 모든 행위가 수행되므로, class 대신 object 로 만들어보아도 좋겠네요.
오 그렇군요!
생각을 못하고 있었는데 감사합니다 :)

2023-06-09 00:49 UTC, graygreat commented on src/main/kotlin/step2/calculator/Operator.kt
> +    }
넵 수정해보겠습니다.

2023-06-09 00:52 UTC, graygreat commented on src/main/kotlin/step2/calculator/Operator.kt
> +    }
추가로 궁금한게, 메시지만 모아두는 클래스를 따로 만드는 것에 대해서 어떻게 생각하시나요?
다른 로직에서 사용하지 않을거라면 그냥 하드코딩으로 박아줘도 되지 않을까 싶은데, 현구님의 생각이 궁금합니다 :)

2023-06-09 00:53 UTC, graygreat commented on src/main/kotlin/step2/calculator/Operator.kt
> +    fun operate(op1: Int, op2: Int) = operation.apply(op1, op2)
이건 이유가 있는걸까요? 아니면 코틀린 개발자들의 암묵적인 컨벤션인가요 ㅎ

2023-06-09 00:59 UTC, graygreat commented on src/main/kotlin/step2/calculator/TokenizedExpression.kt
> +}
* data class는 일반적으로 불변이지만, class는 불변성에 대한 제약은 없습니다.
* data class는 equals, hashcode, toString, ...이 포함됩니다. (보일러플레이트 코드를 줄여주는 효과?)

2023-06-09 01:05 UTC, graygreat commented on src/main/kotlin/step2/calculator/Calculator.kt
> +        }
숫자 이외에 값에 대해서는 **사칙 연산 기호로 판단**하려고 했습니다.
A가 들어오게 되면 숫자는 아니니 사칙 연산 기호 검증으로 넘어갈테고, 사칙연산 기호가 아니니 그에 따른 예외가 발생하는 구조로 만들었습니다.

혹시 좋지 않은 방법일까요?

2023-06-09 01:07 UTC, graygreat commented
@Hyeon9mak 
안녕하세요 :)

리뷰 받은거 바탕으로 수정 해놓았습니다!
감사합니다!

2023-06-09 23:02 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Input.kt
> +    }
충분히 알고 사용해주신 것 같습니다 👍
추가로 아래와 같은 내용도 있으니 참고해보시면 재밌을 것 같습니다 😄  
https://www.bsidesoft.com/8187

2023-06-09 23:06 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Operator.kt
> +    }
저는 보통 좋다 나쁘다의 기준을 유지보수 상황, 장면을 상상하면서 결정하는데요.
가령 "문자열을 이용한 연산자 선택 정책을 수정해주세요." 라는 요구사항이 더 많을지
"에러 메세지가 전반적으로 마음에 들지 않아요. 모두 수정해주세요." 라는 요구사항이 많을지 고민해봅니다.

전자라면 각 기능별 클래스 파일에 하드코딩 해두는 것이 유리할테고
후자라면 메세지만 모아두는 별개 클래스를 생성해두는 것이 유리하겠네요.
(유지보수 시에 하나의 클래스파일만 열어보기 위함 - 단일 책임 원칙)

2023-06-09 23:06 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Operator.kt
> +    fun operate(op1: Int, op2: Int) = operation.apply(op1, op2)
후자입니다 ㅎㅎㅎ

2023-06-09 23:07 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Operator.kt
> +    fun operate(op1: Int, op2: Int) = operation.apply(op1, op2)
간혹 equals, hash code 와 같은 오버라이드 메서드는 가독성을 위해 동반 객체보다 아래에 두기도 하는 것 같더라구요.

2023-06-09 23:11 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/TokenizedExpression.kt
> +}
엇, data class 역시도 불변에 대한 제약이 존재하지 않습니다.

```kotlin
data class GrayGreat(
  var variable: String,
  val value: String,
) {
  fun updateVariable(variable: String) {
    this.variable = variable
  }
}
```

말씀해주신 두번째 차이점이 더욱 와닿겠네요 😄 
또한 상속이나 추상화가 불가능하고, 생성자에 프로퍼티가 1개 이상이어야한다는 제약이 있습니다 👍

2023-06-09 23:14 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Calculator.kt
> +        }
오~! 그렇게 연결되어서 검증이 진행되는군요. 제가 더 자세히 파악했어야했는데.. 😢 🙏 
동작은 충분히 잘 돌아갈 것 같아요!
사실 `try-catch` 절에 `NumberFormationException` 가 사용되어 자연스럽게
'문자열에 대한 검증은 진행해주지 않는걸까?' 라는 생각을 했어요.

2023-06-09 23:18 UTC, Hyeon9mak approved these changes
안녕하세요 준형님
피드백 빠르게 잘 반영해주셨습니다 👍 
아주 간단한 코멘트 2개 남겼으니 확인해주세요 😄 
다음 단계도 화이팅입니다 💪

2023-06-09 23:18 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/Input.kt
> +}
kotlin 에서는 `Scanner` 없이 `readln()` 만으로도 입력을 전달받을 수 있습니다 후후..

2023-06-09 23:18 UTC, Hyeon9mak commented on src/main/kotlin/step2/calculator/TokenizedExpression.kt
> +}
아-! 다음 단계 진행에 앞서 data class 이야기를 해보고 싶어서 남겨둔 코멘트이니, `TokenizedExpression` 에 반영하실 필요는 없습니다 🙇‍♂️

2023-06-09 23:18 UTC, merged

2023-06-10 01:06 UTC, graygreat commented on src/main/kotlin/step2/calculator/Input.kt
> +}
오 그렇군요!! 
다음 미션때 사용해보겠습니다 ㅎㅎ 감사합니다 :)