🚀 2단계 - 문자열 계산기
next-step/kotlin-racingcar pull request #1037
Opened 2023-06-07 14:11 UTC by sksskaw

얼마나 정교한 계산기를 구현해야 할지 고민했어요

두자리 수 이상 숫자도 처리되어야 하는가?  O
실수도 계산이 되어야 하는가? ex) "1.5 * 2.6"  X
나눗셈의 결과는 실수로 처리되어야 하는가?  X 몫으로 처리 ex) "10 / 3" -> 3

2023-06-08 11:17 UTC, pci2676 requested changes
안녕하세요! 빠르게 구현해 주셨네요! 👍 

> 얼마나 정교한 계산기를 구현해야 할지 고민했어요

그런데 위와 같은 고민을 하셨다면 구현하고자하는 요구사항을 README.md를 생성해서 정리해보시는 건 어떨까요?(비단 이번 미션뿐 아니라 앞으로의 미션도요!) 구현하는 입장에서도 그리고 코드리뷰를 하는 입장에서도 조금 더 이루고자하는 바를 명확히 알 수 있을것 같습니다! 😵‍💫 여러가지 케이스에 대해 태훈님이 생각하시는 결과를 적어주시면 좋을것 같습니다.

그리고 git commit을 조금 더 세세하게 나눠 보시는건 어떨까요?
위에 말씀드렸던 README에 적어두었을 기능 요구사항과 그 결과에 대한 commit이 될 수 도 있을것 같습니다!

그리고 참여하신 교육이 TDD에 중점을 두고있는 만큼
실패하는 테스트 -> 성공하는 구현 -> 리팩터링 의 과정을 커밋으로 나타내 주시면 저도 태훈님이 코드를 작성하면서 생각하셨던 부분을 조금 더 쉽게 따라갈 수 있을 것 같습니다!

이외의 내용은 코멘트로 달아두었습니다!
확인해주시고 수정하신 다음 다시 리뷰요청 부탁드릴게요! 😃

2023-06-08 11:17 UTC, pci2676 commented on src/test/kotlin/StringCalculate.kt
> +class StringCalculate {
이 클래스를 비롯해 `CharType`, `Operator` 모두 우리가 요구사항을 충족해야하는 제품이고  
테스트하고자 하는 대상이니 main에 위치하는게 좋을것 같아 보입니다!

2023-06-08 11:17 UTC, pci2676 commented on src/test/kotlin/StringCalculate.kt
> +        var y = ""
x, y라는 이름대신 조금 더 명확한 의미를 가질 수 있는 변수명을 사용하는건 어떨까요?

2023-06-08 11:17 UTC, pci2676 commented on src/test/kotlin/StringCalculateTest.kt
> +    }
여러가지 케이스에 대한 테스트를 잘 작성해 주셧네요! 👍   
이 부분을 비롯해 다른 부분들도 묶을 수 있는 부분은  
`@CsvSoure`를 이용해 보는것도 좋을것 같습니다!

2023-06-08 11:17 UTC, pci2676 commented on src/test/kotlin/StringCalculate.kt
> +    fun calculate(input: String?): Int {
StringCalculate calculate가 너무 많은 책임을 가지고 있습니다!  
StringCalculate 클래스는 calculate를 통해 가장 추상적인 식을 계산한다라는 책임만 가지고 식을 **어떻게 분리**하고, **어떻게 연산**하는 등의 **구체적인 책임**은 다른 객체로 분리해 봅시다!

private 함수로 도출하신 부분은 전부 다른 객체에게 책임을 넘길수 있을 것 같아요!

지금은 프로그래밍 요구사항인 `메서드가 너무 많은 일을 하지 않도록 분리하기 위해 노력해 본다.`에서 조금 벗어나 보입니다!

2023-06-08 15:37 UTC, sksskaw commented on src/test/kotlin/StringCalculate.kt
> +    fun calculate(input: String?): Int {
이 부분에 문제가 있다는 것은 인지하고 있는데 어떻게 분리하고 책임을 나눠야 할지 어려웠습니다.
단순히 함수로 로직을 숨기는 것이 아닌 변화에 유연한 설계가 떠오르지 않습니다.

혹시 이 로직에 적용할 수 있는 참고할 만한 디자인 패턴이나 설계가 있을까요?

2023-06-08 16:05 UTC, pci2676 commented on src/test/kotlin/StringCalculate.kt
> +    fun calculate(input: String?): Int {
calculate 함수입장에서 내부의 식이 어떻게 분리되는지 관심이 없을것 같습니다.
다른 객체에게 식의 구성요소를 하나씩 전달하면서 묻도록 해보는건 어떨까요?
'연산자인가? 피 연산자인가?'
그러면 메세지를 받은 객체는 그 대답으로 '연산자 +이다.' 혹은 '피 연산자 1'이다. 와 같은 대답을 하도록 해보시면 좋을것 같습니다.
when절이 개선할 수 있는 부분이 될 수 있을것 같습니다.
디자인 패턴을 굳이 꼽아보면 저는 전략패턴이 생각나네요.

그리고 식을 분리하는 것 뿐 아니라 
분리가 된 연산자와 피 연산자의 집합에 대한 연산은 또 다른 객체에게 넘겨주는것도 좋을 것 같습니다!

> 인지하고 있는데 어떻게 분리하고 책임을 나눠야 할지 어려웠습니다

이 부분은 저도 어렵다고 생각하는데요. 
저의 의견이 조금이나마 도움이 됐으면 좋겠네요. 
잘 이해가 되지 않으시면 지금은 흘려들으셔도 좋을것 같습니다.

책임의 구현에는 추상적인 수준이 존재한다고 생각합니다. 
그리고 이 구현의 추상적인 수준은 동등하게 맞춰주는것이 좋은것 같습니다.

그래서 이름이 굉장히 중요하다고 생각합니다.
예를들어 지금 StringCalculate의 이름에서 알 수 있듯 이 객체는 입력된 식에대한 계산이라는 책임을 가지고 있다고 생각할 수 있을것 같습니다.

입력된 식을 계산한다는 책임을 사용자 입장에서 바라보겠습니다.

계산을 하기 위한 과정은 아래와 같이 분리해 볼 수 있을것 같습니다.
1. 계산 식을 입력받는다.
2. 식을 연산자와 피 연산자로 구분한다.
3. 연산자와 피 연산자를 이용하여 연산을 수행한다.
4. 계산 된 결과 값을 전달한다.

이때 사용자는 1번 계산 식을 입력하고 4번 계산 된 결과 값을 받을 뿐 입니다.
개인적으로 우리가 TV 리모콘 버튼을 누를때 채널이 바뀌기를 기대할 뿐 리모콘의 회로가 어떻게 동작하는데는 관심을 두지 않는것 처럼
사용자는 2번 식을 어떠한 분리하고 3번 분리된 식을 어떠한 연산하는 세부사항에 대해서는 관심이 없다고 생각할 것 같습니다.

그렇다면 1번 4번은 좀 더 높은(추상적인) 수준의 책임이고
2번 3번은 더 낮은(구체적인, 사용자 입장에서 혹은 1번 4번 입장에서 덜 추상적인) 수준의 책임이라고 볼 수 있을것 같습니다.

그렇다면 1번 4번과 2번 3번이 같은 곳에서 구현되는것보다 분리되는 것이 좋을것 같습니다.
이렇게 분리되어야 한다면 서로 다른 객체에 위치하는 것이 테스트하기도 더 좋을것 같네요.

저는 위와 같은 일련의 흐름대로 책임을 분리하고 설계를 하는 편 입니다.
도움이 됐을지 모르겠네요.

이야기 하고 싶은 부분이 있으시다면 언제든 말씀주셔도 좋고 DM을 주셔도 좋습니다.

2023-06-10 10:14 UTC, pci2676 requested changes
안녕하세요 태훈님 코드리뷰 작성해주신것 잘 확인했습니다.

더 개선하면 좋을 것 같은 부분에 코드리뷰 남겨두었습니다.

이번 미션을 끝내지않고 계속해서 개선하실지 
다음 미션으로 넘어가실지에 대해 DM으로 문의드렸으니 확인 부탁드리겠습니다.

2023-06-10 10:14 UTC, pci2676 commented on src/test/kotlin/StringCalculate.kt
> +enum class Operator(val operator: Char) {
앗 제가 test 패키지가 아닌 main으로 옮기는게 좋을것 같다고 말한것은 패키지였습니다 😅

2023-06-10 10:14 UTC, pci2676 commented on README.md
> +나눗셈("/")의 경우 몫으로 처리한다._ ex) "10 / 3" -> 3
👍

2023-06-10 10:14 UTC, pci2676 commented on src/test/kotlin/StringCalculatorScanner.kt
> +                operate()
scan이라는 행위 내부에 계산을 하는 행위가 있는게 저는 어색해보입니다.
scan이름에 걸맞는 행위만 해주는건 어떨까요?

2023-06-10 10:14 UTC, pci2676 commented on src/test/kotlin/StringCalculatorScanner.kt
> +    }
`StringCalculatorScanner`라는 이름을 보고 계산까지 할거라는 예상을 하기 어려울 수 있을것 같습니다.

`scan()`의 결과를 멤버변수로 가지고 있는 새로운 객체에서 `operate()`를 해주면 어떨까요?

지금 상태에서는 각 메서드를 테스트를 하기위해 설정해야하는 멤버변수 값이 무엇인지 추측하기 어려울것 같습니다.

scanner는 scan을 하고 만들어진 operand와 operator의 집합체를 반환하면 그 집합체를 멤버변수로 가지고 있는 객체에서 operate해주면 더 좋을것 같습니다.

2023-06-10 10:14 UTC, pci2676 commented on src/test/kotlin/StringCalculator.kt
> +        input.forEach { c -> stringCalculatorScanner.scan(c) }
Char를 사용하것보다 String을 그대로 사용하는게 조금 더 간결하게 코드를 작성하는 방법이 될 수 있을것 같습니다.
숫자가 연속으로 들어오는경우에 대해 char를 이어붙이는 작업도 필요없어질 것 같습니다.

String의 split 메서드를 이용해서 개선해보는걸 고려해보시면 좋을것 같습니다.

2023-06-10 10:14 UTC, pci2676 commented on src/test/kotlin/StringCalculatorScanner.kt
> +    private var operateResult: Int = 0
모든상황에 그런것은 아니지만 가변적인 상태는 코드를 추적하기 힘들게 됩니다.

하지만 지금은 scan과 operate가 계속해서 상태를 변경하면서 추적하기 힘들어지는것 같습니다.

역할과 책임을 조금 더 나누어 보시는게 좋을것 같습니다.

2023-06-10 10:14 UTC, pci2676 commented on src/test/kotlin/StringCalculatorScanner.kt
> +        if (firstOperand != "" && secondOperand != "") {
`firstOperand != ""`는 `firstOperand.isBlank()`로 간결하게 표현할 수 있도록 코틀린이 함수를 제공하고있습니다!

참고해주시면 좋을 것 같습니다.

2023-06-10 10:14 UTC, pci2676 commented on src/test/kotlin/Operation.kt
> +                Operator.DIVISION -> this.div(x, y)
enum을 이용하면 조금 더 세련되게 표현할 수 있을것 같습니다.

아래 글을 참고해보시면 좋을것 같습니다.

https://techblog.woowahan.com/2527/

2023-06-10 10:14 UTC, pci2676 commented on src/test/kotlin/CharTypeProcessStrategy.kt
> +        scanner.operate()
메서드에 전달된 매개변수가 메서드내에서 상태가 변경되는것은 코드의 추적을 방해하게 되는 요소가 될 수 있습니다.

가능하다면 메서드에 전달 된 매개변수를 메서드 내에서 변경하지 않도록 설계해보시는건 어떨까요?

2023-06-10 10:14 UTC, pci2676 commented on src/test/kotlin/Operation.kt
> +class Operation {
이 클래스뿐 아니라 몇몇 클래스에 대한 단위테스트가 없는것 같아보이네요 😅

2023-06-10 13:42 UTC, pci2676 approved these changes
계산기 구현하느라 고생하셨습니다

이번에 남겨둔 코드리뷰는 다음 미션을 진행하면서 고려해주세요!

머지하겠습니다!

2023-06-10 13:42 UTC, merged