Step2 문자열 계산기
next-step/kotlin-racingcar pull request #1060
Opened 2023-06-08 12:48 UTC by Wordbe

2023-06-09 16:12 UTC, Rok93 requested changes
성호님 개인적인 사정으로 리뷰가 조금 늦었습니다 😅. 
문자열 계산기 깔끔하게 잘 구현해주셨네요! 👍👍👍
지금도 충분히 잘 구현해주셨다고 생각하지만 조금 짚고 넘어가면 좋을 것 같은 부분들이 보여서 코멘트 달아두었습니다. 😃
이 부분 참고해서 반영해주시면 좋을 것 같습니다. 🙏
피드백 받은 내용 중, 이해가 안되거나 어려운 부분이 있으면 언제든지 DM 주세요! 😊 

추가적으로 다음 단계부터는 README.md에 `기능구현 목록표`를 만들어서 기능구현 목록표에 기록한 기능 단위로 커밋을 쪼개보면 어떨까요? 😃

2023-06-09 16:12 UTC, Rok93 commented on build.gradle.kts
> +    testImplementation("io.kotest", "kotest-runner-junit5", "5.5.0")
Kotest 라이브러리를 5.5.0 버전으로 변경하셨네요! 
혹시 변경하신 이유가 있으실까요? 😃

2023-06-09 16:12 UTC, Rok93 commented on build.gradle.kts
> +    testImplementation("io.kotest", "kotest-runner-junit5", "5.5.0")
Kotest 5.5.0에서는 [테스트코드가 스킵되는 버그](https://kotest.io/docs/changelog.html#551-october-2022)가 있었던 것으로 파악돼요. 
5.5.1 버전으로 변경해보면 어떨까요? 😃 

![image](https://github.com/next-step/kotlin-racingcar/assets/47850258/f7e06dd2-79bb-46d5-9949-09d9d9acfa80)


![image](https://github.com/next-step/kotlin-racingcar/assets/47850258/3a9dbcc3-0f45-4966-b28e-ac535d269c6f)

2023-06-09 16:12 UTC, Rok93 commented on src/test/kotlin/calculator/CalculatorTest.kt
> +        forAll(
Kotest의 `Property Test Functions` 잘 활용해주셨네요! 👍👍

바로 위의 Test Case(**사칙연산 기호가 아니면 예외 발생**)도 동일한 방식으로 사칙연산 기호가 아닌 케이스에 대해서 테스트를 작성해볼 수 있지 않을까요?

2023-06-09 16:12 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +            else -> throw IllegalArgumentException("사칙연산 기호가 올바르지 않습니다.")
예외가 발생한 경우, 에러메시지에 `사칙연산 기호로 어떤 값이 들어왔는지` 확인할 수 있으면 좋지않을까요? 🤔

2023-06-09 16:12 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +    fun calculate(input: String): Int {
input 이라는 파라미터 네이밍보다 조금 더 의미있는 네이밍은 없을까요? 🤔
`수식`, `표현식`과 같은 의미를 드러낼 수 있는 네이밍으로 변경해보면 어떨까요? 😃

2023-06-09 16:12 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +            throw IllegalArgumentException("입력값이 공백입니다.")
수식이 공백인 경우에 대해서 예외처리 잘 해주셨네요! 🤩👍

Kotlin에서 제공하는 [require](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require.html), [check](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/check.html) 함수를 활용해서 아래와 같이 더 간단하게 변경해볼 수 있을 것 같아요. 😃
```suggestion
            require(input.isNotBlank()) { "입력값이 공백입니다." }
```

2023-06-09 16:12 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +    private fun operate(operand1: Int, operator: String, operand2: Int): Int {
연산의 기능을 적절하게 메서드로 잘 쪼개셨네요. 👍
조금 더 나아가서 `연산자`를 **객체**로 만들어서 `연산을 수행하는 역할`을 수행하도록하면 변경해보면 어떨까요? 🤔

2023-06-09 16:12 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +            "/" -> operand1 / operand2
나눗셈 연산의 경우 `operand2`가 `0`이면 어떤 문제가 발생할까요?  👀

2023-06-09 16:12 UTC, Rok93 commented on src/test/kotlin/calculator/CalculatorTest.kt
> +        Calculator().calculate("1 + 2") shouldBe 3
테스트 케이스를 보면서 느낀건데, Calcualtor 객체가 상태를 가지고있지 않는 것 같아요. 🤔
이런 경우에는 굳이 Calcualtor를 객체로 관리해야하나? 라는 의문이 드는데, 성호님은 어떻게 생각하시나요? 😃

혹시나 저의 생각과 비슷하게 생각하신다면, Calculator를 [object](https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview) 키워드로 변경해보면 어떨까요?  👀

Calcualtor를 `class`로 선언할 때와 `object`로 선언했을 때의 차이점은 무엇인지 이번 기회에 같이 알아가면 좋을 것 같아요. 😃

2023-06-09 16:12 UTC, Rok93 commented on src/test/kotlin/calculator/CalculatorTest.kt
> +            }
람다 파라미터가 1개뿐이라면 **파라미터명을 직접 명시할 필요 없이** `it`으로 사용할 수 있어요! 😁

```suggestion
        ) {
            val exception = shouldThrow<IllegalArgumentException> {
                Calculator().calculate(it)
            }
```

2023-06-09 16:12 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +        for (i in 1 until parts.size step 2) {
다른 사람이 이 코드를 보게됐을 때, 0, 2와 같은 수가 어떤 값을 의미하는지 알 수 있을까요? 🤔
[이 글](https://javabom.tistory.com/28)을 참고해보시고 조금 더 의미를 명확하게 전달할 수 있도록 변경해보면 어떨까요? 😊

2023-06-10 06:18 UTC, Wordbe commented on build.gradle.kts
> +    testImplementation("io.kotest", "kotest-runner-junit5", "5.5.0")
실행되지 않는 버그가 있어서 버전업을 했습니다. 정보감사합니다. 5.5.1 반영했습니다 😀

2023-06-10 06:39 UTC, Wordbe commented on src/test/kotlin/calculator/CalculatorTest.kt
> +        forAll(
property test functions 여러 개 테스트 진행해보았습니다. 😀

2023-06-10 06:45 UTC, Wordbe commented on src/main/kotlin/calculator/Calculator.kt
> +            else -> throw IllegalArgumentException("사칙연산 기호가 올바르지 않습니다.")
그렇네요 추가했습니다 😄

2023-06-10 06:46 UTC, Wordbe commented on src/main/kotlin/calculator/Calculator.kt
> +    fun calculate(input: String): Int {
expression 변경해보았습니다 😀

2023-06-10 06:52 UTC, Wordbe commented on src/main/kotlin/calculator/Calculator.kt
> +            throw IllegalArgumentException("입력값이 공백입니다.")
더 깔끔해졌네요 유용한 구문 감사합니다 😀

2023-06-10 06:55 UTC, Wordbe commented on src/main/kotlin/calculator/Calculator.kt
> +            "/" -> operand1 / operand2
예외가 발생하네요. 
java.lang.ArithmeticException: / by zero 
예외 처리 하겠습니다 😀

2023-06-10 07:08 UTC, Wordbe commented on src/test/kotlin/calculator/CalculatorTest.kt
> +        Calculator().calculate("1 + 2") shouldBe 3
네 저도 만들면서 그렇게 느꼈습니다. 
굳이 입력값을 필드에 저장할 필요도 없을 것 같구요.
object 로 변경해서 싱글톤 객체로 만들면 좋을 것 같습니다. 😀

2023-06-10 07:15 UTC, Wordbe commented on src/test/kotlin/calculator/CalculatorTest.kt
> +            }
이 부분은 가독성 측면에서 호불호가 좀 생기는 것 같은데, 
선생님은 혹시 항상 it 을 사용하시는 것을 선호하시나요?
저는 상황별로 반반 섞어 사용하는 것 같습니다. 파라미터 변수로 명시하면 1줄 더 생겨서 길어보이지만 읽기는 편하더라구요.
일단 여기서는 단순해서 괜찮을 것 같으니 말씀하신 의견에 따라 it 으로 고쳐볼게요 😊

2023-06-10 07:21 UTC, Wordbe commented on src/main/kotlin/calculator/Calculator.kt
> +        for (i in 1 until parts.size step 2) {
상수로 선언했습니다 감사합니다 😀

2023-06-10 08:07 UTC, Wordbe commented on src/main/kotlin/calculator/Calculator.kt
> +    private fun operate(operand1: Int, operator: String, operand2: Int): Int {
Operator 객체로 분리해서 역할 수행하도록했습니다 😀

2023-06-11 04:16 UTC, Rok93 commented on src/test/kotlin/calculator/CalculatorTest.kt
> +            }
저 같은 경우에는 it을 많이 사용하고있어요. 😊 
가독성 측면 때문에 걱정했던 시기도있으나... 자주 쓰다보니 코드를 읽는데도 그렇게 버벅임 없이 잘 읽혀지더라구요. 🤔 
물론 이 경우도 다른 변수명을 잘 지은 경우에 잘 읽히는거지 앞에서부터 변수명의 의미가 불명확하다면 `it`은 더큰 혼란을 가져오더라구요. 😅

예를들어,  상품 리스트를 **products**로 지정했다면. `products.forEach { /* it */ }` 이라고 뒀다면  it이 products의 한 상품인 `product`를 의미하겠구나하고 빠르게 추측이되는데,  **productBundle**(bundle은 묶음을 의미)로 지정했다면 `products.forEach { /* it */ }`에서 it의 의미가 빨리 파악되지 않을 것 같아요.

추가적으로 여러개의 람다식을 연달아 사용하는 경우에는 `it`을 지양하는 편이고(아마 IntelliJ가 it이 무엇을 지칭하는지 몰라서 그렇게 못쓴쓰지말라고했던걸로 기억해요 😁),

2023-06-11 05:18 UTC, Rok93 approved these changes
성호님 피드백 잘 반영해주셨네요! 👍👍👍
2단계는 이정도면 충분히 잘 구현해주신 것 같아서, 이만 머지하겠습니다. 😁
몇몇 코멘트도 달아두었는데, 확인해주시고 다음 단계 진행하시면서 같이 반영해주시면 될 것 같습니다. 🙏

이제 본격적으로 자동차 미션 진행해보시죠!! 🏎🚀

2023-06-11 05:18 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +        val parts = expression.split(" ")
`" "` 또한 매직넘버를 처리했던 것처럼 상수로 추출해볼 수 있을 것 같아요. 😊

2023-06-11 05:18 UTC, Rok93 commented on src/main/kotlin/calculator/Operator.kt
> +                }
아래와 같이 `find` 함수를 사용하는 코드로 변경해보면 어떨까요? 
```suggestion
            return values().find { it.symbol == symbol } 
                ?: throw IllegalArgumentException("사칙연산 기호가 올바르지 않습니다. : $symbol")
```

2023-06-11 05:18 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +    private const val OPERATION_UNIT = 2
코틀린 코드 컨벤션에 따르면 [상수 선언](https://kotlinlang.org/docs/coding-conventions.html#property-names)의 경우 `top-level property`로 지정해보면 어떨까요? 

```suggestion
private const val FIRST_OPERAND_INDEX = 0
private const val FIRST_OPERATOR_INDEX = 1
private const val OPERATION_UNIT = 2
    
object Calculator {
```

2023-06-11 05:19 UTC, merged

2023-06-11 12:16 UTC, Wordbe commented on src/test/kotlin/calculator/CalculatorTest.kt
> +            }
답변이 유용하고 도움이 되네요 감사합니다. 😄

2023-06-11 12:26 UTC, Wordbe commented on src/main/kotlin/calculator/Calculator.kt
> +    private const val OPERATION_UNIT = 2
첨부해주신 링크의 네이밍 규칙에 의하면
불변값을 담은 object 의 val 프로퍼티도 SCREAMING_SNAKE_CASE 로 쓸 수 있는 것 같은데요.
그래서 현재처럼 사용해도 무방하다고 생각이 듭니다.
어떤 점 때문에 top-level 로 옮겼으면 좋겠다고 생각하시는지 질문드립니다

또한 해당 상수들이 Calculator 라는 객체와만 관련있는 것 같아서 안에다 명시하면 좋을 것 같다는 생각인데 어떻게 생각하시는지 궁금합니다.

2023-06-11 12:26 UTC, Wordbe commented on src/main/kotlin/calculator/Operator.kt
> +                }
유용한 메소드네요
적용했습니다 감사합니다 😀

2023-06-12 06:34 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +    private const val OPERATION_UNIT = 2
제가 `top-level object val properties`라는 표현에서 **object val properties**의 의미를 조금 잘못 이해했던 것 같아요. 🤔
object 의 val property가 지금 성호님이 작성하신 코드의 형태와 동일했군요? (사실 object 잘 안쓰는편이라 생각보다 낯서네요😅) 

> Calculator 라는 객체와만 관련있는 것 같아서 안에다 명시하면 좋을 것 같다는 생각인데 어떻게 생각하시는지 궁금합니다.

위와 같은 생각을 가지신거라면 저는 `companion object` block 안에서, const val(const를 쓸 수 없는 자료형이라면 그냥 val)로 상수를 선언하여, `Calculator.상수명` 이런 형태로 쓰고있어요!  

성호님과 이렇게 소통하다보니 사실상 `object의 val 프로퍼티`랑 `companion object val 프로퍼티(?)`랑 모양새도 그렇고 쓰임새도 그렇고 사실상 거의 동일하다는 생각이드네요. 😃

2023-06-12 08:29 UTC, Wordbe commented on src/main/kotlin/calculator/Calculator.kt
> +        val parts = expression.split(" ")
상수로 추출했습니다 😀