Step3 - 자동차 경주
next-step/kotlin-racingcar pull request #1082
Opened 2023-06-09 12:36 UTC by sjjeong

저번 [pr](https://github.com/next-step/kotlin-racingcar/pull/1010)에서 리뷰 반영했습니다.

이번에 자동차 경주 구현을 했는데 테스트코드를 어떻게 해야할 지 감이 안와서 구현을 못했습니다.

2023-06-10 12:19 UTC, ddaaac requested changes
안녕하세요 석준님 👋 

구현 깔끔하게 잘 해주셨네요!

몇 가지 코멘트 남겼으니 확인해주세요~

2023-06-10 12:19 UTC, ddaaac commented on src/test/kotlin/study/step3/CarRacingGameApplicationTest.kt
> +            assertThat(Car().canMove(rpm)).isEqualTo(expected)
move를 테스트하기 어려워서 canMove를 public으로 바꾸고 테스트 코드를 작성해주신 것 같네요!

지금 구조에서 테스트가 어렵다면 랜덤을 생성하는 부분을 Car 밖으로 분리해보는 건 어떨까요?
rpm을 파라미터로 받는 대신 랜덤을 생성해주는 Engine을 파라미터로 받을 수 있을 것 같아요 :)

2023-06-10 12:19 UTC, ddaaac commented on src/main/kotlin/study/step3/CarRacingGameApplication.kt
> +            resultView(scoreboard)
개인적으로는 이렇게 scope로 묶으면 현재 클래스의 함수와 컨텍스트 객체의 함수가 구분이 안돼서 선호하지 않는 편입니다.
석준님의 생각은 어떠신가요?

2023-06-10 12:19 UTC, ddaaac commented on src/main/kotlin/study/step3/CarRacingGameApplication.kt
> +        }
코틀린은 다양한 [리스트 초기화](https://www.baeldung.com/kotlin/initialize-list) 방식을 제공합니다. 여러 가지 방법을 학습해보셔도 좋을 것 같네요 😄

2023-06-10 12:19 UTC, ddaaac commented on src/main/kotlin/study/step3/io/Input.kt
> +        readLine()?.toIntOrNull()?.let(callback)
이전에 말씀드린 코멘트처럼 코틀린의 xx 라는 네이밍을 가진 함수들은 예외를 반환할 때 xxOrNull과 같은 네이밍을 사용합니다.
readLine은 초기에 설계된 함수이기 때문에 이 규칙을 지키지 않았고 코틀린 1.6부터는 `readln` `readlnOrNull`이 추가되었습니다. 동작엔 문제가 없지만 새로 추가된 이 두 함수 중 하나를 사용해보시는 것도 좋을 것 같네요 :)

2023-06-10 12:19 UTC, ddaaac commented on src/main/kotlin/study/step3/Scoreboard.kt
> +            toString().dropLast(1)
자바에서는 성능과 효율 때문에 가독성을 희생하더라도 StringBuilder를 사용해야했다면 코틀린에는 [String template](https://kotlinlang.org/docs/strings.html#string-templates)이 존재합니다.
이를 [java code로 변환해서 확인](https://medium.com/@mydogtom/tip-how-to-show-java-equivalent-for-kotlin-code-f7c81d76fa8)해보시면 내부적으로 StirngBuilder로 변환하는 것을 확인하실 수 있을 거에요.

2023-06-13 11:08 UTC, sjjeong commented on src/test/kotlin/study/step3/CarRacingGameApplicationTest.kt
> +            assertThat(Car().canMove(rpm)).isEqualTo(expected)
뭔가 move할 때 마다 Engine을 받는게 조금 어색해요
자동차가 움직일 때마다 Engine을 받는게 아니라 자동차를 만들 때 Engine이 존재해야 하는게 아닌가 싶어요

혹시 좋은 예제가 있다면 소개해주세요

2023-06-13 11:18 UTC, sjjeong commented on src/main/kotlin/study/step3/Scoreboard.kt
> +            toString().dropLast(1)
제가 간단하게 테스트 해보니까 String template는 StringBuilder로 변환되서 사용되는게 맞는 것 같습니다.
그런데 이렇게 복잡한 구조에서 String template으로는 오히려 가독성이 안좋아질 것으로 생각되는데 어떻게 생각하시는지 궁금합니다.

2023-06-13 11:19 UTC, sjjeong commented on src/main/kotlin/study/step3/CarRacingGameApplication.kt
> +            resultView(scoreboard)
안드로이드에서는 보통 view의 초기화 같은 경우 이런 패턴으로 많이 사용했습니다.

with 제거하고 직접 호출하도록 변경 했습니다.
5c1588bba8901ba98e1af3b908cf411e52e37faf

2023-06-13 11:19 UTC, sjjeong commented on src/main/kotlin/study/step3/CarRacingGameApplication.kt
> +            resultView(scoreboard)
안드로이드에서는 보통 view의 초기화 같은 경우 이런 패턴으로 많이 사용했습니다.

with 제거하고 직접 호출하도록 변경 했습니다.
5c1588bba8901ba98e1af3b908cf411e52e37faf

2023-06-13 11:19 UTC, sjjeong commented on src/main/kotlin/study/step3/CarRacingGameApplication.kt
> +        }
감사합니다.
fddabb6c88ffbcc9a388fe6e983b9ea2c731e92d

2023-06-13 11:20 UTC, sjjeong commented on src/main/kotlin/study/step3/io/Input.kt
> +        readLine()?.toIntOrNull()?.let(callback)
저번에 말씀해주신 것 생각해서 toIntOrNull을 사용했었는데 readlnOrNull이 있는지는 몰랐습니다.

내부적으로 readlnOrNull이 readLine을 호출하고 있는데 readLine보다 readlnOrNull을 권장하시는 이유가 어떤건지 궁금합니다.
fddabb6c88ffbcc9a388fe6e983b9ea2c731e92d

2023-06-14 10:21 UTC, ddaaac approved these changes
안녕하세요 석준님 👋 

리뷰 반영 잘 해주셨습니다.

다음 단계 진행해주세요~

2023-06-14 10:21 UTC, ddaaac commented on src/main/kotlin/study/step3/Scoreboard.kt
> +            toString().dropLast(1)
그렇네요. List<List<T>> 의 프로퍼티를 예쁘게 출력하기가 쉽지 않겠네요. joinToString을 활용해서
```kotlin
scoresList.joinToString("\n") { scores ->
            scores.joinToString("\n") { "-".repeat(it.score) }
        }
```
이런 식으로 문자열을 만들어볼 수도 있겠구요. 성능이 중요한 게 아니라면 매라인마다 println()을 해주는 것도 가독성을 높일 수 있는 방법이지 않을까 싶어요.

2023-06-14 10:21 UTC, ddaaac commented on src/test/kotlin/study/step3/CarRacingGameApplicationTest.kt
> +            assertThat(Car().canMove(rpm)).isEqualTo(expected)
그 부분이 어색하다면 말씀주신대로 Engine을 Car의 프로퍼티로 만들어서 생성자로 받아도 될 것 같아요!

랜덤을 객체에서 분리해서 테스트 가능한 구조로 만드는 방법에 대해서는 수업시간에 진행을 했어서 그 부분을 참고해주시면 될 것 같습니다 😄

2023-06-14 10:21 UTC, ddaaac commented on src/main/kotlin/study/step3/io/Input.kt
> +        readLine()?.toIntOrNull()?.let(callback)
readLine 같은 경우에는 네이밍만 보고 nullable한지 바로 파악할 수 없습니다. 코틀린 1.6에 readln과 readlnOrNull이 구분돼서 추가된 이유 역시 좀 더 직관적이고 코틀린스러운 네이밍을 사용하기 위함으로 알고 있어요.
기존 코드와의 호환성 때문에 readLine()을 없애지는 않겠지만 새로 추가된 좀 더 코틀린스러운(?) 함수를 활용하는 것도 좋을 것 같아서 추천드렸습니다.

2023-06-14 10:21 UTC, merged