3단계 - 자동차 경주
next-step/kotlin-racingcar pull request #1087
Opened 2023-06-09 14:39 UTC by devyonghee

안녕하세요 동철님!! 👋

자동차 미션 3단계인 경주에 대해서 구현했습니다!!
코틀린으로 구현해보니까 더 간결한 모습으로 표현되는 것 같아요 🤔😆

그런데 이전 단계에서 남겨주신 코멘트들에 대해 궁금한 점이 있어서 제가 추가 코멘트를 남겼는데요
동철님께서 말씀해주신 의도에 대해 제가 이해를 못해서 이번 단계에서 수정을 못했습니다 😭😭
추가 코멘트 한번만 더 부탁드리겠습니다. 🙇‍♂️🙇‍♂️
[2단계 - 문자열 계산기 #1047](https://github.com/next-step/kotlin-racingcar/pull/1047)
어떠한 의도에서 주신 코멘트였는지 파악이 어려웠던 것 같습니다 😅😅

그럼 이번 3단계 미션도 잘 부탁드리겠습니다!! 🙏

2023-06-10 11:46 UTC, sah3122 requested changes
자동차 경주 미션 구현도 너무 잘해주셨네요 👍 
남겨주신 코멘트에 대해 답변 달아두었는데 확인 부탁드리며 다음 요청시 머지 하도록 하겠습니다 !

2023-06-10 11:46 UTC, sah3122 commented on src/main/kotlin/racingcar/controller/RacingCarGame.kt
> +fun main() {
깔끔한 main 구현 👍

2023-06-10 11:46 UTC, sah3122 commented on src/main/kotlin/racingcar/model/RacingCar.kt
> +        get() = RacingCar(moveStrategy, movedStatuses + moveStrategy.movedStatus)
자동차가 움직일때마다 movedStatus 가 추가되는 구현 너무 좋은것 같습니다 👍

2023-06-10 11:46 UTC, sah3122 commented on src/main/kotlin/racingcar/model/RacingStadium.kt
> +    infix fun racing(cars: Collection<RacingCar>): RacingHistory {
중위 표기법으로 구현해주셨네요 👍 
평소에도 이와같은 구현을 자주 하실까요 ?

2023-06-10 11:46 UTC, sah3122 commented on src/main/kotlin/racingcar/model/RandomMoveStrategy.kt
> +            MovingStatus.STOP
비즈니스 로직이 들어가는 경우 함수로 구현해보는건 어떨까요 ?

2023-06-10 11:46 UTC, sah3122 commented on src/main/kotlin/racingcar/model/MovingStatus.kt
> +            get() = count { it == GO }
확장함수를 적극적으로 사용해주시는 코드가 처음엔 코드를 읽기 어려웠는데, 점점 눈에 익숙해지네요 😄

2023-06-10 12:10 UTC, sah3122 commented on src/main/kotlin/racingcar/model/MovingStatus.kt
> +            get() = count { it == GO }
이번 과정을 진행하면서 확장함수의 사용을 줄여보는것이 어떨지 제안 드립니다. 
과정을 진행하며 도메인 중심의 객체지향적 구현을 학습하게 됩니다. 
확장함수의 사용이 객체지향적 구현을 저하하는것은 아니지만 도메인 객체가 제공해야하는 책임이 도메인을 생성하지 않고 제공될수 있기 때문에 과정을 진행함에서는 적절한 도메인 객체들에게 책임을 부여하는 방향으로 진행하면 어떨지 제안 드려봐요 !

2023-06-10 12:31 UTC, devyonghee commented on src/main/kotlin/racingcar/model/RacingStadium.kt
> +    infix fun racing(cars: Collection<RacingCar>): RacingHistory {
하나의 인자라면 가능하면 중위 함수를 활용하는 방법이 좋지 않을까 생각합니다 🤔
일반 함수처럼 사용할 수 있기도 하며 중위함수를 통해서도 가독성을 향상 시킬 수 있다고 생각합니다

2023-06-10 12:33 UTC, devyonghee commented on src/main/kotlin/racingcar/model/RandomMoveStrategy.kt
> +            MovingStatus.STOP
개인적으로는 클라이언트 입장에서는 값을 전달해주기만 하면 된다고 생각합니다 
동철님이 말씀해주신 의도처럼 함수로 구현을 하게 된다면 
외부에 비즈니스 로직이 존재한다고 표현하는 것이며 이는 캡슐화에 위배된다고 생각합니다.

2023-06-10 13:12 UTC, devyonghee commented on src/main/kotlin/racingcar/model/MovingStatus.kt
> +            get() = count { it == GO }
동철님께서 말씀해주신 방향은 일급 컬렉션을 선언하면서 해당 역할을 추가하라는 말씀같습니다 🤔
개인적으로는 `wentSize` 값을 가져오는 역할은 사실은 `Collection<MovingStatus>` 의 역할이 적절하다고 생각했기 때문에 이렇게 표현하게 되었습니다. 🤔🤔

동철님이 말씀해주신 의견은`Collection<MovingStatus>` 을 도메인 객체로 보지 않는다는 의견이셨을까요??

2023-06-11 14:19 UTC, sah3122 commented on src/main/kotlin/racingcar/model/RandomMoveStrategy.kt
> +            MovingStatus.STOP
상세한 설명 감사합니다 💯 
개인적으로 프로퍼티는 클래스가 가진 값으로 제공해줄수 있어야 한다고 생각하고 있어요 😄 
값을 그대로 제공해줄수 없다면 함수로 구현하는 편이니 해당 코멘트는 참고만 해주시면 될것 같습니다 👍

2023-06-11 14:21 UTC, sah3122 commented on src/main/kotlin/racingcar/model/MovingStatus.kt
> +            get() = count { it == GO }
일급 컬렉션을 선언하는것 보단 확장함수를 사용하기 보단 적절한 도메인 클래스를 정의해보는것이 어떨지에 대한 코멘트였습니다 😄 
`Collection<MovingStatus>`이 의미를 가지는 도메인 객체가 되기 위해선 클래스로 정의되어야 한다고 생각하고, 비즈니즈 요구사항을 만족하고, 적절한 책임이 부여 되어야 한다고 생각해요 !

2023-06-11 14:53 UTC, sah3122 approved these changes
남겨드린 피드백에 대한 상세한 코멘트 감사합니다 🙏 
저의 의견을 추가로 남겨두었는데 확인 부탁드리며 다음 미션도 진행해주세요 !

2023-06-11 14:53 UTC, merged

2023-06-11 15:44 UTC, devyonghee commented on src/main/kotlin/racingcar/model/MovingStatus.kt
> +            get() = count { it == GO }
개인적으로 `Collection<MovingStatus>` 에 `wentSize` 라는 프로퍼티를 추가하면서 
`MovingStatus` 을 모아놓은 '그룹' 에 대해 비즈니스 요구사항을 만족하고 적절한 책임이 부여됐다고 생각했습니다 🤔🤔

'클래스' 로 정의되어야 의미를 가지는 '도메인 객체' 가 될 수 있다는 말씀도 이해하기 어려운 것 같은데요. 🤔
그 이유에 대해서 자세하게 설명을 부탁드려도 될까요?? 🙏 
그리고 혹시 `Collection` 은 의미가 없는 객체가 맞을까요?? 🤔

2023-06-13 04:39 UTC, sah3122 commented on src/main/kotlin/racingcar/model/MovingStatus.kt
> +            get() = count { it == GO }
Collection 자체로는 도메인의 의미를 부여할수 없다고 생각합니다. 
예를 들어 앞으로 전진하는 상태들과 전진하지 않는 상태들이 도메인에서 중요한 의미를 가지고 관리되어야 한다면  Collection<MovingStatus> 하나 만으로는 의미를 나타낼수 없게 됩니다. 
비즈니스 관점에서 중요하게 관리되어야 한다면 Collection<MovingStatus>를 의미를 가지는 클래스로 정의하는것이 어울릴것 같습니다 😄

2023-06-13 05:09 UTC, devyonghee commented on src/main/kotlin/racingcar/model/MovingStatus.kt
> +            get() = count { it == GO }
에릭에반스의 ddd 책에서 참고해보면 
도메인 모델이라는 것은 소프트웨어로 해결하고자 하는 영역을 모델로 표현한 것이라고 이해했는데요.

여기서 해결하고자 하는 영역은 `MovingStatus` 라는 묶음에서 `GO` 라는 요소들만 가져오는 것인데 
이 문제를 해결하기 위해서는 그 요소들의 집단이라는 모델에서 `MovingStatus`을 필터링을 도와주는 도메인 모델이 필요하다고 생각합니다.

동철님 말씀처럼 `Collection` 자체만으로는 그 모델을 표현하기는 어렵지만
`Collection<MovingStatus>` 라는 제너릭 클래스로 그 대상을 표현한다면 
다른 개발자들에게도 그 의도가 표현된다고 생각하는데요.

물론 새로운 클래스로 정의할 수 있긴 하지만 
`Collection` 을 사용한다고 해서 도메인의 의미를 전달할 수 없다는 점은 이해가 잘 안되는 것 같습니다 🤔

혹시 제가 참고할만한 자료나 이에 대한 부연 설명을 부탁드려도 될까요??🙇‍♂️🙇‍♂️