Step3: 자동차 경주
next-step/kotlin-racingcar pull request #1088
Opened 2023-06-09 15:08 UTC by hyunju-seo

안녕하세요 현석님! 
https://github.com/next-step/kotlin-racingcar/pull/1050에서 리뷰주신 내용이랑 3단계 미션 진행했습니다.
감사합니다!

2023-06-10 12:23 UTC, BeokBeok requested changes
이전 단계 피드백과 자동차 경주 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-06-10 12:23 UTC, BeokBeok commented on src/main/kotlin/step2/Calculator.kt
> +        check(remainingOperators.isEmpty()) { "올바르지 않은 연산식 입니다." }
제가 의도한 것은 require, check와 같은 선언적 체크(declarative check)는 주로 함수의 전반부에 위치하는 것이였습니다.
그러나, remainingOperators는 calculate 함수의 로직을 수행한 결괏값에 해당하므로, 함수 전반부에 위치할 수 없습니다.
해서, 본 위치에서의 선언적 체크는 약간 의도와 맞지 않아보여서, 선언적 체크를 사용하지 않는 것을 의도했습니다. 😅

2023-06-10 12:23 UTC, BeokBeok commented on src/main/kotlin/step2/Operator.kt
> +            require(input2 != 0) { "0으로 나눌 수 없습니다." }
input1이 0인 경우에는 어떤 일이 발생할까요?

2023-06-10 12:23 UTC, BeokBeok commented on src/main/kotlin/step3/Configuration.kt
> +package step3
패키지명을 자동차 경주와 관련하여 좀 더 의미있는 이름으로 작성해보면 어떨까요?

2023-06-10 12:23 UTC, BeokBeok commented on src/main/kotlin/step3/domain/CarGame.kt
> +        private const val INITIAL_POSITION = 0
초기 포지션 값을 상수로 잘 정의해주셨네요. 👍 
다만, 포지션과 관련된 값은 CarPosition 클래스와 더 관련이 있지 않을까요?

2023-06-10 12:23 UTC, BeokBeok commented on src/main/kotlin/step3/domain/GameResult.kt
> +    private val positionsResult: MutableList<CarPositions> = mutableListOf()
positionsResult의 타입을 MutableList로 만들어 주셨네요. 👍 
다만, MutableList로 만들게 되면, 외부에서 변경이 가능해요.

외부에서 변경을 하더라도 영향을 받지 않도록, 아래의 테스트 코드를 통과할 수 있도록 개선해보면 어떨까요?
```kotlin
val list = mutableListOf(CarPositions(positions = listOf()))
val result = GameResult(
    initialPositions = CarPositions(positions = listOf()),
    positionsResult = list
)

list.clear()

result.getPositionsResult().size shouldBe 1
```

2023-06-10 12:23 UTC, BeokBeok commented on src/main/kotlin/step3/domain/strategy/MoveStrategy.kt
> +interface MoveStrategy {
전략 패턴 사용 👍

2023-06-10 12:28 UTC, BeokBeok commented
추가로, 리뷰를 반영하실 때, 리뷰당 하나의 커밋으로 반영해주신 후 관련 코맨트에 커밋ID를 달아주시면 리뷰어에게 큰 힘이 됩니다! 🙏

2023-06-10 15:19 UTC, hyunju-seo commented on src/main/kotlin/step3/domain/GameResult.kt
> +    private val positionsResult: MutableList<CarPositions> = mutableListOf()
https://github.com/next-step/kotlin-racingcar/commit/9618b0b7c4bcb8803e3d5c7e02822dcd6f0a0a67 반영했습니다!

2023-06-10 15:39 UTC, hyunju-seo commented on src/main/kotlin/step3/domain/CarGame.kt
> +        private const val INITIAL_POSITION = 0
https://github.com/next-step/kotlin-racingcar/pull/1088/commits/07bd788b399bab1a6db5505716e3ed43ef7e327a CarGame 클래스에서 초기 포지션을 설정하려는 의도로 CarGame에 관련 상수를 선언했습니다. 근데 코멘트를 보고 생각해보니 초기 포지션이 0이 아닌 경우가 요구사항에 없기도 하고, 항상 0일것 같아서 Carposition 생성자에 기본인자로 설정했습니다.

2023-06-10 15:40 UTC, hyunju-seo commented on src/main/kotlin/step2/Operator.kt
> +            require(input2 != 0) { "0으로 나눌 수 없습니다." }
input1이 0이면 결과가 0이 되지 않나요,,?(리뷰 주신 내용을 잘 이해 못했습니다🥲)

2023-06-10 17:19 UTC, hyunju-seo commented on src/main/kotlin/step3/Configuration.kt
> +package step3
https://github.com/next-step/kotlin-racingcar/pull/1088/commits/8863893d343f4dd1f5f54c26072895d55ff74434

2023-06-10 17:47 UTC, hyunju-seo commented on src/main/kotlin/step2/Calculator.kt
> +        check(remainingOperators.isEmpty()) { "올바르지 않은 연산식 입니다." }
https://github.com/next-step/kotlin-racingcar/pull/1088/commits/a5bb9bc3f589d8414a1334b8fefd16962eb8d6ab check는 IllegalStateExcption을 던지기 때문에 꼭 전반부에만 위치하지 않아도 될것같은데 관례적으로 그렇게 쓰이는군요🤔 수정했습니다

2023-06-11 11:21 UTC, BeokBeok commented on src/main/kotlin/step2/Operator.kt
> +            require(input2 != 0) { "0으로 나눌 수 없습니다." }
이 부분은 제가 코맨트를 잘못 작성했습니다. 🙏

2023-06-11 11:30 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2023-06-11 11:30 UTC, BeokBeok commented on src/main/kotlin/step3/domain/GameResult.kt
> +    }
테스트가 통과하도록 잘 구현해주셨네요. 👍 
지금도 좋지만, 가급적이면 외부에서 보이는 타입은 Immutable(불변)으로 만드는 것이 좋습니다.

```suggestion
    positionsResult: List<CarPositions> = emptyList()
) {
    private val positionsResult = positionsResult.toMutableList()
```

2023-06-11 11:30 UTC, BeokBeok commented on src/test/kotlin/step3/domain/GameResultTest.kt
> +    "GameResult 내부 리스트는 외부에서 변경할 수 없다." {
테스트 코드를 잘 활용해주셨네요. 👍

2023-06-11 11:30 UTC, BeokBeok commented on src/main/kotlin/step3/domain/CarPosition.kt
> +class CarPosition(val position: Int = 0) {
```suggestion
class CarPosition(val position: Int = INITIAL_POSITION) {
```
상수를 활용해보면 어떨까요?

2023-06-11 11:30 UTC, merged