[Step2] 문자열 계산기
next-step/kotlin-racingcar pull request #1089
Opened 2023-06-09 15:18 UTC by Kyudong3

문자열 계산기 리뷰 요청드립니다!
감사합니다 🙏🏼

2023-06-10 11:25 UTC, sah3122 requested changes
문자열 계산기 구현 잘해주셨습니다 👍 
몇가지 고민거리를 남겨두었는데 확인 부탁드려요 !

2023-06-10 11:25 UTC, sah3122 commented on src/main/kotlin/study/step2/ArithmeticCalculator.kt
> +    private fun div(operand1: Int, operand2: Int) = operand1 / operand2
사칙 연산을 담당하는 enum class 를 더 활용해보면 어떨까요 ? 
이번 미션에서 enum을 활용하는 방법에 대해 학습해보는것을 권장 드립니다. 
https://techblog.woowahan.com/2527/

2023-06-10 11:25 UTC, sah3122 commented on src/main/kotlin/study/step2/ArithmeticCalculator.kt
> +                operator = setOperator(it)
operator 는 코틀린에서 예약어로 선언되어 있습니다. 
operator 대신 다른 변수명을 고려해보세요 !

2023-06-10 11:25 UTC, sah3122 commented on src/main/kotlin/study/step2/ArithmeticCalculator.kt
> +                operator = setOperator(it)
람다식의 중첩은 오히려 코드의 가독성을 떨어트릴수 있다고 생각해요. 
적절하게 코드를 풀어서 구현해보는건 어떨까요 ?

2023-06-10 11:25 UTC, sah3122 commented on src/main/kotlin/study/step2/ArithmeticCalculator.kt
> +            it.toIntOrNull()?.let { operand ->
입력값이 Int 형으로 변환되지 않으면 operator 라고 정의해주셨는데, 입력 순서에 따라 검증하는 방법도 적절할것 같습니다 😄

2023-06-10 13:41 UTC, Kyudong3 commented on src/main/kotlin/study/step2/ArithmeticCalculator.kt
> +    private fun div(operand1: Int, operand2: Int) = operand1 / operand2
Enum 클래스가 조금 더 책임을 가져가도록 수정해봤어요! 🙏🏼

2023-06-10 13:42 UTC, Kyudong3 commented on src/main/kotlin/study/step2/ArithmeticCalculator.kt
> +                operator = setOperator(it)
놓친 부분인데 잡아주셔서 감사합니다! 🙏🏼

2023-06-11 14:13 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
다음 미션도 화이팅하세요 😄

2023-06-11 14:13 UTC, sah3122 commented on src/main/kotlin/study/step2/ArithmeticOperator.kt
> +enum class ArithmeticOperator(
피드백 반영 👍

2023-06-11 14:13 UTC, sah3122 commented on src/main/kotlin/study/step2/ArithmeticCalculator.kt
> +        inputExpression.split(" ").forEachIndexed { index, input ->
forEach와 when 절을 활용하여 깔끔하게 구현 해주셨네요 👍

2023-06-11 14:13 UTC, merged