3단계 - 자동차 경주
next-step/kotlin-racingcar pull request #1133
Opened 2023-06-11 08:56 UTC by sksskaw

3단계 미션 완료했습니다

2023-06-11 09:50 UTC, pci2676 requested changes
본 미션인 자동차 경주 미션이네요!

이번에도 열심히 해봅시다!

개선하면 좋을 부분에 코멘트를 남겨두었으니 확인해주시고 다시 리뷰요청 부탁드리겠습니다.

2023-06-11 09:50 UTC, pci2676 commented on src/test/kotlin/RandomNumberTest.kt
> +        assertThat(randomNumber).isBetween(0, 9)
이 테스트가 정말로 의미있을지는 의문이 드네요.

코틀린이 제공하는 `random()`를 사용하는 것이라 굳이 테스트 안하셔도 저는 무방할 것 같습니다.

2023-06-11 09:50 UTC, pci2676 commented on src/main/kotlin/Car.kt
> +    val FORWARD_CONDITIONS: Int = 4,
`FORWARD_CONDITIONS`는 고정값으로 모든 Car 객체가 동일하게 사용하게 될 것 같습니다.

이경우 companion object내에 위치시는게 좋지 않을까요?

2023-06-11 09:50 UTC, pci2676 commented on src/main/kotlin/Car.kt
> +    fun move() {
자동차 움직임에 대한 테스틀 힘들게 하는 부분은 random한 값을 가지고 판단을 하는 부분입니다.

이를 인터페이스를 이용하여 테스트 가능한 구조로 변경해보는건 어떨까요?

2023-06-11 09:50 UTC, pci2676 commented on src/main/kotlin/InputView.kt
> +    fun setCarsMessage() {
set이라는 함수명은 해당 객체의 특정 값을 변경하는 듯한 뉘앙스를 가지고 있는것 같습니다.
단순히 출력만 한다면 show 혹은 print와 같은 이름은 어떨까요?

2023-06-11 09:50 UTC, pci2676 commented on src/main/kotlin/InputIO.kt
> +        inputView.displayMessage()
when을 사용하지 않고 enum이 message를 가지고 있다면 더 간결하게 표현할 수 있지 않을까요?

2023-06-11 09:50 UTC, pci2676 commented on src/main/kotlin/main.kt
> +    )
`racingField`를 미리 만들어야 할 이유가 있을까요?

지금과 같이 만들어진 객체에 값을 중간에 변경하는 행위를 통해 객체의 안정성이 많이 떨어지게 되는것 같습니다.

`racingField`의 `createCars`와 `setGameCount`를 사용하지 않도록 리팩터링해보시면 좋을것 같습니다.

생성자에 필요한 값을 받거나 필요한 객체를 전달받는 방향으로 고려해보시면 좋을것 같습니다.

2023-06-11 09:50 UTC, pci2676 commented on src/test/kotlin/CarTest.kt
> +    }
테스트를 꼼꼼하게 작성하시려고 한 부분은 좋지만 이러한 테스트는 아쉽게도 유의미하지 않아보입니다.

car의 move를 통해 변경되는 값을 통제할 수 있고 그에 따른 결과를 테스트 할 수 있어야 할 것 같습니다.

2023-06-11 09:50 UTC, pci2676 commented on src/test/kotlin/RacingFieldTest.kt
> +        field.trySetAccessible()
테스트에서 리플렉션을 사용해서 값을 검증해야하는 이유가 있을까요?

5를 주입하면서 발생하는 결과를 테스트하면 5가 정상적으로 주입되었다는 것을 보장할 수 있지 않을까요?

앞으로의 미션을 진행하면서 리플렉션은 사용하지 말아주시길 바라겠습니다!

2023-06-11 09:50 UTC, pci2676 commented on src/main/kotlin/RacingField.kt
> +            resultView.carDistanceDisplay(cars)
문제해결영역인 도메인 객체 RacingField에서 뷰(resultView)에 대한 의존성을 가제 되었네요.

도메인 객체에서 뷰의 의존성을 제거해보는건 어떨까요?

뷰 영역은 쉽게 변할 수 있고 여러가지가 될 수 있는데 도메인이 뷰에 영향을 받으면 안전한 애플리케이션을 보장하기 어려울 것 같습니다.

도메인 객체는 수행 결과를 반환하면 뷰가 반환된 결과를 가져가 사용하는 방식으로 변경해보시면 좋을것 같습니다.

```
val result = racingFile.gameStart()
val viewDto = ConsoleViewDto(result) // 예를 들은 것이니 이름은 무시하셔도 좋습니다.
resultView.carDistanceDisplay(viewDto) 
```

2023-06-11 09:50 UTC, pci2676 commented on src/main/kotlin/RacingField.kt
> +    private val resultView = ResultView()
도메인 객체에서 view 객체를 제거해주세요!

view가 도메인을 의존하도록 변경해주세요!

2023-06-11 10:28 UTC, sksskaw commented on src/test/kotlin/RandomNumberTest.kt
> +        assertThat(randomNumber).isBetween(0, 9)
그렇군요!
모든 로직에 테스트코드를 작성해야 한다는것에 의식했던것 같습니다

2023-06-11 10:31 UTC, sksskaw commented on src/main/kotlin/InputIO.kt
> +        inputView.displayMessage()
step2에서도 그랬듯이 아직 when 구문을 리펙토링 하는것에  익숙하지가 않네요

2023-06-11 10:33 UTC, sksskaw commented on src/test/kotlin/CarTest.kt
> +    }
move에는 난수를 생성하는 로직이 있는데 정말 테스트가 필요한지 한다면 변경되는값을 통제할수가 없는데 어떤식으로 해야할지 난해하더군요..

2023-06-11 10:36 UTC, sksskaw commented on src/test/kotlin/RacingFieldTest.kt
> +        field.trySetAccessible()
gameCount 필드가 private로 설정을 해서 테스트 해야되서 사용했습니다

처음에는 getGameCount 함수로 테스트를 했는데 테스트로직에만 사용하게 되서 수정했었습니다

2023-06-11 10:48 UTC, sksskaw commented on src/main/kotlin/InputView.kt
> +    fun setCarsMessage() {
최종소스에는 InputView 를 interface로 리팩토링 했습니다

2023-06-11 11:21 UTC, sksskaw commented on src/main/kotlin/main.kt
> +    )
이렇게 리팩토링하니 racingField의 필드변수를 private로 설정할 수 있네요!

2023-06-11 11:51 UTC, pci2676 requested changes
태훈님 안녕하세요~

PR 요청 주신 소스코드에서 컴파일 에러가 발생하는 것 같습니다.

확인 부탁드립니다!

2023-06-11 17:16 UTC, pci2676 requested changes
지난번 코드 리뷰시 개선을 부탁드릴 부분이 덜 반영된것 같습니다.

혹시 어려운 점이 있다면 시간에 상관없이 DM을 주셔도 되니 부담없이 보내주세요!

개선을 하기 위한 힌트를 더 남겨두었으니 참고하여 개선부탁드립니다.

2023-06-11 17:16 UTC, pci2676 commented on src/main/kotlin/InputType.kt
> +    fun display() = println(this.message)
InputType이 정보를 가지도록 변경해주셨네요 👍 
하지만 print 하는 책임까지 가지고 있는건 조금 어색해보이네요.

2023-06-11 17:16 UTC, pci2676 commented on src/main/kotlin/RacingField.kt
> +    fun getGameCount(): Int {
상태를 나타내는 값은 메서드가 아닌 읽기전용 프로퍼티 `val`를 이용해서 조금 더 코틀린스러운 코드를 작성 할 수 있습니다.
다른 부분도 이와 같이 변경할 수 있는 부분이 있는지 살펴보면 좋을것 같습니다.

```
val gameCount: Int
  get() = this.gameCount
```

2023-06-11 17:16 UTC, pci2676 commented on src/main/kotlin/Car.kt
> +class Car(
`Car`의 핵심 기능인 `move()`의 테스트가 필요할 것 같습니다.

테스트를 불가능하게 하는 영역을 interface로 추상화해보면 좋을것 같습니다.

NumberGenerator
ㄴ RandomNumberGenerator
ㄴ FixedNumberGenerator

운영환경과 테스트환경에 서로다른 구현체를 사용한다면 테스트하기 쉬워지지 않을까요?

2023-06-11 17:16 UTC, pci2676 commented on src/main/kotlin/ResultView.kt
> +    fun carDistanceDisplay(cars: List<Car>) {
`Car`의 모든 기능이 `ResultView`의 기능을 수행하기 위해 필요할까요?

`ResultView`에서 표현하고 싶은건 `Car`의 **거리**인 것 같습니다.

하지만 지금은 `ResultView`에서 `Car`의 `move()`와 같이 상태를 변경할 수 있는 기능이 노출되고 있습니다.

이전 리뷰를 참고하여 개선해주세요.

2023-06-11 17:16 UTC, pci2676 commented on src/main/kotlin/RacingField.kt
> +        for (i in 1..count) {
repeat를 이용해서 간결하게 표현할 수 있을것 같습니다.

다른 부분도 동일하게 개선할 수 있는지 찾아보시면 좋을것 같습니다.

2023-06-11 17:16 UTC, pci2676 commented on src/main/kotlin/InputIO.kt
> +        val inputValue = checkNumber(readlnOrNull())
음수를 입력해도 프로그램을 실행이 될 것 같습니다.

요청에 대한 정의를 하고 있는 클래스를 하나 도출해보는건 어떨까요?

view에서 입력받은 값을 해당 클래스의 객체에 넘겨서 객체가 값을 판단하는것도 좋은 방법입니다.

아래와 같이 만들어볼 수 있을것 같네요.
```kotlin
RacingRequest(
  val carCount: Int, 
  val gameCount: Int,
) {
  init {
    //validate
  }
}
```

2023-06-12 04:25 UTC, sksskaw commented on src/main/kotlin/InputIO.kt
> +        val inputValue = checkNumber(readlnOrNull())
![스크린샷 2023-06-12 오후 12 45 43](https://github.com/next-step/kotlin-racingcar/assets/69659375/1bbf402a-4488-47a0-98c2-1ae340c7d062)

하나씩 입력받아 검증하고 문제가 있으면 다시 입력받도록 로직을 구현했습니다.
RacingRequest를 이용해서 두값이 하나로 묶이면 다시 입력받도록 하는 로직을 넣기 어려운것 같습니다.

2023-06-12 12:03 UTC, pci2676 approved these changes
미션 진행을 위해 이번 단계는 여기서 머지하도록 하겠습니다.

다음 미션을 진행하면서 이번에 남긴 코드리뷰를 참고해서 먼저 수정해주시기 바랍니다.

그리고 요구사항 체크리스트에 대해서도 빼놓지 말고 작성해주세요.
미션에 대한 요구사항 중 기본적인 요구사항 외 태훈님께서 추가한 요구사항이 있다면 저는 태훈님의 의도를 알 방법이 없습니다.
요구사항 체크 리스트가 있으면 제가 리뷰할때 더 수월하게 리뷰할 수 있습니다.

궁금한점 있으시면 언제든 DM주세요.

2023-06-12 12:03 UTC, pci2676 commented on src/main/kotlin/Car.kt
> +            randomNumber = FixedNumberGenerator()
실행 환경에 대한 판단을 하기 시작했을 때 환경의 종류가 늘어날때마다 운영코드에 많은 영향을 미치게 될 것 같습니다.

car가 생성될때 환경에 따라 NumberGenerator를 주입받도록 변경해보세요.

운영환경 코드에서는 RandomNumberGenerator지만

테스트 코드에서는 FixedNumberGenerator를 주입해주면 되지 않을까요?

이번 미션에서 위와같이 환경을 판단하는 코드는 반드시 제거해주시기 바랍니다.

2023-06-12 12:03 UTC, pci2676 commented on src/main/kotlin/InputIO.kt
> +        val inputValue = checkNumber(readlnOrNull())
재입력을 받게되는군요!

그런데 지금 상태라면 다른 개발자가 이 코드를 사용한다고 가정했을때 `RacingField`에 음수를 주입할 수 있는 상태 아닌가요? 이 경우 문제가 될 수 있을것 같으니 검증된 값을 사용할 수 있도록 강제할 필요가 있을것 같습니다.

2023-06-12 12:03 UTC, pci2676 commented on src/main/kotlin/RacingField.kt
> +    private val cars: MutableList<Car>,
cars를 `MutableList`로 생성할 필요가 있을까요?

한번 생성되면 더 이상 변할일이 없을 것 같으니 `List`로 변경해주세요.

2023-06-12 12:03 UTC, pci2676 commented on src/test/kotlin/CarMoveTest.kt
> +     */
별도의 설정을 하지 않고 코드를 수행하여도 항상 통과하는 테스트 코드가 유지보수하기 좋을것 같습니다.

자동으로 필요한 설정을 해줄 수 없는 환경이라면
별도의 설정은 제거하고 통과할 수 있도록 해주세요.

2023-06-12 12:03 UTC, pci2676 commented on src/test/kotlin/CarMoveTest.kt
> +        car.move()
이 경우 `car`가 `move()`했는데 조건을 만족하지 못해서 움직이지 못한경우에 대한 테스트는 어떻게 할 수 있을까요?

2023-06-12 12:03 UTC, pci2676 commented on src/test/kotlin/CheckNumberTest.kt
> +        assertThat(negativeValue).isEqualTo(null)
`assertThat(negativeValue).isNull` 을 이용하여 더 간결하게 표현할 수 있으니 참고 부탁드립니다.

2023-06-12 12:03 UTC, pci2676 commented on src/test/kotlin/CheckNumberTest.kt
> +        assertThat(positiveValue).isEqualTo(3)
하나의 테스트에는 하나의 기능에 대해서만 검증할 수 있도록 해주세요.

단일 책임의 원칙은 테스트에서도 동일하게 적용이 되어야 합니다.

2023-06-12 12:03 UTC, pci2676 commented on src/test/kotlin/RacingFieldTest.kt
> +            assertThat(carDistances.stream().allMatch { it in 0..gameCount })
범위에 대한 테스트는 상황에 따라 값이 변할 수 있다는것을 나타낼뿐 그렇게 유의미하지 않습니다.

보다 명확한 테스트 기대값을 설정하여 테스트가 나타내고자 하는 바를 나타내는것이 좋을것 같습니다.

2023-06-12 12:03 UTC, pci2676 commented on src/test/kotlin/RacingFieldTest.kt
> +    fun racingFieldGameStartTest() {
테스트를 파악하는데 있어서 테스트의 이름도 굉장히 중요한 요소입니다.

테스트가 어떠한 것을 나타내고자 하는지 명확하도록 이름을 변경해보는건 어떨까요?
단순히 "~을 실행한다" 보다 "~한 경우 ~한 결과 발생" 과 같이 인과관계가 포함되면 좋을것 같습니다.

`@DisplayName` 을 이용하여 한글로 나타내보시면 좋을것 같습니다.

2023-06-12 12:03 UTC, pci2676 commented on src/main/kotlin/Car.kt
> +    fun getDistance(): Int {
읽기전용 프로퍼티(val)로 표현해주세요.

2023-06-12 12:03 UTC, pci2676 commented on src/main/kotlin/RacingField.kt
> +    fun gameStart(): MutableList<Car> {
반환 타입을 List로 변경해주세요.

외부로 변경가능한 객체를 내보낼 이유가 없는것 같습니다.

2023-06-12 12:03 UTC, pci2676 commented on src/main/kotlin/ResultView.kt
> +    fun carDistanceDisplay(cars: List<Car>) {
고칠 부분이 많아 이 부분은 누락하셨을까요?

다음 미션에서 반드시 개선해주세요.

2023-06-12 12:03 UTC, pci2676 commented on src/main/kotlin/InputIO.kt
> +    fun checkNumber(inputString: String?): Int? {
운영환경에서는 `InputIO` 내에서만 사용될뿐 다른 객체에게 불리는 코드는 아닌것 같습니다.
`private`로 가시성을 제한해주세요.

관련된 테스트는 이 함수를 사용하는 코드를 통해 테스트할 수 있습니다.

2023-06-12 12:03 UTC, pci2676 commented on src/main/kotlin/InputIO.kt
> +        return inputNumber(numberType)
Elvis 연산자를 이용하면 아래와 같이 표현할 수 있습니다.

```suggestion
        return checkNumber(readlnOrNull())
            ?: return inputNumber(numberType)
```

2023-06-12 12:03 UTC, pci2676 commented on src/main/kotlin/ResultView.kt
> +        val displayString = "-"
이 값은 Car에서 처럼 companion object로 관리해주건 어떨까요?

2023-06-12 12:03 UTC, pci2676 commented on src/main/kotlin/main.kt
> +    }
`resultMessage()`를 이용해 출력하는 부분과 자동차의 거리를 출력하는 부분이 분리되어야 하는 이유가 있을까요?

순서를 보장할 수 없어서 다른 개발자가 코드를 이용할때 어떤것이 먼저와야하는지 파악이 되지 않을 수 있을것 같습니다.

출력에 필요한 값만 `ResultView`에 넘겨주고 출력에 대한 보장은 `ResultView`이 내부에서 해주도록 변경해주세요.

2023-06-12 12:03 UTC, merged

2023-06-12 12:07 UTC, pci2676 commented on src/main/kotlin/InputIO.kt
> +            return inputValue
다른 if 블럭과의 통일을 위해 중괄호를 포함해주시면 좋을것 같아요~

2023-06-12 12:08 UTC, sksskaw commented on src/main/kotlin/Car.kt
> +            randomNumber = FixedNumberGenerator()
아.. init로 생성할때 주입하면 되는구나..ㅎ

파라미터로 넣어주려니까 수정할곳이 너무 많아서 고민하다 이렇게 해버렸습니다..ㅠ