[Step2] 문자열 계산기
next-step/kotlin-racingcar pull request #1155
Opened 2023-06-12 01:16 UTC by choihwan2

처음해보는 코틀린이라 어색한 부분이 많을것 같네요 잘부탁드립니다!

2023-06-12 14:02 UTC, Flamme1004K requested changes
안녕하세요!

몇 가지 코멘트를 남겼으니 확인 부탁드리겠습니다!

확인 후 다시 리뷰 요청 드리며, 궁금하신 점에 대해서는 DM 부탁드립니다!

마지막으로 미션 화이팅입니다! 🙌

2023-06-12 14:02 UTC, Flamme1004K commented on src/main/kotlin/step2/CalculatorImpl.kt
> +class CalculatorImpl : Calculator {
Calculator와 Operator에 대한 클래스를 두개로 나누어 리팩토링해보는 건 어떨까요?

2023-06-12 14:02 UTC, Flamme1004K commented on src/main/kotlin/step2/CalculatorImpl.kt
> +    }
enum class를 사용해볼까요?

2023-06-12 14:02 UTC, Flamme1004K commented on src/main/kotlin/step2/CalculatorImpl.kt
> +        val inputs = input?.split(" ") ?: throw IllegalArgumentException()
require를 사용해 볼까요?

링크
- [require()](https://www.google.com/search?q=kotlin+require&oq=kotlin+require&aqs=chrome..69i57j0i512l9.1696j0j7&sourceid=chrome&ie=UTF-8)

2023-06-12 14:02 UTC, Flamme1004K commented on src/main/kotlin/step2/CalculatorImpl.kt
> +        var result = inputs[0].toInt()
inputs[0]이 숫자가 아니면 어떻게 되나요?

계산하기 전에 숫자인지, 연산기호인지 체크할 수는 없을까요?

2023-06-12 14:02 UTC, Flamme1004K commented on src/main/kotlin/step2/CalculatorImpl.kt
> +        inputs.drop(1).forEach {
시간이 지나면 drop(1)이 무엇인지에 대해서 한 번에 알아볼 수 있을까요?

2023-06-12 14:02 UTC, Flamme1004K commented on src/main/kotlin/step2/CalculatorImpl.kt
> +            isSymbol = !isSymbol
연산기호와 숫자가 한 쌍으로 같이간다면 isSymbol과 symbol는 없어도 될 것 같습니다.

2023-06-12 14:02 UTC, Flamme1004K commented on src/test/kotlin/step2/CalculatorImplTest.kt
> +    val calculatorImpl = CalculatorImpl()
CalculatorImpl은 Calculator의 구현체이지요.

Calculator로 작동하는 계산기를 만들어주세요.

2023-06-12 14:02 UTC, Flamme1004K commented on src/test/kotlin/step2/CalculatorImplTest.kt
> +    }
kotest의 table을 사용해볼까요?

링크
[Data Driven Testing with Kotest(번역)](https://wooooooak.github.io/%EB%B2%88%EC%97%AD%ED%95%98%EB%A9%B0%20%EA%B3%B5%EB%B6%80%ED%95%98%EA%B8%B0/2021/01/04/kotest_data_driven_testing/)

2023-06-13 13:14 UTC, choihwan2 commented on src/main/kotlin/step2/CalculatorImpl.kt
> +        val inputs = input?.split(" ") ?: throw IllegalArgumentException()
오늘 수업시간에서도 배웠는데 적용해보겠습니다!

2023-06-13 13:16 UTC, choihwan2 commented on src/main/kotlin/step2/CalculatorImpl.kt
> +        var result = inputs[0].toInt()
한번 고민해보고 고쳐보겠습니다!

2023-06-13 13:16 UTC, choihwan2 commented on src/main/kotlin/step2/CalculatorImpl.kt
> +        inputs.drop(1).forEach {
상수를 쓰는걸 따로 지정해놔야할 것 같네요 감사합니다

2023-06-13 13:17 UTC, choihwan2 commented on src/test/kotlin/step2/CalculatorImplTest.kt
> +    val calculatorImpl = CalculatorImpl()
Calculator 와 Operator 로 나누는걸로 한번 변경해보겠습니다

2023-06-13 13:17 UTC, choihwan2 commented on src/test/kotlin/step2/CalculatorImplTest.kt
> +    }
찾아보고 적용해보겠습니다!

2023-06-13 13:17 UTC, choihwan2 commented on src/main/kotlin/step2/CalculatorImpl.kt
> +class CalculatorImpl : Calculator {
한번 적용해보겠습니다

2023-06-14 14:42 UTC, Flamme1004K approved these changes
안녕하세요!

피드백 반영하시느라 고생하셨습니다! 이만 머지하도록 하겠습니다.

다음 미션도 화이팅입니다! 아좌아좌! 🤩

2023-06-14 14:42 UTC, Flamme1004K commented on src/main/kotlin/step2/Calculator.kt
> +    fun calculate(first: Int, symbol: String, second: Int): Int = when (getBySymbol(symbol)) {
함수 순서가 아래가 더 맞지 않을까요?

추가로 테스트 케이스를 위해 public으로 꼭 열어놔야할까요?

2023-06-14 14:42 UTC, Flamme1004K commented on src/main/kotlin/step2/Calculator.kt
> +const val INTERVAL_SIZE = 2
companion object를 사용해볼까요?

2023-06-14 14:42 UTC, Flamme1004K commented on src/main/kotlin/step2/Calculator.kt
> +    fun calculateString(input: String?): Int {
리팩토링 👍

2023-06-14 14:42 UTC, Flamme1004K commented on src/main/kotlin/step2/Calculator.kt
> +        require(!inputs.isNullOrEmpty())
```suggestion
        require(!input.isNullOrEmpty()) { "error message" }
        val inputs = input.split(" ")
```

처음에 input에 대한 Null check를 하고나서 split를 하는게 더 좋은 로직이 아닌가합니다.

require는 다음과 같이 에러 메시지를 줄 수 있어서 적절한 예외 메시지를 줄 수 있을 것 같네요. require를 사용할 수 있는 부분이 이 함수에서도 하나 더 보이는데, 그 부분도 한번 변경해보시길  바래요.

추가로 split에 문자열인 " "은 상수로 처리할 수 있지 않을까요?

2023-06-14 14:42 UTC, Flamme1004K commented on src/main/kotlin/step2/Operator.kt
> +            Operator.values().find { it.sign == input } ?: throw IllegalArgumentException()
에러 메시지는 어디로 갔을까요?

2023-06-14 14:42 UTC, Flamme1004K commented on src/test/kotlin/step2/CalculatorTest.kt
> +    }
요구사항 반영 👍👍

2023-06-14 14:42 UTC, Flamme1004K commented on src/test/kotlin/step2/OperatorTest.kt
> +package step2
각 단계에 대해 패키지는 하지 말아주세요~

kotlin.racingGame 이렇게 의미있는 이름을 지어주세요.

왜냐하면 처음 시작은 괜찮지만 step4로 간다면 해당 패키지를 그대로 step4로 복사하여 만들기 때문에 step3에서 드린 피드백을 찾기가 힘들어집니다. 🥲

2023-06-14 14:44 UTC, merged

2023-06-14 16:26 UTC, choihwan2 commented on src/test/kotlin/step2/OperatorTest.kt
> +package step2
넵 다음 미션부터는 수정해서 올리도록 하겠습니다!

2023-06-14 16:26 UTC, choihwan2 commented on src/main/kotlin/step2/Operator.kt
> +            Operator.values().find { it.sign == input } ?: throw IllegalArgumentException()
아이고.. 디테일이 조금 부족했네요 ㅠㅠ 다음부터 잘 추가해보도록하겠습니다

2023-06-14 16:27 UTC, choihwan2 commented on src/main/kotlin/step2/Calculator.kt
> +        require(!inputs.isNullOrEmpty())
너무 급하게 코드를 작성하다보니 이런 부분도 놓쳐버렸네요..🥲 다음에는 좀 더 신경써서 작성해보도록 하겠습니다!

2023-06-14 16:28 UTC, choihwan2 commented
리뷰잘해주셔서 감사합니다! 다음미션도 잘부탁드립니다.