refactor : step 5 자동차 경주(리팩터링)
next-step/kotlin-racingcar pull request #1164
Opened 2023-06-12 12:51 UTC by ohsung

1. RacingController start 함수 분리
2. isMove 로직 Engine 으로 이동
3. Race getCarSize 제거, startRacing 함수 수정
4. ResultView showRacing 수정 (Car를 사용하는게 좋은 방식 일까요?)

2023-06-13 10:29 UTC, namjackson commented
> origin/ohsung PR update 된 부분을 push 해야 되는걸로 표시되는데 push 해야 되나요?!
> 다음 step 생성하고 push 하면 되는건가요?!

rebase 되고나면 force push를 해야해서, push를 언제하든 동일할거 같아요!

> 항상 sync fork 로 동기화를 해서 fetch 후 rebase 작업이 어떤 의미인지 잘 이해가 안가서 문의 드립니다.

rebase는 커밋 히스토리가 깔끔하게 정리됩니다, 
또한 다음 미션 PR에 변경된 commit만 보여지기 때문에 협업하기에도 좋아요!
 sync fork  는 merge되는 방식이라 , 자세한건 rebase와 merge의 차이를 한번 알아보셔도 좋을거 같아요!

2023-06-13 10:31 UTC, namjackson requested changes
안녕하세요 성오님! 
5단계 잘 진행해주셨네요! 고생하셨습니다.! 
답변과, 몇가지 추가로 고민할법한 포인트들 코멘트로 남겼으니, 참고해주세요! 
마지막 단계이니, 추가적으로 자유롭게 리팩토링해보셔도 좋을거같아요 😄

2023-06-13 10:31 UTC, namjackson commented on src/main/kotlin/race/model/Engine.kt
> +    fun isRun() = cycle() >= MOVE_CONDITION
isRun으로 추상화한다면 
cycle함수와 MOVE_CONDITION는 추상화 될필요는 없지않을까요?
cycle함수와 MOVE_CONDITION 모두, Engine의 구현체인 RandomEngine의 관심사가 아닐까요?

2023-06-13 10:31 UTC, namjackson commented on src/main/kotlin/race/model/Race.kt
>          }
getWinner 함수를 테스트하여 검증해볼순 없을까요?
private 함수를 테스트해야한다면, 객체 분리의 신호로도 볼수 있어요! 
Winner 관련 클래스를 분리해보아도 좋을거 같아요!

> startRacing 함수가 많은 역활을 하는게 아닐까요?!

Winner 객체를 만들어서, 역할을 위임해주면 해결될거 같아요 👍

2023-06-13 10:31 UTC, namjackson commented on src/test/kotlin/race/RaceTest.kt
> +        }
given("전진 하지 못하는 a,b,c,d 차와 전진만하는 e 가")
when("3번 race했을때,") 
then("우승자는 d 이다") 
으로 분리할수 있을거 같아요! 

우승자를 테스트하기 위해, startRacing해줘야하기 때문에,
독립적인 우승자 테스트는 startRacing에 의존적이라고 할수 있을거 같아요! 
(위의 코멘트로도 남겼지만, )우승자관련 책임을 분리해봐도 좋을거 같아요!

2023-06-13 10:31 UTC, namjackson commented on src/main/kotlin/race/model/Race.kt
> +    fun startRacing(update: ((List<Car>) -> Unit)? = null): String {
> Car를 파라미터 사용하려다가 VIew 에서 Car(Model) 가지고 있어 Pair로 사용했는데요.
> 이런 경우 Car를 사용하거나 새로운 객체를 사용 어떤 방법이 좋은 코드가 될지 문의 드립니다.

이부분은 trade-off 영역이라고 생각이 들어요, 장단점이 있는거 같아요,
Car을 사용한다면, 불필요하게 객체를 새로 만들어 주지 않아도 되는 장점이 있지만, 
불변 객체가 아니라면, 변경의 위험도 생기게되죠.
View에게 데이터 전달을 위해 DTO같은 클래스를 만들어주거나,
RaceHistory와 같은 결과를 담는 객체를 따로 정의해보셔도 좋을거 같아요!

> 그러고 명확하지 않은 Pair는 어떤 경우에 사용하는게 좋을까요?

사실 구현에는 정답이 없기 때문에 참고만해주셔도 좋아요!
저는 보통 객체 생성까지 필요없거나,
의미가 없는 간단한 리턴의 경우에만 필요한 경우에 사용하는거 같아요,
하지만 가능하다면 의미있는 객체를 생성해서 전달하는것을 선호합니다!

2023-06-13 10:31 UTC, namjackson commented on src/main/kotlin/race/model/Car.kt
>      }
> 남재님께서 말씀하신 "테스트를 위한 함수는 지양해주세요 😄" 듣고 수정해서요
> 같은 맥락의 테스트를 위한 수정이지 않을까요?

이 부분도 참고만해주셔도 좋을거 같아요!
생성 시점에 초기 값을 주입받는 방식은 좀더 유연한 객체생성을 할수 있게해준다고 생각이 들어요,
Car마다 시작점이 다른 레이싱을 해야한다면, 특정 Car의 Position의 초기값이 변경된다면 어떻게 대처할수있을까요?
+ 추가로 Car 객체를 불변 객체로 만들어보아도 좋을거같단 생각이 들어요!

2023-06-16 14:27 UTC, ohsung commented
수정 요청 적용하였습니다.
1.  Car 불변 객체로 변경
2. RandomEngine Car에서 Race로 의존관계 변경
3. Winner.kt class 생성

의존 관계가 Car에서 Race로 가면서 우승자 테스트가 어려워진 느낌입니다. 
Car에 있을 경우에는 Car 생성에서  move  설정이 가능했는데 Race 에서는 우승자 테스트가  어렵습니다. 
좋은 방법 문의드립니다.

Winner 객체 생성도 원하신 방향으로 구현이 잘 된건지 모르겠습니다.

2023-06-17 13:37 UTC, namjackson requested changes
안녕하세요 성오님!
피드백 반영 잘해주셨네요 👍 
몇가지 추가적인 피드백 남겼으니, 확인해주세요!

2023-06-17 13:37 UTC, namjackson commented on src/main/kotlin/race/model/Car.kt
> -    val position: Int get() = _position
불변 객체로 변경해주셨네요 👍 
position 또한 불변으로 선언해주셔야 
진정한 불변 객체가 되지 않을까요?

2023-06-17 13:37 UTC, namjackson commented on src/main/kotlin/race/model/Car.kt
> +    val position: Int get() = _position
name, position이 모두 불변변수 (val) 이라면, 
해당 코드는 의미가 없을거 같아요!

```kotlin
data class Car(
    val name: String,
    val position: Int = START_POSITION
) {
```

2023-06-17 13:37 UTC, namjackson commented on src/main/kotlin/race/model/Car.kt
> +        Car(_name = name, _position = position + 1)
data class의 copy를 활용해보아요!
```suggestion
        this.copy(position = position + 1)
```

2023-06-17 13:37 UTC, namjackson commented on src/main/kotlin/race/model/Winner.kt
> +    }
스타일의 차이긴한데,
개인적으로는 let 과같은 범위지정함수의 경우, 불필요하게 쓰는걸 지양하는 편입니다!
(참고만해주세요!)
```suggestion
    fun getWinner(): String {
        val winnerPosition = cars.maxOf { it.position }
        return cars.filter { car -> car.position == winnerPosition }
            .joinToString { it.name }
```

2023-06-17 13:37 UTC, namjackson commented on src/main/kotlin/race/model/Race.kt
> +            it.move(RandomEngine().cycle())
> 의존 관계가 Car에서 Race로 가면서 우승자 테스트가 어려워진 느낌입니다.
> Car에 있을 경우에는 Car 생성에서 move 설정이 가능했는데 Race 에서는 우승자 테스트가 어렵습니다.
> 좋은 방법 문의드립니다.

"RandomEngine Car에서 Race로 의존관계 변경 "과정에서 랜덤의 의존성이 깨졌네요, 
이전 미션들에서 RandomEngine에서 Engine을 추상화한 이유는 어떤 이유였는지 생각해보셔도 좋을거 같아요! 
Race의 생성시점에 Engine을 주입받아보면 어떨까요?

2023-06-17 13:37 UTC, namjackson commented on src/main/kotlin/race/model/Engine.kt
> +    fun isRun() = cycle() >= MOVE_CONDITION
`fun move(count: Int): Car = if (count >= MOVE_CONDITION) {`
car의 함수와 동일한 로직이 존재하네요! 

Engine의 책임은 무엇일까요?
cycle은 어떤 의미이고, 어떤 용도일까요?

저는 개인적으로 Engine은 전진의 유무를 정하는 책임이 있다고 생각이 들어요,
Engine이 특정 숫자인 MOVE_CONDITION =4 보다 커야만 전진을 해야하는 추상화가 필요할까요?
고민해보아요!

2023-06-17 13:37 UTC, namjackson commented on src/test/kotlin/race/RaceTest.kt
> +    // }
위에서도 코멘트 남긴것 처럼 Race의 생성시점에 FakeEngine을 주입하면 테스트할수 있지 않을까요?


우승자 로직이 변경되었으니, Winner 객체의 테스트 코드도 작성해봐도 좋을거같아요!

2023-06-17 14:48 UTC, ohsung commented on src/main/kotlin/race/model/Car.kt
> -    val position: Int get() = _position
자세한 리뷰 감사합니다. 제가 하나에 집중하다보니 놓쳤네요

2023-06-17 14:48 UTC, ohsung commented on src/main/kotlin/race/model/Car.kt
> +        Car(_name = name, _position = position + 1)
좋은 리뷰 감사합니다.

2023-06-17 14:50 UTC, ohsung commented on src/main/kotlin/race/model/Winner.kt
> +    }
저는 let 함수를 좋아해서요.  마지막 return block(this) 좋아해서요 
참고하겠습니다.

2023-06-17 14:56 UTC, ohsung commented on src/main/kotlin/race/model/Race.kt
> +            it.move(RandomEngine().cycle())
의존 타입보다는 Car 객체 Move 테스트가 어려운거 같다는 생각이였는데요.
예를 들어 
Car 객체 Move 에 대해서 Engine 들어가는 거랑 
Race 를 통해 Engine 들어가면 List<Car> 에 대해서 하나의 Engine 들어가기 때문에 다르다고 생각했는데요 

다시 보니까 Winner 를 만들면서 테스트 부분이 해결 된다는 생각이 드네요.

2023-06-18 01:24 UTC, namjackson requested changes
안녕하세요 성오님! 
피드백 적용 잘해주셨네요! 👍 
미션 종료전에 마지막으로 고민할법한 내용 코멘트로 남겼으니, 고민해보아요!

2023-06-18 01:24 UTC, namjackson commented on src/main/kotlin/race/model/Race.kt
> +            it.move(RandomEngine().cycle())
성오님 말씀대로 Winner를 통해 우승자 찾는 로직을 검증할수 있게된거같아요! 👍 
하지만 racing 함수를 통해 Car가 정상적으로 이동하는지, 이동하지 않는지에 대한 검증도 필요하지는 않을까요?

racing함수내에서 RandomEngine에 의존하게 된다면 위의 기능을 검증하긴 어려울거란 생각이 드네요! 
또한 Engine을 추상화하여 인터페이스를 정의한 이유가 없어졌다는 생각이 들어요!
racing 함수에 대한 검증을 고민해보아요!

2023-06-18 01:24 UTC, namjackson commented on src/test/kotlin/race/CarJunitTest.kt
> +    }
테스트가 깨진거 같아요!

2023-06-18 01:24 UTC, namjackson commented on src/test/kotlin/race/WinnerTest.kt
> +        }
```suggestion
        val cars = listOf(
            Car("a"),
            Car("b", position = 4),
            Car("c", position = 2),
            Car("e", position = 1),
        )
```
위처럼 사용할수도 있어요!

2023-06-18 01:25 UTC, namjackson commented
안녕하세요 성오님! 
아마 추가적으로 드릴 피드백이 없어서, 다음 리뷰요청시 미션을 마무리하려고합니다! 
자동차 미션 고생하셨습니다. 미션과정이 의미있는 시간이 되셨길 바랍니다!

2023-06-18 12:53 UTC, ohsung commented
안녕하세요 
남재님 

Race Engine Test Case 추가 하였습니다. 
private 있는 코드에서 테스트 할수 있는 방법인것 같습니다.

효과적인 방법으로는 racing 함수를 class로 만들어서 FakeEngine 으로 테스트 하는 방법이 좋을 것 같습니다.

처음부터 TDD 했으면 지금과 같은 racing 함수가 만들어 지지 않았을것 같다는 생각이 드네요.

지금까지 리뷰 감사드립니다.
많은 도움이 되었습니다.

2023-06-19 05:55 UTC, namjackson commented
@ohsung 안녕하세요 성오님! 
테스트가 불가능한 랜덤 기능에 대한 의존성을 분리하고, 
추상화된 Engine의 Fake객체로 테스트할수 있었네요! 👍 

개인적으로 TDD의 경우, 처음 작성된 테스트코드를 기반으로 에러나 기타 요구사항으로 부터 자유롭게 리팩터링할수 있는 장점이 있지만,
테스트케이스를 작성하는데, 작성된 테스트케이스 및 테스트 코드의 리팩터링 과정에서 
전체적인 구조나 클래스가 변경되어, 테스트코드가 깨지거나, 
작성된 테스트 코드 기반의 리팩터링만 하는 경우도 많은거 같아요! 
( 그래서 좀 이상을 감지하면, 처음부터 다시 코드를 짜보는게 도움이 되는 경우도 있는것 같아요! )

자동차 미션 진행하시느냐 고생많이 하셨습니다! 
다음미션도 응원하겠습니다! 👍

2023-06-19 05:56 UTC, namjackson approved these changes
안녕하세요 성오님 
자동차 미션은 이대로 종료하도록할게요!
자동차 미션 고생하셨습니다! 
다음미션들도 응원하겠습니다! 💪

2023-06-19 05:56 UTC, merged