[Step2] 문자열 계산기 구현
next-step/kotlin-racingcar pull request #1166
Opened 2023-06-12 13:41 UTC by SongSieun

### Overviews
- 문자열 계산기를 구현했습니다.

### 고민거리
- Calculator 내부 함수를 모두 테스트 해야할 지 고민이 좀 되었는데 전체 함수를 테스트 하는 게 좋을까요?
- kotest or JUnit 중에서 자유롭게 사용하면 되는건가요?

2023-06-12 23:23 UTC, Hyeon9mak requested changes
안녕하세요 시은님, 문자열 계산기 구현 고생하셨습니다.
고민해보시면 좋을 부분 코멘트 남겼으니 확인해주세요.
궁금하신 점 코멘트, DM 남겨주세요 🙇‍♂️

2023-06-12 23:23 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/Calculator.kt
> +    fun calculate(question: String?): Int {
별개의 상태가 존재하지 않으므로 class 대신 object 를 활용해볼 수도 있겠네요.

2023-06-12 23:23 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/Calculator.kt
> +                    s.toIntOrNull() ?: throw IllegalArgumentException("question allows only integer or +, -, * and /.")
각각의 연산기호들을 상수처럼 관리해주면 어떨까요? 상수들의 집합은 어떤 식으로 관리해주는게 좋을까요?

2023-06-12 23:23 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/Calculator.kt
> +                    s.toIntOrNull() ?: throw IllegalArgumentException("question allows only integer or +, -, * and /.")
`s` 의 의미는 무엇인가요? 의미를 축약하면 동료 개발자들이 의미 파악에 더 시간을 투자해야 할 것 같아요 😢

2023-06-12 23:23 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/Calculator.kt
> +                    s.toIntOrNull() ?: throw IllegalArgumentException("question allows only integer or +, -, * and /.")
연산 기호를 발견하지 못했을 때 정수로 변환을 시도하는 이유는 무엇일까요? 🤔

2023-06-12 23:23 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/Calculator.kt
> +            }.let { result = it }
`let` 은 언제 활용하는게 가장 적합할까요? 😉 
https://hyeon9mak.github.io/using-kotlin-scope-function-correctly/#-%EC%A0%95%EB%A6%AC

2023-06-12 23:23 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/Calculator.kt
> +    private fun divider(num1: Int, num2: Int) = num1 / num2
연산 데이터 타입이 `Int` 외 `Double`, `Float`, `BigDecimal` 등 다양하게 변할 수 있을 것 같아요.
원시 데이터를 VO 로 포장해보면 어떨까요?

2023-06-12 23:23 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/CalculatorTest.kt
> +    }
꼼꼼한 테스트 작성 👍 👍 

> kotest or JUnit 중에서 자유롭게 사용하면 되는건가요?

넵, 테스트 작성의 의의는 동작 확인이니까 편하신 방법으로 작성해주시면 됩니다 😄 
학습을 위해서 kotest 를 사용하는 것도 좋을 것 같아요.

2023-06-12 23:23 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/CalculatorTest.kt
> +    }
예외 상황에 대한 케이스는 별개로 테스트를 해주시면 동료 개발자들이 의도를 파악하기 더욱 좋을 것 같아요 👍

2023-06-13 07:44 UTC, SongSieun commented on src/test/kotlin/study/calculator/CalculatorTest.kt
> +    }
넵 알겠습니다~!

2023-06-13 07:56 UTC, SongSieun commented on src/test/kotlin/study/calculator/Calculator.kt
> +                    s.toIntOrNull() ?: throw IllegalArgumentException("question allows only integer or +, -, * and /.")
> 연산 기호를 발견하지 못했을 때 정수로 변환을 시도하는 이유는 무엇일까요? 🤔

사칙연산 기호가 아닌 경우 IllegalArgumentException throw하기 위해 사용하였습니다.
사칙기호에 해당하지 않는 문자가 int형으로 변환되지 않는 경우 반환되는 null값을 통해서 사칙연산 기호도 아니고 숫자도 아닌 경우를 필터링하여 IllegalArgumentException을 throw하기 위해 사용하였습니다

2023-06-13 07:59 UTC, SongSieun commented on src/test/kotlin/study/calculator/Calculator.kt
> +                    s.toIntOrNull() ?: throw IllegalArgumentException("question allows only integer or +, -, * and /.")
> `s` 의 의미는 무엇인가요? 의미를 축약하면 동료 개발자들이 의미 파악에 더 시간을 투자해야 할 것 같아요 😢

흠.. `splittedItem`으로 수정하면 괜찮을까요? 
question으로 들어온 문자열을 공백을 기준으로 분리한 리스트의 아이템인데 적절한 네이밍이 생각나지 않네요 ㅜㅜ

2023-06-13 08:00 UTC, SongSieun commented on src/test/kotlin/study/calculator/Calculator.kt
> +    fun calculate(question: String?): Int {
[306fab3](https://github.com/next-step/kotlin-racingcar/pull/1166/commits/306fab3f8e02a03642d8bdfafa3ff60c3eae2d0a) 해당 커밋에서 반영하였습니다 🙇🏻

2023-06-13 08:01 UTC, SongSieun commented on src/test/kotlin/study/calculator/CalculatorTest.kt
> +    }
[refactor: separate test case](https://github.com/next-step/kotlin-racingcar/pull/1166/commits/d57dd6f238725e27eb08a518bbbfc5805859ac43) 해당 커밋에서 반영하였습니다 🙇🏻

2023-06-13 08:03 UTC, SongSieun commented on src/test/kotlin/study/calculator/Calculator.kt
> +            }.let { result = it }
[refactor: modify let to run](https://github.com/next-step/kotlin-racingcar/pull/1166/commits/de1442778f8a5408ce9bb74cb8565ce41d3a2134) run을 사용하도록 수정하였습니다! 🙇🏻

2023-06-13 08:51 UTC, SongSieun commented on src/test/kotlin/study/calculator/Calculator.kt
> +                    s.toIntOrNull() ?: throw IllegalArgumentException("question allows only integer or +, -, * and /.")
> 각각의 연산기호들을 상수처럼 관리해주면 어떨까요? 상수들의 집합은 어떤 식으로 관리해주는게 좋을까요?

[de14427](https://github.com/next-step/kotlin-racingcar/pull/1166/commits/de1442778f8a5408ce9bb74cb8565ce41d3a2134) 해당 커밋에서 반영했습니다! 🙇

2023-06-13 23:52 UTC, Hyeon9mak approved these changes
안녕하세요 시은님, 피드백 잘 반영해주셨습니다 👍 
다음 단계를 진행하시면서 참고하실만한 코멘트 몇 개 남겼습니다.
다음 단계에서 만나요~ 👋

2023-06-13 23:52 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/CalculatorOperator.kt
> +}
enum class, bifunction 활용 👍 👍 
앞으로 연산자를 확인할 때도 `CalculatorOperator` 만 열어보면 되고,
`CalculatorOperator` 를 이용한 연산로직이 여기저기 파편화되는 문제도 방지할 수 있겠네요.

2023-06-13 23:52 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/Calculator.kt
> +        if (question.isNullOrEmpty()) throw IllegalArgumentException("question was null or empty.")
`require` 를 사용해보는 것도 좋아보여요 😄 

```kotlin
require(question.isNullOrEmpty().not()) { "..." }
```

2023-06-13 23:52 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/Calculator.kt
> +
엄청 가벼워졌네요~ 👍

2023-06-13 23:52 UTC, Hyeon9mak commented on src/test/kotlin/study/calculator/CalculatorTest.kt
> +            .hasMessageContaining("question allows only integer or +, -, * and /.")
해당 테스트는 `CalculatorOperator` 테스트로 분리할수도 있겠어요 😄 👍

2023-06-13 23:52 UTC, merged