Step5 리뷰 요청드립니다
next-step/kotlin-racingcar pull request #1175
Opened 2023-06-12 16:01 UTC by sjparkk

이전 리뷰 사항 반영 내용입니다.

1. 동작 여부를 확인할 수 있도록 main 함수를 추가하였습니다!

2. 이전 요구 사항을 유지해야되는 줄 알고 포함하고 있었습니다..! 이전 요구사항은 없애고 최신 요구 사항으로 수정하였습니다!

3. 새로운 요구 사항인 이름으로 자동차를 생성하는 테스트 검증 코드를 추가하였습니다

4. 네이밍 수정 사항 반영하였습니다!

감사합니다!

2023-06-13 03:40 UTC, D000L requested changes
마지막 step 잘 진행 해주셨습니다.
간단한 수정 사항이 하나 있는데, 수정 후에 바로 머지하도록 하겠습니다.~!

2023-06-13 03:40 UTC, D000L commented on src/main/kotlin/racing/controller/RacingController.kt
> +        carNameViewRacing(tryCount, cars)
출력이 요구사항과 다른 것 같습니다.

현재는
"""
경주할 자동차 이름을 입력하세요(이름은 쉼포(,)를 기준으로 구분).
a,a,b,b,b,d
실행 결과
시도할 횟수는 몇 회 인가요?
10
"""
식으로 "실행 결과" 부분이 횟수보다 앞쪽에 나오고 있습니다.

2023-06-13 03:40 UTC, D000L commented on src/test/kotlin/racing/RacingControllerTest.kt
> +        RacingController(InputView, ResultView).racingGame()
이 부분은 아직  실행에 대한 검증이 빠져있습니다.
검증에 대한 테스트를 진행하시기 어렵다면, UI 부분을 인터페이스하여 해당 인터페이스의 함수들에 적절한 파라미터들이 들어오는지로 테스트하실 수있습니다. 
( 이 한번 해보고 싶으시면 진행해 주시면, 아니면 한번 고민만 해보시면 좋을것 같습니다. )

2023-06-13 15:14 UTC, sjparkk commented
안녕하세요!

먼저 출력 순서가 문제되었던 코드 수정하였습니다.

그리고 피드백 주신 부분 중에 실행에 대한 검증이 빠진 테스트 케이스에 대해서 질문 드립니다.

먼저 테스트 케이스는 아래 1,2번 두개가 존재하였는데 그 중 1번은 이전(step3)에 대한 내용이라 rasingGame() 함수 자체가 step4 구현 내용으로 수정되어 1번의 테스트 케이스는 삭제하였습니다.

1. 레이싱 경주 출력 결과
2. 레이싱 경주(우승자) 출력 결과

문제는 2번도 여전히 실행에 대한 검증이 빠져있는 상태인데요.

원래 해당 케이스의 테스트는 실행에 대한 출력을 확인하기 위해서 생성한 코드였는데 테스트 케이스의 목적상 검증하는 부분이 빠져있기 때문에 삭제하는 것이 맞을까요? 아니면 이렇게 자동차 레이싱의 출력에 대한 전체 결과를 보는 테스트에서도 어떤 유의미한 검증을 할 수 있을까요? (애초에 출력을 확인하기 위해 만들어진 테스트 케이스고 현재는 main 함수에서 실행 결과를 볼 수 있기 때문에 테스트 검증 부분이 없는 이상 삭제하는 것이 맞을까요?)

2023-06-13 15:24 UTC, D000L commented
@sjparkk 
넵 질문감사합니다.

질문주신 테스트는 검증 없이 레이싱 결과만을 출력하는 테스트로 사실상 테스트로서의 역할을 할 수 없습니다.

첫번째 이유는 해당 테스트에서 어떠한 출력을 했다는 정보 또는 정확한 출력을 했다는 확신을 얻기위해서는 테스트시에 어떠한 출력을 했는지 직접 눈으로 확인해야 합니다. 
하지만, 대부분의 테스트는 직접 돌려서 확인하는 케이스보다는 commit 시에 돌아간다거나, pr 시에 돌아가는 것처럼 코드 검증에 대한 자동화를 목적으로 합니다. 그렇기 때문에 직접 눈으로 보아야만 확인할 수 있는 검증 없는 테스트는 테스트로서의 유의미한 효과를 형성하기 어렵습니다.

두번째 이유는 단순히 출력만을 하는 테스트는 통과가 되었는다 정보가지고는 해당 출력이 정확한지에 대한 판단을 할 수 없습니다. 왜냐면 출력방식을 변경하거나 출력내용이 변경되어도 항상 테스트는 통과할 것이기 때믄입니다.

의견 주신대로 검증이 없는 테스트는 이미 없는것과 마찬가지로 보입니다.

2023-06-13 15:27 UTC, D000L approved these changes
마지막 단계 까지 잘 작성해주셨습니다.!
이것으로 미션 마무리 하도록 하겠습니다. 2주차 미션 화이팅하시길 바랍니다.~
질문주신 내용은 답변 달아놓았습니다. 더 궁금하신 내용이 있으시면 dm 으로 질문주시면 확인해보겠습니다.

2023-06-13 15:27 UTC, merged

2023-06-14 11:44 UTC, sjparkk commented
감사합니다~!! :)