[Step3] 자동차 경주
next-step/kotlin-racingcar pull request #1177
Opened 2023-06-12 17:28 UTC by Kyudong3

step3 자동차 경주 리뷰 부탁드립니다~!

테스트 코드를 아직 어떻게 작성해야 할 지 감이 잘 안 오는데 부족한 부분 리뷰 부탁드립니다!!

감사합니다

2023-06-13 10:12 UTC, sah3122 requested changes
자동차 경주 구현 잘해주셨습니다 👍 
몇가지 고민거리를 남겨두었는데 확인 부탁드려요 😄

2023-06-13 10:12 UTC, sah3122 commented on src/main/kotlin/study/step3/Car.kt
> +    val stateList: MutableList<Int> = mutableListOf()
변경가능한 컬렉션이 외부로 노출된다면 어떤 문제점이 있을지 고민해보세요 😄

2023-06-13 10:12 UTC, sah3122 commented on src/main/kotlin/study/step3/InputView.kt
> +object InputView {
InputView 정의 👍

2023-06-13 10:12 UTC, sah3122 commented on src/main/kotlin/study/step3/Car.kt
> +    val stateList: MutableList<Int> = mutableListOf()
변수명에 타입을 선언하는것과 복수형을 선언하는것에 대해 차이점을 고민해보세요 😄

2023-06-13 10:12 UTC, sah3122 commented on src/main/kotlin/study/step3/RacingCarGame.kt
> +    private fun prepareRacingCars(carCount: Int) {
carList를 변경 불가능한 컬렉션으로 선언할수 있을것 같아요 😄 
해당 로직을 init 블록을 사용해 구현해보는건 어떨까요 ?

2023-06-13 10:12 UTC, sah3122 commented on src/main/kotlin/study/step3/RacingCarGame.kt
> +                car.move(randomValue >= 4)
RandomGenerator() 에 의존하여 자동차의 움직임 여부를 판단하는 로직을 전략 패턴을 적용시켜 보는건 어떨까요 ? 
이번 미션에서 전략 패턴을 사용해보는것을 권장 드립니다 😄 
https://itstory.tk/entry/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EA%B7%9C%EC%B9%9921-%EC%A0%84%EB%9E%B5%EC%9D%84-%ED%91%9C%ED%98%84%ED%95%98%EA%B3%A0-%EC%8B%B6%EC%9D%84-%EB%95%8C%EB%8A%94-%ED%95%A8%EC%88%98-%EA%B0%9D%EC%B2%B4%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC

2023-06-13 10:12 UTC, sah3122 commented on src/test/kotlin/study/step3/RacingCarGameTest.kt
> +        }
테스트 코드는 로직을 포함하고 있지 않고 실행과 결과만 존재해야 합니다. 
랜덤값과 같이 런타임 시점에 결정되는 값에 의존하지 않고 테스트를 작성할수 있는 방법을 고민해보세요 😄
앞서 이야기 드린 전략 패턴을 사용하여 프로덕션 코드는 랜덤 전략을 사용하고, 테스트 코드는 전진하는 전략과 전진하지 않는 전략을 주입하는 구조가 된다면 테스트 코드 작성이 용이할거에요 😄

2023-06-13 10:12 UTC, sah3122 commented on src/test/kotlin/study/step3/RacingCarGameTest.kt
> +class RacingCarGameTest {
이번 과정을 진행하면서는 도메인 단위 테스트 코드는 필수로 작성해보세요 😄 
UI 관련 클래스가 아니라면 공개되어 있는 함수의 테스트를 모두 작성하는것을 권장 드립니다 !

2023-06-13 12:41 UTC, Kyudong3 commented on src/main/kotlin/study/step3/Car.kt
> +    val stateList: MutableList<Int> = mutableListOf()
변경가능한 컬렉션은 private으로 제한하고 불변한 List 타입으로 반환하는 함수를 따로 만들었어요!

2023-06-13 12:45 UTC, Kyudong3 commented on src/main/kotlin/study/step3/Car.kt
> +    val stateList: MutableList<Int> = mutableListOf()
변수명에 `stateList`와 같이 타입을 선언하게 되면 불변임을 나타내고
`states`와 같이 복수형으로 선언하면 불변보다 조금 더 리스트의 값들을 나타낼 수 있을 것 같습니다! 생각한 것이 맞는지는 모르겠네요 ㅎㅎ
가변인 MutableList로 타입을 선언했기 때문에 stateList -> states로 변경했어요!

2023-06-13 16:39 UTC, Kyudong3 commented on src/main/kotlin/study/step3/RacingCarGame.kt
> +                car.move(randomValue >= 4)
전략 패턴을 사용해 구현해보았어요! 🙏🏼

2023-06-13 16:39 UTC, Kyudong3 commented on src/test/kotlin/study/step3/RacingCarGameTest.kt
> +        }
테스트 코드에 로직이 들어가지 않고 실행과 결과만 존재해야 한다는 사실을 배웠습니다..! 🙏🏼 
랜덤값에 의존하지 않도록 수정해보았어요!

2023-06-14 13:05 UTC, sah3122 commented on src/main/kotlin/study/step3/Car.kt
> +    val stateList: MutableList<Int> = mutableListOf()
변수명에 구체적인 타입이 포함되면 유연하게 컬렉션을 사용하지 못하게 되어 코멘트 남겨드렸습니다. 
예를 들어 List 라는 타입이 변수명에 포함된다면 Set 컬렉션으로 변경하는 경우 해당 변수를 사용하는 모든 코드가 영향을 받습니다. 
이러한 이유로 특정한 타입을 변수에 선언하기 보단, 복수형과 같이 선언하는 편입니다 😄

2023-06-14 13:23 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
생각거리 몇가지 남겨두었는데 다음 미션을 진행하며 도전해보세요 😄

2023-06-14 13:23 UTC, sah3122 commented on src/main/kotlin/study/step3/Car.kt
> +    fun getStateList(): List<Int> = states
명시적으로 listOf()와 같이 선언해주는것도 좋을것 같아요 😄

2023-06-14 13:23 UTC, sah3122 commented on src/main/kotlin/study/step3/RacingCarGame.kt
> +    }
초기화 👍

2023-06-14 13:23 UTC, sah3122 commented on src/test/kotlin/study/step3/RacingCarGameTest.kt
> +    fun `0에서 9사이 무작위 값을 구해 4 이상일 경우 전진`(condition: Int) {
RandomGenerator 로직이 검증이 되었을까요 ? 
```
RacingCarGame(actualRacingRequest, CarNotMove()) 
RacingCarGame(actualRacingRequest, CarCanMove()) 
```
위와 같이 테스트를 위한 전략 객체를 사용한다면 테스트 하기 어려운 프로덕션 코드를 검증할수 있을거에요 😄

2023-06-14 13:24 UTC, merged

2023-06-14 14:20 UTC, Kyudong3 commented on src/main/kotlin/study/step3/Car.kt
> +    val stateList: MutableList<Int> = mutableListOf()
답변 감사합니다!