Step3 - Racing Car 구현
next-step/kotlin-racingcar pull request #1183
Opened 2023-06-13 08:12 UTC by oliveunji

안녕하세요 이번 커밋에서 중점을 둔 부분은 다음과 같습니다.

- **Domain, Controller, View로 나누어 코드 작성** : 다른 분들이 작성해주신 코드를 보니 나누어 작성한 코드가 많아 이렇게 변경했습니다.
- **요구사항 변경시, 유연하게 대처하기 위한 코드 설계** => racing로직 (현재는 랜덤넘버 생성)이 추후 변경될 수 있다고 생각하였고, Race 함수 바깥에서 선언했습니다. 더 좋은 방법이 있다면 가이드 부탁 드립니다.  또한 Race 클래스와 Car 클래스가 서로 영향을 받지 않게 설계하고자 하였습니다. 

## 궁금한 사항
RacingCarController 클래스에 대해 Unit Test를 어떻게 작성해야 할지 모르겠습니다. 조언 부탁 드립니다! 🙏

2023-06-13 23:45 UTC, Hyeon9mak requested changes
안녕하세요 은지님, 3단계 진행 고생 많으셨습니다! 
고민이 많으셨던거 같아요 😄 이번 단계에서 많은 걸 얻어가시면 좋겠습니다.

> Domain, Controller, View로 나누어 코드 작성

나누어 작성하는 시도도 좋지만, 다른 분들의 코드를 의식하고 따라해보시는 부분이 좋다고 생각합니다 👍 
'저 사람은 왜 저렇게 작성했을까?', '이런 장단점이 있구나.' 일련의 과정이 모두 뼈와 살이 되는거 같아요.

>  랜덤넘버 생성과 racing 분리

이후 자동차 이동 조건이 변경될 수 있기 때문에 좋은 분리라고 생각합니다 👍 
그러나 당장 주어진 요구사항에 대한 검증이 어려운 상황인데요, 
어떻게 하면 해당 부분을 충족시킬 수 있을지 고민해보면 좋겠어요.

> RacingCarController 테스트

RacingCarController 에서 부담하고 있는 전체 기능들을
각 단위로 분리하여 별개 클래스로 만들고, 그 클래스를 테스트 하는 방법은 어떨까요?
우선 미션 요구사항에 주어진 부분을 중점적으로 분리하고 테스트를 해보면 좋을 것 같습니다 😄 👍 

또한 이전 미션부터 커밋내용이 계속해서 이어지고 있는데요,
아래 링크를 참고하셔서 PR 을 작성해주셔도 좋을 것 같아요 😄 👍 
https://edu.nextstep.camp/s/w5G1pCe7/ls/TLrWzZx5

궁금하신 점 코멘트, DM 남겨주세요 🙇‍♂️

2023-06-13 23:45 UTC, Hyeon9mak commented on README.md
> +- [x] 유닛 테스트 작성
꼼꼼한 요구사항 관리 👍

2023-06-13 23:45 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/view/ResultView.kt
> +    println()
input view 와 마찬가지로 object 로 관리해줄 수 있겠네요!

2023-06-13 23:45 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/view/ResultView.kt
> +    println()
`repeat` 은 아래와 같은 방법으로도 축약할 수 있겠어요.

```kotlin
repeat(position) { print(PRINT_SYMBOL) }
```

2023-06-13 23:45 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/controller/RacingCarController.kt
> +    }
for 대신 출력에 사용해주셨던 repeat 을 활용할 수도 있겠네요!

2023-06-13 23:45 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/controller/RacingCarController.kt
> +    }
현재 매 루프마다 `Race` 객체가 생성되고 있는데요, 
`createCars` 에서 자동차 목록에 대한 객체를 만들고 그 객체에게
 "자동차들을 한번씩 움직이고, 그 상태를 가져와" 라고 명령을 내려보는 건 어떨까요?

2023-06-13 23:45 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/controller/RacingCarController.kt
> +        return cars
```suggestion
        return List(count) { Car() }
```
요런 것도 가능합니다 😎

2023-06-13 23:45 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/domain/Race.kt
> +    return Random.nextInt(RANDOM_NUM_RANGE) >= REFERENCE_VAL
```suggestion
    return Random.nextInt(0..9) >= REFERENCE_VAL
```

다른 곳에서 활용해주신 것처럼, range 를 활용해주면 보다 더 직관적인 표현이 가능하겠네요!

2023-06-13 23:45 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/domain/Race.kt
> +}
> 전진하는 조건은 0에서 9 사이에서 무작위 값을 구한 후 무작위 값이 4 이상일 경우이다.

자동차 전진 조건을 충족했는지 테스트 코드 작성이 어려워보여요.
랜덤한 숫자를 자동차가 전달 받고, 이걸 기준으로 전진할지 말지를 결정한다면
테스트 코드 작성이 훨씬 편리해질 것 같아요!

2023-06-13 23:45 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/view/InputView.kt
> +    }
```kotlin
    fun getNumberOfCar(): Int {
        println("자동차 대수는 몇 대인가요?")
        return readlnOrNull()?.toIntOrNull() ?: 0
    }

    fun getNumberOfTrial(): Int {
        println("시도할 횟수는 몇 회인가요?")
        return readln().toInt()
    }
```

`readlnOrNull()` 혹은 `readln()` 를 활용해봐도 좋겠어요 😄

2023-06-13 23:45 UTC, Hyeon9mak commented on src/test/kotlin/racingCar/domain/RaceTest.kt
> +    }
무의미한 검증 같아요 😭

2023-06-14 00:25 UTC, oliveunji commented on src/main/kotlin/racingCar/view/ResultView.kt
> +    println()
감사합니다!!!

2023-06-14 07:24 UTC, oliveunji commented on src/main/kotlin/racingCar/controller/RacingCarController.kt
> +    }
이렇게 개선해보니까 Race Class가 필요 없는 것 같아서 삭제했는데 맞는 접근인지 궁금합니다! 
다음과 같이 수정했습니다. 
```Kotlin
    fun main() {
        val numberOfCar: Int = InputView.getNumberOfCar()
        val numberOfRace: Int = InputView.getNumberOfTrial()

        val cars = createCars(numberOfCar)
        ResultView.printStart()

        repeat(numberOfRace) {
            cars.forEach{
                car -> car.move(randomNumberGenerator())
            }
            ResultView.printResult(cars)
        }
    }
```

2023-06-14 07:33 UTC, oliveunji commented on src/main/kotlin/racingCar/controller/RacingCarController.kt
> +    }
race class를 따로 분리하기 어려웠던 이유는, randomNumberGenerator 함수를 race class에 어떻게 넘겨줄지 고민이 되어서 분리하지 못했습니다. 고민을 많이해봤는데 해결이 안되서 부족함에도 불구하고 현재 버전의 코드를 업로드 합니다!

2023-06-14 23:32 UTC, Hyeon9mak requested changes
안녕하세요 은지님, 3단계 branch 에 코드 수정하신 내용이 push 되지 않은 것 같습니다. 
push 후 다시 요청 주시면 리뷰 진행하도록 하겠습니다. 🙏

2023-06-15 00:27 UTC, oliveunji commented
> 안녕하세요 은지님, 3단계 branch 에 코드 수정하신 내용이 push 되지 않은 것 같습니다. push 후 다시 요청 주시면 리뷰 진행하도록 하겠습니다. 🙏

헉 제가 실수했습니다 ㅠㅠ 다시 요청드립니다! 감사합니다!

2023-06-15 00:38 UTC, oliveunji reviewed
말씀해주신 변경사항 반영하여 Commit 했습니다!

2023-06-16 00:59 UTC, Hyeon9mak approved these changes
안녕하세요 은지님, 피드백 잘 반영해주셨습니다.
조금씩 구조가 잡혀나가는 것 같아요~
바로 다음 단계로 가시죠~

> 개선해보니까 Race Class가 필요 없는 것 같아서 삭제했는데 맞는 접근인지 궁금합니다!

현재 구조도 충분히 유지보수가 쉬울 것 같고, 분리가 불필요하다고 느껴지시면 적극적으로 없애셔도 됩니다.
다음 단계도 화이팅~ 💪

2023-06-16 00:59 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/view/ResultView.kt
> +    }
👍

2023-06-16 00:59 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/controller/RacingCarController.kt
> +    }
메서드 명칭은 난수 생성기인데.. 실제로는 난수를 반환하는거 같아요!
조금 더 직관적인 네이밍이 부여되면 좋겠네요 😄

2023-06-16 00:59 UTC, Hyeon9mak commented on src/main/kotlin/racingCar/domain/Car.kt
> +    }
👍 테스트 코드 작성도 훨씬 수월해졌네요 😄

2023-06-16 00:59 UTC, Hyeon9mak commented on src/test/kotlin/racingCar/domain/CarTest.kt
> +    }
가능하면 경계값 테스트를 진행해주세요 😄 👍

2023-06-16 00:59 UTC, merged