Step5 자동차 경주(리팩터링)
next-step/kotlin-racingcar pull request #1191
Opened 2023-06-13 15:09 UTC by Wordbe

domain, view, controller(RacingMain) 으로 분리했습니다.
테스트 불가한 RandomMovePolicy 는 컨트롤러(최상위계층) 바깥으로 분리하여 테스트 가능한 것만 테스트하도록 했습니다.

2023-06-14 04:16 UTC, Rok93 requested changes
성호님 마지막 단계도 잘 구현해주셨네요! 👍💯
다만 실행결과를 출력하는 부분이 의도한대로 잘 실행되지 않는 것 같아요. 👀
관련해서는 코멘트 남겨두었으니 확인해서 반영해주시면 좋을 것 같아요. 🙏
그 외에도 조금 더 고민해보면 좋을 부분들 코멘트 남겨두었으니 확인해주시고 반영해주실 내용이있다면 반영해주시면 감사하겠습니다. 😊 

잘 이해가 안되는 코멘트 혹은 미션 진행하시면서 어려운점이 있으시면 언제든지 DM 주세요! 🙏

2023-06-14 04:16 UTC, Rok93 commented on src/main/kotlin/racing/view/View.kt
> +        val winners = cars.getWinners().joinToString(WINNER_DELIMITER)
언뜻보면 getWinners()는 getter와 같이 상태 값을 꺼내는 것 같지만, 실제로는 내부적으로 우승자를 선별하는 로직(= 비즈니스 로직)이 포함되어있어요.
InputView는 View의 영역인데 Model의 역할인 비즈니스 로직을 수행하고있는 상황이라고 볼 수 있을 것 같아요. 🤔
메서드 파라미터로 `winners: List<String>`를 주입받는 것이 MVC 패턴을 잘 지킨 구조이지 않을까요? 😃

2023-06-14 04:16 UTC, Rok93 commented on src/test/kotlin/racing/domain/RacingGameTest.kt
> +        val raceResult: List<Cars> = racingGame.race(tryCount = 2, movePolicy = { true })
타입 추론 기능을 사용하셔도 될 것 같은데, 타입을 구체적으로 명시하신 이유가 있을까요? 🤔

2023-06-14 04:16 UTC, Rok93 commented on src/test/kotlin/racing/domain/RacingGameTest.kt
> +        lastCars[2].position shouldBe 6
raceResult size가 tryCount 값과 같을 것 같은데, 현재 이 테스트에서는 `1`번 index(마지막 요소)에 대해서만 검증하고있어요. 👀
`0`번 index의 결과에 대해서도 검증이 필요할 것 같아요. 😃

2023-06-14 04:16 UTC, Rok93 commented on src/main/kotlin/racing/domain/RacingGame.kt
> +    }
콘솔로 자동차경주 게임을 실행시켰을 때, 결과 값 확인해보셨을까요? 👀

![image](https://github.com/next-step/kotlin-racingcar/assets/47850258/bcf27283-5a6e-4063-8512-091c1fe15d66)

결과를 살펴보면 반복되는 position 결과들이 동일해요. 
이는 List에 매 시도횟수마다 저장되는  Cars 객체는 동일한 객체이기 때문에 Cars 객체의 변경은 이미 List에 추가된 Cars 객체(뿐만아니라 Cars 객체가 가지는 각각의 Car 객체들도 동일)와 같은 주소값을 가리키기 때문이에요. 😃
아 내용을 참고하셔서 정상적인 결과값이 출력되도록 변경해주세요! 🙏

아래의 참고자료도 같이 살펴보시면 좋을 것 같아요. 😁
(사실 코드상으로 복사의 행위를 한 것은 아니기 때문에 엄밀히 말하면 이 개념은 아니지만 핵심적인 내용이 여기에 있다고 생각해서 같이 첨부드렸어요)
[깊은복사 vs 얕은복사](https://rok93.tistory.com/entry/%EC%96%95%EC%9D%80%EB%B3%B5%EC%82%AC-VS-%EA%B9%8A%EC%9D%80%EB%B3%B5%EC%82%AC)

2023-06-14 04:16 UTC, Rok93 commented on src/main/kotlin/racing/domain/RandomMovePolicy.kt
> +package racing.domain
MVC 모델로 분리하면서 적절히 패키지도 분리해주셨네요. 👍👍👍

2023-06-14 04:16 UTC, Rok93 commented on src/main/kotlin/racing/domain/RacingGame.kt
> +    fun race(tryCount: Int, movePolicy: MovePolicy): List<Cars> {
RacingGame 객체의 입장에서 `tryCount`(시도횟수)는 외부에서 주입을 받는게 좋을지 RacingGame 객체가 `tryCount`를 상태 값으로 가지는게 좋을지에 대해서 고민해보시면 좋을 것 같아요. 😊

2023-06-14 04:16 UTC, Rok93 commented on src/test/kotlin/racing/domain/CarsTest.kt
> +fun cars() = Cars(
testFixture를 쉽게 만들기위한 메서드를 만드셨군요!  매우좋은 시도라고 생각해요.  👍👍
하지만 지금의 경우에는 이 메서드를 통해서 생성하는 Cars 일급 컬렉션이 어떤 Car 객체들을 가지고있는지 그 세부 구현을 사용하는 개발자가 

 Cars Test 객체를 생성하는 메서드가 3개의 Car 객체를 포함하고있고, 또 각각의 Car 객체의 초기 position 값이 얼마인지 TestFixture를 사용하는 개발자가 알고있어야한다는 문제점이 있어요. 이 문제점을 해결할만한 좋은 방법이 지금 당장에는 안떠올라서, 저라면 조금 번거롭더라도, cars 객체가 필요한 테스트 코드에서 매번 Cars 객체를 새롭게 정의를 할 것 같아요.

또한, 이 testFixture 객체를 생성하는 로직은 어디에 위치하는게 좋을까요? 🤔
Cars 객체를 생성하니 CarsTest 파일에 있는 것도 괜찮은 방법이 될 수도 있지만, 코드양이 많아질수록 테스트 코드와 Test Fixture를 생성하는 로직이 뒤섞여서 TestFixture 생성 코드를 확인하기가 어려워질 것 같아요. 

저 같은 경우에는  CarsTestFixture 라는 별도의 파일을 만들고, 이 파일에서 Cars TestFixture를 생성하는 로직들을 관리하는 편이에요. 😁

[우아한테크코스의 지원플랫폼 파트](https://github.com/woowacourse/service-apply/blob/master/src/test/kotlin/apply/JudgmentFixtures.kt)에서도 제가 언급한 방식과 동일한 방식으로 TestFixture를 관리하고있네요. 😃

2023-06-14 15:35 UTC, Wordbe commented on src/main/kotlin/racing/view/View.kt
> +        val winners = cars.getWinners().joinToString(WINNER_DELIMITER)
말씀하신게 옳네요. 반영했습니다 😁

2023-06-14 15:38 UTC, Wordbe commented on src/test/kotlin/racing/domain/RacingGameTest.kt
> +        val raceResult: List<Cars> = racingGame.race(tryCount = 2, movePolicy = { true })
추론을 할 수도 있지만, race 메소드를 처음보는 사람은 반환값이 뭔지 모를 수 있어서 가독성을 높이기 위해 타입을 명시해봤습니다 😀

2023-06-14 16:03 UTC, Wordbe commented on src/main/kotlin/racing/domain/RacingGame.kt
> +    fun race(tryCount: Int, movePolicy: MovePolicy): List<Cars> {
생각해보니 객체입장에서 자동차 경주 게임이 시도횟수도 같이 가지고 있는게 적합할 것 같네요. 🙏

2023-06-14 16:05 UTC, Wordbe commented on src/main/kotlin/racing/domain/RacingGame.kt
> +    }
😱😱😱 제대로 확인을 하지 않았었네요.
`mutate` 메소드를 만들어 깊은 복사를 하도록 구현했습니다.
마침 race 에 대한 테스트도 마지막 자동차만 테스트하도록 되어있어서 이 부분을 빠뜨린 것 같습니다.
피드백 감사합니다 🙏🙏👏

2023-06-14 16:06 UTC, Wordbe commented on src/test/kotlin/racing/domain/RacingGameTest.kt
> +        lastCars[2].position shouldBe 6
모든 테스트를 하도록 추가했습니다 😀
아래 race 가 정상작동하지 않는 것을 보니, 꼼꼼한 테스트가 중요한 이유를 알았네요.
감사합니다. 😁

2023-06-14 16:17 UTC, Wordbe commented on src/test/kotlin/racing/domain/CarsTest.kt
> +fun cars() = Cars(
`CarsTextFixture` 예시 감사합니다
코틀린은 named arguments 를 지원해서 이런 픽스쳐를 만들어내기 용이한 장점이 있더라구요.

또 말씀해주신 부분에 대해 테스트코드는 가급적 DRY 대신 DAMP(Descriptive And Meaningful Phrase) 를 지향하라 라는 말이 떠오르네요. (구글엔지니어는 이렇게 일한다, 12장 단위테스트)
중복되는 부분을 재사용하도록 만들고자하는 욕구가 있지만, 테스트코드에는 좀 반대로 하려고 노력해봐야겠어요.
감사합니다 😄

2023-06-15 13:49 UTC, Rok93 approved these changes
성호님 고생많으셨어요! 👏👏👏 
워낙 자동차 경주 미션 잘 구현해주셨었고 추가적으로 피드백 반영도 잘 해주셔서 자동차 경주 미션은 이만 종료하려고합니다. 😁 

남은 미션들도 이번 미션처럼 충분히 잘하실거라 생각합니다. 
이어지는 다른 미션들도 꼭 완주하시길...  화이팅입니다! 💪

2023-06-15 13:49 UTC, Rok93 commented on src/main/kotlin/racing/domain/RacingGame.kt
> +    )
지금은 사용처가 한군데 뿐인 기능이라, 지금 구현하기에는 오버엔지니어링이 될 수도 있을 것 같지만 조금 더 나아가서 Cars의 확장함수 혹은 Cars의 함수로 깊은복사 기능을 제공하도록 할 수도 있을 것 같아요. 😃

#### 확장함수 예시
```kotlin
fun Cars.deepCopy(): Cars = Cars(
    cars = this.map {
        Car(
            name = it.name,
            position = it.position,
        )
    }
)
```

만약 Car가 Data Class였다면, `copy()` 함수를 통해서 매번 Car 객체를 생성하는 로직을 단순히 copy() 함수를 호출하는 로직으로 변경해볼 수도 있겠네요. 😊 

지금 Car 클래스를 Data Class로 변경하게되면, 지금처럼 position을 `private set`하게 방어하지 못하게 될 것 같아요. 
그러면 Car class를 불변객체로 가져가거나 private set을 포기해야하는 상황이 될 것 같은데, 전자는 코드 변경이 생각보다 많을 것 같고 후자는 지금 상황에서는 피하고싶은 선택지일 것 같아요. 🤔

그냥 Data Class의 copy() 함수를 언급해보고자 꺼내본 이야기니, 이런 방법도 있겠구나? 정도로 생각해주시면 될 것 같아요. 😁

```suggestion
    private fun mutate() = Cars(
        cars.map { it.copy() }
    )
```

2023-06-15 13:49 UTC, merged

2023-06-15 14:03 UTC, Wordbe commented on src/main/kotlin/racing/domain/RacingGame.kt
> +    )
좋은 확장함수 예시 감사합니다.
자동차 경주 과제 동안 리뷰 함께해주셔서 감사합니다.
덕분에 많이 배웠습니다. 👍👏👏👏😀