Step3 - 자동차 경주
next-step/kotlin-racingcar pull request #1202
Opened 2023-06-14 16:16 UTC by sumniy

리뷰 잘 부탁드리겠습니다!

2023-06-15 11:52 UTC, ohgillwhan requested changes
코드 좋습니다! 조금 더 고민해볼 만한 리뷰를 남겨봤어요.
확인 부탁드리며, 요구사항 정의도 한번 작성해볼까요?

2023-06-15 11:52 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Car.kt
> +        private set
외부에 안보이게 하는것 좋네요! 💯

2023-06-15 11:52 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Car.kt
> +    }
요구사항을 텍스트로 정의해보면
어떠한 조건을 만족하면(랜덤한 숫자가 나오고 4이상 일 경우) 전진한다. 일것 같아요. 
이 어떠한 조건이 외부에서 결정되어서 넘어오는것 같아요.  결국 랜덤은 이 안에서 결정해야 하지 않을까요?

2023-06-15 11:52 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Cars.kt
> +        cars.forEach { it.move((0..9).random()) }
`random()` 💯

2023-06-15 11:52 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Cars.kt
> +    }
`moveAll()`의 리턴을 잘 활용하면, 해당 함수 없이도 가능할것 같아요. 디미터 법칙도 한번 지켜볼까요?

2023-06-15 11:52 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Cars.kt
> +        cars.forEach { it.move((0..9).random()) }
`moveAll()`도 테스트가 가능하면 좋겠는데, `random()` 이라서 쉽지 않은것 같아요.
이렇게 변하기 쉬운것은 전략패턴을 이용해보는건 어떨까요?
https://victorydntmd.tistory.com/292

2023-06-15 11:52 UTC, ohgillwhan commented on src/main/kotlin/racingcar/view/InputView.kt
> +object InputView {
전체적으로 좋은 코드 💯

2023-06-15 11:52 UTC, ohgillwhan commented on src/main/kotlin/racingcar/view/ResultView.kt
> +    fun printResult(positions: List<Int>) {
좋네요~

2023-06-15 11:52 UTC, ohgillwhan commented on src/test/kotlin/racingcar/CarTest.kt
> +class CarTest {
코드 좋습니다!

2023-06-15 11:52 UTC, ohgillwhan commented on src/main/kotlin/racingcar/RacingGame.kt
> +        tryCount = InputView.receiveTryCount()
만약에 자동차 경주 게임이 너무 인기가 많아서, 웹으로 전환해야 한다고 했을 때 `InputView`를 사용하지 않아도 될거 같아요. 결국 `RacingGame`은 `domain`과 같이 외부 입출력에는 무관하게 동작해야 할거 같아요.

2023-06-15 11:52 UTC, ohgillwhan commented on src/main/kotlin/racingcar/RacingGame.kt
> +    private var tryCount: Int = 0
`RacingGame`은 `cars`와 `tryCount`가 어떤 값으로든지 생성만 되면 될것 같아요. 그래야 조금 더 범용적으로 사용할 수 있을것 같네요! 생성자로 옮겨서 좀 더 범용적으로 사용할 수 있게 해볼까요?
만약에 `step3`처럼 자동차 갯수만큼만 만들어져야 한다면, 팩토리 메소드를 통해서 해당 객체를 생성하는것을 제공하되, 생성자를 통해 객체를 생성할 수 있도록 범용적으로 만들면 좋을것 같아요. 그럼 어떠한 조건이 생기던지 생성자는 가만히 두고, 팩토리 메소드나 다른 방법을 통해 해당 객체를 쉽게 생성할 수 있겠죠?

2023-06-16 04:47 UTC, sumniy commented
좋은 피드백 많이 남겨주셔서 감사합니다~ 피드백 반영 내용 확인 부탁드리겠습니다!

2023-06-16 12:17 UTC, ohgillwhan requested changes
수민님 코드 잘 봤습니다!
코드가 훨씬 깔끔해지고, 좋아졌네요 💯 
조금 더 고민해볼 리뷰 남겨봤습니다.
혹시 주말에 저와 페어프로그래밍을 해보시고 싶으시면, DM 남겨주세요!!

2023-06-16 12:17 UTC, ohgillwhan commented on README.md
> +## 요구사항
유구사항 잘 작성해줬네요 💯

2023-06-16 12:17 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Car.kt
> +    var conditionGenerateStrategy: ConditionGenerateStrategy = RandomStrategy()
객체가 생성 될 때는 생성자를 통해서 객체의 값을 설정해주는게 제일 깔끔합니다.
대신 잘못된 값이 생성자를 통해 들어왔는지 체크는 해줘야겠습니다.

해당 전략을 생성자를 통해 받아보면 어떨까요? 그러면 테스트코드를 작성하기 더 쉬워질거 같아요!

2023-06-16 12:17 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Car.kt
> +        }
만약 자동차가 움직인다. 라는 조건이 `THRESHOLD`가 아니라, 다른 조건으로 바뀐다면 어떻게할까요? 조금 더 범용적으로 사용하려면 `generate()`의 리턴값이 `boolean`이면 좋지 않을까요?~

2023-06-16 12:17 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Cars.kt
> +class Cars(private val cars: List<Car>) {
💯

2023-06-16 12:17 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Main.kt
> +    val cars = Cars.from(carsSize)
이 부분은 입력과는 조금 다른 부분이네요! 한칸 위에 공백을 주고, 아래는 공백을 없애서 `result`와 같이 두는건 어떨까요?

2023-06-16 12:17 UTC, ohgillwhan commented on src/main/kotlin/racingcar/PositionHistory.kt
> +        require(positions.all { it >= Car.DEFAULT_POSITION }) { "Car의 포지션은 ${Car.DEFAULT_POSITION} 이상이어야 합니다" }
보호코드 💯

2023-06-16 12:17 UTC, ohgillwhan commented on src/main/kotlin/racingcar/RacingGame.kt
> +        }
💯  `mutable`을 어떻게 하면 없애볼 수 있을까요?
`(0..tryCount).map { PositionHistory(cars.moveAll()) }`또는 `buildList{}` 를 통하면 `mutable`을 없앨 수 있을거 같아요.

2023-06-16 12:17 UTC, ohgillwhan commented on src/main/kotlin/racingcar/RacingGame.kt
> +    private val gameResult: MutableList<PositionHistory> = mutableListOf()
함수에서 사용하고 끝낼 변수는 함수에만 넘어볼까요?

2023-06-16 12:17 UTC, ohgillwhan commented on src/main/kotlin/racingcar/strategy/ManualStrategy.kt
> +class ManualStrategy(private val condition: Int) : ConditionGenerateStrategy {
테스트하기 좋은 전략! 테스트에만 필요하다면 테스트 모듈로 옮겨볼까요?

2023-06-16 12:17 UTC, ohgillwhan commented on src/main/kotlin/racingcar/strategy/RandomStrategy.kt
> +        return (ConditionGenerateStrategy.MIN_CONDITION_VALUE..ConditionGenerateStrategy.MAX_CONDITION_VALUE).random()
💯 !!!

2023-06-16 12:17 UTC, ohgillwhan commented on src/test/kotlin/racingcar/CarTest.kt
> +        car.conditionGenerateStrategy = manualStrategy
아마 자동차의 생성자를 `strategy`를 받을 수 있다면 해당 코드가 사라지겠죠?

2023-06-19 03:02 UTC, sumniy commented
피드백 반영했습니다! 작업을 너무 늦게 시작해서 연락은 못 드렸어요 죄송합니다 ㅠㅠ

2023-06-19 08:03 UTC, ohgillwhan approved these changes
수빈님 코드 좋습니다! 💯 
조금 더 힘내볼까요?~ 다음 `step`진행해주세요~

2023-06-19 08:03 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Car.kt
> +        if (conditionGenerateStrategy.generate()) {
생성하다. 라는 의미인 `generate`가 좋을까요?~ 
해당 코드를 한글로 표현하면

만약 조건생성전략을 생성하면
 움직인다

조금 어색해보여요~ 조금 더 자연스럽게 읽힐 수 있도록 해볼까요?

2023-06-19 08:03 UTC, ohgillwhan commented on src/main/kotlin/racingcar/strategy/ConditionGenerateStrategy.kt
> +    }
이 값은 이제 `RandomStrategy`로 옮겨봐도 괜찮을거 같아요.

2023-06-19 08:03 UTC, merged