[Step3] 자동차 경주 구현
next-step/kotlin-racingcar pull request #1212
Opened 2023-06-16 12:27 UTC by SongSieun

잘 부탁드립니다 🙇 
`race()` 함수의 테스트 작성이 쉽지 않아서 `checkMoveAvailable()` 함수를 만들어서 테스트했습니다🥲

2023-06-16 12:29 UTC, SongSieun commented
왜 이전 커밋들까지 포함되었을까요? 😢

2023-06-17 02:44 UTC, Hyeon9mak requested changes
안녕하세요 시은님, 3단계 진행 고생하셨습니다.
4단계 진행에 앞서서 클래스를 분리해보면 좋을 것 같아서 코멘트를 남겼어요.
깃 커밋 내역이 포함된 이유는 `step3` 브랜치에서 `next-step:songsieun` 브랜치를 rebase 하면 해결 될 것 같아요. 😄 
이 부분도 이번 PR 에서 해결해보면 좋겠네요!
궁금하신 점 코멘트, DM 남겨주세요.

2023-06-17 02:44 UTC, Hyeon9mak commented on build.gradle.kts
> +    testImplementation("io.kotest", "kotest-runner-junit5", "5.5.0")
테스트 환경마다 조금 차이가 있는 것 같긴한데, 간혹 전체 테스트 수행시 일부 테스트들이 스킵되는 일들이 있더라구요.
kotest-runner-junit5 5.5.0 버전의 버그였다고 하네요.
kotest-runner-junit5 5.5.1 이상의 버전을 사용하는 것도 좋아보여요 👍 
https://kotest.io/docs/changelog.html#551-october-2022

2023-06-17 02:44 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/InputView.kt
> +class InputView {
상태값이 없으므로 `object` 를 활용할 수도 있겠네요 😄

2023-06-17 02:44 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/InputView.kt
> +    }
`readln()` 에서 자동으로 입력값 nul 에 대한 검증이 진행될 것 같아요.
현재는 숫자가 아닌 다른 값 입력에 대한 exception 을 던져야 할 것 같아요.

2023-06-17 02:44 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/InputView.kt
> +    }
`readln` 과 `readlnOrNull` 이 혼용되고 있네요 😱

2023-06-17 02:44 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RacingCar.kt
> +    var randomNumber = (1..9).random()
`전진하는 조건은 0에서 9 사이에서 무작위 값을 구한 후 ...` 😉

2023-06-17 02:44 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RacingCar.kt
> +    }
scope function 활용 👍

2023-06-17 02:44 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RacingCar.kt
> +    }
- "자동차 대수는 음수가 되면 안될 것 같아요. 검증 로직을 추가해주세요."
- "경주 횟수는 무조건 양수여야해요. 검증 로직을 추가해주세요."
- "아~ 지금 딱히 떠오르는 방법이 없는데, 자동차 경주 횟수가 음수도 전달되면 시범경기로 해보는 건 어떨까요?"
-  ...

현재 `RacingCar` 클래스에는 수 많은 로직이 추가될 가능성을 내포하고 있고, 수 많은 리팩터링이 진행될 것 같아요.
앞으로 동료 개발자들과 함꼐 프로젝트를 진행한다면 `RacingCar` 클래스의 편집 내용을 merge 할 때 conflict 도 자주 발생할 수 있을 것 같아요.
어떤 상황에 어떤 유지보수 내용이 전달될지 상상해보고, 그것들으 기준으로 객체(클래스)를 나눠보는 건 어떨까요?
이번 미션에서는 "비즈니스 규칙은 잘 변화하지 않으나, 출력에 대한 변화는 잦다." 를 기준으로 해보면 좋겠어요.

2023-06-17 02:44 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RacingCar.kt
> +    }
우선 게임 진행 횟수와 차량 대수를 VO 로 포장해보는 건 어떨까요?

2023-06-19 09:39 UTC, SongSieun commented on build.gradle.kts
> +    testImplementation("io.kotest", "kotest-runner-junit5", "5.5.0")
저도 이전에 전체 테스트 시에 일부 테스트들이 스킵되던 문제가 있었는데, 버전 업데이트하니 해결되었네요 ㅎㅎ
감사합니다!

2023-06-19 09:47 UTC, SongSieun commented on src/main/kotlin/racingcar/InputView.kt
> +    }
[e69a8da](https://github.com/next-step/kotlin-racingcar/pull/1212/commits/e69a8dafb5c733399f0e86cb0f7f193093a9f5db) NPE대신 NumberFormatException을 throw하도록 수정했습니다~!

2023-06-19 09:47 UTC, SongSieun commented on src/main/kotlin/racingcar/InputView.kt
> +class InputView {
[53cbbfd](https://github.com/next-step/kotlin-racingcar/pull/1212/commits/53cbbfdf17efb5181c153525c6dc59e6e67534ed) 지난 PR에서도 받았던 리뷰였는데😂 더 신경쓰겠습니다 🙏

2023-06-19 09:49 UTC, SongSieun commented on src/main/kotlin/racingcar/RacingCar.kt
> +    var randomNumber = (1..9).random()
[2100e6c](https://github.com/next-step/kotlin-racingcar/pull/1212/commits/2100e6c5b8416e71be0d64329fab25ad7c1fb4e9) 감사합니다 😭

2023-06-19 14:59 UTC, SongSieun commented on src/main/kotlin/racingcar/RacingCar.kt
> +    }
[aded83e](https://github.com/next-step/kotlin-racingcar/pull/1212/commits/aded83edf5ace9d6aedd8b4246daf8568be5563d) Car 클래스와 Race 클래스를 생성해서 수정했습니다 🙂

2023-06-20 09:20 UTC, Hyeon9mak approved these changes
안녕하세요 시은님, 피드백 잘 반영해주셨습니다.
4단계 진행에 참고하실만한 코멘트 남겼으니 확인해주세요.
다음 단계도 화이팅입니다~ 💪

2023-06-20 09:20 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/InputView.kt
> +    }
`toInt()` 내부에서 `parseInt()` 를 호출하고, `parseInt()` 가 자연스럽게 NumberFormatException 를 던지고 있어요.
이렇게되니 `toInt()` 를 사용해도 좋을 것 같아요 😄

2023-06-20 09:20 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/Race.kt
> +class Race(var numberOfCars: Int, var numberOfRounds: Int)
단순히 값을 전달해주는 객체로 보여요. 그렇다면 데이터 클래스도..?

2023-06-20 09:20 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/Race.kt
> +class Race(var numberOfCars: Int, var numberOfRounds: Int)
프로퍼티들이 가변일 필요가 없어보이네요 😄

2023-06-20 09:20 UTC, Hyeon9mak commented on src/test/kotlin/study/racingcar/RacingCarTest.kt
> +    }
경계값 테스트를 진행하면 조금 더 좋겠어요 😄 👍

2023-06-20 09:20 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RacingCar.kt
> +        val cars = List(size = numberOfCars) { Car() }
List 활용 👍

2023-06-20 09:20 UTC, merged