🚀 5단계 - 자동차 경주(리팩터링)
next-step/kotlin-racingcar pull request #1231
Opened 2023-06-22 11:19 UTC by junho85

지난 리뷰 반영 및 Step5 진행하였습니다.

2023-06-22 12:51 UTC, pci2676 requested changes
5단계 요구사항에 맞도록 패키지 구분을 잘 해주신것 같습니다.

그 외에 조금 더 개선해보면 좋을것 같은 부분에 리뷰를 남겨두었습니다.

조금만 더 개선해보시고 다시 PR 부탁드리겠습니다.

2023-06-22 12:51 UTC, pci2676 commented on src/main/kotlin/racingcar/controller/RacingGame.kt
> +    val winners: List<Car>
가시성을 private로 해야할것 같습니다.

외부에서 start를 호출하기전에 winners를 호출하면 올바른 기대값을 얻지 못할 것 같습니다.

2023-06-22 12:51 UTC, pci2676 commented on src/main/kotlin/racingcar/controller/RacingGame.kt
> +        ResultView().printWinners(winners.map { it.carName.name })
I/O 작업은 그 비용이 비싸니 한번만 호출할 수 있도록 개선해보는것도 나쁘지 않을것 같습니다.

2023-06-22 12:51 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    val size: Int
이 코드는 테스트 코드에서만 사용되네요!

굳이 존재할 필요가 없어보입니다!

2023-06-22 12:51 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +        this.cars = carNames.map { Car(it) }
init에서 생성하지 말고 바로 cars에 주입해주는것이 코드를 파악하기에 더 쉬울것 같습니다.


`val cars: List<Car> = carNames.map { Car(it) }`

2023-06-22 12:51 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    }
지금은 모든 Car가 하나의 ConditionGenerator를 사용하고 있는데요.

그래서 3개의 Car를 생성하고 한개의 Car만 우승자로 만드는 작업이 힘들어 보입니다.

이를 해결하기 위해서 어떻게 개선하면 좋을지도 생각해보시면 좋을것 같습니다.

꼭 개선할 필요는 없고 욕심이 나시면 도전해보시기 바랍니다.

2023-06-22 12:51 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/Car.kt
> +        private set
name을 var로 따로 선언할 필요가 있을까요? 

private set로 선언했다는 것은 변경될 소지가 없다는 것이니 아래와 같이 선언해두어도 괜찮을것 같습니다.

```suggestion
class CarName(val name: String) {
```

2023-07-03 00:52 UTC, junho85 commented
@pci2676 꼼꼼한 리뷰와 팁 감사합니다.
리뷰내용들을 반영해 보았습니다 :)

2023-07-03 15:57 UTC, pci2676 requested changes
테스트에서 조금 아쉬운 부분이 있어서   
한번 더 개선을 요청드립니다!

코드 리뷰를 확인후 다시 요청해주세요.

2023-07-03 15:57 UTC, pci2676 commented on src/main/kotlin/racingcar/controller/RacingGame.kt
> +    }
테스트에서만 사용되는 기능같습니다.

제거해주세요!

2023-07-03 15:57 UTC, pci2676 commented on src/test/kotlin/racingcar/controller/RacingGameTest.kt
> +        racingGame.winnerNames shouldContain "pobi"
특정 자동차를 우승 자동차로 만들어주고 싶다면

car가 conditionGenerator를 의존하고 있으면 가능하지 않을까요?

조금 설계를 수정해보시면 원하시는 테스트의 결과 값을 얻을 수 있을것 같습니다.

makeWinner는 테스트에서만 사용되는 코드이니 사용하지 않고 테스트 할 수 있도록 개선해보면 좋을 것 같습니다.

2023-07-05 13:37 UTC, junho85 commented
@pci2676 
말씀하신 것 처럼 Car가 conditionGenerator를 의존하도록 수정하였습니다. 
특정 Car를 승자로 만들기에 좀 더 좋은 구조가 된 것 같습니다 :)

2023-07-05 14:38 UTC, pci2676 approved these changes
그동안 레이싱 게임 구현하시느라 수고하셨습니다!

머지하겠습니다!

2023-07-05 14:38 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/WinnerConditionGenerator.kt
> +class WinnerConditionGenerator : ConditionGenerator {
`LooserConditionGenerator`와 마찬가지로 테스트에서만 사용되는 클래스라면 테스트 패키지에 위치시켜도 좋을것 같습니다~

2023-07-05 14:38 UTC, pci2676 commented on src/main/kotlin/racingcar/RacingGameApplication.kt
> +    racingGame.start(tryNum)
이번 미션의 요구사항은 아니지만
입출력에 대한 테스트도 interface로 의존성을 역전시키면 가능해집니다!
시간이 나실때 고민해보시면 좋을것 같습니다 😄

2023-07-05 14:38 UTC, merged