🚀 3단계 - 자동차 경주
next-step/kotlin-racingcar pull request #1235
Opened 2023-06-25 05:00 UTC by goyounggyeong

안녕하세요.
조금 늦었지만 올려봤습니다.
잘 부탁드려요.

2023-06-25 16:51 UTC, Rok93 requested changes
영경님 자동차 경주 미션 잘 구현해주셨네요. 👍
애플리케이션 실행 결과가 요구사항과 조금 다른 것 같은데, 이 부분 확인해서 수정해주셨으면합니다. 🙏
그 외에도 고민해보면 좋을 부분들이 보여서 추가로 코멘트 남겨두었습니다. 확인해서 반영해주세요. 

미션 진행하시면서 어려운 부분이 있으면 언제든지 DM 주세요. 😃

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/constant/RacingGameConstant.kt
> +    const val RESULT_SENTENCE = "실행 결과"
응집도를 높이기 위해서 상수는 사용하는 위치의 클래스 파일에 정의해서 사용하는 것이 어떨까요? 🤗

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/constant/RacingGameConstant.kt
> +package racing.constant
현재 Ktlint Check가 통과하지 않는 것으로 보여요. 👀
통과하지 않는 부분 확인해서 수정해주세요! 🙏

혹시 아직 린트 설정이 안 되어 있다면 아래 명령어를 실행해 보세요!
```
./gradlew ktlintApplyToIdea
mkdir .git/hooks
./gradlew addKtlintCheckGitPreCommitHook
./gradlew clean check
```

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/service/Racing.kt
> +class Racing(carCount: Int) {
`Racing`도 상태를 가지는 `도메인 모델`로 분류할 수 있을 것 같아요. 🤔
service 패키지에 위치시킬 것이 아니라 model에 위치시키는 것이 좋지 않을까요? 😃

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/service/GameMachine.kt
> +
불필요한 줄바꿈은 제거해주세요! 🙏
```suggestion
```

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/service/GameMachine.kt
> +        return readLine().orEmpty().toInt()
readLine() 보다는 `readln()` or `readlnOrNull()` 함수로 대체해서 사용해주세요! 😃

<img width="604" alt="image" src="https://github.com/next-step/kotlin-racingcar/assets/47850258/6905b7df-8d0a-4edb-9356-a934c91487f2">

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/view/RacingGame.kt
> +    GameMachine.printResult(carCount, tryGameCount)
현재 자동차경주 게임을 실행시켜보면 아래와 같은 결과가 나와요. 👀
실행결과 부분의 결과 값이 요구사항과는 다르게 출력되고있는 것 같아요. 🤔
Racing 클래스의 `play()`와 Car 클래스의 `run()` 메서드 두군데 모두 수정이 필요할 것 같아요.

<img width="337" alt="image" src="https://github.com/next-step/kotlin-racingcar/assets/47850258/7ee7d653-a0a9-4c10-8c8f-a494854d7753">

[자동차 경주 미션 소개 페이지](https://edu.nextstep.camp/s/w5G1pCe7/ls/fr4k7KMk)의 실행 결과 예시는 아래와 같아요.

```
자동차 대수는 몇 대인가요?
3
시도할 횟수는 몇 회인가요?
5

실행 결과
-
-
-

--
-
--

---
--
---

----
---
----

----
----
-----
```

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/service/Racing.kt
> +            print(START_POINT_SYMBOL)
각 차량이 레이싱을 시작할 때마다 `-`를 하나 출력하시는 이유가 있을까요? 🤔

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/service/Racing.kt
> +            println()
print() 함수로 문자 하나하나를 출력하는 것이 아니라, String의 `repeat()` 확장함수를 활용해서 출력할 위치 값을 완성해서 한번에 출력하도록 변경해보면 어떨까요? 😃
```suggestion
            val position = CAR_SYMBOL.repeat(moving)
            println(position)
```

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/model/Car.kt
> +}
현재 `GameMachine`의 printResult 메서드에서 실제 시도횟수만큼의 레이싱 경주를 수행하고있어요. 
자동차 경주에 참가하는 자동차가 2대이고 각각의 자동차는 A, B 라고 할게요. 또한 시도횟수는 3회로 설정했다고 가정해보죠.

시도 횟수만큼 자동차는 전진 혹은 정지할거에요. 

### 1번째 시도
A는 한칸 전진, B는 정지합니다.

실행결과 (이름을 출력하라는 요구사항은 없었지만, 가독성을 위해 임의로 추가해볼게요)
```
A: -
B:
```

### 2번째 시도
A는 또 한칸 전진, B도 한칸 전진

실행결과
```
A: --
B: -
```

### 3번째 시도
A는 또 한칸 전진, B는 정지

실행결과
```
A: ---
B: -
```

위와 같이 시도횟수가 증가하더라도 A, B라는 자동차는 새로운 자동차가아니라 처음 자동차 경주에 참여한 자동차들이라는 것을 알 수 있어요. 그리고 시도횟수가 증가할 때마다 이전에 시도했던 결과들은 자동차에게 누적되어 다음 결과에 반영되고있어요.

위의 지금 구현하신 방법의 가장 큰 문제점은 시도횟수가 늘어나더라도 자동차의 이전 시도의 결과가 누적되지 않고 각 시도횟수마다 독립적인 새로운 자동차가 만들어지고있다는 점이에요. 🤔

해당 Car 클래스를 객체지향 프로그래밍의 `객체`로 둬서, Car라는 클래스가 자신의 `위치`를 상태 값으로 가지고 자신의 상태를 직접 관리하도록 변경해보면 어떨까요? 😃


### 객체지향 프로그래밍이란 ?
> 객체 지향 프로그래밍 (Object-Oriented Programming, OOP)은 프로그래밍에서 필요한 데이터를 추상화 시켜 상태와 행위를 가진 객체로 만들고, 객체들간의 상호작용을 통해 로직을 구성하는 프로그래밍 방법이다.

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/model/Car.kt
> +        private fun getMoving(): Int {
해당 메서드를 companion object로 두신 이유가 있을까요? 🤔

Car 클래스 내부의 private 메서드로 두시는게 더 좋지 않을까요? 😊

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/model/Car.kt
> +            return moving
굳이 moving 변수의 값을 재할당할 필요는 없을 것 같아요. 🤔 
그렇다면 moving 변수는 val로 선언할 수 있을 것 같아요. 😃
(불변 변수는 꼭 `val`로 변수를 선언해주세요. 😊)


```suggestion
            val moving = (0..9).random()
            return if (moving >= 4) moving
                else 0
```

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/model/Car.kt
> +            moving = if (moving >= 4) moving
[기능 요구 사항](https://edu.nextstep.camp/s/w5G1pCe7/ls/fr4k7KMk)에서 `전진하는 조건은 0에서 9 사이에서 무작위 값을 구한 후 무작위 값이 4 이상일 경우이다.` 라는 내용이 있어요. 

저는 위의 요구사항이 무작위 값이 4이상인 경우 (**한칸**) 전진한다는 의미로 생각했는데, 영경님은 어떻게 이해하셨을까요? 
moving이 4이상이라면 moving을 반환하는게 의도하신 구현이 맞으실까요? 🤔

2023-06-25 16:51 UTC, Rok93 commented on src/main/kotlin/racing/model/Car.kt
> +            moving = if (moving >= 4) moving
코드를 처음 보는 사람이라면 `0`, `9`, `4` 같은 숫자를 보고 어떤 의미를 가지는지 알 수 있을까요? 🤔
[참고 자료](https://javabom.tistory.com/28)를 읽어보시고 조금 더 의미를 명확하게 파악할 수 있도록 변경해보면 어떨까요? 🤗

2023-06-27 11:42 UTC, goyounggyeong commented on src/main/kotlin/racing/model/Car.kt
> +}
슬라이드에서 결과만 보고 개발했는데 이해했습니다. 감사합니다.

2023-06-27 18:22 UTC, Rok93 approved these changes
영경님 피드백 반영 잘 해주셨네요. 😃
빠른 미션 진행을 위해서 이번 단계는 이만 머지하겠습니다. 🚀
고민해볼 포인트들이 있어서, 코멘트 남겨두었으니 4단계 진행하실 때, 같이 반영해주세요! 🙏

또한 다음 단계에서는 꼭 `자동차 경주` 도메인에 대한 `테스트 코드`를 작성해주셨으면해요. 
미션 진행하시면서 어려운 부분이 있으면 언제든지 DM 주세요! 😉

2023-06-27 18:22 UTC, Rok93 commented on src/main/kotlin/racing/model/Car.kt
> +    private var moving: Int = 0
가급적 `주생성자를 통해서 (객체의) 프로퍼티를 초기화`할 수 있도록 코드를 작성해보시면 어떨까요? 🙌

```suggestion
class Car(
    private var moving: Int = 0,
) {
```

2023-06-27 18:22 UTC, Rok93 commented on src/main/kotlin/racing/model/Car.kt
> +    private var moving: Int = 0
변수명은 일반적으로 `명사`로 짓도록 권장되고있어요. 😉
또한 moving이라고 선언하신 변수는 자동차의 `위치`를 나타내는 프로퍼티이기 때문에 `위치`라는 의미를 가진 네이밍으로 변경하면, 조금 더 Car 객체를 파악하기가 쉬울 것 같아요. 😃

[좋은 코드를 위한 자바 변수명 네이밍](https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/)을 참고해보시면 좋을 것 같아요. 😃

2023-06-27 18:22 UTC, Rok93 commented on src/main/kotlin/racing/model/Car.kt
> +    }
현재 `자동차 경주` 미션에 대한 테스트 코드가 없는 것 같아요. 🥲
다음 리뷰요청 때는 테스트 코드도 꼭 같이 작성해서 리뷰요청 주셨으면합니다. 🙏

혹시라도 테스트 코드를 작성하시는 것이 많이 낯설고 어려우신 상황이라면, 
다음 리뷰 요청 때는 꼭 해당 `run` 메서드에 대한 테스트를 작성해보셨으면 합니다. 🤗

2023-06-27 18:22 UTC, Rok93 commented on src/main/kotlin/racing/service/GameMachine.kt
> +    fun askCounting(question: String): Int {
적절한 줄바꿈을 통해서 프로퍼티와 함수를 구분하기 쉽게 분리해주시면 좋을 것 같아요. 😃
```suggestion
    private const val RESULT_SENTENCE = "실행 결과"
    
    fun askCounting(question: String): Int {
```

2023-06-27 18:22 UTC, Rok93 commented on src/main/kotlin/racing/service/GameMachine.kt
> +                println()
https://github.com/next-step/kotlin-racingcar/pull/1235#discussion_r1241223462 부분은 반영이 안된 것 같아요. 👀

아래와 같이 변경해볼 수 있을 것 같아요. 😉
```suggestion
                println(CAR_SYMBOL.repeat(moving))
```

2023-06-27 18:22 UTC, Rok93 commented on src/main/kotlin/racing/service/GameMachine.kt
> +    fun play(carCount: Int, tryGameCount: Int) {
play 메서드는 GameMachine 내에서만 사용되는 메서드인 것 같아요. 👀
접근제한자를 `private`로 변경해주시면 좋을 것 같아요. 😃

2023-06-27 18:22 UTC, Rok93 commented on src/main/kotlin/racing/service/GameMachine.kt
> +        println()
현재 `Racing` 객체가 아무런 역할도 안하고 있는 것 같아요. 🤔
racing 객체에게 `레이싱 경주를 수행하는` 역할을 부여해보면 어떨까요? 😃

아래와 같이 변경해보시면 좋을 것 같아요. 😉

```suggestion
        val racing = Racing(carCount, tryGameCount)
        racing.play()
```

2023-06-27 18:23 UTC, merged