[Step5] 자동차 경주 리팩토링
next-step/kotlin-racingcar pull request #1244
Opened 2023-07-06 12:04 UTC by choihwan2

- Engine 구현체 RacingCarEngine 구현
- Car.printView()  확장함수에서  View에서 Car를 받아 표시하는 printCarView로 변경

2023-07-07 10:39 UTC, Flamme1004K requested changes
안녕하세요!

벌써 마지막 미션이군요! 축하드립니다!

한 가지 코멘트를 남겼으니 확인 부탁드리겠습니다!

확인 후 다시 리뷰 요청 드리며, 궁금하신 점에 대해서는 DM 부탁드립니다!

마지막으로 미션 화이팅입니다! 🙌

2023-07-07 10:39 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/RacingCarEngine.kt
> +}
피드백 반영 좋습니다~

2023-07-07 10:39 UTC, Flamme1004K commented on src/main/kotlin/racingcar/controller/RacingCarsGame.kt
>  object RacingCarsGame {
해당 object를 domain으로 넣을 수는 없으려나요~?

이 부분만 변경된다면 요번 미션은 끝이라고 생각됩니다!

2023-07-10 07:32 UTC, choihwan2 commented on src/main/kotlin/racingcar/domain/RacingCarEngine.kt
> +}
이 형식을 적용하는데 힘들었네요ㅠㅠ

2023-07-10 07:33 UTC, choihwan2 commented on src/main/kotlin/racingcar/controller/RacingCarsGame.kt
>  object RacingCarsGame {
Package 구조를 좀 변경해 보겠습니다!

2023-07-10 11:45 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/RacingCarEngine.kt
> +}
고생하셨어요!  요번 자동차 미션의 핵심 부분이라서 힘드셨을거라 생각합니다.

그래도 해당 패턴을 잘 기억하시다보면 실무에서도 많이 쓰실거라 생각됩니다 ㅎㅎ

2023-07-10 11:46 UTC, Flamme1004K approved these changes
안녕하세요!

피드백 반영 감사합니다! 그리고 그동안 자동차 경주 미션 고생하셨습니다! 🤩

나머지 미션도 화이팅입니다! 응원하겠습니다!

2023-07-10 11:46 UTC, merged