2단계: 문자열 계산기
next-step/kotlin-racingcar pull request #1303
Opened 2023-10-25 10:16 UTC by Factoriall

일단 문자열 계산기를 공백 기준으로 나누어서 하긴 했는데... 이게 맞는건지는 모르겠네요.

맞는 부분인지 체크하는 Class를 따로 나누긴 했는데 이게 맞는지 헷갈려, 클래스를 나누는 기준이 궁금합니다.

2023-10-25 12:38 UTC, pci2676 requested changes
조금 더 개선해보면 좋을것 같은 부분에 리뷰를 남겨두었습니다.

참고하여 다시 PR 부탁드리겠습니다.

이해가 되지 않는 부분이 있으시다면 DM이나 코멘트를 남겨주세요 :)

2023-10-25 12:38 UTC, pci2676 commented on src/test/kotlin/study/CalculatorTest.kt
> +        assertThatThrownBy { calculator.calculate("1 / / 2") }.isInstanceOf(IllegalArgumentException::class.java)
`@ParameterizedTest`를 사용하시면 검증 구문을 하나로 줄이실 수 있습니다.

https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests

참고하여 수정해보시면 좋을것 같습니다.

2023-10-25 12:38 UTC, pci2676 commented on src/test/kotlin/study/CalculatorTest.kt
> +        assertThatThrownBy { calculator.calculate("     ") }.isInstanceOf(IllegalArgumentException::class.java)
`@NullAndEmptySource`와 `@ValueSource`를 조합하여 간단하게 표현할 수 있을것 같습니다.

https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources

참고하여 수정해보시면 좋을것 같습니다.

2023-10-25 12:38 UTC, pci2676 commented on src/main/kotlin/study/Calculator.kt
> +        if (!checker.isInputValid(input)) throw IllegalArgumentException()
`input`으로 입력된 문자가 스스로 검증을 할 수 있다면 어떨까요?

예를 들어 나이를 나타내는 Int값이 있다면 아래와 같이 표현해 볼 수 있을것 같습니다.

```kotlin
class Age(
    val value: Int,
) {
    init {
        check(value >= 0) {"입력된 나이값($value)이 0보다 작습니다."}
    }
}
```

입력된 String이 nullable한 상태(`String?`)로 사용되는 것 보다 nullable하지 않은 상태(`String`)가 보장된 상태에서 사용한다면 코드를 작성하고 이해하기 더 좋을것 같습니다.

2023-10-25 12:38 UTC, pci2676 commented on src/main/kotlin/study/Calculator.kt
> +    private fun operate(formulaQueue: List<String>): Int {
메서드가 하는 일이 많은것 같습니다.

- 숫자가 입력될 차례인지, 연산자의 입력차례인지 검증
- 숫자라면 Int로 치환
- 연산자라면 알맞은 연산자를 찾아 누산하기
- 분리된 식의 크기가, 식 자체가 올바른 입력인지

등등

역할에 따라 클래스를 나누어 객체를 생성하여 하나의 메서드가 하는 일을 분리해보면 좋을것 같습니다.

2023-10-25 12:38 UTC, pci2676 commented on src/main/kotlin/study/Calculator.kt
> +                    }
지금은 연산자의 종류가 추가될때마다 두가지 작업이 필요합니다.

1. 연산자에 따른 메서드를 구현해야하는 행위
2. 연산자를 찾아서 알맞는 메서드를 호출하는 행위

1번을 구현하더라도 2번 구현을 누락한다면 애플리케이션의 실행에는 문제가 없을수 있지만  
예상한대로 동작하지 않을 수 있습니다.

Map을 이용하거나 enum을 이용해보시면 조금 더 간결하게 변경할 수 있을것 같습니다.

enum이 생소하시다면 아래 글을 참고해보시면 좋을것 같습니다.

https://techblog.woowahan.com/2527/

2023-10-25 12:38 UTC, pci2676 commented on src/test/kotlin/study/CalculatorTest.kt
> +        assertThat(calculator.calculate("4 + 2")).isEqualTo(6)
`1 + 2`를 검증하고 `4 + 2`도 검증하는것이 유의미한 차이가 있나요?

차이가 없다면 한번만 검증해도 좋을 것 같습니다.

2023-10-25 12:38 UTC, pci2676 commented on src/test/kotlin/study/CalculatorTest.kt
> +class CalculatorTest {
여러가지 경우에 따라 꼼꼼하게 테스트를 작성해주셨네요! 👍

2023-10-25 12:40 UTC, pci2676 commented
> 일단 문자열 계산기를 공백 기준으로 나누어서 하긴 했는데... 이게 맞는건지는 모르겠네요.
> 
> 맞는 부분인지 체크하는 Class를 따로 나누긴 했는데 이게 맞는지 헷갈려, 클래스를 나누는 기준이 궁금합니다.

https://github.com/next-step/kotlin-racingcar/pull/1303#discussion_r1371681520

위 리뷰에서 언급하였듯이 클래스를 역할에 따라 나누어 보시면 좋을 것 같습니다.

2023-10-25 15:00 UTC, Factoriall commented
수정한 부분 모두 반영해서 올렸습니다! 수정하다보니 좀 코드를 어떻게 옮겨야하는지 감이 오는거 같습니다.

이전에 제가 3단계 코드를 미리 올렸었는데, 죄송하다는 말씀 올립니다.
제가 내일부터 토요일까지 코드를 볼 시간이 없을 것으로 보여 미리 코드를 작성해 올렸습니다. 일요일 이후 남은 과제를 끝내려면 미리 PR을 받아야할 것으로 보여 3단계 코드도 봐주신다면 일요일 이후에 관련 반영해서 올릴 수 있도록 하겠습니다. 다시 한번 죄송합니다 (_ _)

2023-10-26 13:53 UTC, pci2676 approved these changes
빠른 미션진행을 위해 이번 단계는 머지하도록 하겠습니다.

리뷰로 남긴 내용을 꼼꼼히 확인해주시고

다음 단계를 수행할때 개선해서 같이 PR 주시면 됩니다.

머지하겠습니다.

2023-10-26 13:53 UTC, pci2676 commented on src/main/kotlin/step2/Arithmetic.kt
> +    PLUS("+"), MINUS("-"), TIMES("*"), DIVIDE("/")
enum은 새로로 나열해 주시는 것이 추후 가독성과 유지보수하기에 더 편리한 점이 있습니다~

참고해주시면 좋을것 같습니다 😄

2023-10-26 13:53 UTC, pci2676 commented on src/main/kotlin/step2/Calculator.kt
> +    }
이 부분에 대해 같이 조금씩 개선해보면 좋을것 같습니다.

제가 리뷰에 남긴바와 같이 지금은 연산자가 추가되면 연산식을 지원하는 메서드도 추가해야하는 문제가 있습니다.

먼저 이를 해결하기 위해 Map을 사용해보면 다음과 같이 구현할 수 있습니다.

```suggestion
        private fun operate(numberList: List<Int>, arithmeticList: List<Arithmetic>): Int {
        var result = numberList[0]

        val expressionCount = arithmeticList.size
        for (i in 0 until expressionCount) {
            val operand = numberList[i + 1]
            val arithmetic = arithmeticList[i]
            result = arithmeticMap[arithmetic]
                ?.invoke(result, operand)
                ?: throw IllegalArgumentException("지원하는 연산자($arithmetic)를 찾지 못하였습니다.")
        }

        return result
    }

    private val arithmeticMap: Map<Arithmetic, (Int, Int) -> Int> = mapOf(
        Arithmetic.PLUS to { a, b -> a + b },
        Arithmetic.MINUS to { a, b -> a - b },
        Arithmetic.TIMES to { a, b -> a * b },
        Arithmetic.DIVIDE to { a, b -> a / b }
    )
```

이제 지원하는 연산자에 해당하는 연산식을 Map 한곳에서 관리함으로써 연산자와 연산식을 연결하지 못하면서 발생하는 문제는 방지하였습니다.

다만 이 방법은 `Arithmetic`이 객체로서 역할을 다한다고 하기에는 조금 아쉬운점이 있습니다.  
`Arithmetic`이 자기에게 알맞는 식을 가지고 있어야 테스트하기 수월해지고 응집도 있는 코드가 완성될 것 같습니다.

이를 해결하기 위해 enum을 조금더 발전시킨다면 다음과 같이 변경할 수 있습니다.

```kotlin
enum class Arithmetic(
    val expr: String,
    val function: (Int, Int) -> Int,
) {
    PLUS("+", { operand1, operand2 -> operand1 + operand2 }),
    MINUS("-", { operand1, operand2 -> operand1 - operand2 }),
    TIMES("*", { operand1, operand2 -> operand1 * operand2 }),
    DIVIDE("/", { operand1, operand2 -> operand1 / operand2 }),
    ;

    fun calculate(operand1: Int, operand2: Int): Int = function(operand1, operand2)

    companion object {
        fun findBy(arithmetic: String): Arithmetic {
            return values().find { it.expr == arithmetic }
                ?: throw IllegalArgumentException("지원하는 연산자($arithmetic)를 찾지 못하였습니다.")
        }
    }
}


    private fun operate(numberList: List<Int>, arithmeticList: List<Arithmetic>): Int {
        var result = numberList[0]

        val expressionCount = arithmeticList.size
        for (i in 0 until expressionCount) {
            val operand = numberList[i + 1]
            val arithmetic = arithmeticList[i]
            result = Arithmetic.findBy(arithmetic = arithmetic.expr)
                .calculate(operand1 = result, operand2 = operand)
        }

        return result
    }
```

이렇게 수정하면서 `Arithmetic`이 조금 더 응집도 있는 코드를 가지게 되었고 테스트도 신뢰할 수 있는 테스트를 작성할 수 있게 되었습니다.

객체가 가지고 있는 값을 활용하여 유의미한 메세지를 전달할 수 있도록 해보시면 좋을것 같습니다.

2023-10-26 13:53 UTC, pci2676 commented on src/main/kotlin/step2/Input.kt
> +data class Input(val text: String?) {
객체 내부에서 text에 대해 nullable하지 않음을 확인해 주었다면

외부에 값을 공개할때는 nullable하지 않은 값을 공개해주는게 더 좋을것 같습니다.

2023-10-26 13:53 UTC, pci2676 commented on src/main/kotlin/step2/Calculator.kt
> +    }
private method에 구현세부사항이 많이 노출되는것 같습니다.

별도의 클래스로 분리해보시면 좋을것 같습니다.

2023-10-26 13:53 UTC, pci2676 commented on src/main/kotlin/step2/CalculatorChecker.kt
> +    private fun isOdd(idx: Int) = idx % 2 == 1
Token이라는 객체가 있다면 해당 객체에게 메세지를 던지는 방식으로 수정해볼 수 있을것 같습니다.

val token :Token
val isNumber: Boolean = token.isNumber
val isEven: Boolean = token isEven

이와 같이 객체에게 메세지를 던지도록 개선해보세요.

2023-10-26 13:53 UTC, merged

2023-10-30 03:44 UTC, Factoriall commented on src/main/kotlin/step2/Calculator.kt
> +    }
오... enum 안에 함수식을 넣어서 처리하는 방안은 생각해보지 못했는데 관련 방안에 대해 앞으로 고민해보도록 하겠습니다!