Step3 [1 주차] : 자동차 경주
next-step/kotlin-racingcar pull request #1322
Opened 2023-10-25 16:31 UTC by baek0318

이번 step3 도 잘 부탁드리겠습니다

### 고민사항
main 메서드 내부에 정해진 횟수만큼 게임이 진행되고 결과를 총합하는 로직이 그대로 노출되고 있습니다
저는 개인적으로 생각할때 RacingGame이라는 컴포넌트의 역할은 한번의 게임을 진행하는데까지라고 생각을 해서 어쩔 수 없이 로직을 외부로 노출시켰는데
이것을 확장해서 해당 로직도 RacingGame에서 품는게 맞을지 아니면 별도의 컴포넌트를 하나 더 만드는게 좋을지 고민이 됩니다

2023-10-25 23:58 UTC, laco-dev commented
> main 메서드 내부에 정해진 횟수만큼 게임이 진행되고 결과를 총합하는 로직이 그대로 노출되고 있습니다
저는 개인적으로 생각할때 RacingGame이라는 컴포넌트의 역할은 한번의 게임을 진행하는데까지라고 생각을 해서 어쩔 수 없이 로직을 외부로 노출시켰는데
이것을 확장해서 해당 로직도 RacingGame에서 품는게 맞을지 아니면 별도의 컴포넌트를 하나 더 만드는게 좋을지 고민이 됩니다

MVC 관점으로 어플리케이션을 완성하는 대신 현재 단계에서는 도메인 기능에 집중해주시면 됩니다.
말씀주신 고민은 미션의 마지막 단계에서 다시 고민 해 볼 기회가 있습니다 🙏🏻

2023-10-26 04:21 UTC, laco-dev requested changes
좋습니다.

현재는 각 객체가 하는 역할이 다소 명확하지 않고 수동적인 존재처럼 느껴집니다.
클린코드를 지향하기 위해 기본적으로 객체지향 프로그래밍에 익숙해질수록 더욱 좋습니다.

린트 관련해서는 채널에 안내가 나와있으니 참고해서 적용 해 주세요. 🙏🏻

2023-10-26 04:21 UTC, laco-dev commented on README.md
> +## 자동차 경주 (3단계)
```
\Car.kt:1:1 File must end with a newline (\n) (final-newline)
\Dice.kt:1:1 File must end with a newline (\n) (final-newline)
\InputView.kt:1:1 File must end with a newline (\n) (final-newline)
\Main.kt:1:1 File must end with a newline (\n) (final-newline)
\OutputView.kt:1:1 File must end with a newline (\n) (final-newline)
\RacingGame.kt:1:1 File must end with a newline (\n) (final-newline)
```

`ktlintCheck` 한번 더 !

2023-10-26 04:21 UTC, laco-dev commented on src/main/kotlin/racinggame/Car.kt
> +    fun currentPosition(): Int = position
현재는 position이 var로 작성되었기 때문에 만들어진 함수로 보이는데요.
프로퍼티는 setter에 대한 가시성 변경을 할 수 있습니다.

```kotlin
class Car(position: Int = 0) {
   var position: Int = position
      private set
}
```

https://kotlinlang.org/docs/properties.html#getters-and-setters

2023-10-26 04:21 UTC, laco-dev commented on src/main/kotlin/racinggame/InputView.kt
> +    }
`InputView.input()` 이 무엇을 반환할 것이라는 것이 예측이 어렵지 않을까요?
가령 다른 타입의 반환 형태가 필요하더라도 이름이 겹치기 때문에 불가능합니다.

입력이 요구되었을 때 사용자에게 어떤식으로 알릴지에 대해서도 InputView의 역할로 본다면 각각의 메시지를 함수로 분리 해 보면 좋을 것 같습니다
```kotlin
fun getCarCount(): Int
fun getTryCount(): Int
```

2023-10-26 04:21 UTC, laco-dev commented on src/main/kotlin/racinggame/OutputView.kt
> +    }
마찬가지로 Output이 무엇을 출력하기를 기대하는지 드러나지 않습니다.
파라미터로 전달하는 값 또한 무엇을 전달하는 것인지 나타내보면 좋을 것 같습니다

```kotlin
fun printRacingResult(...) 
```

2023-10-26 04:21 UTC, laco-dev commented on src/main/kotlin/racinggame/RacingGame.kt
> +    private val diceStrategy: () -> Int
Dice는 RacingGame 내부에서 사용하는 개념인데, 생성자로 dice 전략을 외부로 드러내는것에 모순이 발생합니다.
"내부에서 구현을 Dice를 사용하지 않는다면?" 을 예로 들수 있겠습니다.

전진 조건 자체를 객체로 정의하여 사용하면 어떨까요?
```kotlin
interface Dice {
   fun roll(): Int
}

class RandomDice: Dice { ... }
class FixedDice: Dice { ... }
```

2023-10-26 04:21 UTC, laco-dev commented on src/main/kotlin/racinggame/RacingGame.kt
> +    }
RacingGame이라면 게임에 대한 시작과 끝이 명확하게 있으면 좋겠습니다.
지금은 단순히 차들을 한바퀴 경주시키는 역할만 하고 있습니다.
또한 몇바퀴 진행할지에 대해서도 경주의 입장에서 필요한 개념인데 Main 함수에서 처리를 하고 있어요

이 내용을 참고한다면 OutputView로 출력하는 전략에 대해서도 도움이 될 것 같습니다.
`val 경주_결과 == 경주.시작()`

2023-10-26 04:21 UTC, laco-dev commented on src/main/kotlin/racinggame/Car.kt
> +    }
현재 자동차 객체는 움직이기 위해 항상 수동적으로 동작합니다.
만약 조건에 따라 자동차를 다르게 움직여야 하는 방법이 여러개라면, 호출하는 곳마다 조건에 따라 forward()를 호출해야만 합니다.
또한 경우에 따라서는 자동차가 뒤로 갈수도 있겠네요.

자동차가 **스스로** 움직일 수 있도록 자율적인 객체로 만들어 보면 어떨까요?
아래 스닙핏을 참고 해보세요

```kotlin
class Car(val moveCondition: MoveCondition) {
   fun move() {
      if (moveCondition.canForward()) {
         forward()
      }
   }
}
```

2023-10-26 09:02 UTC, baek0318 commented on README.md
> +## 자동차 경주 (3단계)
제가 린트체크를 자주 놓치네요 수정하도록 할게요!

2023-10-28 00:00 UTC, baek0318 commented on src/main/kotlin/racinggame/RacingGame.kt
> +    }
몇바퀴를 주행해야하는지에 대해서도 처음에는 포함할려고 했다가 게임의 영역에는 포함되지 않는다고 생각했는데 
리뷰어님의 말처럼 경주라고 생각을 하니 몇바퀴에 대한 정보도 포함되는게 맞겠네요 감사합니다

2023-10-28 06:35 UTC, laco-dev approved these changes
피드백 반영하느라 고생 많으셨습니다.
자기만의 역할을 해야하는 객체가 전부 주사위라는 의존성이 생겨서, 확장성이 아쉬워진 상태입니다.

다음 4단계 미션을 통해, 현재의 구조도 같이 수정될 수 있어서 남겨드린 내용은 참고하셔서 반영 해 주시면 되겠습니다.

2023-10-28 06:35 UTC, laco-dev commented on src/main/kotlin/racinggame/Car.kt
> +    fun move(diceResult: Int) {
Car라는 도메인은 dice라는 랜덤요소와 더이상 연관이 없습니다.
외부에서 Car를 사용할 때 move 함수로 전달하는 diceResult가 무엇인지 모를 것 같은데요.

dice 타입 자체를 전달하는 것과 어떤 차이가 있을까요?
```kotlin
fun move(dice: Dice) {
   ...
}
```

2023-10-28 06:35 UTC, laco-dev commented on src/main/kotlin/racinggame/Car.kt
> +}
CarCondition이라는 타입만 두고 보았을 때, `CarCondition.FORWARD.apply(10)` 이라는 코드가 어떤 동작을 할지 의미가 충분히 전달되고 있을까요..?

아마 이동하는 동작 자체를 추상화 하기 위해 분리를 해 주신 것으로 보입니다.
다만, Car와 CarCondition이 충분한 협력 관계를 가지고 있는가? 는 조금 애매하게 느껴집니다.
지금으로서는 Car 객체가 다음과같이 가지고 있는것이 자연스러워 보입니다.
```kotlin
class Car {
  private var currentCondition: CarCondition = CarCondition.STOP

  fun move(gas: Int) {
      if (gas > 4) { currentCondition = FORWARD }
   ... 
  }
}
```

위 내용은, 요구사항과 상관없이 임의대로 작성한 코드이므로, 무시해주셔도 됩니다.
결론은 CarCondition이라는 이름이 적절한가? 입니다

2023-10-28 06:35 UTC, laco-dev commented on src/main/kotlin/racinggame/Dice.kt
> +    override fun pitch() = Random.nextInt() % 10
코틀린에서 랜덤값을 사용할 때는 IntRange를 주로 활용하고는 합니다.
```kotlin
(0..10).random()
```

2023-10-28 06:35 UTC, laco-dev commented on src/main/kotlin/racinggame/RacingGame.kt
> +}
아직 `List<LIst<String>>` 값이 무엇인지 잘 모를 수 있는데요.
타입을 만들어서 관리해보면 어떨까요?

```kotlin
class RaceResult(
   val roundResults: List<RoundResult>
   ...
)

class RoundResult(cars, ...)
```

2023-10-28 06:35 UTC, laco-dev commented on src/test/kotlin/racinggame/CarConditionTest.kt
> +    Given("주사위가 던져졌다") {
파라미터 이름이 diceResult라고 되어있지만 `CarConditionTest` 의 입장에서는 실제로 주사위라는 관심사를 가지고 있지 않습니다.

주사위가 아닌 다른 방식으로 상태가 결정된다면 이 테스트는 논리적으로 잘못된 테스트가 됩니다

2023-10-28 06:35 UTC, merged