Step3 자동차 경주
next-step/kotlin-racingcar pull request #1428
Opened 2023-10-30 05:10 UTC by jung-woo-kim

안녕하세요!
이번 미션에서는 저번 미션에서 말씀해주신 부분들(VO 등..)을 최대한 활용해보려고 노력했습니다!
좋은 리뷰 덕에 많이 배우고 있습니다 🙏
리뷰 부탁드려요~

2023-10-31 03:42 UTC, Hyeon9mak requested changes
안녕하세요 정우님! 3단계 깔끔히 잘 구현해주셨습니다.
Car 가 의존하는 대상을 interface 로 두신 덕분에 간편한 테스트가 가능하군요 💯 
view 의 책임이 여기저기 분포되어 있는 느낌인데요, 이것들을 한번 정리해보면 좋을거 같습니다.
궁금하신점 언제든지 코멘트, DM 남겨주세요.

2023-10-31 03:42 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/controller/CarController.kt
> +        )
`println("자동차 대수는 몇 대 인가요?")` 역시도 출력방법과 관련이 있지 않을까요?
출력을 담당하는 view 패키지 내부 객체가 관리해줄 수 있겠어요.

2023-10-31 03:42 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/controller/CarController.kt
> +        }
`Cars` 에게 "tryCount 만큼 움직이도록 해!" 라고 메세지를 보내볼 수도 있겠네요 😄 👍

2023-10-31 03:42 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/model/Car.kt
> +    }
자동차 이동거리 표현 역시도 view 와 관련있어보여요.

2023-10-31 03:42 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/model/Cars.kt
> +    }
합치는 것도 역시나 😉

2023-10-31 03:42 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/model/NaturalNumber.kt
> +    }
값을 표현하는 객체라면 value class 를 활용해볼 수 있겠네요!

2023-10-31 03:42 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/model/NaturalNumber.kt
> +        }
생성자와 완전히 동일해보이는데, 별개 팩터리 메서드를 만드신 이유가 있을까요? 🤔

2023-10-31 03:42 UTC, Hyeon9mak commented on src/test/kotlin/racingcar/model/TrueEngine.kt
> +}
`Car` 가 의존하는 대상을 interface 로 두신 덕분에 간편한 테스트가 가능하군요 👍 👍

2023-10-31 17:08 UTC, jung-woo-kim commented on src/main/kotlin/racingcar/model/NaturalNumber.kt
> +    }
덕분에 value class에 대해서 더 공부해보게 되었네요! 감사합니다 🙏

2023-10-31 17:31 UTC, jung-woo-kim commented on src/main/kotlin/racingcar/model/NaturalNumber.kt
> +        }
전 이런 Wrapper class는 가독성 측면에서 또, Util적인 측면에서 생성자 같더라도 정적 팩터리 메서드를 만들어주는 것이 좋다고 생각하는데 현구님 생각은 다르신가요?

2023-10-31 17:34 UTC, jung-woo-kim commented on src/main/kotlin/racingcar/controller/CarController.kt
> +        }
사실 똑같이 구현했다가, car가 한번 이동 후 출력해줘야하는 로직 상 model인 cars가 OutputView를 사용하게되는 방향이 좋은가?를 생각했을 때 저는 아니라고 생각했어요. 출력이 바뀌면 model도 그에 영향을 받을거라고 생각했거든요.

차라리 Controller에서 model을 활용해서 n번 try하면 OutputView에 대한 요구사항이 바뀌더라도 Cars에 영향을 주지 않겠다고 생각했어요.

2023-10-31 17:37 UTC, jung-woo-kim commented
안녕하세요 현구님~ 리뷰 재요청 드립니다 🙏

```
약간의 고민 포인트가 있었는데요. 가령 Car나 Cars의 인스턴스 변수를 기본 로직만 기능하기엔 private로 충분했는데, 이를 테스트하려고 하니 Getter를 만들거나 Private를 제거해서 값을 확인해야했어요. 혹시 뭔가 더 좋은 방법이 있다면 알려주세요!
```

위 질문에 대한 답 혹시 가능할까요! 저의 현재 생각은 Setter를 test를 위해 여는 것은 구현 상의 문제가 있는 것이고, Getter 정도는 괜찮다고 생각해요!

2023-11-01 12:19 UTC, Hyeon9mak approved these changes
안녕하세요 정우님! 리팩터링 잘 진행해주셨습니다 👍 👍 

> private method 를 테스트하려고 하니 getter 를 만들거나 private 을 제거해서 값을 확인해야했어요. 혹시 뭔가 더 좋은 방법이 있다면 알려주세요!

근본적으로 private method 는 테스트 할 필요가 없다고 생각해요.
저희가 특정 객체에게 기대하는 모든 동작은 public method 들이고,
저희는 사실 private method 가 존재하는지도 몰라야합니다.

그럼에도 "private method 동작 내용이 불안해서 꼭 테스트 하고 싶어." 라는 마음이 생길 때가 있는데,
해당 private method 하나에서 너무 많은 일이 진행되는 건 아닌지 의심해볼 수 있는 신호 같아요. 
즉, 개별 클래스로 분리할만하다는 것이죠.
개별 클래스로 분리되면 자연스럽게 private method 가 public method 로 변하고, 테스트 코드 작성도 훨씬 수월해질 것 같아요.

정우님은 어떻게 생각하시나요? 😄 
다음 단계를 진행하시면서 정우님의 생각을 알려주세요.

2023-11-01 12:19 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/controller/CarController.kt
> +        }
> 지금 생각해보니 Car의 position history를 저장해서 가지고 있는 model이 추가적으로 필요하겠다는 생각이 드네요..

👍 맞아요. 미션 요구사항이 실시간으로 경주 진행 상황을 보여주는 것 같아도, 내부적으로는 히스토리를 기록 후 뿌려줄 수도 있죠.
꼭 바꾸셔야하는 건 아니고 아이디어를 제안드린 것이니, 정우님께서 더 적합하다고 생각하시는 구조를 선택하시면 될거 같아요.

2023-11-01 12:19 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/model/NaturalNumber.kt
> +        }
저는 기본 생성자 외 별개 팩터리 메서드가 존재하면 '다른 동작을 추가로 수행하나?' 라는 생각과 함께 추가로 확인해보는 수고가 생긴다고 생각해서요. 정우님의 생각도 좋다고 생각합니다 👍

2023-11-01 12:19 UTC, merged