feat(step3): add racing car core class and application
next-step/kotlin-racingcar pull request #1435
Opened 2023-10-30 09:43 UTC by yw9594

안녕하세요 멘토님 :) 피드백 부탁드립니다.

제가 실수로 이번 3단계에서 4단계의 일부 요구사항을 헷갈려서 4단계의 우승자 관련된 코드가 조금 들어가있어요.(getWinners) 이 부분은 감안하고 봐주셨으면 합니다. (_ _)

궁금한 점이 있는데요. 혹시 콘솔 입력을 받는 경우 테스트를 어떻게 따로 하시는지 궁금합니다. :)

2023-10-30 14:50 UTC, MyStoryG requested changes
윤완님 안녕하세요.
3단계 미션 잘 구현해주셨습니다. 👍 
몇 가지 코멘트 남겼는데 확인하시고 반영 후에 다시 리뷰 요청 부탁드립니다.

2023-10-30 14:50 UTC, MyStoryG commented on README.md
> +  - RacingcarGameApplication 클래스 구현
기능 목록을 작성하는 이유는 해당 단위로 커밋을 하도록 유도하는 의미도 있습니다.

2023-10-30 14:50 UTC, MyStoryG commented on src/main/kotlin/racingcar/RacingcarGameApplication.kt
> +        println("실행 결과")
View를 나누셨는데 여기서 출력을 하는 것은 View의 역할을 여기서 하고 있는 것이 아닐까요?

2023-10-30 14:50 UTC, MyStoryG commented on src/main/kotlin/racingcar/RacingcarGameApplication.kt
> +        }
0부터 입력값까지 반복하면 3회 시도 시 실제로는 4회를 실행하게 됩니다.
그리고 round라는 index도 사용하지 않고 있으니 repeat로 변경해 보세요.

2023-10-30 14:50 UTC, MyStoryG commented on src/main/kotlin/racingcar/RacingcarGameApplication.kt
> +        private val resultView: RacingcarGameResultView = RacingcarGameResultView()
view를 companion object 내에 선언하셨네요.
이 방법도 있지만 view 자체를 class가 아닌 object로 만드는 방법도 있으니 참고하세요.

2023-10-30 14:50 UTC, MyStoryG commented on src/main/kotlin/racingcar/RacingcarGameApplication.kt
> +}
클래스와 메인함수가 같이 있네요! 이 부분도 분리하시면 더욱 유연한 구조가 될거에요.

2023-10-30 14:50 UTC, MyStoryG commented on src/main/kotlin/racingcar/component/RacingcarGameContext.kt
> +class RacingcarGameContext(
개인적으로 클래스명만으로는 어떤 역할을 하는지 알기가 어렵다고 생각해요.

2023-10-30 14:50 UTC, MyStoryG commented on src/main/kotlin/racingcar/component/RacingcarGameContext.kt
> +        carMovementManager.moveCarsWithCondition(cars)
CarMovementManager 클래스가 존재하는데 굳이 이 클래스에서 의존성을 가질 필요는 없겠네요. 구조를 조금만 바꾸시면 좀 더 객체의 역할이 분명해 질 것 같아요.

2023-10-30 14:50 UTC, MyStoryG commented on src/main/kotlin/racingcar/component/RacingcarGameContext.kt
> +    fun getWinners(): List<Car> {
만약 moveCarsWithCondition 기능을 이 클래스에서 제거하게 된다면 이 클래스는 우승자를 찾는 역할만 하게 됩니다. 그러면 이 클래스의 이름과 역할이 분명하게 정해지겠네요!

2023-10-30 14:50 UTC, MyStoryG commented on src/main/kotlin/racingcar/model/Car.kt
> +    fun currentDistance(): Int {
함수명은 동사로 시작하면 더욱 좋겠죠?

2023-10-30 14:50 UTC, MyStoryG commented on src/main/kotlin/racingcar/model/Car.kt
> +            return cars.toList()
List로 바꿔서 외부에서 변경을 막으려고 의도하신 것 같네요! 👍

2023-10-30 14:50 UTC, MyStoryG commented on src/test/kotlin/racingcar/component/RacingcarGameContextTest.kt
> +        test("distance changed after some rounds") {
우리는 영어보다는 한글이 익숙한 한국 사람이니 테스트명도 한글로 적어보시면 어떨까요? 그럼 좀 더 명확히 테스트 하려고 하는 내용을 파악할 수 있을 것 같아요. 그리고 지금과 같이 모호하게 몇 라운드 후에 거리가 변화된다는 것보다는 정확한 숫자로 표기하면 더 좋을 것 같습니다. 또한 테스트는 이렇게 큰 덩어리로 묶기 보다는 기능 명세로 적으신 내용들 단위로 나눠서 해보시는 것도 추천드려요.

2023-10-31 10:39 UTC, yw9594 commented
안녕하세요. 피드백 반영하였습니다. 

다만 기능 명세의 경우 제가 todo 리스트로 잘못 이해해서 이번 step까지는 조금 이해해주십사 합니다. (_ _)

2023-11-01 12:45 UTC, MyStoryG approved these changes
윤완님 안녕하세요.
피드백 반영 하시느라 수고하셨습니다!
다음 단계 진행을 위해 머지하도록 하겠습니다!

2023-11-01 12:45 UTC, merged