[Step3] - 자동차 경주
next-step/kotlin-racingcar pull request #1439
Opened 2023-10-30 11:05 UTC by parker1609

안녕하세요. 현재님!
3단계 코드리뷰 요청드립니다!

## 고민 포인트

### 책임을 어느 객체에 부여해야 할까?

`RacingGame`: 사용자에게 받은 입력과 정해진 게임 규칙을 바탕으로 레이싱 게임을 실행하는 책임
`RacingCar`: 레이싱 자동차는 게임 규칙에 따라 이동할 수 있을지 판단하고, 위치에 대한 모든 정보 저장 (위치는 현재 정보와 각 시도마다 모두 저장하고 있습니다.)
`RacingGameMoveRule`: 게임 규칙 (랜덤값으로 인해 테스트하기가 어려워 인터페이스로 추상화를 하였습니다. 테스트때는 테스트에서만의 게임 룰을 정해서 진행하는 것으로 테스트를 나름 가능하게 만들었습니다.)

잘부탁드립니다!

2023-10-30 15:37 UTC, hjjae2 requested changes
안녕하세요, 성범님!

몇 가지 코멘트 남겼는데요, 확인 한번 부탁드립니다! 🙇

2023-10-30 15:37 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/RacingCar.kt
> +    var position: Int = 0
외부에서도 값을 변경할 수 있겠네요. 

[private set](https://kotlinlang.org/docs/properties.html#getters-and-setters) 을 활용해보면 어떨까요?

2023-10-30 15:37 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/RacingCar.kt
> +            position++
지난번에 한 줄로 표기하는 것이 더 읽기 편하게 느껴지신다고 하셨는데요, 요 부분도 한 줄로 표현하면 좋겠네요!

ktlint 같은 린트 도구를 idea 에 자동으로 적용해주는 방법도 있으니 필요하시다면 사용해보셔도 좋을 것 같아요!

2023-10-30 15:37 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/utils/RandomNumberGenerator.kt
> +}
java, kotlin 이 이미 만들어둔 랜덤 클래스(Random)를 사용해 볼  수도 있을 것 같은데요. 

보통 간단한 유틸리티성 클래스는 직접 구현해 사용하시나요?? 궁금해서 여쭤보아요! 💭

2023-10-30 15:37 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/view/ConsoleView.kt
ConsoleView 는 네이밍, 패키지 위치를 통해 입/출력을 담당해주는 파일로 이해했습니다.

하지만 지금은 입/출력을 포함해 컨트롤러 역할 까지도 수행하고 있는 것 같습니다.

입/출력, 컨트롤러의 역할을 분리, 정리해보면 어떨까요? 🤔

2023-10-30 15:37 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/rule/RandomRacingGameMoveRule.kt
> +    }
[클래스 내 코드 작성 순서](https://kotlinlang.org/docs/coding-conventions.html#class-layout)에 대한 가이드가 있습니다. 한번 참고해봐주시면 좋을 것 같아요!

2023-10-30 15:37 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/RacingCar.kt
> +    val moveRecords: MutableList<Int> = mutableListOf()
이 부분 조금 고민이 되네요. 🤔 

이 값을 말씀하신 "위치에 대한 정보"라고 본다면  RacingCar가 갖고 있는 것도 어색하진 않아보이는데요, 이것을 "위치에 대한 정보"라고 보는 것에 조금 의문이 듭니다. 오히려 "위치에 대한 정보"는 position 으로 볼 수 있을 것 같고, 이것은 "움직임에 대한 기록 정보" 정도로 해석하는게 더 적절한 것 같기도 해서요.

그렇게 본다면 움직임에 대한 기록을 RacingCar가 갖고 있는게 맞을까? 자동차는 움직이는 행위 자체에만 신경쓰는 것이 더 적절하진 않을까?

오히려 움직임에 대한 기록 정보는 게임 실행에 대한 책임을 갖고 있는 `RacingGame`이 갖고 있는 게 더 적절할 수 있을까 싶은 생각이 들었습니다.

이 부분에 대해서 성범님은 어떻게 생각하실까요? 성범님 의견이 궁금합니다.

2023-10-30 15:37 UTC, hjjae2 commented on src/test/kotlin/me/parker/nextstep/kotlinracingcar/RacingCarTest.kt
> +        val racingCar = RacingCar(TestRacingGameMoveRule(true))
RacingGameMoveRule 인터페이스를 통해 랜덤성에 대한 테스트 코드를 해결하셨군요. 👍

2023-10-30 15:43 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/RacingCar.kt
> +    val moveRecords: MutableList<Int> = mutableListOf()
\+ PR 본문에 적어주신 RacingGame, RacingCar, RacingGameMoveRule 에 대한 책임을 정리해주신 부분에 대해서 크게 어색함을 느끼지 않고, 적절히 설정해주셨다고 생각합니다.

다만, 이 코멘트를 통해 RacingGame, RacingCar 에 역할에 대해 다시 한번 사소한 고민을 해볼 수 있지 않을까 싶습니다.

2023-10-31 10:46 UTC, parker1609 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/utils/RandomNumberGenerator.kt
> +}
네! 대부분 유틸 클래스로 분리하고 사용하고 있습니다. 테스트하기도 더 유용하다고 생각했었고, 만약에 다른 라이브러리로 변경하더라도 유틸 클래스 내부만 바꿔주면 되어서 좀 더 변경에 유연하지 않을까한 생각도 있었습니다.
사실 현재 랜덤 숫자 뽑는 기능은 간단하다고 생각되어 추천해준 코드를 바로 사용했었는데, Random 클래스도 기본적으로 제공해주는 기능이라 이를 사용하는 것이 더 가독성이 좋아 적용해보았습니다!

2023-10-31 11:17 UTC, parker1609 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/view/ConsoleView.kt
피드백 감사합니다!

이를 분리하니 나중에 입출력이 콘솔이 아니라 다른 것으로 바뀌어도 훨씬 유연하게 변경할 수 있겠다고 느꼈습니다.
(지금은 적용하지 못하였지만, 인터페이스로 분리한다면 컨트롤러에 거의 코드 변화없이도 바꿀 수 있겠구나라고 생각하였습니다!)
감사합니다!

2023-10-31 12:01 UTC, parker1609 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/RacingCar.kt
> +    val moveRecords: MutableList<Int> = mutableListOf()
피드백 감사합니다!

말씀해주신 부분에 크게 공감을 하였습니다. 레이싱 자동차의 모든 기록을 자동차 자체에서 가지고 있는 것은 생각해보니 어색하다고 느꼈습니다. 자동차는 이전 라운드와는 전혀 무관하고 현재 시점이 중요하다고 생각합니다. 과거 정보는 조금 다른 성격의 데이터라고 보였습니다.

- RacingCar: 레이싱 자동차는 게임 앱에서 실행되는 주체로 게임의 진행에 따라 움직이는 역할 (게임이 진행되는 현재 시점의 데이터로 계속 업데이트되는 정보를 갖는다.)
- RacingGame: 레이싱 게임은 각 시도(라운드)가 존재하고, 이 라운드마다의 정보는 레이싱 게임이 관리하는 정보이다.

2023-11-01 08:48 UTC, hjjae2 approved these changes
안녕하세요, 성범님!

의견 드린 부분에 대해서 잘 반영해주셨네요. 

추가로 코멘트 남긴 내용이 있으니 다음 미션 진행하며 함께 확인부탁드립니다. 고생하셨습니다. 🙇

2023-11-01 08:48 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/RacingGame.kt
> +        private set
클래스 변수로 사용해야 하는 걸까요? start() 메서드 내 지역변수로 관리해볼 수도 있는걸까요?

2023-11-01 08:48 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/RacingGame.kt
> +        var round = 1
사소하지만 매직 넘버는 변수/상수로 관리하면 좋겠네요. 👍

2023-11-01 08:48 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/view/ViewController.kt
view 와 controller 는 분리된 개념인데, 패키지/파일 네이밍으로 유추할 때 view 로 해석해야 할 지 controller 로 해석해야 할 지 혼란을 야기할 수 있을 것 같아요. 패키지를 분리해보거나 파일명을 수정해보면 어떨까요? 🤔

2023-11-01 08:48 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/view/ConsoleView.kt
> +object ConsoleView {
사소한 의견입니다. 

역할을 분리해보는 연습을 하는 중이기도 하니, input, output 에 대한 처리를 나눠봐도 좋겠네요.

> https://edu.nextstep.camp/s/lepg4Qrl/ls/I3gtHPZY (프로그래밍 요구 사항 참고)

2023-11-01 08:48 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/view/ConsoleView.kt
> +        print("Result: ${racingGame.resultOfRacingCars}")
이 로직(출력)은 필요한가요?

2023-11-01 08:48 UTC, hjjae2 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/view/ConsoleView.kt
> +        print("Result: ${racingGame.resultOfRacingCars}")
라운드 정보를 관리하는 쪽(지금은 `racingCarGameRounds: List<RacingCarGameRound>`)에서 numOfAttempts, numOfRacingCar 에 대한 정보를 (추출할 수 있어보여)추출하거나, 명시적으로 이 정보를 관리해준다면 ConsoleView 에서 racingGame 에 대한 의존을 제거할 수도 있을 것 같네요.

혹시 어떻게 생각하실까요? 🤔

2023-11-01 08:49 UTC, merged

2023-11-01 22:58 UTC, parker1609 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/view/ConsoleView.kt
> +        print("Result: ${racingGame.resultOfRacingCars}")
디버깅 과정에서 라운드별 출력을 보기쉽게 구분하기 위해 사용하였다가 그대로 남겨두었었습니다.. 삭제하였습니다! 감사합니다!

2023-11-01 23:09 UTC, parker1609 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/view/ConsoleView.kt
> +        print("Result: ${racingGame.resultOfRacingCars}")
피드백 감사합니다!

생각해보니, 출력하는 곳에서 레이싱 게임의 모든 정보를 갖는 `RacingGame` 객체를 가지는 것은 쓸데없이 너무 큰 의존성을 갖는다고 느꼈습니다. 게임 결과를 출력하기 위해서는 **명확**하게 게임의 결과만 갖고 있는 객체에 의존을 하는 것이 맞겠다고 생각하여 반영해 보았습니다!

2023-11-01 23:13 UTC, parker1609 commented on src/main/kotlin/me/parker/nextstep/kotlinracingcar/RacingGame.kt
> +        private set
디버깅 과정에서 마지막 레이싱 결과를 출력하기 위해서 클래스 변수로 사용했었습니다. 이 출력은 제거하였고, 해당 변수도 지역변수로 사용하도록 하였습니다! 감사합니다!