Step5 - 리팩터링 적용
next-step/kotlin-racingcar pull request #1519
Opened 2023-11-04 17:18 UTC by Yunho-Park

step4 PR (#1454)  에서 주신 피드백적용과 함께,
step5 에서 요구하는 MVC 패턴을 적용 해 보았습니다.

2023-11-05 02:41 UTC, Yunho-Park commented
1급 컬렉션 SimpleCars 를 정의해서 써봤고, 질문이 있습니다!
단일 property가 가진 api (제 코드에선, List<> 의.) 들을 직접 사용하고 싶은데요

아래와 같이 단일 프로퍼티를 참조하는 단계가 들어가는것이 불편합니다.
```kotlin
val cars = SimpleCars()
cars.carList.isEmpty() // cars.isEmpty() 로 쓸 수 없나
cars.carList.size()  // cars.size() 로 쓸 수 없나
```

단일 프로퍼티를 public으로 두고 직접 접근하는게 `다들 쓰는 방식인지`, 아니면 `더 좋은방법이 있는지` 궁금합니다

## 상세 고민 내용
List가 제공하는 api를 SimpleCars() 에서 하나하나 오버라이드 한다면
1급 컬렉션을 사용하는 의미가 없는것 같습니다.
[이전 PR에서 주신 참고자료](https://tecoble.techcourse.co.kr/post/2020-05-08-First-Class-Collection/)를 예로 들면,
IceCreams 외에 SnackList, HotFoods 등의 1급 컬렉션에도 오버라이드를 선언하겠지요

직접 List를 상속받아도 매번 abstract function들을 구현 해줘야 하구요

2023-11-05 04:57 UTC, pci2676 requested changes
조금 더 개선해보면 좋을 부분에 리뷰를 남겨두었습니다.

확인 부탁드립니다.

2023-11-05 04:57 UTC, pci2676 commented on src/main/kotlin/race/domain/SimpleCars.kt
> +}
고민 하신 내용에 답변입니다.

List의 특정 기능을 일급컬렉션에서 동일하게 제공하시고 싶으신것 같습니다.

그 경우 일급컬렉션에는 필요한 기능만 구현을 해서 제공합니다.

이미 일급컬렉션이 가지고 있는 멤버변수가 Collection으로 이루어져 있기 때문에

일급컬렉션은 collection의 기능을 외부로 전달하기만 하면 될 것 같습니다.

가령 컬렉션 사이즈를 확인하고 싶다면 collection의 size()가 필요합니다.

그러면 일급컬렉션에는 아래와 같이 구현합니다.

```kotlin
class SimpleCars(carNames: List<String>) {
    val carList: List<SimpleCar>

    init {
        this.carList = carNames.map { SimpleCar(it) }
    }

    val size:Int
        get() = carList.size

}
```

Collection 인터페이스를 구현해야하는것 아닌가? 라는 고민을 하신 것 같습니다.

그러나 일급컬렉션이 Collection의 모든 인터페이스를 필요로 하지 않기때문에

필요한 기능만을 위와 같이 제공하면 될것 같습니다.

---

그런데 만약 정말 Collection의 모든 인터페이스가 필요하다. 다 있었으면 좋겠다 라면 방법이 있습니다.

다만 일급컬렉션의 구조를 조금 바꾸어주시는것이 좋을것 같습니다.

1. 생성자 위치 변경
코틀린은 주생성자 하나와 여러개의 부생성자를 두는 것이 관리하기에 용이합니다.  
아래와 같이 먼저 변경을 해보겠습니다.

```kotlin
class SimpleCars(val carList: List<SimpleCar>){
    constructor(carNames: List<String>) : this(carNames.map { SimpleCar(it) })
}
```

2. 이제 아래와 같이 Collection(여기서는 List)를 구현하도록 하고 delegate를 이용하여 구현의 책임을 모두 위임할 수 있습니다.

```kotlin
class SimpleCars(val carList: List<SimpleCar>) : List<SimpleCar> by carList {
    constructor(carNames: List<String>) : this(carNames.map { SimpleCar(it) })
```

이렇게 하면 SimpleCars를 이용하여 List의 모든 기능을 이용할 수 있습니다.

다만 위에서 말씀드렸듯이 **모든 기능을 노출할 명확한 이유가 없다면** 굳이 이렇게 구현할 필요가 없어보입니다.

2023-11-05 04:57 UTC, pci2676 commented on src/test/kotlin/race/domain/SimpleCarsTest.kt
> +    }
테스트 이름과 다른 검증 구문이 많이 존재하는것 같습니다.

테스트에서 검증하고자 하는 부분을 명확하게 하기 위해

불필요한 검증 구문은 제거해주시는 것이 좋을것 같습니다.

2023-11-05 04:57 UTC, pci2676 commented on src/test/kotlin/race/domain/SimpleCarsTest.kt
> +    }
또한 테스트를 하기 위해 수반되어야 하는 동작이 많은것 같습니다.

가장 멀리 이동한 자동차들이 우승한다는 것을 나타내기 가장 좋은 방법은

가장 멀리 이동한 자동차를 미리 만들어두고 그 자동차가 우승자가 된 것을 확인하는 것 일 것 같습니다.

```kotlin
val loseCar = SimpleCar(location = 0, name = "loser")
val winnerCar = SimpleCar(location = 100, name = "winner")

val cars = SimpleCars(listOf(loseCar, winnerCar))
val winners = cars.findWinners()
...
```

2023-11-05 04:57 UTC, pci2676 commented on src/main/kotlin/race/domain/SimpleCars.kt
> +    }
이 기능도 테스트할 수 있도록 구조를 변경해보시는 것이 좋을것 같습니다!

2023-11-05 04:57 UTC, pci2676 commented on src/main/kotlin/race/domain/SimpleCar.kt
> +            throw IllegalArgumentException("자동차 이름은 ${NAME_MAX_LENGTH}자를 초과할 수 없습니다")
value object를 참고하여 개선해보시면 좋을것 같습니다!

새로운 객체가 탄생할 수 있을것 같습니다.

https://kotlinlang.org/docs/inline-classes.html

2023-11-08 11:02 UTC, Yunho-Park commented on src/test/kotlin/race/domain/SimpleCarsTest.kt
> +    }
테스트를 위해 코드가 수정되어서는 안된다고 배워서, location을 받는 생성자를 추가하지 않고
직접 이동시켜 가며 단독우승 및 공동우승 케이스를 테스트했습니다.

말씀하신대로 수정하려면 SimpleCar 및 SimpleCars의 생성자를 더 만들어야 하는데
다른 방법은 없을까요

2023-11-08 12:18 UTC, Yunho-Park commented on src/main/kotlin/race/domain/SimpleCars.kt
> +}
이번 강의에서 DSL관련 내용을 듣고
전달받은 `코드블록을 List<SimpleCar> 타입 프로퍼티에 redirect` 해주는 SimpleCars.forEach()를 구현하고싶었는데,
아래와 같이 구현하니 블록 안에서 "it"을 못찾습니다
도움주실 수 있을까요?

```kotlin
// 현재 : simpleCars.carlist.forEach { println(it.name) }
// 하고싶었던것 : simpleCars.forEach { println(it.name) }   (중괄호 내부에서 it 이 자동 정의되지 않습니다)

// SimpleCars.kt
 fun forEach(block: SimpleCar.() -> Unit) {
        carList.forEach{ block }
 }
```

2023-11-08 13:24 UTC, Yunho-Park commented on src/test/kotlin/race/domain/SimpleCarsTest.kt
> +        Assertions.assertThat(cars.findWinners().map { it.carName.name }).contains(*carNames)
value class 를 도입하긴 했는데, 이렇게 `it.carName.name` 으로 1depth더 들어가는 모양새가 너무 불편합니다
이건 어쩔수 없는건가요?

2023-11-08 13:40 UTC, Yunho-Park commented on src/main/kotlin/race/domain/SimpleCar.kt
> +            throw IllegalArgumentException("자동차 이름은 ${NAME_MAX_LENGTH}자를 초과할 수 없습니다")
반영했습니다! [2709508](https://github.com/next-step/kotlin-racingcar/pull/1519/commits/2709508fceaea912e8e63199ea93c402bfb2e8c3)

2023-11-08 13:48 UTC, Yunho-Park commented on src/main/kotlin/race/domain/SimpleCars.kt
> +    }
랜덤값 생성을 SimpleCar 클래스로 내리자니 SimpleCar.move() 의 테스트가 불가능해지고,
moveAll() 의 인자로 랜덤값을 받는다는건 모든 자동차의 move()에 모두 같은 값을 전달하게 됩니다.
변경할수 있는 방법이 떠오르질 않는데 어떤 구조를 그리신걸까요?

2023-11-09 00:16 UTC, pci2676 commented on src/test/kotlin/race/domain/SimpleCarsTest.kt
> +        Assertions.assertThat(cars.findWinners().map { it.carName.name }).contains(*carNames)
이전에 일급컬렉션에서 size를 노출했던 것과 동일하게 적용하시면 될 것 같습니다.

이러한 경우 디미터 법칙을 적용한다고 부르곤 합니다.

아래 글을 비롯하여 디미터 법칙을 검색하여 참고해보시면 좋을것 같습니다. 😄 

https://tecoble.techcourse.co.kr/post/2020-06-02-law-of-demeter/

2023-11-09 00:20 UTC, pci2676 commented on src/main/kotlin/race/domain/SimpleCars.kt
> +    }
테스트가 불가능하다 -> 테스트를 힘들게 하는 요소가 제어 불가능한 영역에 있다. -> 테스트를 힘들게 하는 요소를 제어 가능한 영역으로 옮긴다.

위와 같은 흐름으로 변경해보시면 가능할 것 같습니다.

이제 이를 구현하기 위한 두가지 방법이 있을것 같습니다.

1. 제어가 안되는 값을 외부에서 전달받는다.
2. 제어가 되지 않는것을 의존하지 않는다. (의존성 역전)

1번의 경우 moveAll내에서 생성하던 random 값을 moveAll의 파라미터로 주입받으면 될 것 같습니다.  

2번의 경우 random 값을 생성하는 부분을 interface로 변경합니다. 이 부분은 의존성 역전에 대해 검색해보시면 참고할 만한 많은 글이 나올것 같습니다.

2023-11-09 00:33 UTC, pci2676 commented on src/test/kotlin/race/domain/SimpleCarsTest.kt
> +    }
>테스트를 위해 코드가 수정되어서는 안된다고 배워서, 

맞습니다. 그런데 상황에 따라 조금은 다르게 받아들여질 수 있습니다.  
'테스트를 하기 힘들다'는 곧 운영 코드의 구조 개선이 필요할 수 있다는 신호로 받아들일수도 있기 때문입니다.

운영코드에서 꼭 이렇게 구현하는 방법이 최선인가를 고민해보고 지금 방법 말고는 다른 방법이 없다라면 어쩔수 없을 것 같습니다.  
하지만 다른 방향으로 운영 코드를 바꿀수 있고 그로 인해 테스트도 가능해진다면 더 견고한 애플리케이션의 작성이 가능해질 수 있다고 보는 편입니다.

지금 상황에서 자동차를 생성할때 이름을 전달하면 아래와 같이 내부 init절에서 자동차를 생성하고 있습니다. 

```kotlin
class SimpleCars(carNames: List<String>) {
    val carList: List<SimpleCar>

    init {
        this.carList = carNames.map { SimpleCar(it) }
    }
}
```

이를 조금 변경해보면 아래와 같이 표현할 수 있습니다.  
```kotlin
class SimpleCars1(val cars: List<SimpleCar>) {
    constructor(carNames: List<String>) : this(carNames.map { SimpleCar(it) })
}
```

코틀린은 주생성자에서 프로퍼티 노출이 가능합니다.  
그래서 주생성자에 노출할 프로퍼티를 정의하고 부생성자를 통해 여러가지 생성방법을 제공할 수 있습니다.  
이렇게 변경하면 운영코드에서 사용되지 않는 코드도 없고 테스트를 할때도 SimpleCar를 직접 제어하여 주입할 수 있습니다.

같은 방법으로 SimpleCar도 변경한다면 테스트에서만 사용되는 코드는 없고, location의 제어가 한층 수월해지고, 테스트가 편해지는 이점을 가져갈 수 있을것 같습니다.

테스트 코드는 하나의 문서 역할을 하기도 합니다.  
문서가 짧고 간결하면 이해하기 편한것처럼 테스트 코드에서 여러가지 행위를 하면 그 행위까지 이해를 해야하기 때문에 부담이 될 수 있습니다.  

또한 테스트 코드에는 가능한 구현 세부사항이 나오지 않도록 하는것을 권장드립니다.  
보통 구현세부사항은 변경이 잦은 영역이라고 합니다. 변경이 잦으면 운영코드 하나 수정했을때 테스트 코드에서 하나이상 N개의 테스트 코드를 수정해야 하는 상황이 발생합니다. (일급 컬렉션의 내부 구조를 노출하는 것도 동일합니다. 외부에서 보았을때 일급컬렉션의 내부 구조도 구현세부사항에 불과하기 때문입니다.)

> 만약 상황에 따라 테스트를 위한 코드 수정이 용인된다면, 참고할 만한 기준이 있을까요

그래서 저는 구현 세부사항이 테스트를 하기 위해 많이 노출이 되어야 한다면 이를 코드 개선의 신호로 받아들이는 편입니다.

2023-11-09 00:45 UTC, pci2676 commented on src/main/kotlin/race/domain/SimpleCars.kt
> +}
```kotlin
fun forEach(block: (SimpleCar) -> Unit) {
        carList.forEach(block)
    }
```

이렇게 해주시면 원하시는대로 될것 같습니다~!

2023-11-09 09:33 UTC, pci2676 requested changes
코멘트로 달아둔 답변을 참고하여 다시 리뷰요청부탁드립니다.

2023-11-11 00:41 UTC, Yunho-Park commented on src/test/kotlin/race/domain/SimpleCarsTest.kt
> +    }
[3a84a8f](https://github.com/next-step/kotlin-racingcar/pull/1519/commits/3a84a8fa2cc05059ab6ee4a41bf63fc5e17d3991) SimpleCar 클래스는 location까지 받느라 시그니처가 달라져서 잘 반영했으나,
SimpleCars는 JVM 기준으로 List<SimpleCar> 와 List<String> 가 같은 시그니처로 판단되어 `컴파일이 실패`하므로
부득이하게 팩토리 함수 선언이 필요했습니다.

> 이렇게 변경하면 운영코드에서 사용되지 않는 코드도 없고

SimpleCar의 location을 입력받는 `운영에 쓰이지 않는 코드조각` 이 기존에 쓰이던 생성자와 같은 라인에 끼워넣어졌으니,
정확히는 운영코드에서 사용되지 않는 코드는 있지만 그게 `온전한 한줄을 이루지 않을 뿐`이지 않나요?
SimpleCars 역시 운영에서 사용되지 않을 형태로 주 생성자를 정의한건 마찬가지인듯 합니다.

하지만 그런점이 있더라도 유지보수성이나 협업 상황까지 고려했을 때
테스트가 간결하고 구현 세부사항 노출이 적은 현재 형태가 좋을것같습니다

2023-11-11 01:11 UTC, Yunho-Park commented on src/main/kotlin/race/domain/SimpleCars.kt
> +    }
> 1번의 경우 moveAll내에서 생성하던 random 값을 moveAll의 파라미터로 주입받으면 될 것 같습니다.

moveAll은 보유한 모든 SImpleCar 인스턴스들의 move("주사위값") 를 호출하는 메서드인데,
그 주사위값을 외부에서 주입받는다는게 어떤 뜻인지 모르겠습니다.
`모든 차를 전진`시키거나 `모든차를 정지`시키려는게 아니면 1번은 현재 상황에 맞지 않는 구조 아닐까요?
다른 뜻으로 말씀하신 거라면 추가 설명 부탁드립니다

> 2번의 경우 random 값을 생성하는 부분을 interface로 변경합니다. 이 부분은 의존성 역전에 대해 검색

의존성 역전 개념도 글들을 읽어 보았는데요,
SimpleCars는 일급 객체로서 List<SimpleCar> 를 wrapping 할 뿐이라 해당 개념이 적용될 부분이 맞나 싶습니다.
또한, random값을 생성하는 부분을 interface로 뺀다고 해도.. moveAll 을 테스트 하려면 여전히 mocking 하는것 외에 방법이 없지 않나요? random() 을 mocking 하는데서 직접 구현한 메서드를 mocking하는걸로 바뀔 뿐이지 않냐는 의문입니다.

2023-11-11 01:42 UTC, Yunho-Park commented on src/test/kotlin/race/domain/SimpleCarsTest.kt
> +        Assertions.assertThat(cars.findWinners().map { it.carName.name }).contains(*carNames)
[5f9349a](https://github.com/next-step/kotlin-racingcar/pull/1519/commits/5f9349a33ea51366159442286561c05f7cb3deba) 에서 자동차 이름이 아닌 인스턴스 확인으로 변경되어 해당 코드는 없어졌지만,

SimpleCar에서 carName 프로퍼티의 값을 반환해주는 메서드 carName() 을 두면 됐겠네요
감사합니다

2023-11-11 18:16 UTC, pci2676 commented on src/test/kotlin/race/domain/SimpleCarsTest.kt
> +    }
> [3a84a8f](https://github.com/next-step/kotlin-racingcar/pull/1519/commits/3a84a8fa2cc05059ab6ee4a41bf63fc5e17d3991) SimpleCar 클래스는 location까지 받느라 시그니처가 달라져서 잘 반영했으나,
SimpleCars는 JVM 기준으로 List 와 List 가 같은 시그니처로 판단되어 컴파일이 실패하므로
부득이하게 팩토리 함수 선언이 필요했습니다.

아 그렇네요 제가 깃헙에서 바로 코드를 작성해서 컴파일 에러가 날거라고 생각지 못하고 작성했네요.  
팩토리 함수 선언 좋은것 같습니다 👍 

---

>SimpleCar의 location을 입력받는 운영에 쓰이지 않는 코드조각 이 기존에 쓰이던 생성자와 같은 라인에 끼워넣어졌으니,
정확히는 운영코드에서 사용되지 않는 코드는 있지만 그게 온전한 한줄을 이루지 않을 뿐이지 않나요?
SimpleCars 역시 운영에서 사용되지 않을 형태로 주 생성자를 정의한건 마찬가지인듯 합니다.

오! 네네 코멘트 달아주신 부분도 맞다고 생각하고 공감합니다! 👍 

조금 더 제 의견을 말하자면 `코틀린은 주생성자에서 프로퍼티 노출이 가능합니다.` 이 부분이 큰 강점이라고 생각을 하고있습니다.  

코틀린 클래스를 파악할때 가장 처음에 알 수 있는 정보는   
클래스의 시그니쳐인 클래스의 이름과 주 생성자 부분이라고 봅니다.

그런데 코틀린은 앞서 말했듯이 생성자에 주입받을 수 있는 값을 외부로 노출하는 프로퍼티로 사용할 수 있기 때문에  
기존 생성자에 주입받은 값을 init절에서 가공하는 과정을 통해 외부에 노출할 프로퍼티로 변환하는 과정과 비교했을 때  
보다 클래스를 파악하기 쉽다라고 생각하여 이전에 말씀 드린 방향을 추천드렸습니다.

여기서 파악하기 쉽다라는 것은 특정 클래스가 어떤 역할과 책임이 있는지를 파악할 때 좋다는 것을 의미하였습니다.  
생성을 어떻게 하는지 보다 어떤 책임을 가지고 있는지가 더 중요하다고 생각하기 때문입니다.

즉, 운영에서 직접적으로 사용되지 않는 코드일수 있으나 클래스가 노출하고자 하는값을 시그니쳐에 표현하는것 만으로도 큰 의미가 있다고 생각하여 추천드렸습니다. 거기에 더해 앞 코멘트에서 말씀드렸던 테스트를 쉽게 할 수 있는 장점도 얻을 수 있을것 같습니다.

물론 모든 상황에서 제가 말씀드린 것이 유리한 것은 아니니 상황에 따라서는 구현해주신 방법이 더 좋을때도 있다고 생각합니다.

2023-11-11 18:31 UTC, pci2676 commented on src/main/kotlin/race/domain/SimpleCars.kt
> +    }
>moveAll은 보유한 모든 SImpleCar 인스턴스들의 move("주사위값") 를 호출하는 메서드인데,
그 주사위값을 외부에서 주입받는다는게 어떤 뜻인지 모르겠습니다.
모든 차를 전진시키거나 모든차를 정지시키려는게 아니면 1번은 현재 상황에 맞지 않는 구조 아닐까요?
다른 뜻으로 말씀하신 거라면 추가 설명 부탁드립니다

아 이 부분은 제가 코드를 잘못 이해했네요. 죄송합니다.. 😢 

2번의 경우로 말씀드린 의존성 역전을 사용하는것이 가장 좋을것 같습니다.

지금 구조에서 의존성 역전을 하면 아래와 같은 구조이지 않을까 싶습니다.
```kotlin
interface NumberGenerator {
    fun generate(): Int
}

class RandomNumberGenerator : NumberGenerator {
    override fun generate(): Int {
        return (0..9).random()
    }
}

//// SimpleCars.kt
    fun moveAll(numberGenerator: NumberGenerator) {
        carList.forEach { it.move(numberGenerator.generate()) }
    }
```
이렇게 변경하면 테스트 코드에서 NumberGenerator를 구현한 테스트용 객체를 주입하여 테스트할 수 있을것 같습니다.

>또한, random값을 생성하는 부분을 interface로 뺀다고 해도.. moveAll 을 테스트 하려면 여전히 mocking 하는것 외에 방법이 없지 않나요? random() 을 mocking 하는데서 직접 구현한 메서드를 mocking하는걸로 바뀔 뿐이지 않냐는 의문입니다.

이 부분에서 우려하시는게 테스트용 객체를 넣어도 그게 mock이랑 뭐가다른가? 라는 부분이실까요?  
만약 맞다면 구현 세부사항에 의존하지 않는다는 차이점이 있습니다.

mock 라이브러리를 이용하면 `random()`이라는 메서드 자체를 조작해야합니다. 이 `random()`은 구현 세부사항으로 **어떻게 숫자를 생성하는가**에 초점이 맞추어져 있습니다.

interface를 이용하여 테스트용 객체를 만든다면 구현세부사항에 의존하지 않아 실제 코드의 구현방법, 지금의 경우 `random()`을 이용한 숫자를 생성하는 방식이 바뀌어도 영향을 받지 않습니다.  

그러나 mock 라이브러리를 사용했다면 구현 세부사항이 테스트 코드에 노출되었기 때문에(=의존했기 때문에) 테스트 코드는 영향을 받게됩니다. 

>SimpleCars는 일급 객체로서 List 를 wrapping 할 뿐이라 해당 개념이 적용될 부분이 맞나 싶습니다.

이 부분은 의존성이 역전된 객체를 SimpleCars가 멤버변수로 들게 있게 되는 상황을 생각하시고 말씀해주신것일까요??  
만약 맞다면 위에 코드를 작성한것처럼 파라미터로 전달하는것을 생각하고 말씀드린것이었습니다 😄

2023-11-11 18:34 UTC, pci2676 requested changes
의견을 많이 나누었고 지금 상태로도 이번 미션의 요구사항은 모두 잘 지킨것 같습니다. 👍 

질문해주신 부분에 대하여 답변을 남겨두었습니다.

한번 더 개선하고 싶으시다면 개선후 리뷰요청을 하시면 되고

이번 미션을 여기서 마무리 짓고 싶으시다면 DM으로 말씀주신후 한번 더 리뷰요청해주시면 머지하도록 하겠습니다. 😄

2023-11-12 03:21 UTC, Yunho-Park commented on src/main/kotlin/race/domain/SimpleCars.kt
> +    }
답변 감사드립니다 ㅎㅎ
마지막으로 [1cd5b4a](https://github.com/next-step/kotlin-racingcar/pull/1519/commits/1cd5b4a53843cffa02bd3da316623e221a16f1ac) 에서 반영해봤습니다

2023-11-12 08:21 UTC, pci2676 approved these changes
그간 자동차 미션 하시느라 정말 고생 많으셨습니다. 👍 

머지하겠습니다.

2023-11-12 08:21 UTC, merged