Step5 자동차 경주(리팩터링)
next-step/kotlin-racingcar pull request #1548
Opened 2023-11-11 14:03 UTC by JiwonKwon

안녕하세요 경록님~! 드디어 마지막 step5 PR입니당!
그동안 리뷰로 정말x100 많이 배울 수 있었습니당. 🐥
이번 PR내용은 아래와 같습니당!
- [지난번에 리뷰해주신 내용 반영](https://github.com/next-step/kotlin-racingcar/pull/1545) & mvc 패턴으로 분리 

마지막까지 잘 부탁드립니다! ☺️🫡

2023-11-12 09:37 UTC, Rok93 requested changes
지원 5단계 미션도 빠르게 구현 잘 해주셨네요 👍💯
MVC 패턴에 맞춰서 잘 분리해주셔서 여기에 관련된 코멘트는 따로 드릴부분이 없었고
그외 몇몇 짚고 넘어가면 좋을 부분이 있어서 코멘트 남겨두었습니다. 
확인해서 반영해주세요. 🙏

이제 정말 마지막인 것 같네요. 😃
마지막까지 화이팅입니다. 💪💪

2023-11-12 09:37 UTC, Rok93 commented on src/main/kotlin/racing/controller/RacingCarController.kt
> +    private val racingCarService = RacingCarService()
주생성자를 통해서 프로퍼티를 주입받을 수 있도록하면 (지금은 테스트하고있지 않지만)  테스트하기가 더 쉬울 것 같아요. 🤗

```suggestion
class RacingCarController(private val racingCarService = RacingCarService()) {
```

2023-11-12 09:37 UTC, Rok93 commented on src/main/kotlin/racing/domain/Car.kt
> +    }
메서드 파라미터에 어떤 position이 들어오냐에 따라서 true가 나오더라도 우승자가 아닐 수도 있을 것 같아요.
메서드와 메서드 파라미터 네이밍 둘 다, 변경되어야할 것 같아요. 👀

이 메서드에대한 테스트 코드를 작성해보시면 좋을 것 같습니다. 🙏

2023-11-12 09:37 UTC, Rok93 commented on src/main/kotlin/racing/service/RacingCarService.kt
> +    }
이 정도의 간단한 기능이라면 Service 메서드로 뽑는 것 보다는 그냥 Controller의 private 메서드로 둬도 충분할 것 같아요. 😃

2023-11-12 09:37 UTC, Rok93 commented on src/main/kotlin/racing/view/ResultView.kt
> +        val winners = cars.filter { it.isWinner(winnerPosition) }
이 두메서드는 우승자를 선별하는 로직이라고 느껴지는데, 이 부분은 `도메인 로직`(= model 영역)이라고 느껴지는데, 지금은 View의 영역에 있네요. 🤔

도메인 객체가 우승자를 선별하면, 그 결과를 view에서 메서드 파라미터로 주입받아서 노출하도록 변경해보면 어떨까요? 🤗

2023-11-12 09:37 UTC, Rok93 commented on src/test/kotlin/racing/domain/RacingTest.kt
> +        val cars = CarNameMapper.map(names)
테스트를 작성하실 때는 테스트하려는 대상 메서드를 제외한 다른 메서드를 테스트 케이스 내에서 사용하지 않는 것이 좋다고 생각해요. 😃
만약 CarNameMapper의 map 메서드의 기능이 바뀐다면 이 테스트 케이스도 꺠질 수 있을 것 같아요. 🤔

2023-11-16 09:44 UTC, JiwonKwon commented on src/main/kotlin/racing/service/RacingCarService.kt
> +    }
경록님 요거 private 메소드로 빼려보니 그렇게하면 컨트롤러 테스트가 어려워 지더라구요 ㅠ.ㅠ 이런경우는 어떻게 해야할까요?

2023-11-16 09:51 UTC, JiwonKwon commented on src/test/kotlin/racing/domain/RacingTest.kt
> +        val cars = CarNameMapper.map(names)
그렇네요 ! 연관있는 car list 를 세팅하도록 하고, CarNameMapper는 제거했습니다 🙌

2023-11-16 09:53 UTC, JiwonKwon commented on src/main/kotlin/racing/view/ResultView.kt
> +        val winners = cars.filter { it.isWinner(winnerPosition) }
Winner 클래스를 만들고 로직을 이동시켰습니다 👍

2023-11-16 09:55 UTC, JiwonKwon commented on src/main/kotlin/racing/domain/Car.kt
> +    }
음 그렇네요 winnerPosition에 항상 winnerPosition이 들어온다는 보장이 없으니... 
네이밍 변경하고, 테스트 코드 추가해두었습니당!

2023-11-16 10:02 UTC, JiwonKwon commented
> 지원 5단계 미션도 빠르게 구현 잘 해주셨네요 👍💯 MVC 패턴에 맞춰서 잘 분리해주셔서 여기에 관련된 코멘트는 따로 드릴부분이 없었고 그외 몇몇 짚고 넘어가면 좋을 부분이 있어서 코멘트 남겨두었습니다. 확인해서 반영해주세요. 🙏
> 
> 이제 정말 마지막인 것 같네요. 😃 마지막까지 화이팅입니다. 💪💪

경록님 리뷰달아주신 부분 애매한것 하나 빼고 반영완료했습니당 😊 확인부탁드립니다!

2023-11-17 13:09 UTC, Rok93 commented on src/main/kotlin/racing/service/RacingCarService.kt
> +    }
저는 이런 간단한 맵핑 함수는 꼭 테스트 해야하는 대상이 아니라고 생각해서 private 메서드로 뒀어도 괜찮을거라 생각했어요. 😃

2023-11-17 13:10 UTC, Rok93 commented on src/main/kotlin/racing/service/RacingCarService.kt
> +    }
Controller 테스트 또한 사실 콘솔로 입력을 받아야하기 때문에 테스트가 불가한 대상이라고 생각했어요. 
도메인 모델에 대한 테스트만 잘 작성해주셔도 무방하다고 생각해요. 😉

2023-11-17 13:13 UTC, Rok93 approved these changes
지원님 마지막까지 피드백 반영 잘해주셨습니다 💯💯💯 
이제 자동차 경주 게임은 이만 종료할까합니다. 😉
그동안 고생 많으셨고 남은 미션들도 화이팅입니다. 💪💪💪💪

2023-11-17 13:13 UTC, merged