Step2 : 문자열계산기 구현
next-step/kotlin-racingcar pull request #1602
Opened 2024-11-13 06:21 UTC by ddoriya-dev

Step2 : 문자열계산기 구현

2024-11-13 15:33 UTC, ddaaac requested changes
안녕하세요 상준님~

계산기 구현 잘 해주셨어요!

몇 가지 코멘트 남겼으니 확인부탁드려요.

2024-11-13 15:33 UTC, ddaaac commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +}
[enum](https://kotlinlang.org/docs/enum-classes.html)을 활용해보는 건 어떨까요~?

2024-11-13 15:33 UTC, ddaaac commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +            else -> throw IllegalArgumentException("Invalid operator.")
enum을 활용한다면 [when](https://kotlinlang.org/docs/control-flow.html#when-expressions-and-statements) 절을 사용할 때도 특별한 이득을 볼 수 있습니다.

2024-11-13 15:33 UTC, ddaaac commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +        }
- depth가 깊어지고 있어요. 
- temp라는 변수명은 읽는 사람이 유추하기 어려운 변수명입니다.

[filterIndexed](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/filter-indexed.html) 등의 확장함수를 사용해서  구현해봐도 좋을 것 같아요.

2024-11-13 15:33 UTC, ddaaac commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +    }
enum을 활용한다면 이 부분도 각 Operator가 가져갈 수도 있겠네요.

2024-11-14 00:35 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +}
네 enum 을 사용할지 object 로 변수를 선언할지 고민하는 부분이 있었는데 작은 시스템으로 생각하여 해당 방법을 사용 하였는데요.
아무래도 enum 으로 가져와 해당 plus, 등 메서드를 넣어주는 방식이 더 좋아 보이네요 :)

2024-11-14 00:37 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +    }
넵 enum 방식으로 변경하도록 하겠습니다~

2024-11-14 01:29 UTC, ddoriya-dev commented
안녕하세요. 리뷰에 따라 코드 개선 진행하였습니다!
혹시 부족한 부분이 있다면 리뷰 부탁드릴꼐요~ :>

2024-11-15 00:11 UTC, ddaaac reviewed
안녕하세요 상준님

리뷰 반영 잘 해주셨습니다!

다음 단계 진행해주세요.

2024-11-15 00:11 UTC, ddaaac commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +            }
이렇게 depth가 깊어지는 부분은 어떻게 처리할 지 고민해보면 좋을 것 같아요!

- 로직을 살짝 변경해서 간소화 할 수도 있을 것 같고
- 아니라면  메서드 분리 등을 도입할 수도 있겠네요.

다음 단계부터 고민해보시면 좋을 것 같습니다.

2024-11-15 00:11 UTC, ddaaac commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +            }
만들어두신 메서드를 활용할 수 있어보입니다. `Operators.findOperator() ?: throw xxx`

2024-11-15 00:11 UTC, ddaaac commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +                result = Operators.findOperator(operator)!!.operation(result, expression.toDouble())
[not-null assertion(!!)](https://kotlinlang.org/docs/null-safety.html#not-null-assertion-operator)의 생긴 모양을 보면 그다지 사용하고 싶게 생기지는 않았습니다. 실제로 이는 코틀린 개발자들이 의도한 바에요.
필요한 경우에는 사용해야하지만 이 경우는 로직을 조금 수정하면 이를 없앨수도 있겠다는 생각이 드네요.

2024-11-15 00:11 UTC, ddaaac approved these changes

2024-11-15 00:11 UTC, merged

2024-11-15 00:46 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +            }
넵 알겠습니다~

2024-11-15 00:47 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +            }
아 그러한 방법이 더좋겠네요. 감사합니다.

2024-11-15 00:55 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +                result = Operators.findOperator(operator)!!.operation(result, expression.toDouble())
아 그렇군요. 해당값이 validate 메서드에서 되었다 판단하에 진행하긴 했는데 아무래도 없애는 방향이 더 좋을것 같아 보이네요 
감사합니다.

2024-11-15 00:59 UTC, ddoriya-dev commented on src/main/kotlin/study/calculator/StringCalculator.kt
> +            }
forEachIndexed, filterIndexed 두 부분에 대해 고민을 해보긴했는데
filterIndexed -> throw 를 두번 진행해서 간결화 및 depth를 깊어지지않게 하는 부분 나을까요? 하나의 loop로 끝내는 방향이 좋을까 고민이 되어 여쭤봅니다 ㅠ