Step2 문자열 계산기
next-step/kotlin-racingcar pull request #1612
Opened 2024-11-13 13:56 UTC by DuhanMo

문자열 계산기 리뷰요청드립니다. 🙇‍♂️

2024-11-14 13:18 UTC, Rok93 requested changes
두한님 2단계 구현 잘해주셨네요! 👍 
몇몇 코멘트 남겨두었는데, 확인해서 반영부탁드릴게요. 
미션 진행하면서 어려운 부분이있으면 언제든지 DM 주세요. 🙏🤗

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +    }
`더하기`, `빼기`, `곱하기`, `나누기`는  연산자 객체의 역할로 볼 수 있지 않을까요? 🤔

Operator 객체에게 이 역할을 위임해보면 어떨까요? 😃

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +class Calculator {
Calculator는 상태를 가지지 않기 때문에 꼭 객체를 생성할 필요가 없을 것 같네요. 👀
이런 경우에는 [object 클래스](https://kotlinlang.org/docs/object-declarations.html)로 변경해보면 어떨까요? 😃

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +        }
적절한 예외처리 👍💯

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/Player.kt
> +package calculator
클래스 파일명이 적절해 보이지 않다고 생각되는데요. 🤔
어떤 의도가 있으신건지 궁금합니다.

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/InputParser.kt
> +        val operatorRegex = "[+\\-*/]".toRegex()
이 코드를 처음보는 사람의 입장에서는 `"\\d+(\\.\\d+)?"` 혹은 `"[+\\-*/]"`가 어떤 의미를 가지는지 한눈에 이해하기가 어려울 것 같아요. 🤔 아래의 글을 참고해서 개선해보면 어떨까요? 🤗

[의미가 불분명한 매직 넘버를 상수로 선언하라.](https://javabom.tistory.com/28)

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/InputParser.kt
> +        val operatorRegex = "[+\\-*/]".toRegex()
또한 Pattern과 같이 `생성 비용이 아주 비싼 객체`의 경우 `캐싱`하여 사용해보면 어떨까요? 

[참고 글 - 이펙티브 자바 [아이템6] 불필요한 객체 생성을 피하라](https://lovethefeel.tistory.com/141)

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/InputValidator.kt
> +        if (tokens.size % 2 == 0 || tokens.last().isOperator()) {
이미 앞에서 tokens이 짝수개인지 확인했고 뒤에서 홀수번째 위치가 operator인지 검증하기 때문에
여기서 마지막 token이 `operator`인지 검증은 불필요한 것 같아요.

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/InputValidator.kt
> +    private fun String.isDouble(): Boolean = this.toDoubleOrNull() != null
확장함수 활용  💯👍 

하지만 `isOperator`의 경우에는 한가지 질문사항이 있어요! 
만약에 새로운 `operator` (ex. `^`)가 추가되게 되면 어떨까요?  

아마도 `Operator` enum class에 `^` 요소가 추가될거에요. 
그리고 이 메서드에도 `^`가 필요하게 될 것 같은데요. 

Operator의 요소가 추가됐을 때, 이 메서드에는 별도 수정없이 자연스럽게 대응이 되도록 변경해보면 어떨까요? 😃
(만약 제가 제안드린 방식처럼 변경된다면 추가적으로 이 확장함수의 위치도 Operator로 옮기면 좋을 것 같네요 😉)

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/Operator.kt
> +            entries.find { it.token == token } ?: throw IllegalArgumentException("Not found operator from token")
예외 메시지에 어떤 token이 들어왔는지도 표기되면 조금 더 예외의 원인을 파악하기가 쉽지 않을까요 ? 😉

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/Operator.kt
> +    private val token: String,
enum class 활용 👍💯

조금 마이너한 얘기지만
개인적으로 token보다는 `symbol` 같은 의미가 조금 더 적절하다고 생각하는데, 두한님은 어떻게 생각하시나요?

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/Player.kt
> +        val input = readLine()
개인적으로 nullable한 타입을 쓰는걸 좋아하지 않는데요. 😃 (null 처리에 따른 복잡성 추가.. 등등)
가급적 non-nullable한 타입이 되도록 앞단에서 만들어주면 어떨까요? 

```suggestion
        val input = readlnOrNull() ?: throw IllegalArgumentException("...")
```

1.6.0 버전 이후부터는 readLine() 대신에 [readlnOrNull() 메서드를 사용](https://lovelyunsh.tistory.com/284)해야한다고 하네요. 😃

2024-11-14 13:18 UTC, Rok93 commented on src/main/kotlin/calculator/StringCalculator.kt
> +            }
이 연산의 과정이 한눈에 이해하기가 조금 어려운듯한데요. 
체이닝 연산과 (위에서 언급했던) 매직넘버가 섞인 것이 그 원인인 듯합니다. 

이 로직을 조금 더 가독성 좋게 개선해보면 좋을 것 같아요. 😃 
이 부분은 고민을 조금해주시고 혹시라도 개선 방향을 잘 못잡으시겠다면 추가적으로 질문주시면 좋을 것 같습니다. 🙏

2024-11-14 13:25 UTC, DuhanMo commented on src/main/kotlin/calculator/Calculator.kt
> +    }
네! 처음 구상은 계산기가 계산을 해야되겠다는 의미로 계산 로직을 `Calculator`에게 위임했었는데요,

Operator라는 연산객체에게 역할을 위임하는 것이 좋을 것 같습니다🙂

2024-11-14 13:27 UTC, DuhanMo commented on src/main/kotlin/calculator/Calculator.kt
> +class Calculator {
좋은 의견 감사해요! 상태가 없는 객체는 object 클래스로 대체하는 것을 앞으로도 고려할 수 있게 되었어요 👍

2024-11-14 13:30 UTC, DuhanMo commented on src/main/kotlin/calculator/Player.kt
> +package calculator
패키지명은 단순 미션(스텝) 구분을 위해 두었어요.
merge된 작업공간에 계산기 미션과 자동차미션 구분을 위해서요!

경록님께서는 패키지 구분을 하실 때 어떤 기준을 보통 두시나요? 의견 궁금합니다💭

2024-11-14 13:32 UTC, DuhanMo commented on src/main/kotlin/calculator/InputParser.kt
> +        val operatorRegex = "[+\\-*/]".toRegex()
처음엔 변수명으로 의도를 나타내려고 했었는데요! 경록님 의견을 들어보니 충분히 한눈에 이해하기 어려울 수 있을 것 같아요,
매직넘버 상수화와 Pattern의 캐싱을 적용하도록 하겠습니다 🙇‍♂️

2024-11-14 13:35 UTC, DuhanMo commented on src/main/kotlin/calculator/InputValidator.kt
> +    private fun String.isDouble(): Boolean = this.toDoubleOrNull() != null
네 의견에 동감해요!

Operator 확장엔 열려있고 수정엔 닫혀있도록 코드 구성을 해보겠습니다🙂

2024-11-14 13:36 UTC, DuhanMo commented on src/main/kotlin/calculator/Operator.kt
> +            entries.find { it.token == token } ?: throw IllegalArgumentException("Not found operator from token")
좋은 의견 감사해요! 🙇‍♂️ 예외 메시지를 좀 더 명확히 하도록 수정할게요.

2024-11-14 13:37 UTC, DuhanMo commented on src/main/kotlin/calculator/Operator.kt
> +    private val token: String,
`symbol` 너무 적절한 것 같아요! 😁 전혀 마이너하다고 생각하지 않습니다 ..! 감사해요!

2024-11-14 13:40 UTC, DuhanMo commented on src/main/kotlin/calculator/Player.kt
> +        val input = readLine()
네! 저도 고민한 부분인데요, `InputValidator`가 input을 검증하는 로직이다보니,
검증 행위를 해당 객체에 응집도있게 뭉치려고 했어요.

물론 그러다보니 nullable한 상태가 해당 객체까지 흘러들어가는 문제?가 발생했는데,
말씀 주신것처럼 앞단에서 처리하는 것도 적절해보이네요! 수정하도록 하겠습니다 🙇‍♂️

2024-11-14 13:41 UTC, DuhanMo commented on src/main/kotlin/calculator/StringCalculator.kt
> +            }
네 해당부분 충분히 고민해보고 적용하도록 하겠습니다 좋은 의견 감사해요!👍

2024-11-14 13:42 UTC, DuhanMo commented on src/main/kotlin/calculator/InputValidator.kt
> +        if (tokens.size % 2 == 0 || tokens.last().isOperator()) {
네! 불필요한 검증은 제거하도록 하겠습니다🙇‍♂️

2024-11-14 13:51 UTC, Rok93 commented on src/main/kotlin/calculator/Player.kt
> +package calculator
@DuhanMo 님 조금 오해가있었는데 패키지명이 아니라 파일명을 이야기하는거였어요!

2024-11-14 13:57 UTC, DuhanMo commented on src/main/kotlin/calculator/Player.kt
> +package calculator
네, 제가 의도를 잘못파악했네요🥲

계산 문자열을 입력하는 객체가 `계산을 실행한다`라는 의미를 부여해 `Player`라고 네이밍했습니다.
Input을 받는 객체에 대한 이름이 너무 비약적이라고 문득 생각이 드네요.. 

파일명도 충분히 고려 후에 수정진행하겠습니다 🙇‍♂️

2024-11-14 15:31 UTC, DuhanMo commented
@Rok93 경록님! 꼼꼼한 리뷰 감사드려요🙏
말씀주신 사항들에 대해 반영해보았어요 🙂
반영한 사항은 아래와 같아요!
- 실제 연산역할을 연산자 객체에게 위임
- `Calculator`객체를 `object`로 변환
- Input 객체 파일명 고려
- 정규표현식의 상수화
- Pattern 비용고려 후 캐싱
- input 검증시 불필요한 검증 로직 제거
- OCP 원칙을 고려한 연산자 여부 메서드 수정
- 연산자 적절한 예외 메시지 처리
- 연산자 객체의 변수명 수정
- nullable 빠르게 예외 처리
- readLine() -> readlnOrNull() 수정
- 결과 계산 로직 가독성 증대

추가로 개인적으로 반영한 사항은 아래와 같아요.
- 정규표현식을 통해 패턴을 찾을 때 연산자가 추가될수있음을 고려해 동적 패턴 생성

그리고 고민사항도 아래 조금 적겠습니다🥹 대체로 경록님의 의견이 궁금한 사항들이에요!
**고민사항**
고민사항

1. `연산자 여부 확인 확장함수(String.isOperator())`를 최상위함수로 뺄지, 동반객체에 넣을지 고민하다 동반객체가 더 의미있어보여서 동반객체로 구현했어요. 경록님은 확장함수를 보통 어떻게 처리시키는지 궁금해요.

2. `runCatching.getOrElse` 와 `try catch`중 선호하는 방식이 있으신지, 아니면 상황에 맞게 다르게 쓰시는지 궁금해요.

3. `companion object` 클래스 최하단에 두는것이 컨벤션이라고 들었는데 경록님은 동반객체를 코드의 어디에 위치시키는편이신지 궁금해요 ([[kotlin coding-convetion](https://kotlinlang.org/docs/coding-conventions.html#modifiers-order)](https://kotlinlang.org/docs/coding-conventions.html#modifiers-order))

그럼 추가 의견 기다리고있겠습니다! 😊

2024-11-16 09:44 UTC, Rok93 approved these changes
두한님 피드백 반영 잘해주셨네요. 👍👍 
이제 본격적으로 자동차 경주 미션으로 넘어가볼까요? 🤗🚀

추가적으로 질문에 대한 답변과 추가 코멘트 남겨두었는데, 확인해서 다음 단계 진행하면서 같이 확인 부탁드릴게요. 😉

2024-11-16 09:44 UTC, Rok93 commented on src/main/kotlin/calculator/Operator.kt
> +        ): Double = a + b
이제 새로운 연산자가 추가되면 `Operator`만 수정하면 되겠군요!? 😃 💯

kotlin에서 제공하는 [SAM](https://kotlinlang.org/docs/fun-interfaces.html)를 활용한다면
이 부분을 조금 더 개선해볼 수 있을 것 같아요!

2024-11-16 09:44 UTC, Rok93 commented on src/main/kotlin/calculator/Operator.kt
> +        fun String.isOperator(): Boolean = entries.map { it.symbol }.contains(this)
> 질문1) 연산자 여부 확인 확장함수(String.isOperator())를 최상위함수로 뺄지, 동반객체에 넣을지 고민하다 동반객체가 더 의미있어보여서 동반객체로 구현했어요. 경록님은 확장함수를 보통 어떻게 처리시키는지 궁금해요.

선호도의 차이로 보이는데, 저는 확장함수는 최상위 함수에 두는 것을 조금 더 선호하는 것 같아요. 😃 
확장함수를 동반객체에 뒀던 경우를 거의 없었던 것 같아요. 🤔

이와는 별개로 kotlin의 `확장함수`는 정말 강력한 기능이라고 생각해요. 
그래서 저는 왠만하면 확장함수를 제한적으로 쓰려고하는 편인데요. 
아무래도 확장함수를 무분별하게만들어두게되면 추후 협업하는 다른 개발자는 이 함수를 언어단에서 제공하는 함수라고 생각해서 잘 못 사용할 위험성이 생기게 될 수 있다고 생각해요. 😃 

애초에 common하게 쓸 용도의 함수가 아니라면 private 확장함수를 만들어서 필요한 곳에서만 쓰고, 
추후 이런 확장함수의 필요성이 다른 곳에서도 필요하게된다면 public으로 접근제한자를 열어줄지 말지(이 확장함수를 어디에 둘지도 같이)를 고민하는 편이에요. 

![image](https://github.com/user-attachments/assets/a89657ab-c340-452d-8a12-5094e7b717ca)

2024-11-16 09:44 UTC, Rok93 commented on src/main/kotlin/calculator/Calculator.kt
> +}
Operator 객체에게 연산하는 역할을 위임했으니 이제 Calculator는 불필요하지 않을까요? 🤔

Calculator.calculate 를 호출하는 위치에서  바로 `operator.operate(a, b)`를 바로 호출해도 될 것 같아서요!

2024-11-16 09:44 UTC, Rok93 commented on src/main/kotlin/calculator/InputParser.kt
> +        private val operatorRegex =
(`const` 키워드를 쓸 수는 없겠지만... ) 이 둘의 경우에도 사실상 상수로 볼 수 있지 않을까요?
상수 네이밍 규칙을 동일하게 적용시켜주면 어떨까 싶어요.

2024-11-16 09:44 UTC, Rok93 commented on src/main/kotlin/calculator/InputValidator.kt
> +        }
kotlin에서 제공하는 [require 함수](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require.html)를 활용해볼 수 있을 것 같아요.  😃
```suggestion
        require(input.isNotBlank()) { "The input cannot be null or blank" }
```

2024-11-16 09:44 UTC, Rok93 commented on src/main/kotlin/calculator/Input.kt
> +        runCatching {
> (질문2) runCatching.getOrElse 와 try catch중 선호하는 방식이 있으신지, 아니면 상황에 맞게 다르게 쓰시는지 궁금해요. 

선택의 이유가있는 것은 아닌데 저는 회사에서 Java 프로젝트와 Kotlin 프로젝트를 둘 다 관리하고있는데, 
아마 백엔드의 기준에서는 `try catch`로 예외를 처리하는 방식이 전통적(?)인 방식이다보니 runCatching하여 `Result` 응답을 받아 후처리하는 방식이 조금 낯설어서 적용하지 않은 것 같아요. 🤔  

현재 유지보수하고있는 프로젝트에서도 `runCatching` 사용하는 로직이 있는지 확인해봤는데, 없네요. 😅

2024-11-16 09:44 UTC, Rok93 commented on src/main/kotlin/calculator/InputParser.kt
> +    companion object {
> (질문3) companion object 클래스 최하단에 두는것이 컨벤션이라고 들었는데 경록님은 동반객체를 코드의 어디에 위치시키는편이신지 궁금해요 ([kotlin coding-convetion](https://kotlinlang.org/docs/coding-conventions.html#modifiers-order))

사실 코틀린 공식 컨벤션이 뭐라하든, 팀 컨벤션이 우선이라고 생각해요. 😃 
팀 컨벤션이 당연 1순위이라고 생각하고, 제 개인적인 선호도는 저도 Kotlin 코드 컨벤션 가이드를 따르는걸 좋아하는 편입니다.

2024-11-16 09:44 UTC, Rok93 commented on src/main/kotlin/calculator/StringCalculator.kt
> +        return if (result.isInteger()) result.toInt().toString() else result.toString()
결과를 꼭 문자열로 반환할 필요는 없을 것 같아요. 🤔

이와는 별개로 `toString()`의 경우 아래와 같이 if else 식의 결과에 한 번만 적용해줘도 동일하게 적용될 것 같아요. 🤔

```kotlin
    return if (result.isInteger()) {
            result.toInt()
        } else {
            result
        }.toString()
```

2024-11-16 09:44 UTC, Rok93 commented on src/main/kotlin/calculator/StringCalculator.kt
> +    private fun Double.isInteger(): Boolean = this % 1.0 == 0.0
(수정해달라는 이야기는 아니에요!)

지금 같은 확장함수의 경우 범용적으로 쓸 수 있어보여서 이런 경우에는 public 확장함수로 둬도 괜찮아보이네요. 😃

2024-11-16 09:44 UTC, merged