2단계, 문자열 계산기
next-step/kotlin-racingcar pull request #1621
Opened 2024-11-13 16:44 UTC by Minsu-Lee

안녕하세요
미숙하지만 열심히 만들어 보았습니다.
문자열 계산기 과제 PR 요청드립니다. 
잘부탁드립니다 🙏🏻

2024-11-14 07:37 UTC, vsh123 requested changes
안녕하세요 :) 

문자열 계산기 빠르게 작성해주셨네요!! 👍 

몇가지 코멘트를 남겼으니 확인 부탁드립니다!

2024-11-14 07:37 UTC, vsh123 commented on src/test/kotlin/study/StringTest.kt
> +    fun `연산자 체크`() {
[Guide to JUnit 5 Parameterized Tests](https://www.baeldung.com/parameterized-tests-junit-5)를 적용하기 좋은 예시인 것 같아요! 한번 적용해보시면 어떨까요?

2024-11-14 07:37 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +package study.calculator
해당 파일의 위치가 test 디렉토리 하위에 있는 것 같아요.

production코드는 main 하위로 옮겨주면 어떨까요?

2024-11-14 07:37 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +interface Calculator {
Calculator를 인터페이스화 시켰을때의 장점이 무엇일까요?


sealed interface에 대해 알아보고 적용이 가능할지 검토해보면 어떨까요?
* https://kotlinlang.org/docs/sealed-classes.html

2024-11-14 07:37 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +            return CalculatorImpl()
특정 인스턴스를 만들어주는 팩터리 메서드가 인터페이스에 위치하는게 괜찮을까요? 🤔

2024-11-14 07:37 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +private class CalculatorImpl : Calculator {
object class에 대해 알아보고 적용을 고려해보면 어떨까요?

* https://kotlinlang.org/docs/object-declarations.html

참고로 1.9.0부터 data object라는 것도 정식 릴리즈되었답니다!

* https://kotlinlang.org/docs/object-declarations.html#data-objects

2024-11-14 07:37 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +        return rawInput.getResultIntOrZero(true)
input이 nullable하기때문에 계속해서 `?.` 연산이 이루어지는 것 같아요!

null검증 및 처리를 먼저해주면 어떨까요?

2024-11-14 07:37 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +    private val rawInput: OperationInput by lazy {
지연 초기화 👍

2024-11-14 07:37 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +        rawInput.initialize()
calculate호출시마다 rawInput프로퍼티를 초기화시켜주고 있는데요!

혹시 rawInput을 calculate함수내의 지역변수로 설정하지 않으신 이유가 있을까요?

2024-11-14 07:37 UTC, vsh123 commented on src/test/kotlin/study/calculator/Operator.kt
> +                '+' -> PLUS
'+' 라는 매직넘버를 없앨 수 없을까요?

`PLUS.char`를 활용해볼 수 있을 것 같아요!

https://tecoble.techcourse.co.kr/post/2020-05-07-avoid-hard-coding/

2024-11-14 07:37 UTC, vsh123 commented on src/test/kotlin/study/calculator/Operator.kt
> +    DEFAULT(null),
default를 없앨수는 없을까요??

2024-11-14 13:14 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +package study.calculator
인지 못하고 있었습니다.
경로 변경하였습니다. 확인 감사합니다

2024-11-14 13:15 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +interface Calculator {
@vsh123 
초기 개발 로직의 의도를 완벽히 이해되지 않은 상태에서 제3자가 클래스를 상속받아 원하는 일부 기능을 재정의하여 사용하게 된다면, 초기 개발한 의도 이외에 클래스의 잘못된 사용 가능성이 생기지 않을까요?

외부에서는 구현체에 대해서 직접 참조하지 않고, 인터페이스로 간접 참조 함으로써, 구현한 로직에 대한 안정성을 높일 수 있는 방법이라 생각하였습니다.

sealed interface 는 제안주신 의도가 어떤 건지 알 수 있을까요?
sealed interface 는 상태 표현이나, 결과 처리 등 상태 및 이벤트 관리에 사용 되는거라 이해하고 사용하고 있습니다.
현재 구현한 로직의 개발 의도에서는 sealed interface 도입의 필요성을 찾지 못하였습니다. 😢

2024-11-14 13:16 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +            return CalculatorImpl()
@vsh123 
저도 일반적인 방법은 방법은 아니라 생각됩니다 😅
[위에 해당 질문에 남긴 답변 내용](https://github.com/next-step/kotlin-racingcar/pull/1621#discussion_r1842203053) 처럼, 객체를 직접 참조하지 않게 인터페이스화 한 의도에 덫붙여 외부에서 온전히 구현체에 대해서 모르게 하는것도 괜찮은 캡슐화 방법이 아닐까 생각하였습니다.

해당 부분은 별도의 팩토리 클래스를 생성해도 되지만 객체를 생성 하는 로직이 간략하기도 하고 별도의 팩토리 클래스로 분리하는게 부담스러워서 interface 내 compainon object 에 객체 생성 메서드를 위치하게 되었습니다.

인터페이스 내, 팩토리 메서드를 위치하면 안되는 사유나 조심해야될점이 있을까요?

2024-11-14 13:17 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +private class CalculatorImpl : Calculator {
@vsh123 
object는 내부에서 객체를 singletone으로 관리하기 때문에 제가 생각한 개발 의도에서 벗어나는 제안 같습니다. 😅
CalculatorImpl 는 calculate 에서 계산 수행이 끝날때 까지 `rawInput` 전역변수에 상태값을 저장하면서 수행됩니다.

object로 선언하여 여러 비동기 로직들에서 CalculatorImpl 객체를 참조하여 계산 로직이 수행 된다면,
계산중에 다른 요청에 의해 rawInput에 할당된 입력값들이 초기화 되거나 섞이는 상황이 발생되어
의도한 결과대로 정상적으로 수행되지 않을것 같습니다. 🥲

2024-11-14 13:17 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +        return rawInput.getResultIntOrZero(true)
@vsh123 
좋은 방법 같습니다.
말씀해주신 방향으로 수정해 보았습니다.
감사합니다.

2024-11-14 13:17 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +    private val rawInput: OperationInput by lazy {
👍

2024-11-14 13:17 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +        rawInput.initialize()
@vsh123 
Calculator 를 재사용하게 될때마다 `rawInput` 객체를 매번 생성함으로써 불필요한 메모리 상주를 야기시키는게 아닌가 생각되어서
재사용과 불필요한 메모리 상주를 고려하여 전역변수로 선언해두고 계산이 수행될때 마다 초기화하여 사용하게 구성해보았습니다.

2024-11-14 13:17 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Operator.kt
> +                '+' -> PLUS
@vsh123 
enum 내, char 를 이용하는 방법 괜찮은것 같습니다. 👍 
수정하였습니다. 감사합니다.

2024-11-14 13:18 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Operator.kt
> +    DEFAULT(null),
@vsh123 
calculate 메서드 내에서 `trimmedInput` 를 최소한으로 순회하면서 계산을 진행하게 구상하였습니다.
아래 구조에서 중간중간 계산을 진행하기 이전 검증을 진행하게 되는데,
- operator를 만날때까지 input1 를 입력 받다가
- **operator**를 만다면 input2 를 입력하고,
- 또 다시 operator를 만나게 되면 rawInput에 operator를 저장 → **isReadyToCalculate**
- 계산을 수행하기 전 **검증을 진행**하고 → 검증 수행 위치
- 계산 이후 결과값을 input1에 담으며 반복하는 구조

현재 잘못된 연산식이 들어온 경우를 rawInput.append 내에서 감지하여 DEFAULT로 담고 있습니다.
```kotlin
override fun append(input: Char) {
    when {
        !input.isDigit() -> _operator = Operator.toOperator(input) // <- 잘못된 연산식 판별 및 저장
        _operator == null && _secondInput.isNullOrEmpty() -> _firstInput = (_firstInput ?: "") + input
        _operator != null -> _secondInput = (_secondInput ?: "") + input
    }
}
```

DEFAULT를 없애고자 한다면 OperatorInputImpl 내 잘못 연산된 operator를 담을 변수를 추가 해야되고
ensureValidCalculation 내, 사칙연산 기호가 아닌경우를 체크할때, _operator 대신 잘못 연산된 operator를 담을 변수로 가르키면  가능은 할것 같습니다.

이미 생성되어 있는 객체에 저장함으로써, 불필요한 변수선언을 줄이고 연산자는 한곳에 담김으로써 오히려 가독성이 높아질거라 생각했는데, 어떻게 생각하시나요?

2024-11-14 13:51 UTC, Minsu-Lee commented on src/test/kotlin/study/StringTest.kt
> +    fun `연산자 체크`() {
@vsh123 
좋은 정보 감사합니다.
그러나 지금 테스트한게 맞는건지, 어떤식으로 테스트를 진행해야될지 감이 안오네요 😅

2024-11-14 15:53 UTC, Minsu-Lee commented
@vsh123 
회사에서 답변 남기고 수정한내용들
집에와서 다시 검토하려고 했는데, 수정한 내용들이 안가져와져서
이것저것 시도하다가 pr이 close 된거 같습니다.

pr을 다시 올려야되는 상황인걸까요...?

2024-11-15 03:07 UTC, vsh123 commented
@Minsu-Lee 님 넵 그대로 진행해주시면 됩니다 :)

2024-11-15 08:49 UTC, vsh123 requested changes
안녕하세요! 빠른 피드백 반영해주셨군요! 💯

몇가지 추가 코멘트를 남겼으니 확인부탁드립니다!!

2024-11-15 08:49 UTC, vsh123 commented on src/test/kotlin/study/StringTest.kt
> +class StringTest {
해당 테스트도 production 코드의 패키지와 클래스파일에 맞게 수정 및 분리할 수 있을 것 으로 보여요~~!! CalculatorTest, OperatorTest등으로 분리해보면 어떨까요?

2024-11-15 08:49 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +interface Calculator {
> 초기 개발 로직의 의도를 완벽히 이해되지 않은 상태에서 제3자가 클래스를 상속받아 원하는 일부 기능을 재정의하여 사용하게 된다면, 초기 개발한 의도 이외에 클래스의 잘못된 사용 가능성이 생기지 않을까요?

이런 목적이라면 더욱 더 sealed class 혹은 interface를 사용해야한다고 생각을 합니다.

첨부드린 문서의 첫문단을 보시면

> No other subclasses may appear outside the module and package within which the sealed class is defined

이라고 적혀져있는데요! Sealed class(interface) 의 가장 큰 목적은 자기 자신을 다른 패키지 혹은 모듈에서 상속받아 구현하지 못하도록 막는데 있다고 생각합니다!

2024-11-15 08:49 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +            return CalculatorImpl()
말씀주신 내용은 DIP라는 관점으로 좋은 설계라고 볼 수 생각합니다.

다만 저는 인터페이스에 인스턴스를 생성하는 메서드가 있다는게 좀 어색한 것 같아요. 인터페이스는 구현체를 몰라야한다고 생각합니다.

오히려 이경우는 별도 팩토리 클래스가 존재하는게 더 좋지 않을까 생각해서 코멘트를 남겼어요!

2024-11-15 08:49 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +private class CalculatorImpl : Calculator {
아하 멀티 스레드 환경을 고려하셨군요 👍  이부분은 rawInput을 지역변수로 가지고 있는 아래부분에서 코멘트 드리도록 하겠습니다.

2024-11-15 08:49 UTC, vsh123 commented on src/test/kotlin/study/calculator/Calculator.kt
> +        rawInput.initialize()
CalculateImpl 인스턴스의 프로퍼티로 존재하는 rawInput과 지역변수로 존재하는 rawInput을 생각해봤을 때 
성능 측면에서는 인스턴스 생성에 대한 비용을 줄이기 때문에 지금 방식이 더 좋을 수 있다고 생각합니다.
하지만 메모리 효율성 측면에서는 지역변수로 존재하는게 더 효율적이라고 생각하는데요.

지금구조에서 rawInput은 `CalculateImpl 생성 후 calculate 호출(지연초기화) ~ CalculateImpl 인스턴스 종료 ` 시점까지 메모리를 점유하고 있지만

지역변수로사용한다면 `calculate 호출 ~ calculate 종료` 시점까지만 메모리를 점유하고 있지 않을 것 같아요

2024-11-15 08:49 UTC, vsh123 commented on src/test/kotlin/study/calculator/Operator.kt
> +    DEFAULT(null),
`Operator.toOperator` 내부에서 잘못된 연산기호라면 에러를 던진다면, 에러발견시점을 더 앞당길 수 있지 않을까요?
그렇게하면 DEFAULT도 없앨 수 있을 것 같아요~

2024-11-15 08:49 UTC, vsh123 commented on src/main/kotlin/step2/calculator/OperationInput.kt
> +    override fun getResult(isInvalid: Boolean): String {
isInvalid가 테스트 외에는 모두 true인 것 같은데요~!
해당 필드가 정말 필요한 필드일까요??

특정 validation을 skip하고 하는 테스트가 괜찮은 테스트일지 생각해보면 좋을 것 같습니다.

2024-11-15 08:49 UTC, vsh123 commented on src/main/kotlin/step2/calculator/OperationInput.kt
> +        val arg1 = _firstInput!!.toInt()
append없이 getResult만 호출된다면 !! 부분에서 NPE가 발생하지 않을까요? 코틀린의 장점을 살려서 null safe한 코드로 작성을 해보면 어떨까요?

2024-11-15 08:49 UTC, vsh123 commented on src/main/kotlin/step2/calculator/OperationInput.kt
> +                else -> arg1.div(arg2)
해당 when절도 DEFAULT가 없다면 else대신 Operator.DIV로 표시될 수 있을 것 같아요!

2024-11-15 14:08 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +            return CalculatorImpl()
@vsh123 
실제 현업에서는 이렇게 안하지만 
이것저것 해보고싶은게 많아서 시도해봤습니다.
의견 감사합니다 ㅎㅎ

2024-11-15 14:13 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +            return CalculatorImpl()
@vsh123 
이 부분은 팩토리 클래스를 별도로 분리하도록 하겠습니다

2024-11-15 14:16 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +private class CalculatorImpl : Calculator {
확인 감사합니다~

2024-11-15 14:19 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +        rawInput.initialize()
@vsh123 
말씀하신것처럼 전역변수로 재사용 하는게 오히려 **더 오랜기간동안 메모리를 점유**하고 있어서 
제가 답변드린 내용이 모순이 됬네요
이해하기 쉽게 풀어주셔서 감사합니다 👍 
rawInput은 지역변수로 옮기는게 맞을것 같습니다.
수정하겠습니다~

2024-11-15 14:41 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Operator.kt
> +    DEFAULT(null),
@vsh123 
그것도 좋은 방법이네요 👍 
하지만 예외를 발생시키는 로직이 한곳에 모이지 않게 되서 아쉬움이 생기네요.
다음에는 mvc 같은 구조로 시도해봐야겠습니다.

ensureValidCalculation 메서드 내에서 사칙연산을 체크하고 throw 하는 부분만 메서드로 추출했고,
append 에서 operator를 담기 전에 체크하도록 수정해보았습니다.
append는 숫자가 아닌경우 공백도 들어올 수 있어서 사칙연산을 체크하는 추출 메서드의 인자로 ignoreWhitespace 상태값을 전달받아 공백을 스킵하게 수정해 보았습니다.

2024-11-15 14:59 UTC, Minsu-Lee commented on src/test/kotlin/study/StringTest.kt
> +class StringTest {
좋은 의견같습니다.
구현체별로 나눠보았습니다.
- CalculatorTest
- OperatorTest
- OperatorInputTest

2024-11-15 15:05 UTC, Minsu-Lee commented on src/main/kotlin/step2/calculator/OperationInput.kt
> +    override fun getResult(isInvalid: Boolean): String {
isInvalid는 테스트를 위해서 사용된게 아니라
getResult에서 input이 null인 경우, 검증없이 getResultIntOrZero를 호출하기 위함이였습니다.

지금와서 다시 생각해보니 null인경우, 0을 바로 리턴하고
isInvalid 는 제거해도 괜찮을것 같습니다.

그런데 filechaged에서 확인해보니 코드가 최신으로 반영되지 않은것 같습니다. 🤔

2024-11-15 15:47 UTC, Minsu-Lee commented on src/main/kotlin/step2/calculator/OperationInput.kt
> +        val arg1 = _firstInput!!.toInt()
OperationInput 객체를 직접 사용할 수 있으니 말씀하시는 것처럼 NPE를 대비해야할것 같습니다.
확인감사합니다.
_firstInput?.toIntOrNull() ?: 0 으로 대체하였고
0으로 나누는 계산요청이 있을것 같아 ensureSafeDivision 추가하였습니다.

2024-11-15 16:06 UTC, Minsu-Lee commented on src/main/kotlin/step2/calculator/OperationInput.kt
> +                else -> arg1.div(arg2)
Operator.toOperator else 에서 사칙연산 throw를 반환하게 수정하여 DEFAULT를 제거하였습니다. 😅

2024-11-15 16:22 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Calculator.kt
> +interface Calculator {
말씀하신 내용 납득 했습니다.
허나 실제 적용은 어떻게 해야할지 생각이 안나서
이부분은 gpt의 도움을 받아서 적용해보았습니다.
수정된이 맞게 수정되었는지 확인부탁드립니다 😅

2024-11-16 05:24 UTC, vsh123 commented on src/test/kotlin/study/calculator/Operator.kt
> +    DEFAULT(null),
예외를 한곳에 모아둔다는 것에 대해 공감하지만, 지금 케이스는 예외를 책임지는 객체가 다른 것 같아요!!

만약 Operator를 활용하는 다른 Calculator가 존재한다면 해당 Calculator가 없는 연산자에 대한 에러를 처리하게 해줘야하는데, 그런 방식보다는 Operator가 존재하지 않는 연산자에 대한 검증 및 에러를 발생시키는게 더 좋은 방식이라고 생각합니다!

2024-11-16 05:35 UTC, vsh123 approved these changes
안녕하세요!!
피드백 반영 잘해주셨네요 💯 

이번 미션은 여기서 머지하도록 하겠습니다! 다음 미션에서 뵐게요!! :)

2024-11-16 15:56 UTC, Minsu-Lee commented on src/test/kotlin/study/calculator/Operator.kt
> +    DEFAULT(null),
그렇네요, 예외를 책임지는 객체가 다른점에서 납득 되었습니다.
이번 과제를 진행하면서 초기 구조 설계에 대한 부족함 때문에 이러한 아쉬움들이 생겨난게 아닌가 생각하게 되었습니다.
좋은 피드백 감사합니다. 👍

2024-11-17 05:17 UTC, merged