[Step2] 문자열 계산기 구현
next-step/kotlin-racingcar pull request #1625
Opened 2024-11-14 11:47 UTC by pkch93

안녕하세요 성호님 :)

2단계 문자열 계산기를 구현했습니다.

`build.gradle.kts`의 의존성을 보니 kotest도 들어있어 kotest로 테스트를 작성해보았습니다.

미션 편의상 `Calculator.kt`에 필요한 타입들을 모두 정의해서 사용했습니다.

리뷰 부탁드립니다

2024-11-14 15:59 UTC, Wordbe requested changes
계산기 미션 고생하셨습니다!

Calculator 안에 여러클래스가 있는데, 각 클래스가 정말 하나의 공간에 있으면 괜찮을지 고민해봤으면 좋겠습니다. 예를 들어 CalculatorTest 에는 나머지 클래스에 대한 테스트는 조금 취약하다는 생각이 드네요..!

2024-11-14 15:59 UTC, Wordbe commented on src/main/kotlin/Calculator.kt
> +    private fun parseExpression(expression: String): MathExpression {
이 클래스가 Calculator, MathExpression 둘중 어디가 적합할지 고민해봤으면 좋겠습니다 😀
이와 연결지어서 private 메소드는 테스트하기가 어렵죠? 테스트하기 쉬운 구조는 어떤건지도 생각해봤으면 좋겟습니다.

2024-11-14 15:59 UTC, Wordbe commented on src/main/kotlin/Calculator.kt
> +        return result
코틀린은 표현력높은 풍부한 메소드를 지원하므로 가변변수를 만들지 않아도 몇번의 메소드 체이닝으로 표현이 가능할 것 같아요.
생각해보면 좋을것같습니다 🙂

2024-11-14 15:59 UTC, Wordbe commented on src/main/kotlin/Calculator.kt
> +}
값 자체를 Double 로 받아보는 건 문제 있을까요?
또한 필드가 1개이므로 성능향상을 위한 value class 도 한번 도입가능한지 검토해보면 좋을 것 같아요 :)

2024-11-14 15:59 UTC, Wordbe commented on src/main/kotlin/Calculator.kt
> +    },
익명객체를 사용한 방법말고 간결함을 살리기 위한 다른방법도 혹시 있을까요?

2024-11-14 16:28 UTC, pkch93 commented on src/main/kotlin/Calculator.kt
> +        return result
"가변 변수를 만들지 않더라도"가 중점인거 같아서 `foldIndexed` 메서드를 적용해서 일단 수정했어요.

fixed 78147865

다른 더 좋은 방법도 있을지는 모르겠지만, `foldIndexed`로 변경한 코드가 처음 본 개발자분도 한눈에 파악하기 좋을지는 잘 모르겠네요. 어떻게 생각하시나요?

2024-11-14 16:31 UTC, pkch93 commented on src/main/kotlin/Calculator.kt
> +}
물론 Double을 바로 받아 볼 수 있겠지만 외부에서 Operand에 대한 검증을 처리해서 값을 전달받는거 보다는 Operand 자체에 있는게 맞다고 생각했어요. 때문에 입력받을 수 있는 raw 값을 받고 검증하는 로직을 Operand에서 수행하도록 처리했어요. 때문에 value class는 사용할 수 없었구요.

값 자체를 정제해서 받는게 낫다고 보시는 걸까요?

2024-11-14 16:35 UTC, pkch93 commented on src/main/kotlin/Calculator.kt
> +    },
생각해본다면 `Function`을 인자로 가지고 활용하는 방법이 있을 수 있겠네요

```kotlin
private enum class Operator(
    private val symbol: String,
    private val operation: Function2<Double, Double, Double>
) {
    PLUS("+", { left, right -> left + right }),
    MINUS("-", { left, right -> left - right }),
    MULTIPLY("*", { left, right -> left * right }),
    DIVIDE("/", { left, right -> left / right }),
    ;

    companion object {
        fun parse(symbol: String): Operator {
            return entries.find { it.symbol == symbol } ?: throw IllegalArgumentException("지원하는 연산자가 아닙니다.")
        }
    }
    
    fun operate(left: Double, right: Double): Double = operation(left, right)
}
```

2024-11-14 16:47 UTC, pkch93 commented on src/main/kotlin/Calculator.kt
> +    private fun parseExpression(expression: String): MathExpression {
정확히는 MathExpression에 있는게 맞는거 같네요

fixed b085a9e0

2024-11-14 16:55 UTC, pkch93 commented
피드백 감사합니다. 

Calculator 안에 여러클래스를 둔 것에 대해서는 크게 문제는 없다고 생각합니다.

Java 였다면 한 파일에 여러 클래스를 두기 어렵고 다른 파일로 두더라도 적절한 접근 제한자를 두기 어려워 애매한 경우가 많았다고 생각하는데요. Kotlin에서는 한 파일에 여러 클래스를 정의할 수 있고 접근 제한자를 적절히 활용하면 더 응집도가 높은 코드를 만들수 있을거라 기대하는데요.

지금 미션에서 Calculator 하위에 private 클래스들은 다른 클래스에서 사용될 일 없이 Calculator만 사용되는 클래스들이기 때문에 파악이 용이하고 굳이 별도 파일로 나눌 필요는 없다고 생각합니다.

물론, 파일이 너무 비대해 지지않게 잘 관리하는 것도 중요하겠지만요. 현재 Calculator는 지금 수준에서는 문제없다고 생각해요.

저도 궁금한점 코멘트 남겼는데 다시 한번 보시면서 확인부탁드립니다 :)

2024-11-15 15:25 UTC, Wordbe commented on src/main/kotlin/Calculator.kt
> +        return result
네 반영감사합니다.
foldIndexed 사용 좋아보이네요. 다만 말씀하신 것처럼 "이게 무슨 일을 하는 메소드지" 라는 의문이 들것같긴한데요.
이부분은 스크럼때 공유하거나 코드리뷰를 통해 다른 개발자분들도 충분히 금방 적응할 수 있다고 생각이 들기도합니다. 
대부분 개발자분들이 reduce 는 아실 것 같은데, reduce 와 흡사하지만 조금더 일반화된 부분이라 더욱 이해가 수월할 것 같기도하구요.
저는 코틀린이라는 언어를 개발팀이 선택했다는 것 자체가 이런 함수형 프로그래밍을 어느정도는 과감히 도입해보겠다로도 생각이 되어서 괜찮다는 생각이드네요. 🙂 (자바였으면 힘들것같습니다 🤣)

2024-11-15 15:29 UTC, Wordbe commented on src/main/kotlin/Calculator.kt
> +}
네 저는 Operand 객체 자체가 숫자인 값을 받는다면, 올바른 '피연산자' 가 될 수 있다고 생각했습니다. 
이를 Operand 가 최초 생성되는 시점인 생성자에서 검증하면 어떨까 생각이드네요. 예컨데 다른 문자가 들어오면 애초에 객체가 생성되지도 않는 방식인거죠. 😀

2024-11-15 15:29 UTC, Wordbe commented on src/main/kotlin/Calculator.kt
> +    },
말씀해주신 제안은 더 간결해보이는데 이렇게 변경하실 의향있으신가요?
아니면 지금이 더 좋아보이는 이유가 있으실까요?

2024-11-15 15:32 UTC, Wordbe commented
> 피드백 감사합니다.
> 
> Calculator 안에 여러클래스를 둔 것에 대해서는 크게 문제는 없다고 생각합니다.
> 
> Java 였다면 한 파일에 여러 클래스를 두기 어렵고 다른 파일로 두더라도 적절한 접근 제한자를 두기 어려워 애매한 경우가 많았다고 생각하는데요. Kotlin에서는 한 파일에 여러 클래스를 정의할 수 있고 접근 제한자를 적절히 활용하면 더 응집도가 높은 코드를 만들수 있을거라 기대하는데요.
> 
> 지금 미션에서 Calculator 하위에 private 클래스들은 다른 클래스에서 사용될 일 없이 Calculator만 사용되는 클래스들이기 때문에 파악이 용이하고 굳이 별도 파일로 나눌 필요는 없다고 생각합니다.
> 
> 물론, 파일이 너무 비대해 지지않게 잘 관리하는 것도 중요하겠지만요. 현재 Calculator는 지금 수준에서는 문제없다고 생각해요.
> 
> 저도 궁금한점 코멘트 남겼는데 다시 한번 보시면서 확인부탁드립니다 :)

네 맞습니다. 다만 제가 클래스를 분리해보자고 한 이유는 Calculator 외에 다른 클래스의 테스트가 빈약해보였기 떄문인데요.
이번과정이 TDD 과정인 만큼 혹시 보강해보실 수 있을까요? 보강하게 될 때 혹시 불편한 점은 없으실지 한번 여쭙고싶습니다.

2024-11-16 01:31 UTC, pkch93 commented on src/main/kotlin/Calculator.kt
> +}
음 말씀 주신 내용이 잘 이해가 되지는 않네요. 현재 제가 구현한 Operand에서도 생성 시점에서 검증하는게 아닌가요? 객체 생성 시점에서 터지겠지만 애초에 객체가 생성되지 않는거랑 큰차이는 없지않나 생각이 드는데요.

```kotlin
val class Operand(
    val value: Double,
)
```
아마 위와 같이 숫자를 받는 `Operand` 클래스를 기대하신건가 싶은데요. 위와 같이 처리한다면 외부에서 입력값을 처리하는 메서드 또는 객체가 따로 필요할텐데요. 그것보다는 `Operand`가 가지는게 낫다고 생각합니다.

2024-11-16 01:33 UTC, pkch93 commented on src/main/kotlin/Calculator.kt
> +    },
조금 간결하다 뿐이지 읽는데는 큰 문제는 없어보이는데요. 애초에 operate의 본문이 단순해서..

지금이 더 좋아보인다긴 보다 별 차이가 없어서 굳이 변경할 필요는 없다고 생각합니다.

2024-11-16 01:48 UTC, pkch93 commented
음 Calculator를 구성하는 클래스들을 public으로 변경해서 굳이 테스트를 작성할 수는 있겠는데요.

그전에 납득이 안되는점이 있어서요. CalculatorTest에 같은 파일에 정의된 private 클래스들의 로직까지도 테스트로 커버를 하고 있는데요. 테스트가 빈약해보인다는 이유가 궁금합니다. 단지 각 클래스별 Test 클래스가 정의되지 않아서일까요?

추가로 "TDD과정인 만큼"이라고 말씀주셨는데 리뷰어분께서 생각하시는 TDD도 궁금합니다.

TDD가 모든 클래스를 싹다 쪼개라는 방법론은 아니라고 생각이 드는데요. 테스트를 먼저 작성하고 리펙토링을 하면서 더 적절한 구조를 찾아가는 방법론이라고 생각하는데요. 제가 생각했을때 Calculator가 다른 케이스들을 모두 커버 가능하니 그게 테스트를 통해서 나온 결과이기도 하구요.

확인부탁드립니다.

2024-11-16 14:53 UTC, Wordbe reviewed
고생하셨습니다. 🙏

질문에 대한 답을 드리자면,
저는 한 역할을 담당하는 기본단위가 클래스로 가정하고 말한 것이었고, 그럴 때 클래스별로 테스트 케이스가 있으면 안정성이 높고 설계에도 도움을 줄 수 있는 테스트를 작성할 수 있다는 의견이었습니다.

그런데 경철님은 클래스 단위가 아닌 특정 '기능' 단위가 좋다는 의견 주신 것같아요. 그리고 경철님이 생각하시는 기준을 한 파일에 담으신 것 같구요. 
말씀해주신 것이 괜찮은 것 같아서 앞으로 리뷰시에 경철님 의견도 반영해보겠습니다. 

댓글로 남겨드린 리뷰 한번 확인해주시면 승인드리도록 하겠습니다 감사합니다.

2024-11-16 14:53 UTC, Wordbe commented on src/main/kotlin/Calculator.kt
> +}
Operand  를 생성하는 생성자나 정적메소드에서 String 을 받고,  Long 으로 바꾸는 걸 생각해봤어요
이렇게하면 Operand 안에 구성될 수 있다고 생각합니다.
경철님 구현하신 부분은 생성시점엔 `.map { Operand(it) }` 으로 생성이 된 상태에서
나중에 `operands[0].value` 와 같이 생성시점이 아닌 계산시점에, 즉 value 를 호출했을때 검증이 될 것같습니다.

2024-11-16 14:53 UTC, Wordbe commented on src/main/kotlin/Calculator.kt
> +    },
람다가 익명클래스보다는 보통 간결해보이는 편이니 그렇게 말씀드렸습니다.
문제없으시먄 유지하시죠. 😃

2024-11-16 20:49 UTC, pkch93 commented on src/main/kotlin/Calculator.kt
> +}
정적 메서드를 따로 정의해서 변경하는것도 방법이라고는 생각하는데요.

현재 구현이 `생성시점이 아닌 계산시점에, 즉 value 를 호출했을때 검증이 될 것같습니다.` 라는 의견은 잘 이해가 안되서요.

```kotlin
private class Operand(
    val rawValue: String?,
) {
    val value: Double
        get() = rawValue?.toDouble() ?: throw IllegalArgumentException("사칙 연산이 불가능한 값입니다.")
}
```
위와 같이 구현이 되었다면 계산 시점에서 검증이 된다는 것이 맞을 것 같은데요. 어떤 부분에서 `생성 시점이 아닌 계산 시점에 검증이 될 것 같다`라고 보셨을지 궁금합니다.

  현재 제가 구현했던 Operand를 java 코드로 바꿔 봤을때도 현재 구현이 생성자에서 처리가 되는거 같아보여서요
```
import kotlin.Metadata;
import org.jetbrains.annotations.Nullable;

@Metadata(
   mv = {1, 9, 0},
   k = 1,
   xi = 48,
   d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0010\u0006\n\u0002\b\u0003\b\u0002\u0018\u00002\u00020\u0001B\u000f\u0012\b\u0010\u0002\u001a\u0004\u0018\u00010\u0003¢\u0006\u0002\u0010\u0004R\u0011\u0010\u0002\u001a\u00020\u0005¢\u0006\b\n\u0000\u001a\u0004\b\u0006\u0010\u0007¨\u0006\b"},
   d2 = {"LOperand;", "", "value", "", "(Ljava/lang/String;)V", "", "getValue", "()D", "kotlin-racingcar"}
)
final class Operand {
   private final double value;

   public Operand(@Nullable String value) {
      if (value != null) {
         double var2 = Double.parseDouble(value);
         this.value = var2;
      } else {
         throw new IllegalArgumentException("사칙 연산이 불가능한 값입니다.");
      }
   } // 생성자에서 검증

   public final double getValue() {
      return this.value;
   } // getter에서는 검증이 완료된 value만 조회
}
```

2024-11-17 11:42 UTC, Wordbe commented on src/main/kotlin/Calculator.kt
> +}
@pkch93 
아아..!! 그러네요. 죄송합니다 제가 이부분을 놓쳤던 것 같습니다. 덕분에 배우고가네요 감사합니다. 🙏

2024-11-17 11:45 UTC, Wordbe approved these changes
경철님 승인드립니다 다음스텝 가시죠!!

2024-11-17 11:45 UTC, merged