3단계 - 자동차 경주 리뷰 요청드립니다.
next-step/kotlin-racingcar pull request #1631
Opened 2024-11-14 14:01 UTC by bird798

안녕하세요. 한솔님.

지난번에 해주신 리뷰 매우 즐겁게 잘 봤습니다.

최근에 혼자 일하다보니 초심도 잃어버리고, 리뷰해주시는 분도 딱히 없어 무료했는데.
해주시는 리뷰 하나 하나가 죽어 있는 개발자 세포(?)를 하나하나 깨워주는 거 같아요.

이번에도 코딩을 하긴 했는데, 구조를 잘못 짠 것인지, TestCase를 작성할 Class가 별로 없는것 같아요.
기능 분할을 잘못한 게 아닌가 생각되는데요.

부족한 코드이지만, 신랄한 리뷰 부탁드립니다.

좋은 저녁 되십시오.

감사합니다.

2024-11-15 01:32 UTC, catsbi requested changes
찬희님 3단계 미션 잘 진행해주셨어요 👍 

좀 더 고민해보면 좋은부분들 피드백 남겨드렸으니 확인 후 다시 리뷰요청 부탁드립니다!

2024-11-15 01:32 UTC, catsbi commented on src/main/kotlin/step3/Race.kt
> +package step3
미션을 진행하면서 패키지를 미션 step별로 구분하는건 권장드리지 않아요. 과정이 진행될수록 기존의 코드가 어떻게 개선되는지도 파악이되야하는데, step으로 아예 분리가되어버리면 중복 코드가 생길수도 있고, 다른 스텝간의 레이어 침범이 일어날수도 있거든요. 

좀 더 도메인적인 패키지명으로 지어서 관리해보는건 어떨까요? 
레이어드 아키텍처 혹은 도메인아키텍처 어떤 방식으로 해도 상관없습니다.

2024-11-15 01:32 UTC, catsbi commented on src/main/kotlin/step2/Calculator.kt
> +        DIVIDE("/", { a, b -> if (b != 0.0) a / b else throw IllegalArgumentException(ERROR_MESSAGE_DIVIDE_ZERO) }),
피드백 반영 👍

2024-11-15 01:32 UTC, catsbi commented on src/main/kotlin/step3/RacingGame.kt
> +class RacingGame {
로직을봐선 Controller계층과 View 계층 그리고 Service계층이 섞인 것 같네요. 물론 둘 다 UI 레이어로 테스트 대상은 아니지만, 객체의 책임 관리 측면에서 볼 때 책임이 혼재될 경우 개발을 해나가면서 계속 여기저기 난잡하게 코드들이 뒤섞일 수 있습니다. 

그리고 서비스 계층의 책임도 있는건 테스트 대상이라는건데, 컨트롤러는 테스트 대상이 아니니 또 애매해질 수 있구요. 

적절히 책임 분리를 해보는건 어떨까요? 컨트롤러, 서비스,뷰 계층의 책임이 무엇인지 고민해보면 좋을 것 같아요

2024-11-15 01:32 UTC, catsbi commented on src/main/kotlin/step3/ui/InputView.kt
> +        }
while(true) 같은 명확한 중단조건이 없는 반복문은 사용이 지양됩니다. 
내부 로직에 문제가 생기거나 조금만 놓쳐도 중단하지못해 스택오버플로 예외가 터지기 쉽습니다.

2024-11-15 01:32 UTC, catsbi commented on src/main/kotlin/step3/Car.kt
> +}
객체가 정상적으로 생성이 잘 되는지, tryMove가 정상동작하여 의도하는대로 이동을 하는지에 대한 테스트가 있으면 어떨까요?

2024-11-15 01:32 UTC, catsbi commented on src/main/kotlin/step3/Race.kt
> +    }
실패만이아닌 정상 생성 테스트도 해보면 어떨까싶네요!

2024-11-15 01:32 UTC, catsbi commented on src/main/kotlin/step3/Race.kt
> +    fun move() {
해당 함수는 테스트할 수 없을까요? 정상적으로 자동차들에게 이벤트 발행이되어 전진혹은 유지를 하는지 테스트가 있으면 좋을 것 같네요

2024-11-15 01:32 UTC, catsbi commented on src/test/kotlin/step3/ui/InputViewTest.kt
> +        assertThatIllegalArgumentException().isThrownBy { InputView("   ") }
Parameterized를 이용해볼 수 있을 것 같아요. 
테스트를 작성할 때 동일한 부류의 테스트 코드가 반복되어 작성되는건 경계해주세요. 
항상 같이 신경써줘야하는 문제가 되어 유지보수성을 낮출 수 있습니다.

2024-11-15 14:05 UTC, bird798 commented on src/main/kotlin/step3/Race.kt
> +package step3
도메인 아키텍쳐 스타일로, Application, Core, Presentation으로 Pacakge를 분리해봤습니다.

2024-11-15 14:09 UTC, bird798 commented on src/main/kotlin/step3/RacingGame.kt
> +class RacingGame {
기존에 RacingGame Class가 Controller와 Service와 View가 각각 의존성을 가지고 혼합되어 있는 듯하여, 의존성을 덜어내고, 기능을 분리해봤습니다.

의도하신방향과 맞을지 모르겠습니다, 다르다면 커멘트 부탁드립니다.

2024-11-15 14:09 UTC, bird798 commented on src/main/kotlin/step3/ui/InputView.kt
> +        }
무한반복문을 덜어대고, 특정횟수만 반복하도록 수정하였습니다.

2024-11-15 15:03 UTC, bird798 commented on src/main/kotlin/step3/Car.kt
> +}
객체의 생성과, 내부 함수의 정상동작여부를 확인하는 TestCase를 추가하였습니다.

2024-11-15 15:05 UTC, bird798 commented on src/main/kotlin/step3/Race.kt
> +    }
Car의 생성을 생성자에서 함수로 변경하였고, 해당 함수의 Testcase를 추가하였습니다.

2024-11-15 15:06 UTC, bird798 commented on src/main/kotlin/step3/Race.kt
> +    fun move() {
move함수내에 난수발생부분과 이동 부분을 분리하여 함수화하고 해당 케이스에 대해 테스트케이스를 추가하였습니다.

2024-11-15 15:07 UTC, bird798 commented on src/test/kotlin/step3/ui/InputViewTest.kt
> +        assertThatIllegalArgumentException().isThrownBy { InputView("   ") }
ParameterizedTest를 이용하도록 수정하였습니다.

2024-11-15 23:56 UTC, catsbi requested changes
찬희님 3단계 미션 피드백도 잘 반영해주셨어요 👍 

전체적으로 간결하게 잘 작성되었고 피드백도 잘 반영되었는데 조금만 더 신경쓰면 좋을 부분들이 있어 피드백 추가해드렸으니 확인 후 다시 리뷰요청 부탁드려요!

2024-11-15 23:56 UTC, catsbi commented on src/main/kotlin/racinggame/application/RacingController.kt
> +        // 입력을 받는다.
불필요한 주석같다는 생각이 듭니다. 찬희님은 주석을 다는 규칙이 있을까요? 
저는 기본적으로 Clean Code 기반의 주석 작성 기준을 가지고 결정하는편인데요, 
public api에 대한 javadoc(혹은 KDoc)을 작성하는걸 기본으로 코드내에서 주석은 함수 시그니처가 제공하기 힘든 영역이나 주의점 혹은 할일 등에 대해서 작성하는편입니다.

2024-11-15 23:56 UTC, catsbi commented on src/main/kotlin/racinggame/application/RacingController.kt
> +        }
컨트롤러에서 레이싱을 진행시키는 것 같아요. 이건 서비스의 영역이 아닐까요? 비즈니스 로직으로 보입니다

2024-11-15 23:56 UTC, catsbi commented on src/main/kotlin/racinggame/application/RacingService.kt
> +    lateinit var cars: MutableList<Car>
서비스 계층에서 상태를 가져야할 필요가 있을까요?

2024-11-15 23:56 UTC, catsbi commented on src/main/kotlin/racinggame/application/RacingService.kt
> +class RacingService() {
서비스 계층은 무상태성을 지향하기 때문에 object 로 선언해서 사용해도 되지 않을까 싶네요. 
전진전략과 같은 DI대상이 생성시점에 무조건 있는 상태를 의도한다면 private val 로 선언을 했겠지만 지연 로딩을 의도하셨다면 object도 괜찮을 것 같다는 생각이 드네요

2024-11-15 23:56 UTC, catsbi commented on src/main/kotlin/racinggame/application/RacingService.kt
> +    }
현재의 로직을 보면 짧기 때문에 놓치기 쉽지만, 트랜잭션 스크립트 패턴입니다. 
서비스 계층에서 도메인의 책임을 가져와 직접 행위를 주도하는 상황인데요. 트랜잭션 스크립트 패턴은 작성이 용이하다는 장점이 있지만, 책임의 중앙화로 인해 유지보수성이 떨어질 수 있고, 책임의 캡슐화가 노출된다는 단점도 있습니다. 

패키지를 도메인 주도로 바꿨다면 이런 책임도 도메인 주도로 적절히 분배하는게 어떨까요? 

서비스에선 도메인에 적절한 매개변수와 함께 요청하고 실제 코어 로직은 도메인 계층에게 넘겨보면 좋을 것 같습니다.

2024-11-15 23:56 UTC, catsbi commented on src/main/kotlin/RacingApplication.kt
> +
현재 커밋 메세지를 보면, 이번 미션에서 요구했던 방향인 [AngularJS Git Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153) 커밋 컨벤션을 따르지 않고 있는 것 같아요. 이 부분도 신경써주면 좋을 것 같아요

2024-11-15 23:56 UTC, catsbi commented on src/main/kotlin/racinggame/presentation/InputView.kt
> +        return true
```suggestion
        val convertedValue = value?.toIntOrNull()
        return convertedValue != null && convertedValue  > 0
```

이렇게 요약될 수도 있지 않을까요 ㅎㅎ

2024-11-17 08:25 UTC, bird798 commented on src/main/kotlin/racinggame/application/RacingController.kt
> +        // 입력을 받는다.
구현단계에서 작성해야할 코드에 대해 주석을 달아 놓고 개발하는 습관이 있습니다.
이후 해당 코드를 다시 볼경우 바로 상기할 수 있도록 하기 위함입니다.
현재는 교육 중이므로 리뷰어님의 의견을 따라, 주석을 추가하지 않도록 하겠습니다.

2024-11-17 08:48 UTC, bird798 commented on src/main/kotlin/RacingApplication.kt
> +
이후 커밋 로그를 룰에 따라서 작성하겠습니다.

2024-11-17 08:48 UTC, bird798 commented on src/main/kotlin/racinggame/presentation/InputView.kt
> +        return true
그게 더 간략하고 보기가 쉬울거 같습니다. 
반영하겠습니다.

2024-11-17 09:03 UTC, bird798 commented on src/main/kotlin/racinggame/application/RacingService.kt
> +    }
Condition체크를 Service에서 Car로 이동하였습니다.

2024-11-17 09:54 UTC, bird798 commented on src/main/kotlin/racinggame/application/RacingService.kt
> +class RacingService() {
해당 클래스를 object로 변경하였습니다.

2024-11-17 09:55 UTC, bird798 commented on src/main/kotlin/racinggame/application/RacingService.kt
> +    lateinit var cars: MutableList<Car>
초기화가 안된경우를 위한 예비코드였습니다.
변수를 클래스 초기화시점에 생성하도록 하여, 해당 문구 삭제하였습니다.

2024-11-17 09:55 UTC, bird798 commented on src/main/kotlin/racinggame/application/RacingController.kt
> +        }
서비스 쪽으로 이동하였습니다.

2024-11-17 15:28 UTC, catsbi approved these changes
찬희님 피드백 반영 잘 해주셨어요. 👍 

몇 가지 추가 피드백 남겨드렸는데 확인 후 다음 미션진행하면서 같이 반영 부탁드립니다.
3단계는 머지하도록 하겠습니다!

2024-11-17 15:28 UTC, catsbi commented on src/main/kotlin/racinggame/application/RacingService.kt
> +    var rounds: MutableList<Round> = mutableListOf()
서비스 계층은 여러 사용자가 재사용할 수 있도록 제공하기 위해 무상태 객체를 지향하는 편입니다. 
행위자체가 상태에 대한 책임을 가지기보단 행위에 대한 책임을 가지기 때문에 별도의 상태를 가질 필요도 없구요. 

cars나 rounds가 꼭 이 객체가 가져야 할 상태일까요? 함수내에서 지역변수로만 선언하여 재사용성을 높힐 순 없을까요?

2024-11-17 15:28 UTC, catsbi commented on src/main/kotlin/racinggame/core/Car.kt
> +        if (condition.canMove()) position += 1
블럭`{}`을 언제는 생략하고 언제는 작성하고 기준이 명확하지 않을 경우 일관성이 떨어지고, 그러다보면 정말 필요한 블럭도 생략할 수 있고, 가독성도 낮아질 수 있습니다. 그렇기 때문에 저는 블락 생략을 권장드리지 않습니다.

2024-11-17 15:28 UTC, catsbi commented on src/main/kotlin/racinggame/presentation/ResultView.kt
> +        }
round가 만약 Integer.MAX_VALUE일 경우 너무 많은 println문이 호출될 것 같아요. 이는 내부적으로 System.out.println을 호출하는것으로 System.out은 synchronized 키워드를 사용해 동기화 작업이 수행됩니다. 그렇기에 성능적인 이슈가 생길 수 있어요. 

StringBuilder를 활용해보는건 어떨까요?

2024-11-17 15:28 UTC, merged