Step3 - 자동차 경주 구현
next-step/kotlin-racingcar pull request #1652
Opened 2024-11-15 12:23 UTC by gmltkddl1

step2 피드백과 step3 구현 관련 PR 리뷰 요청드립니다

2024-11-15 17:04 UTC, Flamme1004K requested changes
안녕하세요~

문자열 계산기 피드백 반영 및 자동차 경주 구현 미션 고생하셨습니다!

자동차 경주 구현 미션에 대해서 피드백도 같이 드리려고 했으나, 문자열 계산기 피드백을 좀 더 드리고자 요번에는 문자열 계산기 위주로 피드백을 다시 하게 되었습니다.

피드백 반영 후 다시 리뷰 요청 부탁드립니다!

감사합니다!

2024-11-15 17:04 UTC, Flamme1004K commented on src/test/kotlin/calculator/OperatorTest.kt
>      fun divTest() {
하나의 테스트 케이스에 두 가지 테스트가 들어갔군요.

예외에 대한 테스트 케이스와 성공에 대한 테스트 케이스를 나눠보세요!

2024-11-15 17:04 UTC, Flamme1004K commented on src/main/kotlin/calculator/Calculator.kt
> +            isValid(inputs[i])
isValid를 연산하기 전에 검증하는 건 어떨까요? 지금의 isValid는 처음에는 성공하고, 중간에 검증에 실패했을 때 좋지 않다고 봐요.

2024-11-15 17:04 UTC, Flamme1004K commented on src/main/kotlin/calculator/Calculator.kt
> +            resetQueue(processResult, queue)
resetQueue를 하는 이유를 알 수 있을까요?

2024-11-15 17:04 UTC, Flamme1004K commented on src/main/kotlin/calculator/Calculator.kt
> +    }
null을 반환하는 것보다는, 예외를 일으키는게 명확하지 않을까요?

2024-11-15 17:04 UTC, Flamme1004K commented on src/main/kotlin/calculator/Calculator.kt
> +        require(input.single().isDigit()) { "Invalid input" }
<img width="401" alt="스크린샷 2024-11-16 오전 1 22 32" src="https://github.com/user-attachments/assets/8b40f653-65ba-433a-a347-fb6fbe3a6a7d">

테스트 케이스가 실패하고 있네요~

아마, 두 개의 validation으로 인하여 실패가 되는 게 아닐까 해요! 숫자에 대한 부분과 오퍼레이터에 대한 부분을 분리하여 검증하도록 변경하면 어떨까합니다!

2024-11-15 17:04 UTC, Flamme1004K commented on src/main/kotlin/calculator/Calculator.kt
>      private fun isOperator(input: String): Boolean {
코틀린에서는 isOperator와 getAction을 아래와 같이 표현이 가능합니다!

```
private fun isOperator(input: String): Boolean {
        return Operator.entries.any { it.symbol == input }
    }

    private fun getAction(symbol: String): (Int, Int) -> Int {
        return Operator.entries.first { it.symbol == symbol }.action
    }
```

2024-11-16 01:36 UTC, gmltkddl1 commented on src/main/kotlin/calculator/Calculator.kt
> +            resetQueue(processResult, queue)
현재 계산기는 사칙연산 순서를 고려하지 않아 큐에 3개의 원소가 들어오면 해당 연산을 처리하여 한개의 값만 남기는 형태로 구현하였습니다. 
요구사항 중에 최대한 val을 활용하라고 하여 이렇게 진행했습니다. 변수를 var로 변경하고 새로운 큐를 할당하는 것이 나을까요?

2024-11-16 07:42 UTC, Flamme1004K requested changes
안녕하세요~

2단계 미션 피드백 매우 잘 해주셨어요! 지난번 2단계 미션 피드백과 더불어 3단계 미션인 자동차 미션에 대한 피드백에 대해 코멘트 남겨놨습니다.

반영 후 다시 리뷰 요청 부탁드립니다!

감사합니다.

2024-11-16 07:42 UTC, Flamme1004K commented on src/main/kotlin/calculator/Calculator.kt
> +            require(isOperator(input) || input.single().isDigit()) { "is not operator and digit" }
> Invalid input 하나로 isOperator와 isDigit 중에 무엇이 틀렸는지, 알 수 있을까요? 예외에 대한 부분도 명확하게 분리해 보세요.

지난 미션 때 피드백을 위와 같은 피드백을 드린 적이 있어요~ 이 피드백을 드린 이유는, 예외는 무엇이 잘못되었는지 명확해야 하기 때문이에요. 저는 예외에 대한 명확함이 사용자는 둘째 치더라도(사용자의 관점은 어느 정도 예외를 숨겨야만 하는 상황도 있기 때문이에요.), 개발자는 예외에 대해 잘 알아야 해요. 개발자는 예외 상황에 대해서 빠르게 알아차려야 하기 때문이죠. 하지만, 이처럼 두 개의 예외가 섞여버리면 한 번에 알아차릴 수 있는 것을 더 많은 케이스를 대입하여 알아차려야 하는 경우가 생깁니다.

그런 의미로 한 번 더 코드를 변경해 보세요!

2024-11-16 07:42 UTC, Flamme1004K commented on src/main/kotlin/calculator/Calculator.kt
> +        var queue: MutableList<String> = mutableListOf()
> 요구사항 중에 최대한 val을 활용하라고 하여 이렇게 진행했습니다. 변수를 var로 변경하고 새로운 큐를 할당하는 것이 나을까요?

가변인 부분을 컨트롤 하는 것은 자바나 코틀린이나 매우 어려운 부분이며, 가변을 불변으로 만드는 방법은 매우 많은 고민이 들어간다고 생각해요. 희상님이 구현해주신 부분도 매우 훌륭하다고 생각해요!

이제 슬슬 제가 문자열 계산기에서 구현한 방법도 한번 소개할 때가 됐네요~ 제가 만약 이 부분을 구현한다면, List를 이용하는 방식이 아닌, 코틀린의 고차함수인 fold()나 foldIndexed()를 사용하려고 합니다. 이 두 함수 모두 코틀린에서 List의 값을 연속적으로 불러와 더해주는 방식입니다. 
 - https://axce.tistory.com/137

한번 이 방식으로 구현을 해보고, as-is와 to-be에 대해 장단점을 알아보시죠!

2024-11-16 07:42 UTC, Flamme1004K commented on src/main/kotlin/calculator/Calculator.kt
>              addQueue(inputs[i], queue)
```suggestion
            queue.add(input[i])
```

메서드로 감싸주지 않고, 그대로 표현해도 좋아보입니다~__

2024-11-16 07:42 UTC, Flamme1004K commented on src/main/kotlin/calculator/Calculator.kt
> +        return Operator.entries.first({ it.symbol == symbol }).action
```suggestion
        return Operator.entries.first { it.symbol == symbol }.action
```

() 도 없애도 돼요!

2024-11-16 07:42 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +class Car(var moveCount: Int) {
지금의 moveCount는 외부에서도 변경이 가능해요! Car class 내부에서만 변경 가능하게 변경해 볼까요?

2024-11-16 07:42 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +    }
지금의 move() 와 decide()를 보면 자동차는 외부에 호출에 의해 움직임이 결정되고, 움직인다고 생각해요!

메서드를 하나로 합쳐서 자동차가 내부로 요인으로 인해 움직임이 결정되고 움직이도록 변경해 보세요!

2024-11-16 07:42 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Race.kt
> +fun main() {
main 메서드와 Race 클래스는 따로 kt 파일로 가져가는 게 어떨까요?

main은 입출력에 대한 메서드이고, Race는 도메인 클래스이기 때문에 분리되어야 한다고 생각해요 :)

2024-11-16 07:42 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Race.kt
> +    val numberOfCar = readLine()!!.toInt()
```suggestion
    val numberOfCar = readln().toInt()
```

readln을 사용해 볼까요? readln과 readLine의 차이점은 무엇일까요?

2024-11-16 07:42 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Race.kt
> +    }
```suggestion
class Race(numberOfCar: Int) {
    val carList: List<Car> = List(numberOfCar) {
        Car(0)
    }
```

Race에 대해 초기화하는 로직 마음에 들어요! 잘하셨어요! 여기서 살짝 포인트를 잡는다면, List 함수를 통하여 가변인 부분을 불변으로 위와 같이 지킬 수가 있습니다.

2024-11-16 07:42 UTC, Flamme1004K commented on src/test/kotlin/calculator/OperatorTest.kt
> +        assertThatThrownBy { Operator.DIV.action(4, 0) }.isInstanceOf(ArithmeticException::class.java)
이 예외도 코드상에서 Operator의 예외로 잡아준다면, 코드 상에서 ArithmeticException이 발생할 수 있구나!라고 인지할 수 있겠죠~?

2024-11-16 07:42 UTC, Flamme1004K commented on src/test/kotlin/racingcar/RaceTest.kt
> +class RaceTest {
Race 결과에 대한 테스트도 만들 수 있지 않을까요?

2024-11-16 07:42 UTC, Flamme1004K commented on src/test/kotlin/racingcar/RaceTest.kt
> +    fun drawRaceTest() {
테스트이지만, 무엇을 검증하는지 알 수 없는 테스트네요. 검증에 대한 기준은 무엇이 되어야할까요?

2024-11-16 07:42 UTC, Flamme1004K commented on src/test/kotlin/racingcar/CarTest.kt
> +class CarTest {
자동차가 움직이지 못하는 케이스도 테스트 케이스로 만들 수 있어보여요~

2024-11-16 07:42 UTC, Flamme1004K commented on src/test/kotlin/racingcar/CarTest.kt
> +    }
두 개의 상태를 검증하는 것보다는, 테스트를 두개로 나누는게 어떨까요?

자동차를 한번만 움직여본다, 자동차를 세번만 움직여본다 등등 말이죠.

2024-11-16 09:11 UTC, gmltkddl1 commented on src/main/kotlin/calculator/Calculator.kt
> +            require(isOperator(input) || input.single().isDigit()) { "is not operator and digit" }
이 부분은 분리해보려 하였지만 인풋의 경우의 수가 (operator digit etc)이고 이 중 etc를 골라내는 코드입니다.
두가지 조건이 모두 fail일때 예외가 발생하는데 이경우에도 예외를 분리 할수 있을까요?

2024-11-16 09:26 UTC, gmltkddl1 commented on src/main/kotlin/racingcar/Race.kt
> +    val numberOfCar = readLine()!!.toInt()
반환형이 nullable이냐 아니냐 차이네요 수정하겠습니다

2024-11-16 09:41 UTC, gmltkddl1 commented on src/test/kotlin/racingcar/RaceTest.kt
> +class RaceTest {
레이스의 결과는 랜덤인데 테스트 결과를 검증할 수 있나요?

2024-11-16 10:57 UTC, gmltkddl1 commented on src/main/kotlin/calculator/Calculator.kt
> +        var queue: MutableList<String> = mutableListOf()
foldIndexed를 사용하여 구현해 보았습니다.
장점은 queue객체에 추가하고 리셋하는 로직이 줄어들었다는 것이고
단점은 만약 실제 사칙연산 순서를 고려하는 등 복잡한 로직에 적용하기는 어렵다고 생각했습니다.

2024-11-17 01:38 UTC, Flamme1004K approved these changes
안녕하세요~

3단계 미션 피드백 매우 잘 해주셨어요! 이만 머지하도록 하겠습니다.

4단계 미션도 화이팅입니다!

2024-11-17 01:38 UTC, Flamme1004K commented on src/main/kotlin/calculator/Calculator.kt
> +            require(isOperator(input) || input.single().isDigit()) { "is not operator and digit" }
문자열 계산기의 패턴을 보는 건 어떨까요!?

홀수번째는 숫자가 들어가고, 짝수번째는 사칙연산 기호가 들어가죠. 그렇다면, 간단하게 List의 순서가 홀수 번이면 숫자 검증, 짝수 번이면 사칙연산 검증을 할 수 있어 보여요.

2024-11-17 01:38 UTC, Flamme1004K commented on src/main/kotlin/calculator/Operator.kt
> +        a / b
잘 해주셨어요! 👍👍

2024-11-17 01:38 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Race.kt
> +        List(numberOfCar) { Car(0) }
```suggestion
    val cars: List<Car> =
        List(numberOfCar) { Car(0) }
```

carList보다 cars로 표현하는게 더 어울리지 않을까요~?

2024-11-17 01:38 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Race.kt
> +    }
```suggestion
    fun process() {
        carList.forEach { 
            it.process()
        }
    }
```

저는 for문보다, forEach문을 사용하여 표현하는 걸 선호합니다. 코드가 더 간결해지고, carList의 it이 car을 의미하기에 더 명확하기 때문이죠.

2024-11-17 01:38 UTC, Flamme1004K commented on src/main/kotlin/racingcar/RandomNumberGenerator.kt
> +        return secureRandom.nextInt(10)
10을 상수로 표현하면 더 의미있게 표현할 수 있지 않을까요~?

2024-11-17 01:38 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +class Car(initialMoveCount: Int) {
```suggestion
class Car(initialMoveCount: Int = 0) {
```

코틀린에는 자바와 다르게 defaultValue 라는 기능이 있어요! defaultValue는 여러 생성자를 만들지 않아도 되는 장점을 가지고 있어요. 그 외도 다른 장점이 있는데요~ 미션을 하면서 천천히 알아가죠!

2024-11-17 01:38 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +    var moveCount: Int = initialMoveCount
moveCount는 내부/외부에서도 수정되죠. 하지만, 자동차의 움직임은 Car 클래스 내에서만 수정해야 해요. 외부에서는 수정 못하도록 변경해 볼까요? 그리고 외부에서 수정이 가능하도록 하면 어떠한 문제점이 있을까요?

2024-11-17 01:38 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +        if (number >= 4) {
4도 의미가 담긴 상수로 만들어보시죠~

2024-11-17 01:38 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Race.kt
> +class Race(numberOfCar: Int) {
현재 Race에 대한 테스트 케이스는 자동차가 만들어졌는지에 대한 테스트 케이스는 작성이 가능해보여요! 한번 작성해보세요. 

추가로, https://github.com/next-step/kotlin-racingcar/pull/1652#discussion_r1844946377 에 대한 답변도 여기에 적어볼게요.

현재 랜덤 결과로 인하여 레이스의 결과에 대한 부분이 검증이 실패하는 부분이 있어요. 랜덤에 대해 어떻게 테스트 케이스에서 컨트롤 해야할지는 미션을 하면서 계속 고민해보시길 바래요. 이 고민은 자동차 미션의 최종 종착지 중에 하나일 거예요.

2024-11-17 01:38 UTC, merged