[STEP5] 자동차경주(리팩터링)
next-step/kotlin-racingcar pull request #1679
Opened 2024-11-17 05:42 UTC by JwahoonKim

controller가 domain을 의존하는 것 대신 service 계층을 두어서 처리했습니다.

처리하는 과정에서 결과를 출력하려면 레이싱 경주의 history가 필요하여 history를 저장하는 객체를 추가했습니다.

이 과정에서 조금 코드가 복잡해졌는데 이전보다 좋은 코드인지 모르겠네요ㅠㅠ 리뷰 부탁드립니다! 

감사합니다.

2024-11-17 15:20 UTC, catsbi requested changes
좌훈님 어느새 마지막 미션이네요. 
고민이 많아지면 오버엔지니어링이 될 수도 있고, 불필요한 클래스들도 많이 나오는 것 같지만, 그런 과정 이후 다시 정말 불필요한 코드들을 제거해나가는 과정에서도 인사이트를 얻을 수 있다고 생각합니다. 

마지막으로 몇 가지 피드백 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요!

2024-11-17 15:20 UTC, catsbi commented on src/main/kotlin/racingcar/controller/RacingCarController.kt
> +}
Web이라면 프론트가 CLI역할을 하는데 이런 미션에서는 사용자 입력을 주고받고 소통하는 측면이 없어서 좀 고민이 되는 부분이 있더라구요. 저는 그래서 별도의 CLI 클래스를 만들어서 컨트롤러와 View간의 소통 창구를 만들어서 책임 오염 이슈를 처리하는 편입니다

2024-11-17 15:20 UTC, catsbi commented on src/main/kotlin/racingcar/domain/Car.kt
> +        return getCurrentPosition().compareTo(other.getCurrentPosition())
compareTo 함수가 infix 함수이기에 다음과 같이 표현할수도 있습니다 
```suggestion
        return getCurrentPosition() compareTo other.getCurrentPosition()
```

2024-11-17 15:20 UTC, catsbi commented on src/main/kotlin/racingcar/domain/PositionHistory.kt
> +class PositionHistory(
자동차 도메인이 히스토리를 직접 가질 필요는 없다는 생각이 듭니다. 
레이싱을 할 때도 자동차가 기록정보를 직접 가지기보단, 중계해주는 계층에서 기록을 하니까요. 서비스에서 한 라운드가 끝날때마다 기록을 해줘도 될 것 같아요 🤔

2024-11-17 15:20 UTC, catsbi commented on src/main/kotlin/racingcar/service/RacingCarService.kt
> +)
소스파일에 하나 이상의 클래스를 두는 기준이 있으실까요? 
원래 이펙티브자바에선 하나의 소스파일에 top class가 1개 이상 있는것을 비권장합니다. 소스파일내의 어떤 클래스가 있는지 파악하기 힘들고, 그래서 과거의 JDK에선 컴파일 에러가 발생하도록 되있었죠. 

코틀린에서는 그런 에러가 발생하지는 않는데, 좌훈님은 한 소스파일에 여러 top class를 두는 기준이 있으실까요?

2024-11-17 15:20 UTC, catsbi commented on src/main/kotlin/racingcar/ui/ResultView.kt
> +            println("${car.name} : $position")
매번 print문을 사용하는것보단 StringBuilder등을 사용하여 문자열을 조합하여 한 번 출력하는건 어떨까요?

2024-11-17 15:20 UTC, catsbi commented on src/test/kotlin/racingcar/domain/PositionTest.kt
> +class PositionTest {
테스트를 꼼꼼하게 잘 만들어주셨네요 👍

2024-11-17 15:52 UTC, JwahoonKim commented on src/main/kotlin/racingcar/service/RacingCarService.kt
> +)
소스파일에 top class를 두게 된 배경은 Input, Output이 한 파일에 있어야 응집도가 좀 더 높다고 생각했는데요. 이건 inner class로 두는게 조금 더 의도와 맞을 것 같습니다. 수정해두겠습니다!

2024-11-18 22:17 UTC, catsbi approved these changes
좌훈님, 5단계 피드백 반영까지 잘 해주셨어요. 👍 

추가적으로 피드백 남겨드리긴 했는데, 크리티컬한 이슈는 아니기 때문에 머지하도록 하겠습니다. 
남긴 피드백만 확인 후 다음 주차 미션 진행하시면서 같이 고민해보면 좋을 것 같습니다. 

1주차 미션 진행하느라 고생하셨어요 👍

2024-11-18 22:17 UTC, catsbi commented on src/main/kotlin/racingcar/domain/Car.kt
> +    var position: Int = 0,
var로 선언하면 외부에서 쉽게 위변조가 가능할 것 같네요. 어떻게 막을 수 없을까요 🤔 

변경이 필요한 경우 immutable data class로 만들고 copy를 활용하거나 변경 지점을 적절히 설계해 불필요한 변경지점을 노출하지 않는게 중요할 것 같아요. 

참고: https://catsbi.oopy.io/2885f744-600e-49ea-a6a8-e321a31df527#7824983e-f120-4fe4-b4a8-73daf4de4c32

2024-11-18 22:17 UTC, catsbi commented on src/main/kotlin/racingcar/service/RacingCarService.kt
> +        val racingHistory = (1..input.numberOfAttempts).map {
피드백 반영 👍

2024-11-18 22:17 UTC, catsbi commented on src/main/kotlin/racingcar/service/dto/Input.kt
> +data class Input(
저는 개인적으로 클래스 네이밍이 상당히 중요하다고 생각합니다. 
클래스의 시그니처를 보여줄 수 있고, 그객체의 책임이 클래스명을 통해 추측가능해야 한다고 생각하여

클래스명이 추상적인 클래스일수록 책임져야 할 범위가 너무 넓어지죠.
그래서 클린코드에서는 xxxUtils라는 범용성 객체 생성을 권장하지 않기도 합니다. 

그런측면에서 racingcar라는 패키지로 범위의 제한이 걸려있다해도 Input, Output이라는 네이밍은 너무 많은 책임을 가져갈 것 같은데 좌훈님의 생각은 어떠신가요?

2024-11-18 22:17 UTC, catsbi commented on src/main/kotlin/racingcar/ui/ResultView.kt
>      }
```suggestion
    private fun printHistory(output: Output) {
    val formattedHistory = output.racingHistory.joinToString(separator = "\n\n") { roundHistory ->
        roundHistory.entries.joinToString(separator = "\n") { (carName, position) ->
            "$carName : ${"-".repeat(position)}"
        }
    }
    println(formattedHistory)
}

```

joinToString도 내부적으로 StringBuilder를 사용하기 때문이 이렇게도 표현해볼 수 있을 것 같네요!

2024-11-18 22:17 UTC, merged