[Step4] 자동차 경주(우승자)
next-step/kotlin-racingcar pull request #1690
Opened 2024-11-17 12:08 UTC by KimDabomi

- 자동차 대수 입력 -> 자동차 이름 리스트 입력으로 변경
  - 관련 서비스 로직 수정
- 자동차 이름 예외 생성
- 우승자 클래스 생성
- 우승자 계산 추가 (공동 우승 포함)
- 게임 진행 메시지 수정 및 추가
- 테스트 추가
- README 추가

2024-11-18 08:03 UTC, sah3122 requested changes
새로운 요구사항이 추가되었는데 구조에 변경이 많이 없네요 👍 
잘 짜여진 구조로 요구사항을 잘 반영해주셨습니다. 
몇가지 고민거리를 남겨두었는데 확인 부탁드려요 !

2024-11-18 08:03 UTC, sah3122 commented on src/main/kotlin/racingcar/model/RacingCar.kt
> +        fun getCarNames(userCarName: String): List<String> {
자동차 이름을 파싱하는 역할을 RacingCar 클래스가 담당해야하는 이유가 있을까요 ?

2024-11-18 08:03 UTC, sah3122 commented on src/main/kotlin/racingcar/model/Winner.kt
> +    fun getWinners(raceCars: List<RacingCar>): List<String> {
getter 네이밍은 값을 꺼내는 용도로 사용하곤 하는데 우승자를 구하는 함수임을 명확하게 나타낼수 있도록 변경해보는건 어떨까요 ? 
getter 네이밍을 습관적으로 사용하고 있다면 다른 함수들도 점검해보세요 😄

2024-11-18 08:03 UTC, sah3122 commented on src/main/kotlin/racingcar/model/exception/RacingCarException.kt
> +        private const val CAR_NAME_ERROR_MESSAGE = "자동차 이름은 5자 이하의 소문자만 가능합니다."
유효성 검사 클래스를 별도로 두기 보단 값을 가지는 RacingCar 클래스에 유효성 검사 로직을 녹이는건 어떨까요 ? 
유효성 검사 로직이 외부에 있는것과 내부에 있는것에 대한 차이점을 고민해보세요 😄

2024-11-18 08:03 UTC, sah3122 commented on src/main/kotlin/racingcar/service/RacingCarService.kt
> +        val raceMap = carNames.map { RacingCar(it) }
map 자료형이 아닌 list 자료형일것 같은데 Map으로 선언해주신 이유가 궁금합니다 😄 
개인적으론 raceCars 변수명이 어울리는것 같아요 😄

2024-11-18 08:03 UTC, sah3122 commented on src/main/kotlin/racingcar/service/RacingCarService.kt
> +    fun startWinner(raceMap: List<RacingCar>) {
마찬가지로 함수의 네이밍이 적절하지 않은것 같습니다 !

2024-11-18 09:44 UTC, KimDabomi commented on src/main/kotlin/racingcar/model/RacingCar.kt
> +        fun getCarNames(userCarName: String): List<String> {
서비스에 필요한 역할이 아니라 RacingCar의 데이터를 조작해주는 역할이라 생각해서 해당 클래스에 포함시켰는데,
제가 놓치고 있는 아이디어가 있을까요?!

2024-11-18 09:48 UTC, KimDabomi commented on src/main/kotlin/racingcar/model/exception/RacingCarException.kt
> +        private const val CAR_NAME_ERROR_MESSAGE = "자동차 이름은 5자 이하의 소문자만 가능합니다."
재사용성과 단일책임을 생각해서 예외도 따로 분리했는데, 외부에 있으면 캡슐화에 적절치 않을 거 같습니다🤔

2024-11-18 09:51 UTC, KimDabomi commented on src/main/kotlin/racingcar/service/RacingCarService.kt
> +        val raceMap = carNames.map { RacingCar(it) }
Map 자료형으로 했다가 수정하는 과정에서 빼트렸습니다 핳핳

2024-11-19 12:50 UTC, sah3122 commented on src/main/kotlin/racingcar/model/RacingCar.kt
> +        fun getCarNames(userCarName: String): List<String> {
RacingCar는 자동자 경주에서 도메인 역할을 하는 클래스라고 생각합니다 😄 
입력 값을 파싱하는 역할과는 거리가 먼것 같아요!

2024-11-19 12:55 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
한가지 고민거리를 남겨두었는데 확인 부탁드리며 다음 미션도 화이팅 해주세요 !

2024-11-19 12:55 UTC, sah3122 commented on src/main/kotlin/racingcar/model/RacingCar.kt
> +        private fun checkCarNameTypeAndSize(userCarName: String) {
RacingCar 를 생성하는 시점에 init block을 활용하여 유효성 검사를 하는것과 현재와 같이 값을 파싱하는 과정에서 유효성 검사를 하는것에 대한 차이점을 고민해보시면 좋을것 같습니다 😄

2024-11-19 12:55 UTC, sah3122 commented on src/main/kotlin/racingcar/model/RacingCar.kt
>      override fun toString(): String {
다음 미션을 진행하며 이와 같이 presentation layer에서 필요한 값을 도메인객체와 분리해보세요 😄

2024-11-19 12:55 UTC, merged