[step3] 자동차 경주 게임 구현
next-step/kotlin-racingcar pull request #1699
Opened 2024-11-18 00:38 UTC by pkch93

3단계 자동차 경주 게임 미션 구현하였습니다.

중간에 커밋 내용이 CarRacingGame 테스트 작성, CarRacingGame 성공하도록 구현, CarRacingGame 리펙토링이 한번씩 더 나올텐데 먼저 나온 CarRacingGame의 클래스 명을 Round로 변경하였어서 이점 참고 부탁드립니다 :)

2024-11-18 15:37 UTC, Wordbe requested changes
전반적으로 코드가 보기 좋고 깔끔해보입니다!
구조도 이해하기 쉽구요.
생각해볼만한 부분은 리뷰달았으니 확인 부탁드립니다😀

2024-11-18 15:37 UTC, Wordbe commented on src/main/kotlin/car/view/InputView.kt
> +        val maybeCarAmount = readlnOrNull()
nullable 타입의 변수명이 좋네요 👍

2024-11-18 15:37 UTC, Wordbe commented on src/main/kotlin/car/view/InputView.kt
> +    }
모든 IllegalArgumentException 에 대한 처리가 "자동차 대수는 0보다 커야 합니다." 가 되어서, 만약 Car() 안에서 IllegalArgumentException 가 발생해도 같은 메시지를 내보낼 것 같아요. 
이런 일을 예방하는 차원에서 변경이 어떨지 의견드립니다 🙂

2024-11-18 15:37 UTC, Wordbe commented on src/main/kotlin/car/Car.kt
> +        return MovedCar(position)
Car, MovedCar 을 분리한 이유는 무엇인가요?

2024-11-18 15:37 UTC, Wordbe commented on src/main/kotlin/car/Round.kt
> +            .let { RoundResult(it) }
(옵션입니다)
map → let 이런 패턴을 많이 쓰신 것 같은데, let을 단순히 생성자 호출이라면 생성자를 겉에 감싸는게 더 간단해보입니다.
https://kotlinlang.org/docs/scope-functions.html#let 사용사례

2024-11-18 15:37 UTC, Wordbe commented on src/main/kotlin/car/Round.kt
> +    operator fun get(index: Int): MovePossibility = movePossibilities[index]
연산자 오버로딩 👍

2024-11-18 15:37 UTC, Wordbe commented on src/main/kotlin/car/view/OutputView.kt
> +    }
```
실행 결과
-
-
-
```
대신에 줄바꿈이 한번더 들어가는데 한번 수정해주시면 좋을 것 같아요.

2024-11-18 15:37 UTC, Wordbe commented on src/main/kotlin/car/CarRacingGame.kt
> +}
여기에 사용된 index 와 이 안에 사용된 index 를 사용하는 대신 더 안전해보이는 구조로 변경해볼 수 있을까요?

2024-11-18 20:38 UTC, pkch93 commented on src/main/kotlin/car/view/InputView.kt
> +    }
음 위 try 문에서는 carAmount가 0 미만인 경우밖에 없을것 같은데요. Car 안에서 IllegalArgumentException이 발생할 경우가 있는걸까요? 어떤 부분에서 그렇게 보셨을지 궁금합니다

2024-11-18 20:46 UTC, pkch93 commented on src/main/kotlin/car/Round.kt
> +            .let { RoundResult(it) }
저도 보통은 생성자를 감싸는 형태로 많이 사용하는데요.

이번 미션에서는 대부분 생성자를 감쌌을때보다 let을 사용하는게 더 가독성이 좋아보였어서 CarRacingGameResult나 RoundResult에서는 let을 사용해서 처리했었는데요.

단순 생성자 호출이라면 let 사용을 비추천하셔서 제안주신걸까요?

2024-11-18 20:47 UTC, pkch93 commented on src/main/kotlin/car/view/OutputView.kt
> +    }
확인 감사합니다. 수정했습니다.

fixed f34348fa

2024-11-18 20:50 UTC, pkch93 commented on src/main/kotlin/car/Car.kt
> +        return MovedCar(position)
Car는 자동차 경주 게임에 이용되는 자동차 주체인데 가변 프로퍼티를 가지고 있어서 각 라운드 마다 이동한 결과를 불변인 MovedCar로 표현하고 싶었어요.

2024-11-18 20:56 UTC, pkch93 commented on src/main/kotlin/car/CarRacingGame.kt
> +}
`여기에 사용된 index`와 `이 안에 사용된 index`가 어떤말일까요?? `movePossibilities[it]` 이부분 말씀일까요

2024-11-19 13:58 UTC, Wordbe commented on src/main/kotlin/car/view/InputView.kt
> +    }
만약 다른 로직이 생겼을 때를 대비함으로 말씀드렸습니다 🙂

2024-11-19 14:08 UTC, Wordbe reviewed
경철님 피드백이 빠르시네요! 항상 잘 작성해주셔서 감사합니다.
물어보신 부분 다시 답변드려요!

2024-11-19 14:08 UTC, Wordbe commented on src/main/kotlin/car/Car.kt
> +        return MovedCar(position)
car 에서 postition += 1 을 해주셨는데 결국 자동차경주 결과에 car 가 사용되지는 않는 구조 인것처럼 보이는데요.
car 는 movedCar 를 생성한 후 더이상 필요가 없는 객체가 되는건가요?
그렇다면 객체가 조금 낭비되는 느낌인 것 같은데 Car 의 프로퍼티를 val 로 선언하고 새로 만드는 방식은 어떻게 생각하시나요? 🧐

2024-11-19 14:08 UTC, Wordbe commented on src/main/kotlin/car/CarRacingGame.kt
> +}
네네 맞습니다! 리스트에서 특정 인덱스의 값을 불러오는 건 항상 ArrayIndexOutOfBoundsException 우려가 있어보여서요!

2024-11-19 14:08 UTC, Wordbe commented on src/main/kotlin/car/Round.kt
> +            .let { RoundResult(it) }
네 맞습니다. 처음 봤을 때 무슨 동작을 하는지 약간 생각을 하게 만든 구문이었어요.
허나 저도 가독성을 크게 해치지는 않는 것 같아서 선택사항으로 드립니다 😀

2024-11-20 01:26 UTC, Wordbe requested changes
위에 코멘트 드립니다!

2024-11-20 10:49 UTC, pkch93 commented on src/main/kotlin/car/Car.kt
> +        return MovedCar(position)
네네 과정에만 사용되고 결과에는 사용되지 않는 객체에요.

구현할 때 말씀해주신 것처럼 `Car`를 결과로도 사용할까 생각도 했었는데요. 다음 2가지 이유 때문에 `MovedCar`가 더 낫겠다고 생각했었어요.

1. `Car`가 결과 객체로 사용되는 경우 결과 객체인 `Car`에서 `move`가 가능할 수 있음.
 - 결과는 각 라운드의 결과만 전달하는 역할만 담고 싶었어요.
2. `MovedCar`라는 객체를 둬서 보다 명확한 네이밍 전달
 - `Car` 보다는 `MovedCar`로 이동한 `Car`라는 걸 명확히 하고 싶었어요.

말씀해주신 방식으로 구현해도 객체가 생성되는 수준은 크게 다르지 않을거 같네요. 그것보다는 과정 `Car`과 결과 `MovedCar` 부분을 구분하는게 좀 더 낫다고 생각했어요.

2024-11-20 10:57 UTC, pkch93 commented on src/main/kotlin/car/view/InputView.kt
> +    }
음 그건 그때 고민하면 되지 않을까 싶네요 🙂

확장성 부분을 보신거 같은데요. 어느정도 예상되는 위험, 확장가능성을 고려하는건 필요하다고 생각하는데요.

지금 수준에서 발생 가능한 경우가 보인다면 그를 대비해서 대응을 해도 괜찮다고 생각하지만요. IllegalArgumentException이 발생할 가능성이 자동차 대수가 0 미만인 경우만 있는 상황에서는 굳이 다른 경우까지 고려할 필요가 있을까 싶네요.

굳이 추가한다면 다른 예상치 못한 Exception이 발생했을때 일반적인 에러 메세지를 보여주도록 catch 문 추가하는거 정도는 생각해볼 수 있겠네요.

2024-11-20 11:08 UTC, pkch93 commented on src/main/kotlin/car/CarRacingGame.kt
> +}
`자동차 대수는 몇 대인가요?`로 입력받은 `totalRound`와 `movePossibilities`의 갯수가 동일해서 따로 고려는 안하고 있었는데요. 타 부분에서 수정이 `MovePossibilities`에서 에러가 발생할 여지가 있네요.

수정했습니다. fixed 1fceea58

2024-11-20 11:10 UTC, pkch93 commented
피드백 감사합니다. 제 의견도 남겼는데 확인 부탁드려요

2024-11-20 13:43 UTC, Wordbe commented on src/main/kotlin/car/view/InputView.kt
> +    }
네 알겠습니다 필요할 때 추가해보시죠! :)

2024-11-20 13:43 UTC, Wordbe commented on src/main/kotlin/car/Car.kt
> +        return MovedCar(position)
넵넵 그럼 유지하시죠!

2024-11-20 13:45 UTC, Wordbe approved these changes
리뷰 반영 감사드립니다. 고생하셨습니다 다음 스텝으로 가시죠! 🥳

2024-11-20 13:45 UTC, merged