[Step4] 자동차 경주 구현하기(우승자)
next-step/kotlin-racingcar pull request #1702
Opened 2024-11-18 09:24 UTC by Seokho-Ham

안녕하세요 윤혁님! 4단계 리뷰 요청드립니다.

앞선 단계에서 리뷰해주셨던 내용들은 이번 스텝에서 적용하였습니다.
```
- Main에서 실행되던 반복 로직을 CarGame 클래스로 옮기기
- 디버깅을 위해 예외메세지에 입력값 함께 출력하기
- import 수정
```

그럼 이번 리뷰도 잘부탁드립니다!

2024-11-19 14:44 UTC, malibinYun requested changes
4단계 미션 고생 많으셨어요 :)
이미 5단계 미션의 요구 사항인 View와 Domain의 분리는 잘 수행되어있어서 다음 단계 진행은 안하셔도 될 것 같아요.
더 반영하거나 시도해보고 싶으신 부분이 있으시다면 반영 후 리뷰 요청 부탁드리고, 이만 마무리하시려면 DM이나 코멘트 부탁드려요!

2024-11-19 14:44 UTC, malibinYun commented on src/main/kotlin/racingcar/Car.kt
> +
validateNameLength 함수 내부를 보니, 빈 문자열로 Car를 생성할때 또한 같은 에러메시지로 나타나 디버깅할 때 조금 어색하다는 느낌이 들거라고 예상돼요.
에러를 더 상세히 표현하고자 한다면, require을 두 번 사용해보는 건 어떨까요?

2024-11-19 14:44 UTC, malibinYun commented on src/main/kotlin/racingcar/Main.kt
> +    ResultView.printRaceResult(gameCount, carGame.scoreBoard)
순차적으로 실행 후, 필요한 값을 객체에 꺼내서 쓰는 방법을 활용해주셨네요!
아래 처럼 게임을 시작하면, 그 게임의 결과를 반환하는 방법을 사용해서 코드를 구성해볼 수도 있겠어요 :)
```kotlin
val carGame = CarGame(...)
val gameResult = carGame.start()
ResultView.printRaceResult(gameResult)
```

2024-11-19 14:44 UTC, malibinYun commented on src/main/kotlin/racingcar/RandomNumberGenerator.kt
> +            Random.nextInt(from, until)
아래 처럼 랜덤 수를 생성할 수도 있어요! :)
```kotlin
val randomInt = (0..10).random()
```

2024-11-19 14:44 UTC, malibinYun commented on src/main/kotlin/racingcar/ScoreBoard.kt
> +    val board = mutableMapOf<String, MutableList<Int>>()
템플릿이 여러개 중복되면 어떤 타입이 어떤 값을 의미하는지 점점 알기 어려워진다고 생각해요.
의미있는 값들을 모델로 묶어서 의미있는 이름을 부여해보는 건 어떨까요?

2024-11-19 14:44 UTC, malibinYun commented on src/main/kotlin/racingcar/ScoreBoard.kt
> +        }
!!는 최대한 지양해보는 건 어떨까요?
map의 한 요소를 접근했을 때, null 인 경우엔 A를, null이 아닌 경우에는 B를 수행할 수 있는 메서드가 있으니 한 번 찾아보셔도 좋겠어요!

2024-11-19 14:44 UTC, malibinYun commented on src/main/kotlin/racingcar/ScoreBoard.kt
> +}
이 함수를 호출하고 winners를 가져오는 것 보다는, 우승자를 계산하고 그것을 반환하도록 구성해보는 건 어떨까요?
다른 개발자들이 winners를 먼저 접근하기 이전에 recordWinners()함수를 반드시 호출해야하는지 이 객체를 자세히 들여다보지 않으면 알기 어렵다고 생각해요.

2024-11-19 14:44 UTC, malibinYun commented on src/test/kotlin/racingcar/ScoreBoardTest.kt
> +        scoreBoard.board.values.forEach { records -> records[0] shouldBe 1 }
반복문을 돌려 테스트를 검증하기 보다, list는 기대하는 list를 만들어 직접 비교해보는 건 어떨까요?

2024-11-20 04:57 UTC, Seokho-Ham commented on src/main/kotlin/racingcar/ScoreBoard.kt
> +        }
덕분에 `computeIfAbsent` 메서드라는게 있다는걸 알았네요! 수정했습니다!
(말씀하신 메서드가 이게 맞을까요?ㅎㅎ)

2024-11-20 04:57 UTC, Seokho-Ham commented on src/main/kotlin/racingcar/ScoreBoard.kt
> +}
말씀해주신 부분까지는 고려를 못했던것 같습니다!

피드백 반영해서 외부에서 별도의 호출 없이 회차별로 기록하는 메서드 내부에 `마지막 회차일 경우` 우승자를 집계하도록 코드를 수정했습니다!

2024-11-20 04:58 UTC, Seokho-Ham commented on src/main/kotlin/racingcar/ScoreBoard.kt
> +    val board = mutableMapOf<String, MutableList<Int>>()
말씀해주신걸 바탕으로 각각의 의미있는 객체로 나누었습니다!
하지만 그만큼 복잡도가 올라간거 같기도 해서 어느정도 선으로 나누어야 할지에 대한 고민이 생기네요.

2024-11-20 04:59 UTC, Seokho-Ham commented on src/main/kotlin/racingcar/RandomNumberGenerator.kt
> +            Random.nextInt(from, until)
오 더 직관적이어서 가독성이 좋은 방식 같네요! 적용했습니다!
이것도 내부 동작은 `Random.nextInt()`와 동일하게 동작하는군요!

2024-11-20 05:04 UTC, Seokho-Ham commented
말씀해주신 내용들 바탕으로 개선해보았습니다!
그 중에서 제일 큰 수정사항으로는 기존의 ScoreBoard 내부에 있는 Map 타입의 객체를 의미있는 클래스로 세분화 한 내용입니다.
구현하면서 확실히 의미가 있는 객체로 분리되는것 같아서 좋은것 같으면서도 동시에 너무 복잡도가 올라가나? 라는 생각도 드네요!
이런 부분에 대해서 고민해볼 수 있어서 좋았습니다!

step5는 별도로 진행하지 않더라도 이번 변경사항에 대해서까지는 피드백을 받고 싶습니다!

2024-11-21 02:15 UTC, malibinYun approved these changes
자동차 경주 미션 완주하시느라 고생 많으셨어요!
이번 미션은 이만 마무리하도록 하겠습니다.
미션을 진행하시면서 고민했던 점들이 앞으로 큰 도움이 되시면 좋겠네요 :)
남은 미션들도 모두 완주하시길 응원할게요!

2024-11-21 02:15 UTC, malibinYun commented on src/main/kotlin/racingcar/CarGame.kt
> +        return raceAggregateSystem
Race에 대한 결과만을 담은 객체를 여기에서 만든 다음 넘기는 형태를 사용하면 좀 더 복잡도를 줄일 수 있을 것으로 기대돼요.
```kotlin
class RacingResult(
    val carRacingResults: List<CarAndDistance>,
    val winningCarName: String,
)
```
자동차의 결과도 움직일 때마다 해당 자동자의 이름과 거리만을 담은 모델을 저장하는 형태로 구성해볼 수도 있겠어요.
자동차와 그 기록은 같은 객체로 처리해볼 수도 있지만, 다른 객체로도 충분히 처리 가능하다고 생각해요!

이 방법은 정답으로 제시해드리는 건 아니고, 이러한 방향도 있음을 알려드리고 싶어서 남겨두어요!

2024-11-21 02:15 UTC, merged

2024-11-21 04:14 UTC, malibinYun commented on src/main/kotlin/racingcar/ScoreBoard.kt
> +        }
오 넵 맞습니다! 정확히 이 메서드를 생각하고 말씀드렸어요 :)