Step3, 자동차 경주
next-step/kotlin-racingcar pull request #1703
Opened 2024-11-18 11:01 UTC by Minsu-Lee

지난 과제에서 로직이 너무 복잡하다 싶어서
mvc 형태로 로직을 나누어 진행해보았습니다.
PR 잘부탁드립니다. 🙏

2024-11-18 13:20 UTC, Minsu-Lee commented
PR요청 이후 제출한 코드를 보니
현재 만들어진 로직은 단위테스트를 진행하기에 한계를 느꼈고, 시도 횟수 크기만큼 전진 유무 값을 갖는 
자동차에 대한 객체를 만들어서 관리했더라면 단위테스트를 할 수 있는 케이들이 좀더 늘어나지 않았을까, 아쉬움이 남았습니다.🥲

2024-11-18 15:05 UTC, Minsu-Lee commented
step3 브런치가 step2가 포함되지 않은 상태에서 만들어져서
step3 브런치에 뒤늦게 step2 브런치 머지해두었습니다.
참고부탁드립니다 🥲

2024-11-19 07:46 UTC, vsh123 requested changes
안녕하세요!!

step3 잘 구현해주셨습니다 :) 

몇가지 코멘트를 남겼으니 확인 부탁드려요~

2024-11-19 07:46 UTC, vsh123 commented on build.gradle.kts
> +    jvmToolchain(11)
해당 버전을 11로 내리신 이유가 있을까요? 이번과제는 21로 진행하는 만큼, 21버전을 사용하면 어떨까 싶어요!

2024-11-19 07:46 UTC, vsh123 commented on src/main/kotlin/step2/calculator/Calculator.kt
> +    companion object {
[kotlin class layout](https://kotlinlang.org/docs/coding-conventions.html#class-layout)을 알아보고 적용해보면 어떨까요?

2024-11-19 07:46 UTC, vsh123 commented on src/main/kotlin/step2/calculator/Calculator.kt
> +}
ktlint 적용이 되어있지 않은 것  같아요! 확인해보고 적용부탁드립니다!

2024-11-19 07:46 UTC, vsh123 commented on src/main/kotlin/step3/controller/RacingController.kt
> +fun main() {
main과 Controller파일은 분리해보면 어떨까요?

2024-11-19 07:46 UTC, vsh123 commented on src/main/kotlin/step3/controller/RacingController.kt
> +}
지금 파일명은 RacingController 인터페이스와 동일한것같은데, 안에는 더 많은 클래스들이 존재하는것같아요.

* 인터페이스와 구현체의 파일을 분리하고, 적당한파일 네이밍을 해주면 어떨까요?

2024-11-19 07:46 UTC, vsh123 commented on src/main/kotlin/step3/controller/RacingController.kt
> +        val moveSymbol = '-'
상수는 companion object나 최상위 프로퍼티로 빼주면 어떨까요?

2024-11-19 07:46 UTC, vsh123 commented on src/main/kotlin/step3/controller/RacingController.kt
> +    val inputView: InputView = InputViewFactory.newInstance()
kotlin은 타입추론이 가능하기때문에 타입을 명시하지않아도괜찮은데요!
모든 변수에 타입을 명시하신 이유가 있을까요?

```suggestion
    val inputView = InputViewFactory.newInstance()
```

2024-11-19 07:46 UTC, vsh123 commented on src/main/kotlin/step3/model/RandomGenerator.kt
> +interface RandomGenerator {
Random은 구현의 일종이라고 생각하는데요!

인터페이스는 숫자를 만들어주는 Generator등으로 명시해주면 어떨까요?

2024-11-19 07:46 UTC, vsh123 commented on src/main/kotlin/step3/model/RacingProcess.kt
> +package step3.model
지금 도메인 모델이라고 볼 수 있는 객체가 없는것같아요! 

도메인 객체를 만들어보면어떨까요?

2024-11-19 07:46 UTC, vsh123 commented on src/main/kotlin/step3/model/RacingProcess.kt
> +    ): Array<Array<Int>> {
도메인 객체를 만들게 되면 double Array가아닌 객체를 리턴할 수 있을 것 같아요~

2024-11-19 07:46 UTC, vsh123 commented on src/main/kotlin/step3/model/RacingProcess.kt
> +private class RacingProcessImpl(
해당 클래스에 대한 단위테스트가 보이질 않는것 같아요!

테스트를 작성해보면 어떨까요?

2024-11-19 07:46 UTC, vsh123 commented on src/test/kotlin/study/racing/InputViewTest.kt
> +    fun `숫자 입력값 검증 테스트`() {
step2에서 활용하셨던 parameterizedTest를 이용하면 중복을 제거하고 테스트를 간결하게 만들 수 잇을 것 같아요! :)

2024-11-19 10:29 UTC, Minsu-Lee commented on build.gradle.kts
> +    jvmToolchain(11)
sdk 가 21 버전대로 설정안되어 있었는데, 원인 파악안하고 빨리 과제 진행하려고 내렸었습니다.
원래 버전 21 로 수정했습니다.

2024-11-19 10:43 UTC, Minsu-Lee commented on src/main/kotlin/step2/calculator/Calculator.kt
> +    companion object {
코틀린 컨벤션 공유 감사합니다.
공유주신 의도는 이해했습니다.
평범한 코드가 아니므로 가독성에 방해요소가 될 수 있겠다 싶어서
이전에 언급되었던 팩토리 클래스를 분리하였습니다.

2024-11-19 10:52 UTC, Minsu-Lee commented on src/main/kotlin/step2/calculator/Calculator.kt
> +}
Tasks > verification > check & ktlinktCheck 둘다 진해한 뒤에 푸시를 하고 있는데 어떤것때문에 그럴까요..?
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/4d26fe3d-d0c3-44b3-8cd2-e419ad4a22e6">

2024-11-19 11:07 UTC, Minsu-Lee commented on src/main/kotlin/step3/controller/RacingController.kt
> +fun main() {
반영하였습니다.
step3 > racing 경로 내에, RacingApplication 클래스로 분리하였고,
연관성 있게 racing 경로 내로 controller, view, model 위치시켰습니다.

2024-11-19 11:52 UTC, Minsu-Lee commented on src/main/kotlin/step3/controller/RacingController.kt
> +}
현재 파일내로 들어와야 구성요소가 확인되는 상태이니,
말씀하신것처럼 별도의 클래스로 분리하는게 맞을것 같습니다.
수정하겠습니다~
- RacingController.kt
- RacingControllerFactory.kt
- RacingControllerImpl.kt

2024-11-19 12:13 UTC, Minsu-Lee commented on src/main/kotlin/step3/model/RandomGenerator.kt
> +interface RandomGenerator {
좋은것 같습니다.
NumberGenerator 로 인터페이스 명을 변경해보았습니다.

2024-11-19 12:31 UTC, Minsu-Lee commented on src/main/kotlin/step3/controller/RacingController.kt
> +        val moveSymbol = '-'
좋은것 같습니다~

2024-11-19 14:42 UTC, Minsu-Lee commented on src/main/kotlin/step2/calculator/Calculator.kt
> +}
ktlintCheck 할때마다 어떤경우에는 메서드 인자 마지막에 컴마를 찍어야되거 안찍어도 통과되는 경우도 있던데,
ktlinCheck는 원래 이러나요...?

2024-11-19 14:50 UTC, Minsu-Lee commented on src/main/kotlin/step3/model/RacingProcess.kt
> +package step3.model
말씀하시는 도메인 모델이란게 예시로 자동차에 대한 모델 객체를 말씀하시는것 같은데 맞을까요?
안그래도 오늘 온라인 강의 들으면서 언급되는 예시들 통해서 entity에 해당하는 객체가 없어서
테스트 케이스를 구현하기 힘들었던건가 싶었습니다.

도메인 객체에 대해서 현재는 자동차 entity에 대해서 밖에 떠오르지 않은데, 혹시 도메인 객체가 될수 있는 대상이 더있을까요?
우선 Car entity로 구성해서 로직 수정해보도록 하겠습니다.
감사합니다~

2024-11-19 14:52 UTC, Minsu-Lee commented on src/main/kotlin/step3/model/RacingProcess.kt
> +    ): Array<Array<Int>> {
좋은 의견같습니다~
수정해서 pr 다시 요청드리겠습니다!

2024-11-19 18:20 UTC, Minsu-Lee commented on src/main/kotlin/step3/model/RacingProcess.kt
> +    ): Array<Array<Int>> {
자동차 도메인 객체로 추출하면서
기존에 있던 RacingProcess 로 인해 오히려 더 복잡해짐을 느껴서 해당 로직은 제거하였고,
해당 부분은 Controller 에서 Car 객체를 생성하는 방향으로 수정되었습니다.
수정된 내용이 많아서 힘드시겠지만 잘부탁드립니다 🙏

2024-11-19 18:22 UTC, Minsu-Lee commented on src/main/kotlin/step3/model/RacingProcess.kt
> +private class RacingProcessImpl(
Car 도메인 객체로 분리하면서 
RacingProcess 의 처리내용과 RacingController에서 처리하는 내용이 유사하다 판단하여
RacingProcess는 제거하고 RacingController에서 이에 대한 내용을 수행하게 수정해보았습니다. 🙏

2024-11-19 18:31 UTC, Minsu-Lee commented on src/test/kotlin/study/racing/InputViewTest.kt
> +    fun `숫자 입력값 검증 테스트`() {
테스트 케이스 추가해보았습니다 👍 
```kotlin
@ParameterizedTest
@ValueSource(strings = ["    ", "q2", "1 1", "33-3", "  1"])
fun `숫자 입력값 검증 테스트`(input: String) {
    val inputView = InputViewFactory.newInstance()
    shouldThrow<IllegalArgumentException> {
        inputView.inputNumber(input)
    }.apply {
        message shouldBe "숫자를 입력해주세요."
    }
}
```

2024-11-20 11:17 UTC, vsh123 approved these changes
민수님 안녕하세요!!
리팩토링하느라 고생많으셨습니다!! 👍 

몇가지 코멘트를 남겼으니 다음스텝에서 함께 반영부탁드려요~!! 

이번스텝은 머지하도록 하겠습니다!

2024-11-20 11:17 UTC, vsh123 commented on src/main/kotlin/step3/racing/view/input/InputViewImpl.kt
> +internal class InputViewImpl : InputView {
ConsoleInputView와 같이 구현체의 특징이 담긴 네이밍을 해주면 어떨까요?

2024-11-20 11:17 UTC, vsh123 commented on src/test/kotlin/study/racing/CarTest.kt
> +package study.racing
CarTest의 패키지 위치가 Car 클래스와 다른거 같아요! 확인한번 부탁드립니다!

2024-11-20 11:17 UTC, vsh123 commented on src/main/kotlin/step3/racing/model/car/Car.kt
> +    var position: Int = position
👍

2024-11-20 11:17 UTC, vsh123 commented on src/main/kotlin/step3/racing/model/car/Car.kt
> +        return "$symbol".repeat(position)
symbol은 도메인 보다는 view영역에 가까운 것 같아요! Car에서는 position만 리턴하고 symbol은 view영역에서 정의해보면 어떨까요?

2024-11-20 11:17 UTC, vsh123 commented on src/main/kotlin/step3/racing/controller/RacingControllerImpl.kt
> +        println()
해당 출력도 view영역 아닐까요?

2024-11-20 11:17 UTC, vsh123 commented on src/main/kotlin/step3/racing/model/car/Car.kt
> +    private fun validCarCount(carCount: Int) {
저는 Car라는 클래스는 자동차 1대를 나타내는걸로 이해했는데요!
Car클래스 안에 carCount라는 프로퍼티와 해당 validation이 필요한 이유가 있을까요?

2024-11-20 11:17 UTC, vsh123 commented on src/main/kotlin/step3/racing/model/car/Car.kt
> +    var attemptCount: Int = DEFAULT_ATTEMPT_COUNT,
시도 횟수는 횟수를 제어하는 Controller의 역할이라는 생각이 드는데요! Car의 속성이라고 볼수 있을까요?

2024-11-20 11:17 UTC, vsh123 commented on src/main/kotlin/step3/racing/model/car/Car.kt
> +    private val numberGenerator: NumberGenerator = RandomGeneratorFactory.newInstance(),
이 두값은 자동차의 속성(상태)라고 보기에 조금 애매한 것 같아요!

`move()`의 인자로 generator를 받는건 어떨까요?

2024-11-20 11:17 UTC, vsh123 commented on src/test/kotlin/study/racing/CarTest.kt
> +    }
random을 테스트하기에는 횟수가 한번인게 조금 아쉬운데요!! 
[repeatTest](https://velog.io/@geon_km/%EB%8B%A8%EC%9C%84-%ED%85%8C%EC%8A%A4%ED%8A%B8-rs6ri4fz#4-1-repeatedtest)를 활용해보는건 어떨까요?

2024-11-20 11:17 UTC, vsh123 commented on src/main/kotlin/step3/racing/model/generator/RandomGeneratorImpl.kt
> +internal class RandomGeneratorImpl(private val range: IntRange) : NumberGenerator {
해당 Generator에 대한 단위테스트도 작성해볼수 있지 않을까요?

2024-11-20 11:18 UTC, merged

2024-11-20 12:16 UTC, Minsu-Lee commented on src/main/kotlin/step3/racing/view/input/InputViewImpl.kt
> +internal class InputViewImpl : InputView {
직관적이여서 좋은것 같습니다.
수정해두도록 하겠습니다 :)

2024-11-20 13:01 UTC, Minsu-Lee commented on src/test/kotlin/study/racing/CarTest.kt
> +package study.racing
잘못되어 있는부분 확인했고, 테스트 코드와 경로 최대한 유사하게 가져갈 수 있게
경로 수정해보았습니다.

2024-11-20 13:19 UTC, Minsu-Lee commented on src/main/kotlin/step3/racing/model/car/Car.kt
> +        return "$symbol".repeat(position)
단순 값을 가공한다 생각했었는데, 자동차를 문자료 표현하는거니 view쪽에 위치하는것도 일리있는것 같습니다.
ResultViewImpl 로 해당 로직 이동하였습니다.

2024-11-20 13:22 UTC, Minsu-Lee commented on src/main/kotlin/step3/racing/controller/RacingControllerImpl.kt
> +        println()
println을 놓쳤네요
inputView를 통해서 개행을 처리하도록 수정하였습니다.

2024-11-20 13:39 UTC, Minsu-Lee commented on src/main/kotlin/step3/racing/model/car/Car.kt
> +    private fun validCarCount(carCount: Int) {
초기에 Car 내부에서 게임진행에 대한 로직을 수행했었다가
Car에서의 책임이 너무 많다 느꼈고, 적절하지 않다 판단되어
몇번의 시행착오 끝에 수정된 내용인데, 지금은 불필요한 부분이나 제거하는게 누락된것 같습니다.
Car에서 carCount, attemptCount, validCarCount, validAttemptCount는 제거하도록 하겠습니다.

carCount, attempt 에 대한 검증이 필요할 경우, 입력값을 전달받아 처리가능한 controller에서 처리하거나
이를 위임한 객체에서 다루는게 맞을것 같습니다.

2024-11-20 13:43 UTC, Minsu-Lee commented on src/main/kotlin/step3/racing/model/car/Car.kt
> +    var attemptCount: Int = DEFAULT_ATTEMPT_COUNT,
Car 의 속성으로 보긴 힘듭니다.
몇번의 수정 이후 제거 대상이 되야 했으나 제거하는게 누락된것 같습니다.
해당 속성 및 테스트코드는 제거하도록 하겠습니다.

2024-11-20 14:29 UTC, Minsu-Lee commented on src/main/kotlin/step3/racing/model/car/Car.kt
> +    private val numberGenerator: NumberGenerator = RandomGeneratorFactory.newInstance(),
forwardLimit은 move 메서드의 인자로 전달 받는게 더 적합하단 생각은 들지만
numberGenerator는 별도로 책임을 위임한 객체여서 생성자가 아닌 메서드 인자로 전달받아 처리하는게 맞나 고민됬습니다.
기능 요구사항으로 인해 자주 변동될 가능성이 생길 떄, 수정하는건 어떻게 생각하시나요?

한편으로 생성 방식을 기반으로 테스트 코드를 작성하게 된다면, 매번 새로운 객체를 생성 해야하기에
테스트 코드를 작성하는 기준에서 메서드 인자로 전달받아 처리하는게 더 유연하게 처리할 수 있겠다는 생각도 드네요.

forwardLimit과 numberGenerator는 move 메서드 호출 시, 자주 전달받아 처리할것 같진 않으니
오버로드로 두인자 전달받는 메서드 하나 더 추가해두도록 하겠습니다!

2024-11-20 14:30 UTC, Minsu-Lee commented on src/main/kotlin/step3/racing/model/generator/RandomGeneratorImpl.kt
> +internal class RandomGeneratorImpl(private val range: IntRange) : NumberGenerator {
그렇지 않아도, ParameterizedTest로 min, max를 전달받아 범위 내에 난수가 발생하는지 체크하는 테스트코드 추가해두었습니다. 👍