[step5] car racing game(refactor)
next-step/kotlin-racingcar pull request #1718
Opened 2024-11-19 07:31 UTC by jihoi-kang

안녕하세요.
마지막 과제도 잘 부탁드립니다 :)

2024-11-20 07:28 UTC, namjackson requested changes
안녕하세요 지회님! 
5단계 잘해주셨네요,
크게 코멘트 드릴부분은 없으나,
몇가지 도전해볼법한 코멘트 남겼으니, 확인해주세요 :)

2024-11-20 07:28 UTC, namjackson commented on src/main/kotlin/racing/controller/RacingGameController.kt
> +        }
여전히 Controller에 많은 책임이 있는것 같아요 :)
레이싱 게임이 몇라운드가 실행되는지는 
Controller가 아닌 RacingGame의 관심사는 아닐까요 ?

2024-11-20 07:28 UTC, namjackson commented on src/test/kotlin/racing/domain/AdvanceCheckerTest.kt
> +        val advanceChecker = AdvanceChecker(object : NumberGenerator {
행위를 잘분리해주셨네요! 
AdvanceChecker를 인터페이스로 추상화한다면,
조금더 테스트가 용이해 보여요 :)

2024-11-20 07:28 UTC, namjackson commented on src/test/kotlin/racing/domain/RacingGameTest.kt
> +class RacingGameTest {
라운드만큼 실행되고,
라운드별로 데이터를 그려야하는 부분은 어떻게 테스트할수 있을까요?

2024-11-21 05:50 UTC, jihoi-kang commented on src/main/kotlin/racing/controller/RacingGameController.kt
> +        }
[07b73b7](https://github.com/next-step/kotlin-racingcar/pull/1718/commits/07b73b7d3df69e84746f35e01881323a6066b39f)
Controller에 책임을 줄이기 위해 Racing Game에 `play()` 를 추가하여 Controller에서 호출하게 구현하였습니다.
그런데 원래 로직에서는 각 라운드가 끝날 때마다 결과를 콘솔에 호출해주고 있습니다. RacingGame 내에 View 의존성을 가지지 않게 하기 위해 기록하는 객체(`AdvanceRecorder`)를 하나 추가하였습니다.

2024-11-21 05:50 UTC, jihoi-kang commented on src/test/kotlin/racing/domain/AdvanceCheckerTest.kt
> +        val advanceChecker = AdvanceChecker(object : NumberGenerator {
[56cd080](https://github.com/next-step/kotlin-racingcar/pull/1718/commits/56cd080a12880e45a3459e42987fb06e8e7d9ed4)

2024-11-21 10:35 UTC, namjackson requested changes
안녕하세요! 지회님!
피드백 적용 잘해주셨네요! 
몇가지 추가적인 코멘트 남겼으니 확인해주세요 :)

2024-11-21 10:35 UTC, namjackson commented on src/main/kotlin/racing/controller/RacingGameController.kt
> +        ResultView.printWinner(racingGame.getWinner())
racingGame 내부를 변경하고, 
racingGame의 값을 받아오는 구조라면,
순서가 중요할거같아요 :)

`gameResult = racingGame.play()`
같은 구조로 리턴값으로 객체를 던져주는 방법도 유의미할거같아요 :)

2024-11-21 10:35 UTC, namjackson commented on src/main/kotlin/racing/controller/RacingGameController.kt
> +        ResultView.printWinner(racingGame.getWinner())
Winner 관련 책임도 리턴되는 GameResult에게 위임해볼수도 있을거같아요! 
이부분은 개인적인 의견이니 참고만해주셔도 좋을거같아요 :)

2024-11-21 10:35 UTC, namjackson commented on src/main/kotlin/racing/domain/AdvanceRecorder.kt
> +            add(AdvanceRecord(cars = copy(cars)))
매번 toMutableList로 변경후 수정을 하는 구조네요! 
records를 불변컬렉션으로 선언한 의미가없을거같아요! 

차라리 records를 mutable컬렉션으로 관리하거나 
records 를 일급 컬렉션으로 관리해도 좋을거 같아요 :)

2024-11-21 10:35 UTC, namjackson commented
피드백 잘 작성해주셔서, 추가로 크게 피드백 드릴부분이 없는거 같아요! 
아마 다음 리뷰요청시 미션이 종료될거같아요! 
수정하고싶으신 부분이나, 도전하고 싶으신부분이 있으면 수정해주시면 좋을거같아요 :):)

2024-11-21 14:00 UTC, jihoi-kang commented on src/main/kotlin/racing/controller/RacingGameController.kt
> +        ResultView.printWinner(racingGame.getWinner())
[adf80b0](https://github.com/next-step/kotlin-racingcar/pull/1718/commits/adf80b0c6f4a44edb935633022e6a4b95bc0a61a)
좋은 생각인거 같아 추가하였습니다. 제안 감사합니다 :)

2024-11-21 14:00 UTC, jihoi-kang commented on src/main/kotlin/racing/domain/AdvanceRecorder.kt
> +            add(AdvanceRecord(cars = copy(cars)))
[fbf7716](https://github.com/next-step/kotlin-racingcar/pull/1718/commits/fbf7716422156d715413a44539f630cdcef206ec)

2024-11-21 18:12 UTC, namjackson approved these changes
안녕하세요 지회님! 
자동차 미션 고생하셨습니다! 
미션은 여기서 마무리하도록 할게요! 
한주간 고생많으셨습니다! :)

2024-11-21 18:12 UTC, merged