4단계 - 자동차 경주(우승자)
next-step/kotlin-racingcar pull request #1735
Opened 2024-11-22 10:40 UTC by eshc123

## 주요 내용
- UI 로직과 핵심 로직을 분리하고자 하였고, 차수마다 전체 자동차의 현재 위치를 보여주기 위해 RaceHistory 클래스를 추가하였습니다.
- 분리 작업 이후에도 startRacing 에 대해 테스트 코드를 작성하고자 하였는데 마땅히 테스트할 대상이 도저히 정해지지 않아 이번에도 작성하지 못했습니다..

2024-11-23 08:51 UTC, Rok93 requested changes
석준님 4단계 구현 잘해주셨습니다 👍👍 
몇몇 코멘트 남겨두었으니, 확인해서 반영 부탁드릴게요. 🙏

2024-11-23 08:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +    fun startRacing() {
> 분리 작업 이후에도 startRacing 에 대해 테스트 코드를 작성하고자 하였는데 마땅히 테스트할 대상이 도저히 정해지지 않아 이번에도 작성하지 못했습니다..

아래의 테스트를 작성해보시면 좋을 것 같습니다. 

startRacing 진행 후,  각각의 car의 position이 얼마인지를 검증하는 테스트

2024-11-23 08:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RandomNumberGenerator.kt
> +object RandomNumberGenerator {
RaceConditionChecker이 자신의 역할을 수행하기위해서는 이 0~9 사이의 랜덤한 숫자를 뽑아내는 로직도 필요한데요. 
이를 외부에서 주입받기보다는 RaceConditionChecker 내부에 이 로직이 있는게 조금 더 응집도가 높다고 생각되는데요. 
석준님의 생각은 어떠신가요? 😃

2024-11-23 08:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/Car.kt
> +        private const val MINIMUM_NAME_LENGTH = 5
상수 네이밍이 의도하는바를 제대로 표현하지 못하는 것 같아요. 🤔
`최소 이름 길이`라는 표현이 의도하신 네이밍이 맞으실까요?

2024-11-23 08:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/Car.kt
> +        require(name.length <= MINIMUM_NAME_LENGTH) { "자동차 이름은 5자를 초과할 수 없습니다." }
사소할 수 있지만 이렇게 예외 메시지의 최대 이름 제한 길이도 상수로 주입해준다면 상수 값이 변경되도 따로 예외 메시지를 수정해줄 필요가 없을 것 같아요. 😃

```suggestion
        require(name.length <= MINIMUM_NAME_LENGTH) { "자동차 이름은 ${MINIMUM_NAME_LENGTH}자를 초과할 수 없습니다." }
```

2024-11-23 08:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/CarFactory.kt
> +    fun generateCars(carNames: List<String>) = List(carNames.size) { Car(carNames[it]) }
작성하신 방식이 잘못된 것은 아니지만 
이 부분은 아래와 같이 변경하는게 조금 더 깔끔하지 않을까싶어요. 😃
```suggestion
    fun generateCars(carNames: List<String>) = carNames.map { Car(it) }
```

2024-11-23 08:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +        return cars.filter { it.position == maxPosition }.map { it.name }
[객체에게 메시지를 보내](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/)보면 어떨까요? 😃

2024-11-23 08:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +        return cars.filter { it.position == maxPosition }.map { it.name }
추가적으로 컬렉션 확장 함수들을 체이닝으로 호출하는 경우에 대해서는 
한 줄에 하나의 메서드를 호출하도록 수정해주시면 조금 더 코드의 가독성이 높아진다고 생각해요. 😃

```suggestion
        return cars.filter { it.position == maxPosition }
            .map { it.name }
```

이렇게 했을 때의 장점은 아래와 같이 호출하는 컬렉션 확장함수가 많은 경우에는 IDE에서도 각 함수 호출에 대한 결과 타입을 알기쉽게 보여줘서 코드 작성시에도 도움을 받을 수 있어요.

<img width="541" alt="image" src="https://github.com/user-attachments/assets/69bf672d-f0ee-4179-af92-283c21525013">

2024-11-23 08:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +            raceHistories = raceHistories + RaceHistory(cars)
`raceHistories`를 프로퍼티로 둘 필요 없이  startRacing 메서드 내부에서 `List<RaceHistory>` 변수를 만든 뒤, 반환 값으로 `List<RaceHistory>`를 반환해줘도 되지 않을까요? 🤔

그렇다면 불필요한 프로퍼티를 하나 줄일 수 있을 것 같아요! 😃

2024-11-23 08:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +    fun getRacingChampions(): List<String> {
`getXXX` 와 같은 네이밍은 언뜻보면 연산 작업없이 프로퍼티를 외부로 꺼내는 getter처럼 보일 수 있다고 생각해요. 😃
어떤 행위를 하는지 네이밍적으로 조금 더 드러나도록 변경해보시면 좋을 것 같습니다. 😉

2024-11-23 08:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +    fun getRacingChampions(): List<String> {
RaceManager는 레이스를 수행하는 역할을 이미 가지고있는데요. 
우승자를 판별하는 역할을 RaceHistory 객체에게 위임해보면 어떨까요? 🤔

2024-11-24 12:43 UTC, eshc123 commented on src/main/kotlin/racingcar/domain/RandomNumberGenerator.kt
> +object RandomNumberGenerator {
랜덤한 숫자를 뽑아내는 것은 직접적으로 컨트롤 할 수가 없다라고 생각을 해서 랜덤한 숫자를 뽑아내는 부분을 따로 분리를 했었는데 RaceConditionChecker 내에서 구현을 해도 테스트 유연하면서도 말씀해주신 응집도도 높을 것 같아서 더 적절할 것 같다는 생각이 듭니다!

2024-11-24 12:45 UTC, eshc123 commented on src/main/kotlin/racingcar/domain/Car.kt
> +        private const val MINIMUM_NAME_LENGTH = 5
최대 이름 길이 인데 작성할 때 집중을 못하고 잘못 작성한 것 같습니다. 수정하겠습니다!

2024-11-24 12:48 UTC, eshc123 commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +        return cars.filter { it.position == maxPosition }.map { it.name }
알려주신 링크 페이지 참고해서 개선해보도록 하겠습니다!

2024-11-24 15:12 UTC, eshc123 commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +    fun startRacing() {
궁금한 점이 있습니다. startRacing 내부에서 횟수만큼 랜덤한 숫자를 통해 각각의 car의 position을 정하게 되는데 랜덤하게 숫자를 정하다보니 position이 어떤 값으로 나올지 예상할 수가 없어서 테스트를 작성하기 어렵다고 생각이 드는데 혹시 다른 접근이 필요할까요? 혹은 랜덤한 숫자를 주입하는 것이 startRacing 내부가 아니라 외부에서 주입을 하는 방향으로 생각을 해야하는 것인지도 고민이 되었습니다.

2024-11-25 03:13 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +    fun startRacing() {
> 궁금한 점이 있습니다. startRacing 내부에서 횟수만큼 랜덤한 숫자를 통해 각각의 car의 position을 정하게 되는데 랜덤하게 숫자를 정하다보니 position이 어떤 값으로 나올지 예상할 수가 없어서 테스트를 작성하기 어렵다고 생각이 드는데 혹시 다른 접근이 필요할까요? 

네 맞습니다! startRacing 메서드는 이런 랜덤값과 같이 제어할 수 없는 요소로인해서 테스트가 어려운 상태인데요. 🥲
저희는 이렇게 테스트하기 어려운 요소를 최대한 외부로 분리해내서 테스트할 수 있는 영역을 최대한 확보해야해요! 

> 혹은 랜덤한 숫자를 주입하는 것이 startRacing 내부가 아니라 외부에서 주입을 하는 방향으로 생각을 해야하는 것인지도 고민이 되었습니다.

네, 위에서도 살짝 언급했지만 `테스트할 수 있는 영역을 확보할 수 있는 방법`은 `테스트하기 어려운 요소를 외부로 분리해내는 것`입니다. 외부로 어떻게 추출할 수 있을지 또 테스트를 어떻게 할지...? 등을 고민해보시면서 리팩터링해보시면 좋을 것 같습니다. 
(이 부분은 한번만 더 고민해보시면 좋을 것 같아서 이번에는 힌트만 살짝 드렸는데, 고민해보셨음에도 좋은 방법이 떠오르지 않으신다면 추가적으로 질문주시면 다음에는 제가 생각했던 방식을 공유드려보겠습니다. 😉)

아래의 영상을 참고해보시면 이해하시는데 도움이되실 것 같습니다. 😃
[무엇을 테스트할 것인가? 어떻게 테스트할 것인가? (권용근)](https://youtu.be/YdtknE_yPk4?t=639)

2024-11-25 03:31 UTC, Rok93 approved these changes
석준님 피드백 반영 잘해주셨네요. 👍👍 
이정도면 4단계는 충분한 것 같아서 이만 머지하도록하겠습니다. 

몇몇 코멘트 남겨두었으니 다음 단게 진행하실 때, 같이 확인해서 반영 부탁드릴게요. 🙏

2024-11-25 03:31 UTC, Rok93 commented on src/main/kotlin/racingcar/RacingCarGame.kt
> +        ResultView.printRacingChampion(raceHistories.last().findRacingChampions())
사실 잘 생각해보면 `RaceHistory`의 findRacingChampions은 우승자를 찾는 것이 아닐 수 있다고 생각해요. 
예를들면 `moveCount`가 3인데,  1번째 혹은 2번째 RaceHistory를 가져올 경우에는 findRacingChampions의 결과가 우승자가 아닐 수도 있을 것 같아요. 

즉, 우승자를 판별하기 위해서는 가장 마지막 레이스 히스토리에서 우승자를 판별해야하는데요. `raceHistories.last().findRacingChampions()` 이런 역할을 할 수 있는 (List<RaceHistory>를 상태로 가지는) `RaceResult` 객체에게 우승자 판별하는 역할을 위임할 수 있을 것 같아요.

2024-11-25 03:31 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RaceHistory.kt
> +        return cars.filter { maxPositionCar.position == it.position }
전에 드렸던 [코멘트](https://github.com/next-step/kotlin-racingcar/pull/1735#discussion_r1855147770)는 
`maxPositionCar.position == it.position` 이 로직을 Car 객체의 메서드로 추출해서 호출해보자는 의미였어요. 😃

2024-11-25 03:31 UTC, merged