[step4] 4단계 - 자동차 경주(우승자)
next-step/kotlin-racingcar pull request #1744
Opened 2024-11-23 08:13 UTC by Saerang

잘부탁드립니다!

일부 코멘트가 숨겨져서라고 하셨는데 못찾겠네요..
혹시 다시한번 알려주실 수 있을까요?

2024-11-23 14:40 UTC, vsh123 commented
석균님 안녕하세요~! 
우선 숨겨진 코멘트 링크 드립니다 :) 

https://github.com/next-step/kotlin-racingcar/pull/1680#discussion_r1845411678

https://github.com/next-step/kotlin-racingcar/pull/1680#discussion_r1845411805

2024-11-23 14:52 UTC, vsh123 requested changes
재석님 안녕하세요!!

2024-11-23 14:52 UTC, vsh123 commented on src/main/kotlin/racingcar/RacingCar.kt
> +    val usernames: String = readln()
kotlin은 [타입추론](https://kotlinlang.org/spec/type-inference.html)을 지원하기 때문에 타입을 명시하지 않아도 괜찮은데요!! 

석균님 코드에서는 타입을 명시한것과, 그렇지 않은 것이 섞여있는 것 같아요.

혹시 타입을 명시하시는 본인만의 기준이 있을까요?

2024-11-23 14:52 UTC, vsh123 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    constructor(usernames: String) : this(usernames.split(",").map { username -> Car.init(username) })
`","` 상수화가 가능해보이네요 :)

2024-11-23 14:52 UTC, vsh123 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +class Cars(private var cars: List<Car>) {
cars 프로퍼티가 `var`로 선언되어야할 이유가 있을까요?

2024-11-23 14:52 UTC, vsh123 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    constructor(usernames: String) : this(usernames.split(",").map { username -> Car.init(username) })
* Cars를 생성할 때는 부생성자로 생성
* Car를 생성할 때는 팩터리메서드로 생성
하셨는데, 부생성자로 생성할때와 팩터리 메서드로 생성할때는 어떠한 기준을 가지고 계신가요?

2024-11-23 14:52 UTC, vsh123 commented on src/main/kotlin/racingcar/RacingCar.kt
> +fun gameResult(cars: Cars) {
private 선언이 가능해 보여요!

2024-11-23 14:52 UTC, vsh123 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    fun cars(): List<Car> {
cars프로퍼티를 private으로 막고 함수 `cars()`를 만들어주신 이유가 있을까요?

2024-11-23 14:52 UTC, vsh123 commented on src/main/kotlin/racingcar/domain/Winners.kt
> +    fun getWinners(): List<String> {
`getWinnerNames()`가 함수가 수행하는 역할에 더 맞지 않나 싶어요!

2024-11-23 14:52 UTC, vsh123 commented on src/main/kotlin/racingcar/domain/Car.kt
> +class Car(private var position: Position, private var username: String) {
username이 `var`일 필요가 있을까요??

2024-11-23 14:55 UTC, Saerang commented on src/main/kotlin/racingcar/RacingCar.kt
> +    val usernames: String = readln()
아 대부분 명시하는 것을 선호합니다. 
타입추론 안되어있는건 단축키 써서 만들어졌을 때 인 것 같네요..

2024-11-23 14:56 UTC, Saerang commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    constructor(usernames: String) : this(usernames.split(",").map { username -> Car.init(username) })
자바처럼 생성자 찾다가 저게 있다는게 보여서 썻는데..
팩터리메서드는 보통 이름을 만들고 싶을 때 사용하는데, 
이부분에서도 팩토리메서드로 하는게 좋을수도 있겠네요.

2024-11-23 15:03 UTC, Saerang commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    fun cars(): List<Car> {
내부 변수를 그냥 노출하고 싶진 않았는데, 이름이 똑같아서 사용하는데 있어서 별 차이는 없긴 합니다.

2024-11-23 15:10 UTC, Saerang commented on src/main/kotlin/racingcar/RacingCar.kt
> +    val usernames: String = readln()
명시를 안하면 intellij나 tool에서 보는건 편한데, PR을 올리다보면 해당 페이지에서 보는데 너무 어렵더라구요

2024-11-24 04:52 UTC, vsh123 approved these changes
안녕하세요~!
피드백 빠르게 잘 반영해주셨네요 :) 

DM으로 몇가지 코멘트와 생각을 전달드렸으니, 마지막스테에서 고민해보시구 적용해보시면 좋을 것 같습니다!!

다음 스텝에서 뵐게요!

2024-11-24 04:53 UTC, merged