[Step4] racing car
next-step/kotlin-racingcar pull request #1757
Opened 2024-11-25 11:54 UTC by sksowk156

늦어서 죄송합니다!!

지난번에 주신 피드백을 반영하여 수정을 완료하였으나, 리뷰어님께서 의도하신 대로 수정되었는지 확신이 서지 않습니다.

특히, `DetermineCarMovementUseCase` 클래스에서 숫자가 4를 초과하는지 여부만 반환하는 것이 도메인 로직에 해당하는지, 아니면 `car.move()` 메서드를 호출하여 `Car` 객체를 반환하는 것까지 도메인 로직에 포함되는지 판단하기가 어려웠습니다. 현재는 숫자가 4를 초과하는지 여부만 반환하도록 구현하였지만, 여전히 고민이 되는 것 같습니다. 책임 분리를 어떤 기준으로 해야 할지 리뷰어님의 조언을 구하고 싶습니다.

이번 리뷰도 잘 부탁드립니다. 감사합니다.

2024-11-26 01:20 UTC, sah3122 requested changes
우승자 구현 잘해주셨습니다 👍 
몇가지 생각거리를 남겨두었는데 확인 부탁드려요 😄

2024-11-26 01:20 UTC, sah3122 commented on src/main/kotlin/carracinggame/feature/CarRacingGameViewModel.kt
> +        }
자동차의 이름이 5자를 초과할수 없다는 유효성 검사가 외부에 있다면 어떤 문제점이 있을까요 ? 
코멘트 남겨주신것을 보니 도메인 로직이 어디에 위치해야하는지에 대한 고민이 있으신것 같은데 상태값을 가지고있는 클래스에 위치할수 있도록 반영해보세요 😄

2024-11-26 01:20 UTC, sah3122 commented on src/main/kotlin/carracinggame/feature/CarRacingGameViewModel.kt
> +                car
개인적으론 자동차가 움직이는것만 도메인 로직에 포함할수도, 움직임에 대한 상세한 요구사항을 도메인 로직에 포함할수도 있을것 같습니다. 
자동차는 항상 움직이는것이 아니라 어떤 조건에 의해 움직인다는것은 도메인 로직에 포함하는것이 좋을것 같아요 😄

2024-11-26 01:20 UTC, sah3122 commented on src/main/kotlin/carracinggame/core/model/Car.kt
> +    fun move() {
외부에서 move 함수를 호출하는경우 항상 거리가 증가하는것은 움직임을 결정하는 로직이 분산되었다고 볼수 있습니다. 
움직임을 결정하는 책임을 자동차 클래스가 가질수 있도록 변경해보세요 😄

2024-11-26 01:20 UTC, sah3122 commented on src/main/kotlin/carracinggame/core/model/Car.kt
> +data class Car(
data class 로 정의해주신 이유가 있을까요 ?

2024-11-26 01:20 UTC, sah3122 commented on src/main/kotlin/carracinggame/core/model/GameState.kt
>  data class GameState(
개인적으로 생각하기에 구현의 복잡도가 높다고 생각합니다. 
State와 ViewModel과 같은 클래스를 사용하지 않고 조금더 단순하게 리팩토링해보는건 어떨까요 ?

2024-11-27 18:00 UTC, sksowk156 commented on src/main/kotlin/carracinggame/feature/CarRacingGameViewModel.kt
> +        }
아하...!!! 객체의 상태를 외부에서 변경하면 상태가 일관적으로 유지되지 않을 확률이 높아질 것 같습니다!! 또한 객체지향적으로도 여러 원칙들을 위반하게 되는 것 같습니다! 뭔가 지극히 당연한 것을 당연하게 생각해내지 못한 것 같네요... :sob:

2024-11-27 18:01 UTC, sksowk156 commented on src/main/kotlin/carracinggame/feature/CarRacingGameViewModel.kt
> +        }
감사합니다!! :blush::blush:

2024-11-27 18:03 UTC, sksowk156 commented on src/main/kotlin/carracinggame/feature/CarRacingGameViewModel.kt
> +                car
그런 것 같습니다😃  상세한 설명 정말 감사합니다!!

2024-11-27 18:08 UTC, sksowk156 commented on src/main/kotlin/carracinggame/core/model/Car.kt
> +data class Car(
이건 viewmodel를 사용할 때 car 객체들의 distance가 변경될 때 매번 copy해서 쓰려고 하다보니 data class로 선언했던 것 같습니다! 현재는 distance를 업데이트해서 사용하는 식으로 변경하여 class로 다시 변경했습니다!

2024-11-27 18:10 UTC, sksowk156 commented on src/main/kotlin/carracinggame/core/model/GameState.kt
>  data class GameState(
네! 최대한 불필요해 보이는 클래스 및 객체들을 전부 지우고 다시 수정해보았습니다!
리뷰 부탁드립니다 🙇🙇

2024-11-28 02:36 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
단순해진 구조가 인상적이네요 😄 
몇가지 고민거리를 추가로 남겨두었는데 다음 미션을 진행하며 확인 부탁드립니다 !

2024-11-28 02:36 UTC, sah3122 commented on src/main/kotlin/carracinggame/core/model/Car.kt
> +    private val determineCarMovementUseCase: DetermineCarMovementUseCase,
useCase를 프로퍼티로 가지고 있는것과 메서드 실행 시점에 파라미터로 받는것중 useCase의 변화에 유연하게 대처할수 있는 방법이 무엇인지 고민해보세요 😄

2024-11-28 02:36 UTC, sah3122 commented on src/main/kotlin/carracinggame/core/model/Car.kt
> +        private set
https://kotlinlang.org/docs/coding-conventions.html#class-layout 
선언 순서가 잘못된것 같습니다 ~!

2024-11-28 02:36 UTC, sah3122 commented on src/main/kotlin/carracinggame/core/model/Car.kt
> +        if (determineCarMovementUseCase()) {
도메인 로직으로 정의 👍

2024-11-28 02:36 UTC, sah3122 commented on src/main/kotlin/carracinggame/core/util/CarFactory.kt
> +class CarFactory(
현시점에는 Factory 클래스가 크게 필요하지 않을것 같은데 조금더 단순한 구조를 정의해보는건 어떨까요 ?

2024-11-28 02:36 UTC, sah3122 commented on src/main/kotlin/carracinggame/core/domain/FindWinnersUseCase.kt
> +        return cars.filter { it.totalDistance == maxDistance }
UseCase를 기능단위로 분리하여 하나의 클래스로 정의해주셨는데 `cars.findWinner()`와 같이 도메인 로직을 외부에서 구현하지 않고 메시지를 던지는 구조로 변경해보는것을 권장 드립니다 😄

2024-11-28 02:36 UTC, merged

2024-11-28 14:26 UTC, sksowk156 commented on src/main/kotlin/carracinggame/core/model/Car.kt
> +    private val determineCarMovementUseCase: DetermineCarMovementUseCase,
아 그렇네요! 어차피 controller에서 받는데 굳이 여기서 억지로 받을 필요가 없었던 것 같습니다. Car 생성자 파라미터로서도 어색한 것 같고... 꼼꼼한 리뷰 정말 감사합니다!!

2024-11-28 14:26 UTC, sksowk156 commented on src/main/kotlin/carracinggame/core/model/Car.kt
> +        private set
😭

2024-11-28 14:27 UTC, sksowk156 commented on src/main/kotlin/carracinggame/core/util/CarFactory.kt
> +class CarFactory(
넵! 수정해보겠습니다!