[Step5] 자동차경주 리팩토링
next-step/kotlin-racingcar pull request #1765
Opened 2024-11-27 14:45 UTC by eunice0035

4단계에서 주신 피드백을 적용해 보았습니다.
잘부탁드립니다~

2024-11-27 15:05 UTC, Flamme1004K requested changes
안녕하세요!

4단계 피드백 반영 잘 해주셨어요! 코멘트 남겼으니, 반영 후 5단계 미션 진행해 보시죠~

화이팅입니다!

2024-11-27 15:05 UTC, Flamme1004K commented on src/main/kotlin/racinggame/domain/Game.kt
> +    }
피드백 반영 좋네요~ 👍

2024-11-27 15:05 UTC, Flamme1004K commented on src/main/kotlin/racinggame/domain/Game.kt
> +                car.moveCar(RandomNumberGenerator.generate())
피드백 반영 잘 해주셨어요! RandomNumberGenerator.generate() 전체가 car.moveCar로 들어갔네요. 

만약 class Game(val cars: List<RacingCar>, val totalGameTurn: Int) 의 프로퍼티에 RandomNumberGenerator가 들어가면 어떨까요? 

프로퍼티에 RandomNumberGenerator가 들어가면 어떠한 장점이 있을지 고민해 보시겠어요?

2024-11-28 12:30 UTC, eunice0035 commented on src/main/kotlin/racinggame/domain/Game.kt
> +                car.moveCar(RandomNumberGenerator.generate())
Game 클래스 인스턴스만 만들때 한번만 RandomNumbmerGenerator 인스턴스를 생성할 수 있는 거 같습니다. 현재 코드에서는 for문을 돌때마다 RandomNumber 인스턴스를 생성하게 되는 문제점이 있을 것 같습니다..?

2024-11-28 12:32 UTC, eunice0035 commented
MVC 패턴을 적용하기 위해서 observer를 구현해 보았습니다. 현재 Game의 로직과 ResultView의 로직이 혼합되어 있는 것 같아서, 해당 부분을 분리해 보았습니다.

2024-11-28 15:06 UTC, Flamme1004K commented on src/main/kotlin/racinggame/domain/Game.kt
> +                car.moveCar(RandomNumberGenerator.generate())
오 좋아요! 추가로 새로운 테스트를 만들 수 있지 않을까요? Game을 통해서 미리 애견 된 생성기를 생성자로부터 넣으면, startTurn을 통한 우승자 테스트도 만들 수 있어보여요!

2024-11-28 15:17 UTC, Flamme1004K requested changes
안녕하세요!

5단계 미션 매우 잘 해주셨습니다! 몇 가지 코멘트 남겼으니, 확인 부탁드릴게요!

다음 리뷰 요청에는 머지하도록 하겠습니다!

감사합니다!

2024-11-28 15:17 UTC, Flamme1004K commented on src/main/kotlin/racinggame/domain/Game.kt
> +    var onTurnCompleted: ((Int, List<RacingCar>) -> Unit)? = null
좋은 접근 방식이네요! 단, nullable 한 부분을 지워보는 건 어떨까요?

2024-11-28 15:17 UTC, Flamme1004K commented on src/main/kotlin/racinggame/domain/Game.kt
> +    private val generator: RandomNumberGenerator,
이제 RandomNumberGenerator를 전략 패턴을 사용하여 인터페이스화 시키면 어떨까요? 

- https://ssdragon.tistory.com/140

2024-11-29 11:31 UTC, eunice0035 commented on src/main/kotlin/racinggame/domain/Game.kt
> +    var onTurnCompleted: ((Int, List<RacingCar>) -> Unit)? = null
non-null 값으로 수정했습니다!
여기서 몇가지 질문이 있는데요.

1. observer를 사용하는 것 말고도 다른 좋은 방법이 있을까? 안드로이드 개발에서는 주로 Observer 를 많이 사용해서, 해당 방법말고는 다른 방법이 생각나지 않더라구요.

2. 저는 callback 함수를 GameClass의 파라미터로 받지 않고 var 값으로 해서 외부에서 수정하도록 수정했습니다. 이번에 해당 부분을 파라미터로 받으려고 하니, 클래스의 파라미터가 3개로 늘어나서 좀 지저분해 보인다는 느낌을 받았습니다. 어떤 것이 더 좋은 코드 같은지 형준님의 의견도 궁금합니다.

2024-11-29 11:38 UTC, eunice0035 commented on src/main/kotlin/racinggame/domain/Game.kt
> +    private val generator: RandomNumberGenerator,
RandomNumberStrartegy 인터페이스를 구현하고 적용해보았습니다!
> 오 좋아요! 추가로 새로운 테스트를 만들 수 있지 않을까요? Game을 통해서 미리 예견 된 생성기를 생성자로부터 넣으면, startTurn을 통한 우승자 테스트도 만들 수 있어보여요!

이전에 코멘트 해주신 부분에 대해서 궁금한 점이 있습니다~

전략패턴을 사용해서 RandomNumberGenerator를 테스트 코드에서 override해서 특정 자동차가 우승하게 만들 수 있다는 것이 가능하다는 것을 알았습니다.

혹시 전략패턴말고 다른 방법으로 우승자 테스트를 할 수 있나요? 
제가 생각해 본 부분은 Mockk을 사용하여, RandomNumberGenerator를 2개 만들어서 (1개는 우승자용: 전진만 가능, 1개는 나머지 용: 전진 불가능) 테스트 하는 것인데. Mockk을 이용한 테스트 방식이 형준님이 주신 코멘트 의도와 맞는지 궁금합니다

2024-11-29 11:40 UTC, Flamme1004K commented on src/main/kotlin/racinggame/domain/Game.kt
> +    private val generator: RandomNumberGenerator,
저는 Mockk를 사용하지 않고, 전략 패턴을 통해 테스트 코드를 override해서 특정 자동차가 우승하게 만드는 테스트를 원했어요!

2024-11-29 12:43 UTC, Flamme1004K approved these changes
안녕하세요!

그동안 자동차 미션 잘 해주셨습니다! 이만 머지하도록 하겠습니다.

남은 미션 응원하겠습니다!

2024-11-29 12:43 UTC, merged