[Step2] 문자열 계산기
next-step/kotlin-racingcar pull request #189
Opened 2021-03-02 15:35 UTC by mjung1798

문자열 계산기 구현입니다.

enum의 Minus 식을 처리하는 부분을 어떻게해야 깨끗하면 짤 수 있는지 궁금합니다.

2021-03-03 14:31 UTC, LeeYounghyeon requested changes
안녕하세요 :)

몇가지 코멘트 남겼으니 확인 부탁드립니다.

2021-03-03 14:31 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/domain/Expression.kt
> +        }
`require`를 사용해보는건 어떨까요?
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require.html

2021-03-03 14:31 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/domain/Expression.kt
> +            val operator = Operator.of(tokens[i])
`operator`는 kotlin 예약어이니 사용을 지양해주세요 :)

2021-03-03 14:31 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/domain/Operator.kt
> +            Operand(num1.number * num2.number)
```suggestion
            Operand(num1.number / num2.number)
```
이렇게 되어야 할 것 같네요 :)
각각의 연산자들에 대해 테스트도 추가해주는게 어떨까요?

2021-03-03 14:31 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/domain/Operator.kt
> +import java.lang.IllegalArgumentException
```suggestion
import kotlin.IllegalArgumentException
```
kotlin에서 제공하는 `IllegalArgumentException`이 존재합니다 :)

2021-03-03 14:31 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/domain/Operator.kt
> +        }
```suggestion
        return values()
                .find { it.value == operator } ?: throw IllegalArgumentException("올바르지 않은 연산자 입니다")
        }
```
이렇게 하면 더욱 간결하게 나타낼 수 있을 것 같아요!

2021-03-03 14:31 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/domain/Operator.kt
> +            if (num2.number == 0.0)
`0.0`이 매직 넘버 처럼 보이네요 :)
상수화해서 의미를 분명하게 드러내면 좋을 것 같습니다.

https://www.slipp.net/questions/356
https://stackoverflow.com/questions/3518938/what-are-magic-numbers-in-computer-programming

2021-03-03 14:31 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/domain/Expression.kt
> +    fun execute(): Operand {
`execute`는 `Calculator`가 가지고 있어야 할 책임 같아 보여요 :)

2021-03-03 14:31 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/Runner.kt
> +    val result = Calculator().calculate(inputExpression)
생성과 동시에 메서드 호출이 이루어지고 있으니
`object class`나 `companion object`함수로 정의하면 어떨까요?

2021-03-03 14:31 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/domain/Operator.kt
> +    MULTIPLE("*", { num1, num2 -> Operand(num1.number * num2.number) }),
Operator overloading을 사용해보면 어떨까요?
https://kotlinlang.org/docs/operator-overloading.html#binary-operations

2021-03-03 14:56 UTC, mjung1798 commented on src/main/kotlin/calculator/Runner.kt
> +    val result = Calculator().calculate(inputExpression)
메인함수로 실행을 위해서 사용되는건데 굳이 그렇게 해야 하나 싶었습니다.
사실상 하나의 테스트코드를 실행시키는 것과 별반 다르지 않아보여서요.
또한 그렇게 하나의 object class로 묶에되면 입력값이 주어지기 전에는 실행을 멈출 수 없는 함수가 되다보니 

test 폴더로 묶어서 테스트하기도 굉장히 어렵다고 생각이 듭니다.

2021-03-03 15:02 UTC, mjung1798 commented on src/main/kotlin/calculator/domain/Expression.kt
> +    fun execute(): Operand {
음 저는 Calculator는 하나의 스트링을 받아서 그 결과를 도출하는 것
Expression은 클래스 내부에서 정의된 객체로 입력, 출력을 하는 것으로 책임을 분리했는데,
말씀하신대로 객체의 이름에서 역할에 혼돈을 주는 것 같네요.
기존의 Calculator > StringCalculator
Expression > Caclulator
로 변경하면 조금 명확해 질 것 같습니다.

2021-03-03 15:06 UTC, mjung1798 commented on src/main/kotlin/calculator/domain/Operator.kt
> +            if (num2.number == 0.0)
음.. PI = 3.14, GRAVITY = 9.8 과 같이 의미를 갖는 값은 저도 매직넘버를 사용해야하는 것에 동의를 합니다.
그러나 산술 연산에서 예외가 난다고 알고있어 상식으로 받아들여지는 0까지 매직넘버로 빼는 것은 오히려 헷갈리지 않나 싶습니다..ㅠㅠ 
- 0인 경우에 예외 > 나누기이니까 산술 에러 처리를 한거구나
- MAGIC_NUMBER인 경우에 예외 > 찾아보니 0 > 나누기라서 0에 대한 산술 에러 처리를 한거구나
위 상황과 같이 오히려 0이라는 특수한 경우이기 때문에 숫자 자체가 좀 더 의미를 잘 들어낼 수 있지 않을까 싶었습니다.

2021-03-03 15:33 UTC, mjung1798 commented
@LeeYounghyeon 영현님 코드리뷰 감사합니다 :) 아무래도 자바에 많이 익숙하다보니 코틀린스러운 코드를 짜는게 아직 미숙하네요ㅠ 덕분에 실습하면서 알아갑니다! 특히나 operator overloading은 오오.. 정말 놀랐네요!!

2021-03-05 09:27 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/domain/Operator.kt
> +            if (num2.number == 0.0)
민정님이 남겨주신 코멘트에 대해 충분히 동의합니다. :)

이 부분은 각자만의 스타일이 있기 때문에 피드백 반영안해주셔도 될 것 같아요 :)
납득이 되었습니다 👍

2021-03-05 09:29 UTC, LeeYounghyeon commented on src/main/kotlin/calculator/Runner.kt
> +    val result = Calculator().calculate(inputExpression)
>메인함수로 실행을 위해서 사용되는건데 굳이 그렇게 해야 하나 싶었습니다.
생성과 동시에 메서드 호출이라는 관점보다는 해당 구현을 실제로 실행을 하기위한 메인 러너로 봤습니다.
영현님 말씀대로 생성과 동시에 메서드 호출을하면서 저희 미션의 요구사항을 실행시키는 용도로 사용이 될 수 있겠으나.
그렇게 한다면 해당 메서드를 호출하게되면 어떤 프로그램이든 유저의 입력을 받아야되게 됩니다.

Calculator가 `delimiter` 프로퍼티를 들고 있기 때문에 companion object, object 등으로 구현했을 때 `delimiter`를 입력 받아야 된다는 걸까요? 현재 구현된 코드로 보아 `delimiter`를 잘못입력해도 `IllegalArgumentException`이 나는걸로 보입니다.  Calculator가 delimiter 프로퍼티를 들고있지 않아도 좋을 것 같아요. 만약 의도하신대로 `" "`가 아닌 다른 구분 문자를 입력해도 연산이 가능하도록 구현한다면 구분 문자를 `calculate(input: String, delimiter: String)` 이렇게 구현해주셔야 의도한대로 정상 작동할 것 같아요. 그래서 이부분에서는 companion object, object를 사용해도 문제가 없어 보입니다 :)

>이번 요구사항이 라이브러리 클래스를 만드는 것이라면 정현님 말씀에 동의하지만, 지금과 같이 실행 후 특정 패턴의 유저 인풋을 받고 아웃풋을 도출하는 프로그램성이라면 싱글턴 메서드보다는 실행함수로 있는게 어떨까 싶습니다.

싱글턴 메서드가 아닌 실행함수로 들고있을 때의 이점이 무엇이 있을까요? 
이 부분은 궁금해서 질문 드립니다 :)

>또한 그렇게 하나의 object class로 묶게되면 입력값이 주어지기 전에는 실행을 멈출 수 없는 함수가 되다보니
해당 메서드에 대한 test를 아래 테스트 케이스로 추가를 해야 할 것 같은 느낌이 들고..
test 폴더로 묶어서 테스트하기도 굉장히 어려워 받아들이기 힘드네요

이부분도 1번과 연관되어 있는 것 같아요. 의도하신대로 구현한다면 `input.split(" ")` 테스트와 `calculate()` 테스트는 당연히 따로 분리되어 있어야 할 것 같아요. 

제가 답변에 대한 이해를 잘한건지 모르겠네요 😭

2021-03-05 09:31 UTC, LeeYounghyeon approved these changes
안녕하세요 :)

피드백 반영해주시고 다시 한번 리뷰 요청을 해주셔야합니다.

다음부터는 반영 후 리뷰 요청 꼭 부탁드립니다 :)

피드백 반영 잘해주셨네요 👍 

코멘트에 대한 답변도 남겼으니 확인부탁드립니다.

다음 미션을 위해 머지할게요 :)

2021-03-05 09:31 UTC, merged

2021-03-18 14:33 UTC, mjung1798 commented on src/main/kotlin/calculator/Runner.kt
> +    val result = Calculator().calculate(inputExpression)
아 헉 이걸 지금봤네요..!! 꼼곰히 읽어보니 제가 잘못이해했어요. 
저는 영현님이 Runner.kt 파일을 싱글턴으로 만들라고 하신줄 알고, 실행 클래스인데 왜 싱글턴으로 만들어야하지..?? 라고 생각을 하고 말한거였는데, 지금 영현님이 달아주신 피드백을 보니 영현님은 Calculator를 싱글턴으로 만들라고 하신거군요!! 넵넵 제가 봐도 Calculator는 object 클래스로 만드는게 더 좋은 것 같습니다. 상태값을 들고있지 않은 클래스이니까요. 헉.. 엄청난 커뮤니케이션 오류가 있었군요...😭😭 
꼼꼼하게 얘기해주셔서 감사합니다 :)