[step5] 자동차 경주(리팩터링) 구현입니다.
next-step/kotlin-racingcar pull request #219
Opened 2021-03-07 15:05 UTC by SGKIM94

안녕하세요 리뷰어님.! 🙇‍♂️ 
벌써 마지막 step이네요..!!

제가 우선 MVC라고 생각하는 디렉터리 구조로 변경은했지만..
요구사항이 이러한 형태가 맞는지 확실하진 않네요 ..ㅠㅠ 😢 

혹시 잘못된 부분이 있다면 피드백 부탁드리겠습니다.!! 😃 
감사합니다.!!

2021-03-08 10:46 UTC, vsh123 requested changes
상구님 안녕하세요!
벌써 마지막 단계네요!! 💯 

몇가지 수정하면 좋겠다라는 부분을 코멘트로 남겼습니다
확인부탁드릴게요!

2021-03-08 10:46 UTC, vsh123 commented on src/main/kotlin/domain/racingcar/OverallResult.kt
> +    fun forEach(action: (Records) -> Unit) {
forEach보다 조금더 명확한 네이밍을 해주는게 어떨까요?
이 경우 외부에서 action을 주입받기보다는 스스로가 action을 하면 어떨까요?

2021-03-08 10:46 UTC, vsh123 commented on src/main/kotlin/domain/racingcar/OverallResult.kt
> +class OverallResult(private val records: List<Records>) {
Recode - List<Recode> - List<Recodes> = recodes?  라고 되어있는데요! 네이밍을 조금 더 신경 써보면 어떨까요?

2021-03-08 10:46 UTC, vsh123 commented on src/main/kotlin/domain/racingcar/Records.kt
>      fun forEach(action: (Record) -> Unit) {
여기도 조금더 명확한 네이밍을 해주는게 어떨까요?

2021-03-08 10:46 UTC, vsh123 commented on src/test/kotlin/view/ResultViewTest.kt
> +class ResultViewTest {
View에 대한 테스트가 필요할까요?

2021-03-08 10:46 UTC, vsh123 commented on src/main/kotlin/view/ResultView.kt
> +            printName(it.name)
이름과 자동차 출력정보를 하나의 print로 합칠 수 있을까요?

2021-03-09 08:25 UTC, SGKIM94 commented on src/main/kotlin/domain/racingcar/OverallResult.kt
> +    fun forEach(action: (Records) -> Unit) {
이 부분에 대해 궁금한 사항이 있습니다.
혹시 자동차를 출력하는 action 을 OverallResult 가 스스로 하는 것을 말씀하시는 걸까요?? 😮

2021-03-09 08:25 UTC, SGKIM94 commented on src/main/kotlin/domain/racingcar/OverallResult.kt
> +class OverallResult(private val records: List<Records>) {
앗.. 수정해서 피드백 반영했습니다. 🙇‍♂️

2021-03-09 08:28 UTC, SGKIM94 commented on src/test/kotlin/view/ResultViewTest.kt
> +class ResultViewTest {
ResultView 가 `joinToWinners()` 에 대한 역할을 가지면서 테스트를 추가하게 되었습니다.
테스트가 가능한 구조라면 하는게 맞다고 생각을 했었는데요.! 
혹시 필요하지 않다고 생각하시는 이유가 어떤 것 인지 궁금합니다. 

피드백 부탁드립니다 .감사합니다.! 😃

2021-03-09 08:28 UTC, SGKIM94 commented on src/main/kotlin/view/ResultView.kt
> +            printName(it.name)
출력 정보를 합쳐서 controller 에서 사용하도록 수정했습니다.! 🔧

2021-03-09 08:35 UTC, SGKIM94 commented on src/main/kotlin/domain/racingcar/RacingCars.kt
>              cars.forwardAllByCondition(makeRandomsToRacing(cars.getSize()))
forwardAllByCondition() 가 finishRound 정보를 리턴하려면
finishRound 에 대한 역할도 forwardAllByCondition() 가 해야되는 것이기 때문에

위치를 전진시키는 역할 뿐만아니라 레이싱 결과를 끝내고 생성하는 역할도 같이하게 되어
`너무 많은 일을 하는게 아닐까?` 라고 생각했습니다.!

혹시 이에 대한 의견이 있으시면 피드백 부탁드리겠습니다! 🙇‍♂️

2021-03-09 08:36 UTC, SGKIM94 commented on src/test/kotlin/domain/racingcar/CarTest.kt
> +package domain.racingcar
앗.... 차마 놓친 부분이네요 수정했습니다.!!

2021-03-09 08:53 UTC, SGKIM94 commented on src/main/kotlin/domain/racingcar/Reception.kt
> +package domain.racingcar
앗 😮 Reception 은 사용자 입력 부라고 생각하여 controller 로 이동시켰습니다.!

수업 내용을 다시 복기하는 시간을 가지도록 하겠습니다. ✋

2021-03-09 08:59 UTC, SGKIM94 commented on src/main/kotlin/domain/racingcar/Records.kt
>      fun forEach(action: (Record) -> Unit) {
위 `RacingCars` 의 피드백 내용에 대한 질문과 동일합니다. ✋

2021-03-09 11:32 UTC, vsh123 commented on src/main/kotlin/domain/racingcar/Position.kt
> +class Position(position: Int = START_POSITION) {
우선 저는 자동차 경주게임에서 제일 작은 객체는 `자동차`라고 생각해요!
그래서 position을 클래스로 한번 감쌌을 때의 이점이 무엇인지 잘 모르겠어요.

그래서 위치에 대해서 `자동차`가 오너십이 있다고 생각해요.
자동차가 Position에게 `나 한칸 움직여줘!`라고 하는것도 뭔가 이상하다구 생각하구요
그래서 Position은  `forward()`라는 함수를 가지고 있지만 객체라는 생각이 들지 않았습니다!

또한 상구님이 구현하신 equals/hashcode는 결국 `데이터가 같으면 같은 객체다`라고 선언을 하신 것과 같다고 생각을 했고, 이게 data class와 다를바 없다고 생각했어요.

혹시 이에 대해서 이해가 안가시거나 또 다른 의견이 있으시면 DM이나 코멘트 부탁드릴게요!! :)

2021-03-09 11:33 UTC, vsh123 commented on src/main/kotlin/domain/racingcar/Position.kt
> +class Position(position: Int = START_POSITION) {
우선 저는 자동차 경주게임에서 제일 작은 객체는 자동차라고 생각해요!
그래서 position을 클래스로 한번 감쌌을 때의 이점이 무엇인지 잘 모르겠어요.

그리구 위치라는 상태값에 대해 자동차가 오너십이 있다고 생각해요.
자동차가 Position에게 나 한칸 움직여줘!라고 하는것도 뭔가 이상하다구 생각하구요

또한 상구님이 구현하신 equals/hashcode는 결국 데이터가 같으면 같은 객체다라고 선언을 하신 것과 같다고 생각을 했고, 이게 data class와 다를바 없다고 생각했어요.

혹시 이에 대해서 이해가 안가시거나 또 다른 의견이 있으시면 DM이나 코멘트 부탁드릴게요!! :)

2021-03-09 12:00 UTC, vsh123 requested changes
상구님 안녕하세요!
답변을 보니 코드에 대해서 많은 생각을 하신게 느껴졌습니다 👍 

남겨주신 질문에 대한 답변과, 조금 더 개선하면 좋을 부분을 코멘트 드렸습니다.
확인 부탁드릴게요!

2021-03-09 12:00 UTC, vsh123 commented on src/main/kotlin/domain/racingcar/Cars.kt
>      fun forwardAllByCondition(conditions: List<Int>) {
요기서 조금만 더 나아가보죠!
지금은 외부에서 condition을 만들어서 주입해주는데, `randomToRacing()`과 같이 자동차가 협력할 수 있는 객체(또는 함수)를 넘겨주는 건 어떨까요?

[전략 패턴](https://gmlwjd9405.github.io/2018/07/06/strategy-pattern.html)에 대해서 공부해보고 적용해봐도 좋을 것 같아요!

2021-03-09 12:00 UTC, vsh123 commented on src/main/kotlin/domain/racingcar/OverallResult.kt
> +    fun forEach(action: (Records) -> Unit) {
앗!! 이부분에 대해서 제가 조금 혼란이 있게 피드백을 드렸던 것 같아요!!!

지금 작성한 `forEach`는 결국 외부에서 OverallResult의 프로퍼티를 제어할 수 있는 길을 열어준 것 과 다른게 없어보여요!!
그래서 해당 함수를 없애고 View에서 get하여 출력하면 어떨까 하는 의견이였습니다 :)

2021-03-09 12:00 UTC, vsh123 commented on src/main/kotlin/domain/racingcar/RacingCars.kt
>              cars.forwardAllByCondition(makeRandomsToRacing(cars.getSize()))
객체간 서로 협력을 할때는 요청을 하면 응답이 있어야한다고 생각해요!!
이런 관점에서 저는 Cars에게 `모든 차를 움직여줘!`라고 요청을 보냈을 때, Cars가 `움직인 결과야`하고 리턴해주는 건 자연스럽다고 생각을 해요!

2021-03-09 12:00 UTC, vsh123 commented on src/main/kotlin/domain/racingcar/Records.kt
>      fun forEach(action: (Record) -> Unit) {
넵 위에 답변을 드렸습니다!

2021-03-09 12:00 UTC, vsh123 commented on src/test/kotlin/view/ResultViewTest.kt
> +class ResultViewTest {
저는 테스트코드에 대한 유지보수도 비용이라고 생각해요!
그리고 View에 대한 요구사항은 도메인의 비즈니스 로직보다 더 많이 변할 수 있다고 생각하구요!!
그래서 View를 테스트하는 비용이 과연 효율적일까 하는 의문이 있습니다 :)

이건 제 생각일 뿐이니 상구님의 의견도 충분히 존중합니다! :)

2021-03-10 12:49 UTC, SGKIM94 commented on src/main/kotlin/domain/racingcar/OverallResult.kt
> +    fun forEach(action: (Records) -> Unit) {
아하..!! 제가 이해를 잘못했었네요 ㅠㅠㅠ 😢 
말씀해주신 내용처럼 프로퍼티가 제어된다면 문제가 된다고 생각합니다.
따라서 get 할 수 있도록 변경하고 해당 기능을 View 가 하도록 해서 캡슐화가 이뤄지도록 수정했습니다.!

2021-03-10 13:13 UTC, SGKIM94 commented on src/main/kotlin/domain/racingcar/Position.kt
> +class Position(position: Int = START_POSITION) {
피드백 주셔서 감사합니다.! 🙇‍♂️ 
말씀해주신 내용에 대해서 고민을 해봤습니다.

`제일 작은 객체는 자동차` 라는 말씀에 대해서 고민을 해봤을 때
`Position` 도 `위치`라는 상태를 가지며 `0` 이라는 초기 값을 가지고 `foward` 라는 행위를 가지기 때문에 객체라고 생각을 했습니다.
 그래서 저는 `Car` 도 `Position` 이라는 상태를 가지는 것이기 때문에 가장 작은 것은 `Position` 이 아닐까? 라고 생각했습니다.

Position을 클래스로  감쌌을 때의 이점은 현재는 자동차만 있지만 나중에 비행기나 오토바이가 생긴다면 위치라는 것에 대한 기준(전진은 한칸만 해야된다는 것과 시작이 0이라는 것 등.. - Number 를 별도로 감싸는 것과 비슷한 느낌)을 몰라도 된다는 점이라고 생각했습니다.

자동차를 전진 시켜줘! 라는 것은 자동차가 Position에게 나 위치를 한칸 이동시켜줘! 라는 문맥이 맞다고 생각했습니다.

data class 를 사용한다고 해서 객체가 되지 않는 것은 아니기 때문에 단지 `toString() ` 이나 `copy()`처럼 불필요한 접근을 허용하는게 아닐까.. 라는 의문에서 질문을 드렸던 것이었습니다. 🙌

혹시 이 부분에 대해서 제가 잘못 이해하고 있는 부분이 있다면 피드백 부탁드리겠습니다.! 🙇 
감사합니다. 😃

2021-03-11 00:17 UTC, vsh123 approved these changes
상구님 안녕하세요!!
커밋을 잘 나누어주셔서 커밋을 따라가며 리팩터링 과정을 볼 수 있어서 즐거웠습니다!! 💯 

이번 미션은 여기서 마무리하도록 할게요!!
수고하셨습니다! 다음 미션도 화이팅 하세요~!!

2021-03-11 00:17 UTC, vsh123 commented on src/test/kotlin/domain/racingcar/MockConditions.kt
> +        return conditions.pop()
`pop`을 위해서 LinkedList로 선언하신 걸까여?

2021-03-11 00:17 UTC, vsh123 commented on src/main/kotlin/domain/racingcar/Cars.kt
> +    fun forwardAllByCondition(randomConditions: Conditions): Records {
return 값이 생겼으니 Records기반으로 테스트 코드를 재구성해도 좋을 것 같아요!

2021-03-11 00:17 UTC, merged

2021-03-11 01:57 UTC, SGKIM94 commented on src/test/kotlin/domain/racingcar/MockConditions.kt
> +        return conditions.pop()
넵 맞습니다.! 🙌

2021-03-11 01:57 UTC, SGKIM94 commented on src/main/kotlin/domain/racingcar/Cars.kt
> +    fun forwardAllByCondition(randomConditions: Conditions): Records {
넵 개선해 보겠습니다.!! 감사합니다. 😃