[Step 5] 자동차 경주(리팩터링)
next-step/kotlin-racingcar pull request #231
Opened 2021-03-13 08:26 UTC by ohgillwhan

ResultView에서 allHistories.last()로 winner를 구했는데 리팩터링 하여 Winner를 객체로 빼서 처리하도록 하였습니다.

2021-03-14 09:37 UTC, wotjd243 requested changes
피드백을 잘 반영해 주셨습니다. 👍 
조금 더 고민해 보면 좋을 것 같은 의견을 남겨 놓았으니 충분히 고민하고 도전해 보세요!
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2021-03-14 09:37 UTC, wotjd243 commented on src/main/kotlin/car/domain/Car.kt
> +    fun move(energy: Int) {
개발자는 코드를 작성하면서 확장성(scalability)에 대한 고민을 항상 해야 합니다. 자동차가 다양한 방법으로 움직일 수 있게 구현해 보세요.

2021-03-14 09:37 UTC, wotjd243 commented on src/main/kotlin/car/domain/CarMoveHistory.kt
> +        private const val POSITION_EXPRESSION = "-"
만약 요구 사항에서 자동차의 이동을 "-"가 아닌 "*" 혹은 자동차 그림으로 표현하기로 하였다면 어떻게 될까요? Model은 View의 요구 사항에 따라 계속 바뀌는 것이 맞을까요? 쉽지 않겠지만 고민해 보고 코드로 표현하면 좋을 것 같아요!

2021-03-14 09:37 UTC, wotjd243 commented on src/main/kotlin/car/domain/CarMoveHistoryCollection.kt
> +}
아래의 코드로 개선해 보면 어떨까요?

```suggestion
class CarMoveHistoryCollection(val moveHistories: List<CarMoveHistory>)
```

2021-03-14 09:37 UTC, wotjd243 commented on src/main/kotlin/car/domain/Cars.kt
> +class Cars(private val cars: List<Car>, private val energyProvider: EnergyProvider = RandomEnergyProvider()) {
컬렉션을 포함한 클래스는 반드시 다른 멤버 변수가 없어야 합니다. 아래 코멘트에 대해 고민해 봐요.
https://github.com/next-step/kotlin-racingcar/pull/185#discussion_r587212683

2021-03-14 09:37 UTC, wotjd243 commented on src/main/kotlin/car/domain/Cars.kt
> +    private val _histories: MutableList<CarMoveHistoryCollection> = ArrayList()
코틀린은 읽기 전용 컬렉션과 변경 가능한 컬렉션을 구별해 제공합니다. 아래의 코드로 개선해 보면 어떨까요?

```suggestion
    private val _histories: MutableList<CarMoveHistoryCollection> = mutableListOf()
```

2021-03-14 09:37 UTC, wotjd243 commented on src/main/kotlin/car/domain/Cars.kt
> +        }.toList()
아래의 코드로 개선해 보면 어떨까요?

```suggestion
        }
```

2021-03-14 09:37 UTC, wotjd243 commented on src/main/kotlin/car/domain/EnergyProvider.kt
>      fun getEnergy(): Int
함수 대신 프로퍼티를 사용하면 어떨까요? 아래의 글이 도움 되면 좋겠어요.
https://blog.kotlin-academy.com/kotlin-should-i-define-function-or-property-6786951da909

2021-03-14 09:37 UTC, wotjd243 commented on src/main/kotlin/car/domain/Winners.kt
> +            .max()!!
아래의 코드로 개선해 보면 어떨까요?

```suggestion
            .max() ?: 0
```

2021-03-14 09:37 UTC, wotjd243 commented on src/main/kotlin/car/domain/Winners.kt
> +        return winners.joinToString(",") { toString() }
아래의 코드로 개선해 보면 어떨까요?

```suggestion
        return winners.joinToString(",")
```

2021-03-14 09:37 UTC, wotjd243 commented on src/test/kotlin/car/domain/CarTest.kt
> +        val car: Car = Car(CarName("오길환"))
생성자의 수가 늘어날수록 클래스를 사용하기 위한 유연성은 높아집니다.

```suggestion
        val car: Car = Car("오길환")
```

2021-03-14 13:20 UTC, ohgillwhan commented on src/test/kotlin/car/domain/CarTest.kt
> +        val car: Car = Car(CarName("오길환"))
이 부분에 고민을 조금 했는데, String 인자를 받는게 더 유연하겠네요!! 감사합니다

2021-03-14 13:47 UTC, ohgillwhan commented on src/main/kotlin/car/domain/EnergyProvider.kt
>      fun getEnergy(): Int
이 부분에서 코틀린의 놀라움을 한번 더 느낍니다!

2021-03-19 09:02 UTC, wotjd243 requested changes
피드백을 잘 반영해 주셨습니다. 👍 
추가로 고민해 보면 좋을 것 같은 의견을 남겨 놓았으니 충분히 고민하고 도전해 보세요!
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2021-03-19 09:02 UTC, wotjd243 commented on src/main/kotlin/car/domain/Car.kt
> +    fun isWinner(winnerPosition: Int): Boolean {
함수 이름을 한 단계 더 추상화하면 어떨까요?

2021-03-19 09:02 UTC, wotjd243 commented on src/main/kotlin/car/domain/history/CarMoveHistory.kt
> +        const val DEFAULT_POSITION_EXPRESSION = "-"
아래 코멘트에 대해 고민해 봐요.
https://github.com/next-step/kotlin-racingcar/pull/231#discussion_r593870975

2021-03-19 09:02 UTC, wotjd243 commented on src/main/kotlin/car/domain/winner/WinnerCollection.kt
> +        .filter { it.isWinner(carCollection.maxPosition) }
`carCollection.maxPosition`에 대한 결과 값을 지역 변수에 담아 사용하는 것과 그렇지 않은 것은 어떤 차이가 있을까요?

2021-03-19 09:02 UTC, wotjd243 commented on src/main/kotlin/car/view/ResultView.kt
> +        val list: List<CarMoveHistoryCollection> = carCollection
의미를 담고 있는 변수 이름이 좋겠죠?

2021-03-19 09:02 UTC, wotjd243 commented on src/main/kotlin/car/view/ResultView.kt
> +    private fun printCarPositionHistory(carMoveHistoryCollectionList: List<CarMoveHistoryCollection>, index: Int) {
변수 이름에 자료형은 사용하지 않는 것이 좋아요.

2021-03-19 09:02 UTC, wotjd243 commented on src/main/kotlin/car/view/ResultView.kt
> +            println()
아래의 코드로 개선해 보면 어떨까요?

```suggestion
            println(pretty)
```

2021-03-19 09:02 UTC, wotjd243 commented on src/test/kotlin/car/domain/winner/WinnerCollectionTests.kt
> +        }
매번 이렇게 `move()`를 사용해야 할까요? 어떻게 하면 더 손쉬운 테스트를 할 수 있을까요?

2021-03-19 09:02 UTC, wotjd243 commented on src/test/kotlin/car/view/printer/CarMoveHistoryPrettyPrinterTest.kt
> +    fun `이쁘게 나오는지 확인해보자`() {
처음 보는 사람도 쉽게 이해할 수 있는 이름으로 변경한다면 어떻게 변경할 수 있을까요?

2021-03-20 06:36 UTC, ohgillwhan commented on src/main/kotlin/car/domain/winner/WinnerCollection.kt
> +        .filter { it.isWinner(carCollection.maxPosition) }
현재 상태이면은 이중 반복문 처럼 리소스가 많이 낭비가 되겠네요~~

2021-03-20 17:03 UTC, wotjd243 requested changes
피드백을 전부 잘 반영해 주셨습니다. 💯 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
다음 리뷰 요청 때는 Merge 하도록 하겠습니다.

2021-03-20 17:03 UTC, wotjd243 commented on src/main/kotlin/car/domain/winner/Winners.kt
> +            it.position == maxPosition
아래 코멘트에 대해 고민해 봐요.
https://github.com/next-step/kotlin-racingcar/pull/185#discussion_r587212723

2021-03-20 17:03 UTC, wotjd243 commented on src/test/kotlin/car/domain/winner/WinnersTests.kt
> +    private fun Car(carName: String, position: Int): Car {
가짜 생성자(fake constructor) 👍

2021-03-21 05:32 UTC, ohgillwhan commented on src/main/kotlin/car/Application.kt
> +    val resultView = ResultView(cars, input)
기존에는 ResultView에서 우승자를 가려내는 코드가 작성이 되어있었습니다.
그렇게 되면은 ResultView는 View의 역할을 하지 않고, SRP를 지키지 않는것 같습니다.

2021-03-21 05:32 UTC, ohgillwhan commented on src/main/kotlin/car/Application.kt
> +    val resultView = ResultView(cars, input)
Winners가 바뀌게 되면 View도 바뀌게 되는 문제가 있지 않을까 싶어요!

2021-03-24 02:40 UTC, wotjd243 requested changes
코드를 새로 다 바꿨네요. 쉽지 않은 결정이었을 텐데 고생 많으셨습니다. 👍 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
다음 리뷰 요청 때는 Merge 하도록 하겠습니다.

2021-03-24 02:40 UTC, wotjd243 commented on src/main/kotlin/car/Application.kt
> +    val game: Game = Game(cars)
아래 코멘트에 대해 고민해 봐요.
https://github.com/next-step/kotlin-racingcar/pull/158#discussion_r584423599

```suggestion
    val game = Game(Cars(CarNames(names.splitNameBySplitter())))
```

2021-03-24 02:40 UTC, wotjd243 commented on src/main/kotlin/car/view/input/CarNamesInput.kt
> +class CarNamesInput(names: String?) {
데이터 클래스를 사용하면 컴파일러가 `equals()`, `hashCode()`, `toString()`, `copy()` 등을 자동으로 생성해 줍니다. 아래의 글이 도움 될 거예요.
https://kotlinlang.org/docs/data-classes.html

2021-03-24 02:40 UTC, wotjd243 commented on src/main/kotlin/car/view/input/CarNamesInput.kt
> +        const val NAMES_SPLITTER = ","
아래 코멘트에 대해 고민해 봐요.
https://github.com/next-step/kotlin-racingcar/pull/185#discussion_r587212651

2021-03-24 02:40 UTC, wotjd243 commented on src/main/kotlin/car/view/input/TryCountInput.kt
> +            return toIntOrNull() ?: throw IllegalArgumentException("실행 횟수는 숫자여야 합니다.")
아래의 코드로 개선해 보면 어떨까요?

```suggestion
            return this?.toIntOrNull() ?: throw IllegalArgumentException("실행 횟수는 숫자여야 합니다.")
```

2021-03-24 05:32 UTC, okk1119 commented on src/main/kotlin/car/Application.kt
> +    val game: Game = Game(cars)
아, 이 부분은 다시한번 새겨야겠어요~

2021-03-24 09:35 UTC, wotjd243 approved these changes
수많은 피드백을 반영하고자 대단히 고생 많으셨습니다. 💯 
"인내는 쓰고 열매는 달다."라는 말처럼 정말 달콤한 열매를 수확했길 바랍니다.
이만 Merge 하겠습니다.

2021-03-24 09:35 UTC, merged