Step5 - 자동차경주(리팩토링)
next-step/kotlin-racingcar pull request #355
Opened 2021-10-31 02:49 UTC by seosh817

안녕하세요~ 마지막 리뷰 잘 부탁드립니다.

이번 스텝에서는 저번 스텝 피드백 반영과 몇가지 변수에 대한 일급 컬렉션 적용을 했습니다.

특히, 일급컬렉션은 처음 사용해봐서 잘 사용한건지 감이 잘 안오는데 고칠점이 있는지 확인해주시면 감사하겠습니다!

2021-10-31 12:12 UTC, ka0oll requested changes
리팩토링 잘 해주셨습니다. 👍 

몇가지 코멘트 남깁니다. 고민해보시고 다시 리뷰 요청주세요.
마지막까지 화이팅 입니다.

2021-10-31 12:12 UTC, ka0oll commented on src/main/kotlin/racingcar/car/Cars.kt
> +value class Cars(private val _cars: List<Car>) {
여기도 backing field가 필요없어보여요!

2021-10-31 12:12 UTC, ka0oll commented on src/main/kotlin/racingcar/manager/RacingManagerFactory.kt
>      }
carManager가 engine을 관리하는게 어떨까요? 고민해보세요!

https://betterprogramming.pub/the-3-types-of-dependency-injection-141b40d2cebc

2021-10-31 12:12 UTC, ka0oll commented on src/main/kotlin/racingcar/car/Cars.kt
> +value class Cars(private val _cars: List<Car>) {
일급 컬력션 👍

2021-10-31 12:12 UTC, ka0oll commented on src/main/kotlin/racingcar/car/CarName.kt
> +package racingcar.car
도메인 패키지내에 car,engine등 패키지를 구분하는게 어떨까요. 관리에 더 용이할거같아요!

ex) racingcar.domain.car , racingcar.domain.engine

2021-11-03 11:26 UTC, seosh817 commented on src/main/kotlin/racingcar/car/Car.kt
> +data class Car(private val _Car_name: CarName = CarName(""), private var _position: Int = 0, private var carEngine: CarEngine) {
헉.. 저렇게 되어있는지 몰랐네요.. lint에서도 안 걸리는군요. 수정했습니다.
6a22cfa

2021-11-03 11:27 UTC, seosh817 commented on src/main/kotlin/racingcar/manager/RacingManager.kt
> +        get() = _cars
그렇군요. 잘못 알고 있던거 짚어주셔서 감사합니다!
36d69ef

2021-11-03 11:28 UTC, seosh817 commented on src/main/kotlin/racingcar/car/Cars.kt
> +value class Cars(private val _cars: List<Car>) {
수정했습니다.
4195e43

2021-11-03 11:31 UTC, seosh817 commented on src/main/kotlin/racingcar/manager/RacingManagerFactory.kt
>      }
음... CarManager가 engine을 관리하게 되면 모든 Car가 동일한 engine을 사용하게 되지 않나요??? 지금 조건에서는 상관없지만 추후에 다른 engine을 사용하는 Car들이 경주를 하는 조건이 생길 경우에는 다시 바꿔줘야 하지 않을까요???

2021-11-03 11:31 UTC, seosh817 commented on src/main/kotlin/racingcar/car/CarName.kt
> +package racingcar.car
수정했습니다!
4d72348

2021-11-04 14:04 UTC, ka0oll commented on src/main/kotlin/racingcar/manager/RacingManagerFactory.kt
>      }
그럴수도 있겠네요. 같은 car가  movePosition마다 engine을 동적으로 변경 가능하면 좋지 않을까 했습니다. 🤔

2021-11-04 14:10 UTC, ka0oll approved these changes
마지막 단계 까지 고생 많으셨습니다. 👍 

몇가지 간단한 코멘트 남겼으니 확인해주시면 좋을거같아요.
다른 미션들도 화이팅 입니다.

2021-11-04 14:10 UTC, ka0oll commented on src/main/kotlin/racingcar/domain/engine/RacingCarEngineImpl.kt
>  class RacingCarEngineImpl(
RacingCarEngineImpl 보다는 의미있는 네이밍을 고민해보시면 좋을거같아요.

2021-11-04 14:10 UTC, ka0oll commented on src/test/kotlin/racingcar/RacingManagerTest.kt
>  class RacingManagerTest {
테스트들의 패키지도 같이 옴겨주시는게 좋습니다.!

2021-11-04 14:10 UTC, merged