Step5
next-step/kotlin-racingcar pull request #366
Opened 2021-11-13 15:14 UTC by just-hazard

안녕하세요 선호님 🙂
마지막 미션 리뷰도 잘 부탁드리겠습니다! 🙇🏻‍♂️

레이어 나누는 부분은 2,3,4단계 진행중에 구분하면서 진행하여 특별히 작업하지 않았는데 피드백 주실 부분 있다면 말씀해주세요!
그리고 4단계 리뷰에서 코틀린 네이밍 룰 관련 피드백을 주셨는데 사용자로부터 받는 자동차 이름들의 변수를 복수형태로 변경했는데
제가 제대로 이해한게 맞을지 궁금해서 질문드려봅니다! 혹시 베스트 프랙티스가 있다면 알려주시면 감사하겠습니다!

그럼 잘 부탁드려요~

2021-11-14 04:16 UTC, vsh123 requested changes
안녕하세요!!
구현 잘해주셨네요 👍 

질문 주신 내용처럼 복수형으로 네이밍 잘 변경해주셨습니다 💯 
추가적으로 몇가지 코멘트남겨놓았으니 확인부탁드릴게요~~

2021-11-14 04:16 UTC, vsh123 commented on src/main/kotlin/calculator/CalculatorInputValue.kt
> +        private const val NOT_NUMBER_OR_FOUR_ARITHMETIC = "숫자 또는 사칙연산 기호가 아닙니다."
[이 글](https://stackoverflow.com/questions/44038721/constants-in-kotlin-whats-a-recommended-way-to-create-them)을 읽고 상수 선언 위치를 고려해보면 어떨까요?

2021-11-14 04:16 UTC, vsh123 commented on src/main/kotlin/racingcar/domain/Winners.kt
> +    fun winnerNames(cars: List<Car>): List<Car> {
winnerNames라는 함수라면 List<String>으로 카 이름만 리턴해줘도 좋을 것 같아요~

2021-11-14 04:16 UTC, vsh123 commented on src/main/kotlin/racingcar/domain/Winners.kt
> +    ) = cars.filter { it.carPosition() == maxPosition }
carPosition()을 통해 distance를 get하지않고, maxPosition을 넘겨주어 판단하도록 하면 어떨까요?

2021-11-14 04:16 UTC, vsh123 commented on src/main/kotlin/racingcar/view/ResultView.kt
> +    internal fun racingWinnerName(winners: List<Car>): String {
`internal`로 선언하신 이유가 있을까요?

2021-11-14 19:51 UTC, just-hazard commented on src/main/kotlin/calculator/CalculatorInputValue.kt
> +        private const val NOT_NUMBER_OR_FOUR_ARITHMETIC = "숫자 또는 사칙연산 기호가 아닙니다."
컴패니언 객체를 사용하게 되면 새로운 객체를 생성해서 선언 된다는 것을 망각해서 사용하고 있었네요
전역 상수 같은 경우 ErrorMessage 같은 오브젝트에 넣어서 사용하는 것이 좋을 것 같고 이 외 특정 클래스에 국한 되어 있는 상수들은 클래스 파일 내에서 선언해서 사용하는 것이 더 좋아보여서 이렇게 리팩터링 진행하도록 하겠습니다!
혹시 더 좋은 방안이 있으시다면 피드백 주시면 감사하겠습니다 🙇🏻‍♂️

2021-11-14 20:10 UTC, just-hazard commented on src/main/kotlin/racingcar/domain/Winners.kt
> +    fun winnerNames(cars: List<Car>): List<Car> {
리팩터링하면서 놓치고 있었네요 😂
ResultView에서 필요한 값은 결국 우승자 이름들이니까 Car 객체를 모두 넘겨주는 것보다는 필요로 하는 값들만 넘겨주는 것이 더 좋아보이네요 항상 좋은 피드백 감사드립니다 🙂

2021-11-14 20:20 UTC, just-hazard commented on src/main/kotlin/racingcar/domain/Winners.kt
> +    ) = cars.filter { it.carPosition() == maxPosition }
이동거리 도메인에서 해야했던 역할인데 우승자 체크하는 쪽에서 하고 있었네요!
피드백 감사드립니다!

2021-11-14 20:24 UTC, just-hazard commented on src/main/kotlin/racingcar/view/ResultView.kt
> +    internal fun racingWinnerName(winners: List<Car>): String {
테스트를 하기위한 메서드로 선언하기 위해서 internal 접근제어자를 선언 했었습니다
혹시 안 좋은 방법일까요?

2021-11-16 10:50 UTC, vsh123 requested changes
안녕하세요!
피드백 반영 잘해주셨네요!! 💯 

마지막으로 한가지 코멘트드린 부분이 있는데 확인부탁드려요!
다음 요청에는 머지하도록 하겠습니다 :)

2021-11-16 10:50 UTC, vsh123 commented on src/main/kotlin/racingcar/service/Race.kt
> +import racingcar.domain.Car
불필요한 import는 제거해주세요!

2021-11-16 23:01 UTC, just-hazard commented on src/main/kotlin/racingcar/service/Race.kt
> +import racingcar.domain.Car
앗 ktlint를 믿고 확인을 꼼꼼하게 안했네요 😅
꼼꼼한 피드백 감사합니다!

2021-11-17 08:09 UTC, vsh123 approved these changes
안녕하세요!!
첫미션 정말정말 고생많으셨습니다ㅠㅠㅠ

이번 미션은 여기서 머지하도록 하겠습니다.
다음 미션도 화이팅하시길 바랄게요!!! 👍

2021-11-17 08:09 UTC, merged