Step2 - calculator 생성
next-step/kotlin-racingcar pull request #460
Opened 2022-05-07 05:58 UTC by gabstin

# Calculator 로직 생성 

# 내용
- Calculator reduce 확장 함수 https://github.com/next-step/kotlin-racingcar/commit/d4e17379aff505b7300fec767a3153340233ae1e
  - kotlin reduce inline 확장 함수를 참고하여 reduce 로직을 작성했습니다.
  - 최초 계산된 값이 없는 경우 `x + y` 의 첫번째 연산값이 결과값으로 활용됩니다.
  - 두번째 연산부터는 첫번째 연산 결과값이 acc값으로 활용됩니다.

- Calculator 비지니스 로직 생성 https://github.com/next-step/kotlin-racingcar/commit/fed144b8e5d88cb45470d3a07d42549a666895fb
  - 전달받은 expression 값의 validation을 체크합니다.
  - calculate 의 사칙연산은 기능이 단순하여 다른 메소드로 분리하지 않았습니다.

- 테스트케이스 작성 https://github.com/next-step/kotlin-racingcar/commit/ffb659f48c48b94a4fd4611340502b1145eb6ead
  - 사칙연산 동작을 확인합니다.
  - Validation 통과 여부를 확인합니다.

2022-05-07 06:06 UTC, gabstin commented on src/main/kotlin/Calculator.kt
> +}
이번 PR의 핵심 로직으로 kotlin reduce 확장함수를 참고하여 작성했습니다.

`1 + 2 - 3` 의 예시로 설명하겠습니다.

- Sequence<MatchResult>의 결과값은 `1 , + , 2`, ` , - , 3`입니다.
- 첫번째 요소가 empty string이 아닌 경우 선행된 사칙 연산 결과 값이 없기 때문에 본 식의 결과값을 사용합니다.
- 첫번째 요소가 empty string인 경우 선행된 사칙 연산 결과 값이 있기 때문에 accumulator 값을 이전 결과값으로 변경합니다.

2022-05-07 06:06 UTC, gabstin commented on src/main/kotlin/Calculator.kt
> +        requireNotNull(expression) { NOT_EMPTY_OR_NULL_MSG }
전달 받은 expression값 null을 체크합니다.

2022-05-07 06:06 UTC, gabstin commented on src/main/kotlin/Calculator.kt
> +        require(!matches.none()) { NOT_MATCH_EXPRESSION }
expression 규칙에 일치하는 값이 없으면 IllegalArgumentException을 반환합니다.

2022-05-07 06:07 UTC, gabstin commented on src/main/kotlin/Calculator.kt
> +            else -> throw IllegalArgumentException(NOT_DEFINED_OPERATOR)
사칙연산 로직이 간단하여 로직을 따로 분리하지 않았습니다.

2022-05-08 14:32 UTC, malibinYun requested changes
2단계 미션 고생 많으셨습니다. :)
전반적으로 객체 간의 역할 분리가 적게 이루어 진게 많이 아쉬웠습니다.
로직이 간단하더라도 역할을 명확하게 분리할 수 있다면 객체로 분리하는 연습을 추천드립니다. :)
생각해보면 좋을 점들에 코멘트 남겨두었으니 확인하시고 다시 리뷰 요청 주세요!

2022-05-08 14:32 UTC, malibinYun commented on src/main/kotlin/Calculator.kt
> + */
주석으로 코드의 로직을 설명하는 것은 지양해야 합니다.
해당 내용은 클린 코드 서적에도 잘 설명 되어 있는데요, 간단하게 설명드리자면, 주석은 컴파일러가 감지를 할 수 없기 때문에 업데이트가 안될 수 있습니다. 그로 인해 주석이 로직과는 다른 거짓말을 하는 경우가 많아집니다.

구글과 같은 Docs가 매우 관리가 철처한 라이브러리 성격의 프로젝트라면 활용해도 좋으나, 코드 리팩터링이 잦고 시간적 여유가 부족한 프로덕션 코드에서는 그리 좋은 방법이 아니라고 생각합니다 :)

2022-05-08 14:32 UTC, malibinYun commented on src/main/kotlin/Calculator.kt
> +    var accumulator = 0
해당 역할을 하는 객체로 분리해보는 것은 어떨까요?
모든 Sequence\<MatchResult>에 대해서 사용할 수 있는 유틸성 전역 확장 함수가 아니라는 생각이 듭니다.

2022-05-08 14:32 UTC, malibinYun commented on src/main/kotlin/Calculator.kt
> +    fun run(expression: String?): Int {
run 이라는 네이밍은 반환 값을 줄 거라는 느낌을 받지 못했습니다.
오히려 계산기를 초기화하기 위한 사전 작업 메서드라는 생각이 드네요.

calculate 같은 직관적인 네이밍을 사용해보는 것은 어떨까요?

2022-05-08 14:32 UTC, malibinYun commented on src/main/kotlin/Calculator.kt
> +    private const val NOT_DEFINED_OPERATOR = "미정의된 연산입니다."
상수화를 시키셨네요! 👍

2022-05-08 14:32 UTC, malibinYun commented on src/main/kotlin/Calculator.kt
> +            else -> throw IllegalArgumentException(NOT_DEFINED_OPERATOR)
연산자를 찾고, 해당 연산자로 연산도 해야하네요.
"연산자"의 역할을 하는 Enum class를 작성해보는 것은 어떨까요?

2022-05-08 14:32 UTC, malibinYun commented on src/test/kotlin/CalculatorTest.kt
> +    }
덧셈에 해당하는 테스트는 한 번이면 충분하다고 생각합니다.
여러개를 테스트 해보고 싶다면, ParameterizedTest를 활용해보는 것은 어떨까요?

2022-05-08 14:32 UTC, malibinYun commented on src/test/kotlin/CalculatorTest.kt
> +    }
테스트명은 상세하게 적어주어야합니다.
어떤 경우에 어떤 Exception이 발생하는지 코드에 대한 설명서를 적는다고 생각하시면 좋습니다.

또, 한글 또는 영어 하나로 통일하는 것이 좋아보여요 :) 한글로 쓰면 영어를 모국어 만큼 하는 사람이 아닌 이상 더 빠르게 읽고 이해할 수 있다는 장점이 있습니다.

2022-05-08 14:32 UTC, malibinYun commented on src/test/kotlin/CalculatorTest.kt
> +    }
null 과 empty String이 들어가는 케이스는 각각 다른 케이스라고 생각이 듭니다. 각각 분리해보는 것은 어떨까요?

2022-05-08 14:32 UTC, malibinYun commented on src/test/kotlin/CalculatorTest.kt
> +    fun `뺄셈 연산`() {
각 사칙연산에 대한 테스트코드는 있지만,
1. 사칙 연산자가 혼합된 수식
2. 사칙연산자가 아닌 연산자가 들어있는 수식
3. 불완전한 형태의 수식



등의 테스트코드가 없어 보입니다. 자주 발생할 법한 상황에 대한 테스트를 늘려보는 것은 어떨까요?

2022-05-09 23:48 UTC, gabstin commented on src/main/kotlin/Calculator.kt
> + */
@malibinYun 

코드 주석 제거했습니다. https://github.com/next-step/kotlin-racingcar/pull/460/commits/063261f27621134322c9775db4979f153fbbc1af

2022-05-09 23:52 UTC, gabstin commented on src/main/kotlin/Calculator.kt
> +    var accumulator = 0
@malibinYun 

> 해당 역할을 하는 객체로 분리해보는 것은 어떨까요?
> 모든 Sequence<MatchResult>에 대해서 사용할 수 있는 유틸성 전역 확장 함수가 아니라는 생각이 듭니다.


말씀하신 의도를 정확하게 이해하지 못했습니다. 조금 더 자세한 설명 부탁드려도 될까요? :D

- `Sequence<MatchResult>`을 Calculator 객체로 변경하자는 말씀이시라면 Regex 로직에서 반환된 객체가Sequence<MatchResult> 이기 때문에 다른 객체로 변경하기가 어렵습니다. 

- Calculator Class 에 포함된 private 확장함수를 말씀하신것일까요?
```
object Calculator {
    private inline fun Sequence<MatchResult>.reduce(operation: (acc: Int, operator: String, value: Int) -> Int): Int {
       
    }
```

2022-05-10 00:01 UTC, gabstin commented on src/main/kotlin/Calculator.kt
> +    fun run(expression: String?): Int {
@malibinYun 

calculator에 연산처리하는 메소드를 calculate로 사용했습니다. run 이란 메소드가 반환값을 기대하지 못한다는 문제점이 있으니 아래처럼 변경해보았습니다 https://github.com/next-step/kotlin-racingcar/pull/460/commits/08dbfe4c24d3cf4fb127c03f784f2b1d95cd1e4d

AS-IS -> TO-BE
```
run -> calculate
calculate  -> operate
```

2022-05-10 00:15 UTC, gabstin commented on src/main/kotlin/Calculator.kt
> +            else -> throw IllegalArgumentException(NOT_DEFINED_OPERATOR)
@malibinYun 
https://github.com/next-step/kotlin-racingcar/pull/460/commits/a78e5394a21ad68360758b3e02a585f5ddfbf06d

Operator Enum 클래스를 생성한 후 Operator 연산자 변환, 처리하는 내용을 분리했습니다.

2022-05-10 00:16 UTC, gabstin commented on src/main/kotlin/Calculator.kt
> +    fun run(expression: String?): Int {
https://github.com/next-step/kotlin-racingcar/pull/460#discussion_r868634179

코멘트 주신 내용을 변경하면서 method rename도 수정되어 따로 이슈를 처리 하지 않았습니다.

2022-05-10 00:26 UTC, gabstin commented on src/test/kotlin/CalculatorTest.kt
> +    }
@malibinYun 
ParameterizedTest로 수정했습니다. https://github.com/next-step/kotlin-racingcar/pull/460/commits/c27c99c655b271237af77c4dd8ddceeb90e7fd36

2022-05-10 00:28 UTC, gabstin commented on src/test/kotlin/CalculatorTest.kt
> +    }
@malibinYun 개인적으로 서술형 보다 단어의 조합으로도 충분히 유추할 수 있는 내용이라 생각하여 https://github.com/next-step/kotlin-racingcar/pull/460/commits/cc295a068b2102f76c00cacb6f39c7268f239b20 이렇게 한글로 수정했습니다.

2022-05-10 00:30 UTC, gabstin commented on src/test/kotlin/CalculatorTest.kt
> +    }
@malibinYun 

Null, Empty String을 확인하는 테스트 케이스를 분리했습니다. https://github.com/next-step/kotlin-racingcar/pull/460/commits/528d6336a6ae2ad359c981f34a7f29bf14a40f4f

2022-05-10 00:32 UTC, gabstin commented on src/test/kotlin/CalculatorTest.kt
> +    fun `뺄셈 연산`() {
https://github.com/next-step/kotlin-racingcar/commit/c27c99c655b271237af77c4dd8ddceeb90e7fd36 이슈에서 
복합 연산에 대한 테스트 케이스 작성했습니다.
```
    @ParameterizedTest
    @CsvSource(
        "1 + 2 + 3 - 6 + 1 * 10 / 10, 1",
        "10 - 9 * 10 / 10 * 3, 3",
    )
    fun `복합 연산`(expression: String, expect: Int) {
        assertThat(Calculator.calculate(expression)).isEqualTo(expect)
    }
```

2022-05-10 00:32 UTC, gabstin commented
바쁘실텐데 꼼꼼하게 리뷰해주셔서 감사합니다. 🤗

2022-05-10 14:03 UTC, malibinYun commented on src/main/kotlin/calculator/Operator.kt
> +    val value: String,
value라는 이름은 너무 추상적이라는 생각이 들어요.
symbol정도가 적당하다고 생각합니다. 🙂

2022-05-10 14:03 UTC, malibinYun commented on src/main/kotlin/calculator/Operator.kt
> +        const val NOT_SUPPORT_OPERATOR = "지원하지 않는 연산자 입니다."
외부에서 쓰이지 않는 값은 private을 붙여주세요!

2022-05-10 14:03 UTC, malibinYun commented on src/main/kotlin/calculator/Operator.kt
> +enum class Operator(
Operator에 대한 테스트도 필요합니다 :)

2022-05-10 14:03 UTC, malibinYun commented on src/main/kotlin/calculator/Calculator.kt
> +        }
찾은 Operator의 멤버변수인 expression을 직접 꺼내서 사용하기보다, 메시지를 전달해서 결과를 반환 받는 것은 어떨까요?

2022-05-10 14:03 UTC, malibinYun commented on src/main/kotlin/Calculator.kt
> +    var accumulator = 0
해당 메서드는 `문자열 계산기`라는 도메인에 종속적인 메서드입니다.
kotlin의 reduce 메서드는 도메인에 상관 없이 reduce의미 그대로 사용할 수 있지만, 모든 Sequence\<MatchResult>에 대해서 kotlin의 reduce에 해당하는 기능을 수행하지는 않습니다. 메서드명으로 혼돈이 올 수 있습니다.
그렇기 때문에 다른 객체로 분리해 전역적으로 노출시키지 않는 것이 더 낫다고 생각했습니다 :)

Calculator에 문자열을 연산자와 피연산자로 쪼개고, 연산자를 찾고, 계산하는 일 세 가지가 있어서 해당 기능을 각각 객체로 나누어 보는 연습을 해보시기를 의도했습니다 :)

2022-05-10 14:04 UTC, malibinYun approved these changes
피드백 잘 반영하셨네요! 고생 많으셨습니다. 💪
남겨주신 댓글에 코멘트 달아두었습니다. 확인 부탁드려요!
다음 미션을 위해 머지하겠습니다. 이번 피드백은 다음 미션에 반영해주세요~ 🙂

2022-05-10 14:05 UTC, merged