Step2 문자열 계산기
next-step/kotlin-racingcar pull request #481
Opened 2022-05-09 01:51 UTC by ocipap

문자열 계산기 제출합니다!
궁금한 점은 코멘트로 남겨놓도록 하겠습니다! 잘부탁드립니다!

2022-05-09 01:53 UTC, ocipap commented on src/main/kotlin/calculator/Calculator.kt
> +            }
느낌적인 느낌으로 이 부분이 리펙토링이 가능할 것 같은데... 혹시 관련 키워드가 있을까요??!

2022-05-09 01:54 UTC, ocipap commented on src/main/kotlin/calculator/Calculator.kt
> +    private fun calculateByOperation(operation: String, total: Float, num: Float): Float {
해당 함수는 Calculator 애서만 사용할 것 같아 private 로 작성하였고, 따로 테스트를 작성하지 않았습니다!

2022-05-09 01:55 UTC, ocipap commented on src/test/kotlin/study/Person.kt
>  package study
지난번 과제에서 lint 를 안돌리고 제출해서... 같이 수정되었습니다... 🙏

2022-05-09 09:37 UTC, pci2676 requested changes
계산기 미션 수행하느라 고생하셨습니다~!

질문하신 부분에 대해 참고할만한 아티클을 첨부해두었고
코드를 보면서 아쉽다고 생각된 부분에 코멘트를 달아두었습니다!
참고하셔서 수정해보시면 좋을 것 같습니다!

2022-05-09 09:37 UTC, pci2676 commented on src/main/kotlin/calculator/Calculator.kt
> +    private fun calculateByOperation(operation: String, total: Float, num: Float): Float {
음~! 저는 지금 `Calculate`의 역할이 많다고 생각이 듭니다!

연산을 위해 식을 쪼개고
연산을 위한 연산자에 따른 연산식을 찾고
연산자에 따른 연산식을 수행하고
등등등

물론 최종적으로는 `Calculate가`해당 기능을 수행하는 것은 맞지만, 그 구현에 대해 구체적으로 알아야 할 필요가 있을지 의문입니다!
지금 테스트를 작성하셨을때 `+` 와 같은 연산자가 덧셈으로 동작하는지 확인하기 위해 완벽한 식(공백등이 포함 된)을 주입하고 계시지만
사실 이 기능이 제대로 동작하는지 확인하기 위해 필요한 것은 연산자와 두 개의 피연산자 뿐입니다.
그렇다면 완벽한 식을 주입하면서 테스트를 하는것이 자연스럽다고 볼 수 있을까요?

2022-05-09 09:37 UTC, pci2676 commented on src/main/kotlin/calculator/Calculator.kt
> +                throw IllegalArgumentException("사칙연산 기호가 아닙니다.")
exception이 발생하게된 이유를 보다 더 정확히 알게되면 사용자 입장에서 더 좋지 않을까요?

2022-05-09 09:37 UTC, pci2676 commented on src/main/kotlin/calculator/Calculator.kt
> +            }
`enum class`를 이용해보시면 깔끔하게 변경이 가능할 것 같습니다~!
[Java Enum 활용기](https://techblog.woowahan.com/2527/)

2022-05-09 09:37 UTC, pci2676 commented on src/main/kotlin/calculator/Util.kt
> +        fun groupByIsNumber(inputs: List<String>, bool: Boolean): List<String> {
`groupBy`를 적절하게 사용하셨군요! 👍 
다만 외부에서 입력받은 `Boolean`인 `bool`을 이용해서 내부에서 숫자를 꺼내느냐 연산자를 꺼내느냐 구분을 하고 있네요!
하나의 메서드가 두가지 이상의 일을 한다고 보여지는데요.

명확하게 숫자를 찾는 혹은 연산자를 찾는 두개의 메서드로 나누거나
`groupBy`까지만 수행하고 이후에 사용하는쪽에서 그 결과를 사용하는쪽으로 사용하는게 더 나을것 같습니다.

2022-05-09 09:37 UTC, pci2676 commented on src/main/kotlin/calculator/Calculator.kt
> +        if (formula.isNullOrEmpty()) {
1+2+3 과 같은 입력이 들어오는 경우에도 문제가 발생할 것 같습니다.
요구사항 정리가 되어있지 않은것 같은데요!
귀찮더라도 `README.md`에 요구사항을 같이 정리하면서 미션진행을 부탁드리겠습니다~!

2022-05-09 09:37 UTC, pci2676 commented on src/main/kotlin/calculator/Util.kt
> +        fun groupByIsNumber(inputs: List<String>, bool: Boolean): List<String> {
추가로 `Util` 클래스의 생성은 미션을 진행하시면서 최대한 지양하는 연습을 하시는것을 추천드립니다.
이 기능이 클래스로서 필요하다면 해당 책임을 가지고 있는 클래스를 도출하는 것이 낫지 않을까요?

예를 들어 `식`이라는 클래스가 있고 그 클래스가 프로퍼티로 `List`를 가지고 있다면
클래스에게 
- 연산자를 반환하라
- 피연산자를 반환하라

와 같은 메세지를 전달하는 방식으로 변경이 가능해질것 같습니다.

2022-05-09 09:37 UTC, pci2676 commented on src/test/kotlin/calculator/CalculatorTest.kt
> +class CalculatorTest : DescribeSpec({
테스트 케이스를 꼼꼼하게 작성해주셨군요! 👍 
다만 테스트 클래스의 크기가 너무 큰 것 같다고 느껴집니다.

계산기의 역할은 식을 계산하여 결과를 반환한다 인데요.
계산하는 역할을 제대로 수행하는지 확인만 하면 된다고 생각합니다.
그렇게 된다면 각 연산자 종류별로 모든 케이스를 계산기 테스트에서 확인할 필요가 없을 것 같습니다.
지금의 상태라면 연산자의 종류가 늘어나고 100개가 된다면 매번 계산기 테스트 클래스에 케이스가 추가되어야 하고
연산자 테스트를 제외한 다른 테스트 케이스를 확인하기가 힘들어질것 같습니다.
다시말해 다른 누군가 이 클래스의 역할을 파악하기 힘들어질것 같다는 느낌이 듭니다.

프로덕션 코드에 코멘트를 작성해둔것과 같이 동일하게 계산기가 수행하는 기능들을 다른 클래스에 분리하고 그 클래스와 상호작용하는(=메세지를 던지는) 방식으로 리팩토링 해보시는 걸 연습해보시면 좋을 것 같습니다.

2022-05-09 09:37 UTC, pci2676 commented on src/test/kotlin/calculator/CalculatorTest.kt
> +        }
> 더하기를 수행한다.

라는 작명은 덧셈이 정상적으로 작동하는지를 확인하는 것이라고 느껴집니다.
따라서 `calculator.calculate("1 + 2 + 3")` 를 한번더 검사하는것이 의미가 있는지는 의문이 듭니다.
위 연산을 테스트 하신 것은 덧셈을 테스트하는것에 추가하여 덧셈이 연속적으로, 연산자가 연속적으로 동작하는지를 확인하는 것이 아닌가요?

테스트도 단일 책임 원칙을 지켜 한가지의 역할만을 가지고 있어야 그 의미가 잘 전달될 것 같습니다.
```suggestion
        it("더하기를 수행한다.") {
            val calculator = Calculator()

            val result = calculator.calculate("1 + 2")

            result shouldBe 3
        }
```

2022-05-09 09:37 UTC, pci2676 commented on src/test/kotlin/calculator/CalculatorTest.kt
> +        }
마찬가지로 아래 모든 테스트들이 한번에 여러가지 케이스를 테스트하는 것으로 보이는데 해당 부분도 같이 고쳐보신다면 좋을것 같습니다!

2022-05-14 13:43 UTC, ocipap commented
@pci2676  리뷰 사항 반영완료 했습니다! 감사합니다!

2022-05-14 13:44 UTC, ocipap commented
앗 enum 커밋이 반영안되었네요... 잠시만요..!

2022-05-14 14:28 UTC, ocipap commented
완료했습니다! 평소 자바스크립트만 사용하다보니... enum 이라는 개념이 생소하네요! 한번 정리해보도록 하겠습니다!

2022-05-14 16:38 UTC, pci2676 commented
> 완료했습니다! 평소 자바스크립트만 사용하다보니... enum 이라는 개념이 생소하네요! 한번 정리해보도록 하겠습니다!

@ocipap 님~! next-step 플랫폼에서 리뷰요청을 한번 더 눌러주셔야해요~!

2022-05-15 12:07 UTC, pci2676 approved these changes
문자열 계산기 구현하느라 고생하셨습니다.
조금 더 개선해보셨으면 하는 부분이 보이지만
해당 부분은 다음 단계 진행하면서 다시 짚어보면서 하는 것도 좋을것 같아서 머지하도록 하겠습니다! (코멘트는 한번 확인해보시고 고민해보시면 좋을 것 같아요!)
이제 본 미션인 자동차 미션을 진행해보시죠! 😎

2022-05-15 12:07 UTC, pci2676 commented on src/main/kotlin/calculator/Operator.kt
> +enum class Operator(val symbol: String, val operate: (Float, Float) -> Float) {
Enum 적용을 아주 깔끔하게 잘 적용해주셨군요! 💯

2022-05-15 12:07 UTC, pci2676 commented on src/main/kotlin/calculator/Splitter.kt
> +class Splitter(formula: String) {
클래스 이름이 차라리 Fomula인것이 더 적절하지 않을까요?

1. 식에게 연산자, 숫자를 달라고 요청한다.
2. 분리하는 것에게 연산자, 숫자를 달라고 요청한다.

둘중에 더 자연스러워 보이는게 저는 1번이라고 생각이 들어서요~!

2022-05-15 12:07 UTC, pci2676 commented on src/main/kotlin/calculator/Splitter.kt
> +        operations = getOperations(formulas)
```suggestion
        val formulas = formula.split(" ")
        val numbersAndOperations = groupByIsNumber(formulas)
        numbers = numbersAndOperations[true]!!.map { it.toFloat() }
        operations = numbersAndOperations[false]!!
```
`groupByIsNumber` 를 두번 부를 이유가 없을것 같아요~!

2022-05-15 12:07 UTC, pci2676 commented on src/test/kotlin/calculator/CalculatorTest.kt
> +class CalculatorTest : DescribeSpec({
지난 리뷰에서 제가 잘 전달을 못드렸는지 반영이 되지 않은 것같네요~

`Calculator`는 식을 연산하는 역할을 가지고 있기 때문에
식을 입력받아 결과를 반환하는 테스트와 예외 케이스만 있으면 될것 같습니다.

그렇기 때문에 덧셈, 뺄셈, 곱셈, 나눗셈을 여기서 모두 확인할 필요는 없을 것 같습니다!
오히려 덧셈, 뺄셈, 곱셈, 나눗셈의 연산 테스트는 `OperatorTest`가 지니고 있어야 할것 같아요.

여기서는 하나의 식이 제대로 연산되는지만 테스트해도 될것 같습니다.

2022-05-15 12:07 UTC, merged