Step2: 문자열계산기 코드리뷰 부탁드립니다~
next-step/kotlin-racingcar pull request #488
Opened 2022-05-09 11:26 UTC by joseph415

안녕하세요~ 리뷰요청이 많이 늦었습니다ㅠ
TDD로 작성하는것을 깜박하고 테스트를 마지막으로 작성하였네요ㅠㅠ
다음 과제부터는 인지하고 티디디로 진행해보겠습니다!

리뷰어님 질문이있는데요.
1. 코틀린 컴파일러는 타입을 추론해주지만, 개발자가 직접 명시할 수도 있는데
보통 코드를 작성할 때, 타입을 넣어주는것이 좋은 지, 아니면 유동적으로 생략하면서 필요할때만 명시하는것이 좋은지 궁금합니다.
이전에 자바로만 개발하는것에 익숙하다보니 타입이 안들어가 있으면 약간 어색하여, 명시적으로 타입을 작성하려고하는 습관이 있어서요.
코틀린답지 못한 코드인가 하여 질문드립니다!

2. 코틀린은 null 허용, 비허용 타입이 명시적으로 있는걸로 아는데요. 
이때 Optional(?.) 코드, 또는 null 아님 명시 등 이런코드는 작성을 피하는것이 좋은가요?
예를들어 Int? 타입이지만, 개발자가 판단하기에 어떤상황에서는 절때 null이 안나오는것같아 !! 를 사용한다던가  등.. 이런 것은 피하는것이 좋은지 궁금합니다.

2022-05-09 13:49 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-05-09 13:49 UTC, kyucumber commented on README.md
> -# kotlin-racingcar
Q1. 
```
코틀린 컴파일러는 타입을 추론해주지만, 개발자가 직접 명시할 수도 있는데
보통 코드를 작성할 때, 타입을 넣어주는것이 좋은 지, 아니면 유동적으로 생략하면서 필요할때만 명시하는것이 좋은지 궁금합니다.
이전에 자바로만 개발하는것에 익숙하다보니 타입이 안들어가 있으면 약간 어색하여, 명시적으로 타입을 작성하려고하는 습관이 있어서요.
코틀린답지 못한 코드인가 하여 질문드립니다!
```
이는 팀 컨벤션이나 작성한 코드의 특성에 따라 유동적으로 사용하시면 될 것 같아요.
아래와 같은 경우라면 타입을 한눈에 알 수 없겠죠, 한번 더 함수를 따라가야 합니다.

```kotlin
val data = getSomeData()
```

이는 가독성을 해칠 수 있으니 좋지 않습니다.
기본 전략은 생략이지만 코드의 가독성, 상황을 고려해 타입을 기술해주시면 될 것 같아요.

아래 내용도 한번 참고해보세요.

[이펙티브 코틀린 아이템 14. 변수 타입이 명확하지 않은 경우 확실하게 지정하라](https://kyucumber.github.io/posts/book/effective-kotlin/effective-kotlin-item-14)


Q2.
```
코틀린은 null 허용, 비허용 타입이 명시적으로 있는걸로 아는데요.
이때 Optional(?.) 코드, 또는 null 아님 명시 등 이런코드는 작성을 피하는것이 좋은가요?
예를들어 Int? 타입이지만, 개발자가 판단하기에 어떤상황에서는 절때 null이 안나오는것같아 !! 를 사용한다던가 등.. 이런 것은 피하는것이 좋은지 궁금합니다.
```

기본적으로 코틀린을 사용하더라도 nullable한 타입을 리턴하는 자바 라이브러리를 활용하는 경우도 많아 Safe Call(?) 연산자의 경우 자주 사용합니다.

!!의 경우 개인적으로는 최대한 사용하지 않는게 좋다고 생각해요.
현재 null이 나오지 않는 사실이 확실하다고 미래에 확실한 것은 아니니까요.

아래 내용도 참고해보시면 좋겠네요.

[이펙티브 코틀린 아이템 08. 적절하게 null을 처리하라](https://kyucumber.github.io/posts/book/effective-kotlin/effective-kotlin-item-08)

2022-05-09 13:49 UTC, kyucumber commented on src/main/kotlin/operator/StringCalculator.kt
> +        input = readLine() ?: throw IllegalArgumentException("null")
코틀린의 require을 활용해보셔도 좋을 것 같네요.
require는 조건에 따라 내부에서 IllegalArgumentException을 반환합니다.

[이펙티브 코틀린 아이템 05. 예외를 활용해 코드에 제한을 걸어라](https://kyucumber.github.io/posts/book/effective-kotlin/effective-kotlin-item-05)

2022-05-09 13:49 UTC, kyucumber commented on src/main/kotlin/operator/domain/Calculator.kt
> +            }
> 객체지향 생활 체조 원칙 - 한 메서드에 오직 한 단계의 들여쓰기만 한다.

위 내용에 대해 한번 고민해보시면 좋을 것 같아요.

2022-05-09 13:49 UTC, kyucumber commented on src/main/kotlin/operator/StringCalculator.kt
> +        input = readLine() ?: throw IllegalArgumentException("null")
가급적 가변인 `var`을 사용하지 않고 구현해보시면 좋을 것 같네요.

do while을 활용해보시면 어떨까요?

2022-05-09 13:49 UTC, kyucumber commented on src/main/kotlin/operator/domain/Calculator.kt
> +        }
빈 공백 문자가 하나만 들어가면 이쪽에서 오류가 발생하겠네요.

OperatorService에서 검증하고 있긴 하지만 Calculator 자체가 문자열 계산기로 기능할 수 있도록 이런 예외처리는 Calculator쪽에서 하는게 좋지 않을까 하는 개인적인 생각이 있네요.

예외처리의 조건이 모호하고 흩어지는 경우에 잘 관리되지 않을 것 같아요.

2022-05-09 13:49 UTC, kyucumber commented on src/main/kotlin/operator/domain/Calculator.kt
> +                operands.add(Operand(input.slice(startSliceIndex until i).toDouble()))
operands라는 인스턴스 변수를 여러 함수에서 다루고 있네요.

이런 경우 어디서 어떤 값이 변경되는지 추적하기 힘들어 디버깅이 힘들어집니다.

가급적 가변이 아니라 불변으로 처리해보시면 좋을 것 같아요.

2022-05-09 13:49 UTC, kyucumber commented on src/main/kotlin/operator/domain/Calculator.kt
> +            throw IllegalArgumentException("잘못된 인풋값입니다.")
예외 메시지와 메소드 명은 구체적으로 해주시면 좋을 것 같아요.

Input의 어떤 부분을 검증하려는건지 메소드 이름만 보았을 때 의도를 알기 어려울 것 같네요.

2022-05-09 13:49 UTC, kyucumber commented on src/main/kotlin/operator/domain/Operand.kt
> +data class Operand(val num: Double) {
👍

2022-05-09 13:49 UTC, kyucumber commented on src/test/kotlin/operator/domain/CalculatorTest.kt
> +    @CsvSource( "3+3/2, 3.0", "3 - 2, 1.0" )
0으로 나누거나 하는 엣지 케이스도 검증해보시면 좋을 것 같아요.

2022-05-09 15:53 UTC, joseph415 commented on README.md
> -# kotlin-racingcar
답변 감사드립니다! 이펙티브 코틀린책도 한번 사서 읽어봐야겠네요ㅎㅎ👍

2022-05-09 17:07 UTC, joseph415 commented on src/main/kotlin/operator/StringCalculator.kt
> +        input = readLine() ?: throw IllegalArgumentException("null")
val 과 do while 의 조합으로 재입력 받고 블럭스코프 외부에서 호출할수가 없어서 while(true)로 변경했습니다.

2022-05-09 17:12 UTC, joseph415 commented on src/main/kotlin/operator/domain/Calculator.kt
> +        }
저는 이렇게 개발을 했던 이유는 우선, 외부에서 입력되는 단순 값에 대한 검증은 서비스단, 컨트롤러에서 하고
도메인에 관련된 비지니스적 검증로직은 도메인계층에 들어가야한다고 생각하고 작성했는데요. 

규남님말씀 들어보니, 현재서비스에서 하고있는 검증로직은 도메인적 검증로직에 가까운것 같네요! 수정하겠습니다~

2022-05-09 17:21 UTC, joseph415 commented on src/main/kotlin/operator/StringCalculator.kt
> +        input = readLine() ?: throw IllegalArgumentException("null")
오 감사합니다!.. 현업에 바로 적용해봐야겠네요ㅎㅎ

2022-05-09 18:47 UTC, joseph415 commented on src/main/kotlin/operator/domain/Calculator.kt
> +                operands.add(Operand(input.slice(startSliceIndex until i).toDouble()))
가급적 가변을 사용하는것보단 불변을 사용하는것에 이견이 없는데요!
해당 자료구조를 사용하려면 컬렉션의 값이 변경되는 것은 필수적인것 같은데요.
해당 컬렉션을 사용하면서 어떻게 불변구조로 만들 수 있을까요? 
계속 고민을 해봣는데 떠오르지가 않네요..

고민하면서 드는생각이 VO 같은 값객체에서는 불변 처리가 필수라고 생각하는데,
인스턴스 변수로 컬렉션을 다룰때 내부에서 처리하는게 맞나 생각이들어서요.
Calculator 외부에서 내부 컬렉션을 변경하면 큰 문제가 되지만, 
클레스 내부에서 자신이 자신의 속성을 변경하는것까지 제한을 두어야하나 생각이 들어 질문드립니다.

2022-05-09 19:01 UTC, joseph415 commented
코드리뷰 적용후 질문사항 몇가지 남겼습니다! 감사합니다.

2022-05-10 13:52 UTC, kyucumber commented on src/main/kotlin/operator/domain/Calculator.kt
> +                operands.add(Operand(input.slice(startSliceIndex until i).toDouble()))
```
Calculator 외부에서 인스턴스 변수(operands, operatorTokens)을 변경하면 문제가 되지만,
현재 외부에서 인스턴스변수를 변경할 수 있는 방법은 없고, 클레스 내부에서 자신이 자신의 속성을 변경하는것까지 제한을 두어야하나 생각이 들어 질문드립니다.
```

말씀하신것 처럼 내부에서 변경이 일어나면 크게 문제는 없을 것 같아요.
다만 코드라는게 항상 똑같이 유지되지 않고 계속 변하기 때문에 저는 가독성과 사이드 이펙트 측면에서 가급적 불변을 사용하는 것을 선호하는 편입니다.

불변으로 처리하면 for loop를 한번 돌 걸 두번 세번 돌아야 하는 경우가 있어 성능적인 측면에서 비효율적일 순 있지만 최근 컴퓨팅 자원들의 성능이 굉장히 좋기 때문에 극한의 성능을 요구하는 경우가 아니라면 비효율적이어도 가독성과 사이드 이펙트를 줄이는 방향으로 개발을 진행하는게 더 좋다고 생각해요.

```
해당 자료구조를 사용하려면 컬렉션의 값이 변경되는 것은 필수적인것 같은데요.
```

operands와 operatorTokens를 먼저 불변한 List에 추출한 뒤 연산을 진행해도 요구사항을 충족시킬 수 있을 것 같아요.
첫번째 코멘트 단 제 의견에서도 언급했지만 꼭 해당 자료구조를 꼭 사용해야 할지는 좀 저는 고민이긴 해요.

지금 작성한 함수들은 operands나 operatorTokens 값에 따라 결과가 달라질 수 있는데 저는 가변 값을 여러 함수에서 바꾸는 형태는 최대한 피하고 가급적 순수함수가 되도록 코딩하는 편입니다.

> 순수함수
> 같은 매개변수를 넘기면 항상 같은 결과를 반환하는 함수

제 의견이 정답은 아니니 참고만 해주시면 될 것 같습니다~

2022-05-10 13:54 UTC, kyucumber requested changes
https://github.com/next-step/kotlin-racingcar/pull/488#discussion_r869268306

질문 주신 부분에 대해 답변 남겨두었어요.
해당 내용은 꼭 반영하지 않아도 됩니다. 재 요청 주시면 머지하도록 할게요.

2022-05-11 11:54 UTC, joseph415 commented
자세한 답변 감사드립니다ㅎㅎ. 규모가 커지는 플젝일수록 리뷰어님이 말씀해주신 장점이 더 크게 부각되겠네요.
제가 너무 닫힌 시각으로 본게 아닌가 싶네요ㅎㅎ.
말씀해주신 리뷰는 다음 자동차 경주부터 상기시키면서 해보도록 하겠습니다!
그리고 require과  불변타입 val로 코드를 짜려고 하니 더 좋은 코드가 나오는것 같네요ㅎ

좋은 리뷰 감사합니다! 자동차경주때 리뷰드리겠습니다~

2022-05-11 11:55 UTC, kyucumber approved these changes
수고 많으셨습니다.

다음 단계 진행을 위해 머지할게요

2022-05-11 11:55 UTC, merged