Step3 자동차 경주 리뷰요청 드립니다.
next-step/kotlin-racingcar pull request #515
Opened 2022-05-11 14:28 UTC by sah3122

안녕하세요 리뷰어님 ^^ 
상세한 리뷰 및 답변 감사합니다 😄 

지난 미션과 마찬가지로 최대한 간결하게 작성하려고 노력했습니다. 
남겨주신 코멘트가 너무 도움 되더라구요 👍 
이번에도 많은 코멘트 부탁드려요 🙏

2022-05-12 02:28 UTC, sah3122 commented on src/main/kotlin/car/domain/Car.kt
> +        private set
일반적으로 변경가능한 프로퍼티의 setter를 감추면서 getter를 제공하기 위해 위와 같이 사용하곤하는데 더 나은 방법이 있을까요 ?

2022-05-12 14:08 UTC, ddaaac requested changes
안녕하세요!

3단계 미션 잘 구현해주셨어요! 코틀린의 다양한 API들을 능숙하게 다룬 코드들이 인상적이었습니다 👍 

몇 가지 코멘트 남겼으니 확인 부탁드려요.

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/ui/InputView.kt
> +inline class NumberOfCar(val value: Int)
`inline` 키워드는 코틀린 1.4까지 사용되었고 지금은 deprecated 되었습니다.
[`value`](https://kotlinlang.org/docs/inline-classes.html) 키워드를 사용해볼까요?

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/Application.kt
> +    val (numberOfCar, tryCount) = InputView.input()
data class의 [destructuring](https://kotlinlang.org/docs/destructuring-declarations.html) 기능을 사용해주셨군요 👍

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/domain/Car.kt
> +        private set
생성자 내에서는 private setter 설정을 못해주죠... 저도 아마 이렇게 구현할 것 같습니다.
다만, 생성자의 파라미터 이름에서 `_`는 제거해도 되지 않을까 싶어요.

제가 아는 프로퍼티 명에서의 `_`의 사용처는 [이런 경우]([코틀린 문서](https://kotlinlang.org/docs/coding-conventions.html#names-for-backing-properties)) 가 있습니다!

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/domain/CarRacing.kt
> +    fun race(cars: Cars): List<Position> = cars.move(RandomMovingStrategy())
매번 RandomMovingStrategy를 생성하지 않게 구현할 수 있을 것 같아요 :)

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/domain/Cars.kt
> +        check(numberOfCar.value > MIN_VALUE) { "자동차 수는 $MIN_VALUE 보다 커야합니다." }
- 가장 많이 사용하는 두 가지 표준 예외는 `IllegalArgumentException`과 `IllegalStateException`이 있는데요, [이 스레드](https://stackoverflow.com/a/48736483)에 비춰서 생각해보면 여기서는 `IllegalArgumentException`이 조금 더 적당할 것 같아요.
- 이미 아시겠지만 코틀린은 위 두가지 예외에 대한 처리 함수인 [`require(), check()`](https://seosh817.tistory.com/155)을 제공합니다.

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/domain/Cars.kt
> +private const val DEFAULT_POSITION = 0
포지션의 초기값은 Position 객체가 갖고 있는게 더 적당하지 않을까요?

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/domain/MovingStrategy.kt
> +private const val END_VALUE = 10
상수가 제일 위에 위치하는 건 어떨까요?

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/domain/MovingStrategy.kt
> +    override fun movable(): Boolean = (START_VALUE..END_VALUE).random() >= MOVABLE_VALUE
`rangeTo` 함수의 반환 타입인 `IntRange`의 양 끝 범위는 inclusive 입니다. 미션은 0~9까지의 값만 다루기 때문에 값 수정이 필요해보여요!

<img width="959" alt="image" src="https://user-images.githubusercontent.com/43440195/168092616-09b22fcf-1716-414f-b42c-a5db2cb7f040.png">

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/domain/Position.kt
> +data class Position(
- 상수와 클래스 사이는 한 줄 분리해주시면 보기 더 좋을 것 같아요!
- `Position`도 value class로 만들어보는 건 어떨까요?

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/domain/Position.kt
> +) {
저는 객체에 초기값을 세팅해줄 때, 빈(기본) 생성자를 이용하는 방식보다는 정적 팩토리 메서드를 선호하는 편입니다. `Position()`와 `Position.initial()` 정도 차이겠네요.
이유는 빈 생성자는 사람들마다 그 뜻을 다르게 해석할 수 있다고 생각해서에요. 누군가에게는 빈 생성자가 당연히 특정 의미로 받아질 수 있겠지만 다른 사람은 다르게 받아들이는 경우를 종종 보았거든요.

대표적인 예시로는 `Date` 와 `LocalDateTime`의 초기화 방식 차이가 있겠네요. 리뷰어님의 생각은 어떠신가요?

2022-05-12 14:08 UTC, ddaaac commented on src/test/kotlin/study/car/PositionTest.kt
> +        shouldThrow<IllegalArgumentException> { Position(-1) }
경계값 잘 테스트 해주셨네요 👍

2022-05-12 14:08 UTC, ddaaac commented on src/main/kotlin/car/domain/CarRacing.kt
> +    fun race(cars: Cars): List<Position> = cars.move(RandomMovingStrategy())
"특정 횟수만큼 레이스를 반복한다"를 도메인 로직으로 본다면 여기서 `TryCount`를 관리해도 좋을 것 같습니다.

2022-05-12 14:08 UTC, ddaaac commented on src/test/kotlin/study/car/CarsTest.kt
> +        val move = cars.move { true }
테스트 가능한 구조로 잘 작성해주셨네요 👍

2022-05-12 14:49 UTC, sah3122 commented on src/main/kotlin/car/domain/Car.kt
> +        private set
정확한 사용처를 모르고 습관적으로 언더스코어를 사용하고 있었네요. 😢 
좋은 지적 감사합니다 👍

2022-05-12 14:51 UTC, sah3122 commented on src/main/kotlin/car/ui/InputView.kt
> +inline class NumberOfCar(val value: Int)
Kotlin In Action으로 공부하다보니 deprecated 된줄 몰랏네요 😢

2022-05-12 14:53 UTC, sah3122 commented on src/main/kotlin/car/domain/Cars.kt
> +        check(numberOfCar.value > MIN_VALUE) { "자동차 수는 $MIN_VALUE 보다 커야합니다." }
반영해두었습니다 👍

2022-05-12 14:58 UTC, sah3122 commented on src/main/kotlin/car/domain/Cars.kt
> +private const val DEFAULT_POSITION = 0
포지션의 초기값을 지정하는것이 어플리케이션이 유연하게 변경되는것을 막을수 있을것 같아 아래와 같이 변경하였습니다. 

- 자동차의 초기 포지션은 0이다. 
- 포지션 객체는 0이상의 위치를 가져야한다.

위 요구사항을 만족하도록 변경하였고, 자동차의 초기 포지션 요구사항 변경일어나도 대응할수 있을것 같네요 😄

2022-05-12 15:06 UTC, sah3122 commented on src/main/kotlin/car/domain/MovingStrategy.kt
> +private const val END_VALUE = 10
```kotlin
private const val MOVABLE_VALUE = 4
private const val START_VALUE = 0
private const val END_VALUE = 10

fun interface MovingStrategy {
    fun movable(): Boolean
}

class RandomMovingStrategy : MovingStrategy {
    override fun movable(): Boolean = (START_VALUE..END_VALUE).random() >= MOVABLE_VALUE
}

```

interface와 구현체를 하나의 파일에 넣다보니 상수 위치 지정이 헷갈리더라구요 😢 
모든 구현체에서 위와같은 상수를 사용하지 않을거라 생각하여 구현체 상단에 위치 시켜보았어요. 

개인적으로 가지고 있는 생각은 인터페이스를 분리하고 구현체가 하나인 경우는 하나의 파일에 두고, 구현체가 2개 이상이 되는경우 인터페이스와 구현체 파일을 분리하려고 하고 있습니다. 😄

2022-05-12 15:07 UTC, sah3122 commented on src/main/kotlin/car/domain/MovingStrategy.kt
> +    override fun movable(): Boolean = (START_VALUE..END_VALUE).random() >= MOVABLE_VALUE
until 로 변경해두었습니다 😄

2022-05-12 15:13 UTC, sah3122 commented on src/main/kotlin/car/domain/Position.kt
> +data class Position(
IDE 세팅때문에 new line 이 빠져있는것을 몰랏네요 😢 
현재는 Position class가 하나의 프로퍼티만 가지고 있으니 value class로 변경하는것이 적절하네요 👍

2022-05-12 15:25 UTC, sah3122 commented on src/main/kotlin/car/domain/Position.kt
> +) {
좋은 질문 감사합니다 👍 

우선 제 생각을 남겨드리자면 현재는 정적 팩토리 메소드를 의식적으로 피하려고 하고 있어요. 
정적 팩토리 메소드를 자주 사용하다보니 생성자를 다양하게 선언하기 보다는 primary constructor 하나를 두고, 정적 팩토리 메소드에서 여러 형태의 객체 생성방법을 제공하고 있더라구요. 
정적 팩토리 메소드의 장점인 객체 생성시 특별한 이름을 부여하는것도 어느순간 관례에 맞추어 of, valueOf 와 같은 네이밍을 주로 사용하는 모습을 볼수 있었어요. 

그리하여 최근엔 정적 팩토리 메소드의 사용을 줄이며 최대한 생성자를 다양하게 선언하는것을 선호하고 있습니다. 
특히 Kotlin Style Guide 에는 자바와 다르게 companion object 선언의 위치가 method 하위로 알고 있어요. 
정적 팩토리 메서드는 생성자의 다른 구현방법이라고 생각하여 자바에서는 생성자 하위에 위치하게 두어 생성자들이 한곳에 응집될수 있었죠. 
코틀린에서는 클래스 최하단에 위치하다보니 가독성 및 코드 응집도가 떨어지는것 같더라구요. 😢 
이러한 이유에서도 이번 미션을 진행하며 정적 팩토리 메서드는 최대한 자제하려고 합니다 😄

2022-05-12 15:39 UTC, sah3122 commented on src/main/kotlin/car/domain/CarRacing.kt
> +    fun race(cars: Cars): List<Position> = cars.move(RandomMovingStrategy())
`TryCount를 관리`라는 내용을 제대로 이해 하지 못했는데 이해한대로 코멘트 남겨볼게요 .. ! 

제가 이해한 바로는 레이스 반복을 도메인 로직으로 보게 된다면, CarRacing 객체가 StateLess한 상태를 지키지 못하게 될것 같다고 생각해요. (TryCount의 값을 유지해야하니)

그럼 한번의 race호출로 tryCount 만큼의 경주 결과를 전달해주어야 할텐데, 이순간 ui layer로 전달하기 위한 response 클래스가 필요하게 될것 같다고 생각했어요. 
만약 제 생각이 맞다면, 5단계 미션에서 반영해도 될것 같은데 범준님의 생각은 어떠신가요 ㅎㅎ;;

2022-05-12 15:40 UTC, sah3122 commented on src/main/kotlin/car/domain/CarRacing.kt
> +    fun race(cars: Cars): List<Position> = cars.move(RandomMovingStrategy())
추가로 TryCount, NumberOfCar value object를 ui layer에서만 사용하려고 했는데 어느 순간 NumberOfCar 클래스가 도메인 패키지로 침범했더라구요 .. 이부분도 변경해두었습니다 😄

2022-05-14 15:48 UTC, ddaaac commented on src/main/kotlin/car/domain/MovingStrategy.kt
> +private const val END_VALUE = 10
넵 저도 좋은 구분법이라고 생각합니다. 추가로, sealed class/interface의 경우에도 저는 최대한 한 파일에 두려고 합니다!

2022-05-14 15:48 UTC, ddaaac commented on src/main/kotlin/car/domain/Cars.kt
> +        require(numberOfCar.value > MIN_VALUE) { "자동차 수는 $MIN_VALUE 보다 커야합니다." }
지금 요구사항에서는 자동차 댓수에 대한 검증이 NumberOfCar에 위치해도 괜찮을 거 같아요.
물론 position과 비슷하게 유연성을 어떻게 챙길 것인가에 따라 차이가 있을 수 있겠네요.

2022-05-14 15:48 UTC, ddaaac commented on src/main/kotlin/car/domain/MovingStrategy.kt
> +    override fun movable(): Boolean = (START_VALUE until END_VALUE).random() >= MOVABLE_VALUE
소소하지만 until도 객체를 생성하기 때문에 미리 빼두는 것도 좋아보이네요.

2022-05-14 15:48 UTC, ddaaac commented on src/test/kotlin/study/car/CarsTest.kt
> +package study.car
그러고보니 테스트 패키지가 study 밑에 있군요 😅

2022-05-14 15:48 UTC, ddaaac commented on src/main/kotlin/car/domain/CarRacing.kt
> +    fun race(cars: Cars): List<Position> = cars.move(RandomMovingStrategy())
일단 코멘트는 CarRacing이 꼭 stateless 할 필요가 있을까에서 나오긴 했습니다.
하지만 말씀해주신대로 5단계 때 수정이 발생할 부분이면 그 때 가서 변경돼도 좋을 것 같습니다 😄

2022-05-14 15:49 UTC, ddaaac approved these changes
안녕하세요 :)

리뷰 반영 잘 해주셨습니다 💯 
다음 단계 진행을 위해서 머지할게요!

2022-05-14 15:49 UTC, merged

2022-05-15 12:18 UTC, ddaaac commented on src/main/kotlin/car/domain/Position.kt
> +) {
이 부분 코멘트를 빠트렸네요!

좋은 접근인 것 같아요. static한 메서드의 사용을 줄이려고 companion object 는 일부러 어색하게 만들었나 싶을 정도로 위치나 모양이 불편하더라구요. 이번 교육과정이 끝나면 만족할만한 스타일의 코드 양식을 찾으시면 좋겠네요 👍