3단계 - 자동차 경주
next-step/kotlin-racingcar pull request #516
Opened 2022-05-12 01:04 UTC by juice119

2022-05-12 01:07 UTC, juice119 commented on src/main/kotlin/carRacing/CarRacingManager.kt
> +    abstract fun getMonitoringInformation(): String
모니터링 하는 데이터를 가져오는 함수인데 다향성에 맞게 설계 되는것을 원해서 `abstract`로 만들었습니다.

모니터링 해주는 역할을 가진 클래스를 만드는것을 고민중인데 어떻게 생각하시나요?

2022-05-12 01:20 UTC, juice119 commented on src/main/kotlin/carRacing/RandomNumberCarRacingManager.kt
> +class RandomNumberCarRacingManager : CarRacingManager {
랜덤 자동차 경주를 관리하는 역할을 하는데, 책임 및 역할이 생각보다 많아서 분리를 고민하고 있습니다.

### 책임
- 랜덤 값을 기준으로 전진 여부 판단

### 역할
- 자동차 리스트 관리
- 모니터링 용 데이터 만들기

2022-05-13 08:09 UTC, vsh123 requested changes
안녕하세요!
우선 피드백이 늦어서 죄송합니다ㅠㅠ

몇가지 코멘트를 남겼으니 확인부탁드리겠습니다!
이번주도 고생많으셨습니다!! :)

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/Car.kt
> +package carRacing
[패키지 네이밍 컨벤션](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names)을 참고해서 변경해보면 어떨까요?

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/main.kt
> +    val carCount: String = readLine() ?: throw IllegalArgumentException("자동차 대수는 null 이 올수 없습니다")
[readln](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/readln.html)을 활용해보면 어떨까요?

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/InputDto.kt
> +class InputDto(carCountString: String, movementTryCountString: String) {
[data class](https://kotlinlang.org/docs/data-classes.html)에 대해 알아보고, dto에 적용 가능여부를 판단해보면 어떨까요?

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/InputDto.kt
> +                )
라인을 나누신 이유가 궁금합니다!! (한줄로도 충분히 가독성이 좋아보여서요~!)

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/InputDto.kt
> +        carCount = parseInt(removeSpace(carCountString))
`parseInt`도 좋지만 [toInt](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-int.html)가 조금 더 잘 읽히는 느낌인데요!!
두개의 차이점이 있는지 알아보고 적용해보면 어떨까요?

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/main.kt
> +    for (tryCount in 1..inputDto.movementTryCount) {
[repeat](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/repeat.html)를 활용해보면 어떨까요?

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/RandomNumberCarRacingManager.kt
> +        var inputCars = emptyList<Car>()
* 생성자에서 많은 전처리 작업을 맡고 있는 것 같아요! 이경우 팩터리 메서드를 고려해보면 어떨까요?
* 코틀린의 [List](https://brunch.co.kr/@mystoryg/28)에 대해 알아보고 mutableList나 List로 선언해주면 어떨까요?

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/CarRacingManager.kt
> +    fun addCar(car: Car) {
테스트에만 사용되는 함수인 것 같아요!! 없앨 수 있지 않을까요?

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/CarRacingManager.kt
> +abstract class CarRacingManager {
생성시점부터 완전한  cars List를 받으면 어떨까요?

```suggestion
abstract class CarRacingManager(private val cars: List<Car> = listOf()) {
```

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/CarRacingManager.kt
> +    fun getCarListSize(): Int {
`getCarSize()`정도로만 네이밍을 해도 괜찮지 않을까요?

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/CarRacingManager.kt
> +    fun getCarDistance(index: Int): Int {
해당 역할은 `Car`에 있는게 어떨까요?

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/RandomNumberCarRacingManager.kt
> +class RandomNumberCarRacingManager : CarRacingManager {
네엡 해당부분 저도 동의합니다!!

전진 여부 판단만 책임하는 객체에서 리스트를 관리하고, 실제로 움직이는 작업도 진행하고 있는게 어색해보여요~
또한 모니터링 용 데이터(View를 위한 데이터)는 별도의 View클래스에서 작업해주는게 어떨까요?

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/RandomNumberCarRacingManager.kt
> +    constructor() {}
해당 생성자도 테스트를 위한 것 같은데요! 제거에 도전해보세요!

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/RandomNumberCarRacingManager.kt
> +    fun tryMoveCar(carIndex: Int, randomInt: Int) {
지금 tryMoveCar는 CarRacingManager의 역할이 아닌 RandomNumberCarRacingManager만의 기능인 것 같네요!! 말씀주신대로 고민이 필요해보여요~!

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/RandomNumberCarRacingManager.kt
> +        fun isForwardNumber(randomInt: Int): Boolean {
테스트를 위해 default 접근 제한자를 설정하신걸까요??

2022-05-13 08:09 UTC, vsh123 commented on src/main/kotlin/carRacing/readme.md
> +# 3단계 - 자동차 경주
기능 구현 목록 및 test설명 👍

2022-05-13 08:09 UTC, vsh123 commented on src/test/kotlin/carRacing/CarRacingManagerTest.kt
> +class CarRacingManagerTest : StringSpec({
kotest 활용 👍

2022-05-13 08:10 UTC, juice119 commented on src/main/kotlin/carRacing/RandomNumberCarRacingManager.kt
> +class RandomNumberCarRacingManager : CarRacingManager {
넵 말씀하신 내용으로 진행하면 좋을것 같습니다!

2022-05-13 08:13 UTC, juice119 commented on src/main/kotlin/carRacing/RandomNumberCarRacingManager.kt
> +        fun isForwardNumber(randomInt: Int): Boolean {
넵 맞습니다. 테스트를 위한 용도 이기도 하면서 
외부에서 다시 사용 할수 있다고 생각했어요.

2022-05-14 05:31 UTC, juice119 commented on src/main/kotlin/carRacing/InputDto.kt
> +                )
이거 라인 잘못 나누었어요~

2022-05-14 06:12 UTC, juice119 commented on src/main/kotlin/carRacing/InputDto.kt
> +        carCount = parseInt(removeSpace(carCountString))
# 차이점
- `toInt`는 `radix(진수)`에 옭지 않은 값이 들어간 경우 `IllegalArgumentException` 예외가 발생합니다. 
하지만 `Integer.parseInt`는 radix에 대한 예외 또한 `NumberFormatException` 이 발생합니다. 
![image](https://user-images.githubusercontent.com/39614239/168413176-d8956209-18c4-4f10-ab94-f76dfad4e555.png)
- kotlin 에서 `toInt` 이외에도 `IntOrNull` 와 같은 다양한 옵션을 지원합니다.

## 변경 사항
- `toUint` 라는 정수를 내보내는 타입을 발견하여 이것을 적용하였습니다.
- 기존 `carCount`, `movementTryCount` 를 사용하는 곳은 `Backing properties﻿`를 이용하여 `Int` 타입으로 작동하게 하였습니다.

## 참고 링크
- [`toInt`, `Integer.parseInt` 비교 블로그 글](https://tedblob.com/kotlin-convert-string-to-int/)
- [kotlin Backing properties﻿ 문서](https://kotlinlang.org/docs/properties.html#compile-time-constants)

2022-05-14 07:52 UTC, juice119 commented on src/main/kotlin/car_racing/RandomNumberCarRacingManager.kt
> +        fun fromInputDto(inputDto: InputDto): RandomNumberCarRacingManager {
보조 생성자 가 안티 패턴으로 생각 되어 제거후 팩토리 방식으로 변경하였습니다.

안티 패턴으로 생각하는 이유는 아래와 같습니다.
1. 보조 연산자는 값을 할당 되기전  `init` 함수가 실행되어 예외적인 케이스가 발생할 것 같아요

2022-05-14 07:55 UTC, juice119 commented on src/main/kotlin/carRacing/RandomNumberCarRacingManager.kt
> +    fun tryMoveCar(carIndex: Int, randomInt: Int) {
`tryMoveCar` 메소드는 `RandomNumberCarRacingManager` 에서 선언된 메소드 인데,
`tryMoveCar` 역할이 `RandomNumberCarRacingManager` 아닌 다른 곳에 있어야 된다는 뜻인가요?

2022-05-14 09:39 UTC, juice119 commented on src/main/kotlin/carRacing/RandomNumberCarRacingManager.kt
> +class RandomNumberCarRacingManager : CarRacingManager {
각 역할을 아래 클래스로 분리하였습니다!

### `CarRacingView`

- 모니터링 용 데이터 만들기

### `CarMovementRole`

- 랜덤 수 기준으로 자동차 이동 판단

### `CarListManager`

- List<Car>  관리

2022-05-14 09:51 UTC, juice119 reviewed
1차 리뷰 내용 적용했습니다.

보조생성자 는 안티패턴 이라고 생각하여 팩토리 로 변경혀였습니다.

2022-05-14 09:51 UTC, juice119 commented on src/main/kotlin/car_racing/CarMovementRole.kt
> +class CarMovementRole {
다음 과제에서 `인터페이스`로 분리해서 확장성을 가지고 갈 생각입니다!

2022-05-14 09:51 UTC, juice119 commented on src/main/kotlin/car_racing/CarRacingView.kt
> +        repeat(car.distance) { result += carCharacter }
이쪽을 더 깔끔하게 수정할수 있는 방법이 있을까요?

2022-05-14 09:51 UTC, juice119 commented on src/main/kotlin/car_racing/RandomNumberCarRacingManager.kt
> +        fun fromInputDto(inputDto: InputDto): RandomNumberCarRacingManager {
보조 생성자 가 안티 패턴으로 생각 되어 제거후 팩토리 방식으로 변경하였습니다.

안티 패턴으로 생각하는 이유는 아래와 같습니다.
1. 보조 연산자는 값을 할당 되기전  `init` 함수가 실행되어 예외적인 케이스가 발생할 것 같아요

2022-05-14 09:51 UTC, juice119 commented on src/main/kotlin/car_racing/readme.md
> +- arrayIndex 에 해당하는 자동차 거리 가져오기
역할을 분리하면서 추가된 클래스 정리하였습니다

2022-05-14 09:51 UTC, juice119 commented on src/test/kotlin/car_racing/util/CarRacingManagerForTest.kt
> +class CarRacingManagerForTest(carListManager: CarListManager) : CarRacingManager(carListManager)
추상 클래스를 테스트 하기 위해서 테스트 코드 폴더에 추상 클래스를 상속하여  클래스를 추가했습니다.

2022-05-15 05:26 UTC, vsh123 requested changes
안녕하세요!! :)
피드백 반영잘해주셨네요~!!!

몇가지 코멘트와 질문에 대한 답변을 남겼으니 확인부탁드리겠습니다!

2022-05-15 05:26 UTC, vsh123 commented on src/main/kotlin/car_racing/Car.kt
> +package car_racing
일반적으로 _없이 `carracing`으로 패키지명을 짓는데요! _를 추가하신 이유가 있을까요?

2022-05-15 05:26 UTC, vsh123 commented on src/main/kotlin/car_racing/Car.kt
> +class Car(private var _distance: Int = 0) {
`CarTest`가 없는 것 같아요!

2022-05-15 05:26 UTC, vsh123 commented on src/main/kotlin/car_racing/CarListManager.kt
> +        get() = _cars
여기는 Backing Properties가 필요없어보여요! 한번 검토부탁드려요~!!

```suggestion
class CarListManager(private val cars: List<Car> = listOf()) {
```

2022-05-15 05:26 UTC, vsh123 commented on src/main/kotlin/car_racing/InputDto.kt
> +        get() = _movementTryCount.toInt()
요기도 Backing Properties가 필요한부분에만 적용해주면 어떨까요?

2022-05-15 05:26 UTC, vsh123 commented on src/main/kotlin/car_racing/InputDto.kt
> +        _carCount = removeSpace(carCountString).toUInt()
내부적으로 UInt를 사용하는 곳이 없는데요! 바로 toInt로 변환해주면 어떨까요?

```suggestion
        carCount = removeSpace(carCountString).toInt()
```

2022-05-15 05:26 UTC, vsh123 commented on src/main/kotlin/car_racing/RandomNumberCarRacingManager.kt
> +    fun tryMoveCar(carIndex: Int, randomInt: Int) {
>tryMoveCar 메소드는 RandomNumberCarRacingManager 에서 선언된 메소드 인데,
tryMoveCar 역할이 RandomNumberCarRacingManager 아닌 다른 곳에 있어야 된다는 뜻인가요?

tryMoveCar는 `CarListManager`의 역할인 것 같은데, 지금 선언된 구조로는 `RandomNumberCarRacingManager`가 아닌 다른 구현체가 만들어졌을 때 `tryMoveCar`를 쓸 수 없을 것 같아서 의견을 드렸던 거에요! 혹시 이해가 안간다면 디엠주세요~~!

2022-05-15 05:26 UTC, vsh123 commented on src/main/kotlin/car_racing/main.kt
> +private fun setRandomValue(randomNumberCarRacingManager: RandomNumberCarRacingManager) {
해당 함수가 `random`이라는 keyword에 엮여있는 것 같아요! 
만약 랜덤이 아닌 무조건적으로 이동가능한 carRancingManager가 필요할때도 코드 수정을 최소화할 수 있는 네이밍과 구현으로 변경해보면 어떨까요?

```suggestion
private fun setRandomValue(carRacingManager: CarRacingManager) {
```

2022-05-15 05:34 UTC, juice119 commented on src/main/kotlin/car_racing/InputDto.kt
> +        get() = _movementTryCount.toInt()
여기는 `Get`으로 값을 받을때  `Int` 타입으로 받고 싶어서 `Backing Properties` 를 적용 하였습니다.
응답을 받을때 마다 `Unit` 를 `Int`타입으로 바꾸는 것이 번거롭다고 생각해서 이렇게 했습니다.

`get`에 응답 타입은 `property` 와 같은 타입만 가능 하더라고요!

![image](https://user-images.githubusercontent.com/39614239/168458661-0ab18895-efe2-4871-af09-f06756c1fc12.png)

2022-05-15 05:38 UTC, juice119 commented on src/main/kotlin/car_racing/InputDto.kt
> +        _carCount = removeSpace(carCountString).toUInt()
생각해 보니 앞에 `validation` 로직이 음수 값을 걸러내서 toUnit는 없어도 될것 같네요.
다시 `toInt`로 변경하겠습니다.
 
![image](https://user-images.githubusercontent.com/39614239/168458779-065729ef-40f3-4bac-98f8-faf708d8563a.png)

2022-05-15 05:39 UTC, juice119 commented on src/main/kotlin/car_racing/InputDto.kt
> +        get() = _movementTryCount.toInt()
이거 `toInt` 적용해서 `Backing Properties` 제거 해서 적용할게요

2022-05-15 05:42 UTC, juice119 commented on src/main/kotlin/car_racing/Car.kt
> +package car_racing
앗 이거 제가 잘못 읽었네요! 바로 변경 할게요

2022-05-15 08:21 UTC, juice119 reviewed
너무 복잡한 구조가 된것 같아서 다이어그램표 첨부했어요.
![default](https://user-images.githubusercontent.com/39614239/168463724-acf37d45-219a-4e08-be24-71de9fad0a07.png)

`TryMoveCar`을 `RacingManger`로 옮기고 전진 여부를 판단할때 사용하는 매개변수는 제너릭으로
추후에 추상 클래스를 상속할때 선언하게 바꾸었습니다.

2022-05-15 08:21 UTC, juice119 commented on src/main/kotlin/carracing/CarRacingManager.kt
> +abstract class CarRacingManager<MovementCheckType>(
`RacingMovementRole`에서 전진 여부를 판단할 매개변수 타입을 제너릭으로 선언해서 가져가게 변경하였습니다.

2022-05-15 08:21 UTC, juice119 commented on src/main/kotlin/carracing/RacingMovementRole.kt
> +interface RacingMovementRole<T> {
레이싱에서 전진 여부를 판단하는 객체애 인터페이스이빈다.

다향성을 위해서 전진 여부 판단시 사용할 매개변수 타입은 제너릭으로 사용시 명시하게 하였습니다.

2022-05-15 08:21 UTC, juice119 commented on src/main/kotlin/carracing/CarRacingView.kt
> +    fun getViewString(carRacingManager: CarRacingManager<out Int>): String {
여기서 `View` 역할을 하기 때문에 `Read`이외에 일은 하지 않을것 같다고 생각하여
`out` 을 사용했어요

2022-05-16 09:59 UTC, vsh123 approved these changes
안녕하세요!!
좋은 코드를 위해 열심히 수정하려는 흔적이 돋보이네요!! 👍 

몇가지 코멘트를 남겼으니, 다음 step에 함께 반영해보세요!!
이번스텝은 머지하도록 할게요~!

2022-05-16 09:59 UTC, vsh123 commented on src/main/kotlin/carracing/RandomIntRacingMovementRole.kt
> +    RacingMovementRole<Int> {
일부로 한칸 띄우신걸까요?

2022-05-16 09:59 UTC, vsh123 commented on src/main/kotlin/carracing/main.kt
> +    val randomIntCarRacingManager = RandomIntCarRacingManager.fromInputDto(
필드명에  random이 붙을 필요는 없을 것 같아요!

```suggestion
    val carRacingManager = RandomIntCarRacingManager.fromInputDto(
```

2022-05-16 09:59 UTC, vsh123 commented on src/main/kotlin/carracing/RandomIntCarRacingManager.kt
> +            }
`List`를 이용하여 아래와 같이 작성이 가능해보여요!

```suggestion
           val cars = List(inputDto.carCount) { Car() }
```

2022-05-16 09:59 UTC, vsh123 commented on src/main/kotlin/carracing/RandomIntCarRacingManager.kt
> +    carList: CarList,
`carList`와 같이 특정 컬렉션 네이밍보다는 복수형으로 네이밍을 해주면 어떨까요?
[참고](https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/)

2022-05-16 09:59 UTC, vsh123 commented on src/main/kotlin/carracing/CarList.kt
> +class CarList(val cars: List<Car> = mutableListOf()) {
default가 mutable한 list일 필요가 있을까요?

2022-05-16 09:59 UTC, vsh123 commented on src/main/kotlin/carracing/RandomIntRacingMovementRole.kt
> +class RandomIntRacingMovementRole(
해당 class명은 `RandomIntRacingMovementRole`인데, 내부에는 random과 관련된 요소가 보이지 않아요! 네이밍을 다시 고려해보면 어떨까요?

2022-05-16 09:59 UTC, vsh123 commented on src/main/kotlin/carracing/main.kt
> +const val VIEW_STRING_SEPARATOR = "\n"
2개의 상수는 View에 있어도 좋을 것 같아요!

2022-05-16 09:59 UTC, merged

2022-05-16 16:03 UTC, juice119 commented on src/main/kotlin/carracing/CarList.kt
> +class CarList(val cars: List<Car> = mutableListOf()) {
이것은 추후 확장성을 고려하여 처음 부터 `mutableList`를 사용하였습니다.
리스트 추가가 불가능한 `list`방식을 사용하는것이 좋을까요?

2022-05-16 16:09 UTC, juice119 commented on src/main/kotlin/carracing/RandomIntRacingMovementRole.kt
> +    RacingMovementRole<Int> {
잘못해서 엔터가 하나 더 들어간것 같네요
`addKtlintCheckGitPreCommitHook` 다시 적용하였습니다

확인 감사합니다