Step3 : 자동차 경주
next-step/kotlin-racingcar pull request #523
Opened 2022-05-12 10:13 UTC by Rok93

찬인님 Step2 이후로 조금 늦었네요! 
Step3 구현해서 제출드립니다. 🙇‍♂️ 

"자바의 전략패턴을 코틀린에서는 어떻게 써야할까?"라는 고민을 하면서 유사하게 구현해봤는데, 처음에는 원래 많이 짜던 방식(인터페이스를 두고 구현체만 바꿔치기한다)으로 구현했다가 너무 `자바스러운` 것 같다는 생각이 들어 `함수형 파라미터`를 사용해서 구현해봤습니다. 👀 
(잘 못 구현한거 같아서 찝찝하네요. 😂) 

이번 스텝도 잘 부탁드립니다. 🙏

2022-05-13 15:14 UTC, pci2676 requested changes
레이싱카 미션 1단계 하시느라 고생하십니다!
자바의 인터페이스를 코틀린의 함수형 파라미터로 대체한 것 좋았습니다! 해당 부분은 코트린스럽게 잘 작성하셨습니다 💯

조금 더 코틀린 감수성을추가해볼 수수 있는 부분에 코멘트를 남겨두었고, 이외에 더 수정해보면 좋을 부분에 코멘트를 남겨두었습니다!

2022-05-13 15:14 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/Car.kt
> +class Car private constructor(
`Car` 클래스에 생성자가 하나도 없어서 객체의 생성이 불가능해졌습니다..!!

2022-05-13 15:14 UTC, pci2676 commented on src/test/kotlin/racingcar/domain/RacingGameTest.kt
> +        ).forAll { (cars) ->
2대 미만 이라는 경계가 확실한 케이스인데 자동차가 0일때의 상황을 테스트 할 필요는 없을 것 같습니다!
경계에 맞닿아 있는 부분만 테스트해도 충분할 것 같아요!
불필요한 테스트도 쌓이다 보면 비용이 된다고 생각합니다~!

2022-05-13 15:14 UTC, pci2676 commented on src/test/kotlin/racingcar/domain/RacingGameTest.kt
> +        actual[1][1].position shouldBe 2
테스트의 검증이 테스트의 이름(의도)와 다른것 같아보여요!
size만 검증해도 충분한거 아닌가요?

2022-05-13 15:14 UTC, pci2676 commented on src/test/kotlin/racingcar/domain/RacingGameTest.kt
> +    "자동차 경주 게임을 시도횟수만큼 실행한다.2" {
테스트의 검증 단계를 봤을때 움직이지 않는 것을 확인하는 것이 목적인 것 처럼 보입니다~!
테스트는 해당 객체가 행동하는 것과 동일한 수준의 테스트를 하는게 좋다고 생각합니다!
지금 `RacingGame`은 `Car`들을 이용해서 상호작용하는게 역할인 객체로 보이는데요. 실제로 검증하는건 `Car`의 `moveOrNot`이랑 다를바가 없어 보입니다.

2022-05-13 15:14 UTC, pci2676 commented on src/test/kotlin/racingcar/domain/TryNumberTest.kt
> +    "시도횟수가 1이상이면 정상적으로 객체를 생성한다." {
여기서도 경계값은 1인것으로 보이는데요 1이상의 값을 전부 테스트하는 것이 의미가 있을까 고민이 되네요.
1,2,3,4를 테스트 하는것과 1,2,3,4,5,6,7,8,9,10을 테스트를 하는것과 다를게 없을것 같아요!

2022-05-13 15:14 UTC, pci2676 commented on src/test/kotlin/racingcar/domain/CarTest.kt
> +        listOf(
`condition이 4 미만이면 자동차가 전진하지 않는다.` 테스트와 묶어서 3,4 경계값만 테스트해도 충분할 것 같습니다~!

2022-05-13 15:14 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/TryNumber.kt
> +class TryNumber(value: Int) {
일단 `TryNumber`가 가변객체라서 문제가 되는 것은 아니지만 코틀린 감성을 얹어보도록 하죠!
`TryNumber`를 `Car`처럼 불변객체로 변경해봅시다! 가변 프로퍼티를 제거하고 [inline 클래스](https://kotlinlang.org/docs/inline-classes.html)로 변경해보는건 어떨까요!

2022-05-13 15:14 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/TryNumber.kt
> +        value--
일괄적으로 `this`를 사용하는건 어떨까요?
```suggestion
        if (this.isComplete()) {
            throw IllegalStateException("잔여 시도횟수가 없습니다.")
        }

        this.value--
```

2022-05-13 15:14 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/TryNumber.kt
> +    fun isComplete(): Boolean = value == USE_COMPLETED_TRY_NUMBER
이것도 한번 코틀린 감성을 얹어봅시다!
이 메서드는 해당 객체의 상태를 확인하는것으로 보이는데요.
코틀린의 프로퍼티는 상태를 나타내니까 요렇게 사용자 정의 getter를 이용하는 방법도 있습니다~!
```suggestion
    val isComplete: Boolean
        get() = value == USE_COMPLETED_TRY_NUMBER
```

2022-05-13 15:14 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +        require(cars.size >= MIN_CARS_SIZE)
메세지 정의를 해주는게 명확하게 확인하기 좋지 않을까요?

2022-05-13 15:14 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +    fun play(movementStrategy: () -> Int): List<List<Car>> {
컬렉션<컬렉션> 은 코드를 파악하기도 유지보수하기도 힘들것 같습니다~!
컬렉션을 담을수 있는 [일급컬렉션](https://jojoldu.tistory.com/412)을 생성해보는건 어떨까요?

2022-05-13 15:14 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +        while (!tryNumber.isComplete()) {
`isComplete()`를 `!`를 이용할 거라면 처음부터 `isNotComplete()`로 하는게 코드를 읽기 더 좋지 않을까요?
```suggestion
        while (tryNumber.isNotComplete()) {
```

2022-05-13 15:14 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +    fun play(movementStrategy: () -> Int): List<List<Car>> {
함수형 파라미터를 이용해서 테스트하기 힘든 부분을 잘 처리하셨네요! 👍

2022-05-13 15:14 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/Car.kt
> +        check(position < INITIAL_POSITION) { "자동차의 처음 position은 0이상의 숫자만 가능합니다. position = $position" }
이거.. 수식이 잘못된것 같지 않나요? 😅

2022-05-14 11:04 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/Car.kt
> +class Car private constructor(
아이쿠... 부생성자로 뭔가 해보려고하다가 불필요한 것 같아서 부생성자는 지웠는데, 주 생성자에 private 제한자로 둔걸 깜빡했네요. 😂

2022-05-14 11:07 UTC, Rok93 commented on src/test/kotlin/racingcar/domain/RacingGameTest.kt
> +        ).forAll { (cars) ->
비어있는 경우는 경우에 대해서는 불필요한 테스트 코드 같기는 하네요. 🤔 
kotest의 parameterized test 코드를 많이 짜보고 싶은 맘에 불필요하게 테스트 케이스를 자꾸 늘렸던 것 같아요. 👀

2022-05-14 11:12 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/Car.kt
> +        check(position < INITIAL_POSITION) { "자동차의 처음 position은 0이상의 숫자만 가능합니다. position = $position" }
아이쿠.... check는 잘 안쓰던 함수라 check 함수에 전달되는 파라미터가 true인 경우에 예외가 발생한다고 착각했네요. 😂
내부 로직 확인해보니 파라미터로 전달되는 value(:Boolean)가 false인 경우에 예외가 발생하는 함수였군요. 👍

2022-05-14 11:20 UTC, Rok93 commented on src/test/kotlin/racingcar/domain/RacingGameTest.kt
> +        actual[1][1].position shouldBe 2
처음 테스트의 의도와 달리 `movementStrategy`에 대한 테스트 또한 같이 작성하고있었군요. 👀 
사이즈만 검증하는 것으로 변경하였습니다. 💪

2022-05-14 11:22 UTC, Rok93 commented on src/test/kotlin/racingcar/domain/RacingGameTest.kt
> +    "자동차 경주 게임을 시도횟수만큼 실행한다.2" {
코멘트로 남겨주신 말씀에 매우매우 크게 공감하여, 해당 테스트 케이스는 제거했습니다. 🙏

2022-05-14 11:28 UTC, Rok93 commented on src/test/kotlin/racingcar/domain/TryNumberTest.kt
> +    "시도횟수가 1이상이면 정상적으로 객체를 생성한다." {
테스트 케이스가 너무 적으면 안된다는 생각에 저도 모르게 무의미한 테스트 케이스를 자꾸 추가하고 있었네요. 🙄👀

2022-05-14 11:36 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/TryNumber.kt
> +        value--
에구구....`this` 썼다가 안썻다가... 상당히 일관성이 없는 코드였네요. 🙄

2022-05-14 11:39 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +        while (!tryNumber.isComplete()) {
확실히 `!`를 붙인 부정문은 직관적으로 바로 이해가 안되는 것 같네요. 😃

2022-05-14 11:48 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +        while (!tryNumber.isComplete()) {
해당 코멘트에서는 조금 고민되는 부분이 있습니다! 

현재 `TryNumber#isComplete` 함수는 외부(=RacingGame)에서도 사용되고 있지만 내부(=consume함수)에서도 사용되고 있는데, 이 둘은 `게임이 진행중이 상태`, `게임이 끝난 상태` (반대의 상황)에서 모두 쓰이고 있어서 결국 `isComplete()`로 명칭을 짓던지 `isNotComplete()`로 명칭을 짓던지 결국 `!` 부정문의 사용을 피하기가 힘들 것 같습니다. 

그렇다고 별개의 메서드로 쪼개는 것은 과하다고 생각하는데 지금의 경우에는 따로 메서드를 분리하거나 `!`를 사용하는 방법밖에 없다고 생각하는데 저는 후자가 낫다고 판단하여 `!`를 사용하는 지금의 형태로 유지했습니다. 
(개인적으로 isPlaying이 조금 더 의미있다고 생각되서 네이밍 변경하였습니다!)

2022-05-14 11:51 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +        require(cars.size >= MIN_CARS_SIZE)
아이쿠... 에러 메시지를 안적었군요... 👀   나중에 작성한다는걸 깜빡한 것 같습니다. 
에러 메시지 추가하겠습니다. 👍

2022-05-14 12:05 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/TryNumber.kt
> +    fun isComplete(): Boolean = value == USE_COMPLETED_TRY_NUMBER
오... 코틀린스러움... 너무 좋네요. 😆 

지금 과정과는 조금 별개의 내용이지만, 지금처럼 `isComplete()` 함수를 `isComplete` 프로퍼티로 변경하게 되면, JPA를 사용한다는 가정에서 TryNumber Entity가 생성하는 테이블의 컬럼에 `isComplete 컬럼`이 생기는건지 아닌건지 궁금합니다. 🤔

관련된 내용을 이전에 들은 적이 있었던 것 같은데... 오래전에 봤던 내용이라 어디서 봤던 내용인지 기억이 잘 안나네요. 🥲 
(자바 진영의 경우 특정 애너테이션으로 특정 필드를 컬럼으로 생성하지 않는다고 명시해야했던 것 같은데... 코틀린은 별도로 애너테이션 붙일 필요가 없다고 했던 것 같은데.. 어렴풋이 기억이 나서 이 내용이 맞는지가 궁금하네요. 👀)

2022-05-14 13:41 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +        while (!tryNumber.isComplete()) {
저같은 경우에 그러면 두개의 메서드(`isComplete`, `isNotComplete`)를 전부 만드는 편입니다.
단순하게 단일책임의원칙으로 바라본다면 개별 메서드를 만드는 것이 옳다고 생각합니다!
다만 두 가지가 완벽하게 대칭점에 있고 공개 메서드라는점에서 `isComplete`를 구현했다면 `isNotComplete`는 `!isComplete`로 구현할 것같네요!

2022-05-14 13:42 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/TryNumber.kt
> +    fun isComplete(): Boolean = value == USE_COMPLETED_TRY_NUMBER
엇 요거는 JPA에서 확인 한번 해봐야겠네요~! 저도 한번 확인해보고 코멘트 드릴게요~!

2022-05-16 06:58 UTC, Rok93 commented on src/main/kotlin/racingcar/domain/TryNumber.kt
> +    fun isComplete(): Boolean = value == USE_COMPLETED_TRY_NUMBER
jason이 발표하셨던 [어디 가서 코프링 매우 알은 체하기](https://youtu.be/ewBri47JWII?t=5582)에서 언급해주셨네요! 😃 
AccessType이 Field인 경우에은ㄴ `@Transient` 없이도 컬럼으로 인지하지 못하게 할 수 있다고 하네요! 😃

2022-05-16 09:03 UTC, pci2676 approved these changes
3단계 리뷰반영해주시느라 고생하셨습니다!

다음단계에서 같이 고치면 좋을 부분에 리뷰 남겨두었으니 다음단계 진행하면서 반영해주시면 좋을것 같아요!

그리고 이전에 문의해주셨던 kotlin 사용자 게터에 따른 jpa 영속은 이전에 재성님이 [코프링 세미나](https://youtu.be/ewBri47JWII?t=5581)에서 다뤄주신적이 있네요~!
backing field가 생성되지 않기때문에 컬럼이 생기는것에 대해 우려하는 점은 발생하지 않을것 같습니다!

머지하겠습니다!

2022-05-16 09:03 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +class Cars(
일급컬렉션 👍

2022-05-16 09:03 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +        get() = cars.toList()
흐흐 이름이 겹쳐서 `value`로 네이밍을 하신 것 같군요!
요거는 아래와 같이 변경해서 많이 쓰는편 입니다!
```suggestion
    private val _cars: List<Car>,
) {
    val cars: List<Car>
        get() = _cars.toList()
```

2022-05-16 09:04 UTC, merged

2022-05-16 09:05 UTC, pci2676 commented on src/main/kotlin/racingcar/domain/TryNumber.kt
> +    fun isComplete(): Boolean = value == USE_COMPLETED_TRY_NUMBER
아이코 이미 확인하셨었군요! ㅎㅎ