Step3 리뷰 요청 드려요~
next-step/kotlin-racingcar pull request #524
Opened 2022-05-12 10:25 UTC by liquidjoo

안녕하세요

아직 부족하지만 저번 피드백 주신 것을 통해서 코틀린 답게 한번 해보았습니다!!

표현식 위주로 해보았는데 어색하면서도 재밌네요

감사합니다 🙇

2022-05-12 12:34 UTC, Flamme1004K requested changes
안녕하세요!

확실히 지난번과 다르게 많은 부분이 개선이 되었네요! 그리고, 자동차 구현 정말 잘해주셨습니다! 🥳

요번에도 또 한 발자국 나아가 봅시다! 🙌

몇 가지 코멘트를 남겼으니 확인 부탁드립니다. 확인 후 다시 요청 부탁드립니다!

궁금하신 점에 대해서는 DM 부탁드립니다!

2022-05-12 12:34 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +
postion에 대해 외부 수정을 불가능하기 위하여, 새로 객체를 만드는 방식을 선택하셨군요! 👍👍

외부 수정을 불가능하기 위하여, 해당 방법을 선택하셨다면, 아래와 같이 backing-properties를 사용하는 방법도 있습니다.

[backing-properties](https://kotlinlang.org/docs/coding-conventions.html#names-for-backing-properties)

```
class Car(private var _position: Int = DEFAULT_POSITION) {

    val position: Int
        get() = _position

    fun move(isMove: Boolean) {
        if (isMove) {
            _position += PLUS_POSITION
        }
    }

    companion object {
        private const val DEFAULT_POSITION = 0
        private const val PLUS_POSITION = 1
    }
}

```

그리고 data class를 사용했다면 copy() 메소드를 사용하여 deep copy()를 사용하는 것도 있습니다.

하지만, 자동차가 움직였다고, 새로운 자동차를 만들어줘야 할까? 는 의문이 듭니다. move()가 진행될수록 🚗🚕🛻 이렇게 변화하는 것 같아요.

move()라는 함수가 움직이는 역활만 했으면 좋겠습니다! 😊

2022-05-12 12:34 UTC, Flamme1004K commented on src/main/kotlin/racingcar/DefaultMoveStrategy.kt
> +class DefaultMoveStrategy : MoveStrategy {
통제 불가능한 랜덤 값을 인터페이스를 통하여 테스트가 용이하도록 만들어줬군요! 대단합니다! 👍👍

2022-05-12 12:34 UTC, Flamme1004K commented on src/main/kotlin/racingcar/MoveStrategy.kt
> +@FunctionalInterface
`@FunctionalInterface` 를 사용한 이유를 알고 싶습니다! 🙋🏻

2022-05-12 12:34 UTC, Flamme1004K commented on src/main/kotlin/racingcar/README.md
> +[x] 각 라운드별 자동차 일급컬렉션인 (`Cars`) 의 값을 제어하는 일급컬렉션 생성 ((data 클래스 사용해도 괜찮음 객체를 새로 생성하기에 별도의 메모리 구조를 가짐))
요구 사항 정리 좋습니다!👍👍

2022-05-12 12:34 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Racing.kt
> +        }
```suggestion
       repeat(roundCount) {
            val racingCars = if (racing.isNotEmpty()) racing.last() else cars
            racing.add(racingCars.move(moveStrategy))
        }
```

`repeat()`를 사용하면 반복에 대해 더 쉽게 처리할 수 있습니다  😊

참고
- [repeat()](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/repeat.html)

2022-05-12 12:34 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Racing.kt
> +    fun result() = racing.toList()
가변 리스트를 불변 리스트로 만들어서 외부에서 사용할 수 있도록 만드셨군요!👍👍

위에서 알려준 backing properties 방식도 한번 사용해 보세요! 사용해 보고 느낀 점 부탁드립니다!😊

[backing-properties](https://kotlinlang.org/docs/coding-conventions.html#names-for-backing-properties)

2022-05-12 12:34 UTC, Flamme1004K commented on src/main/kotlin/racingcar/RacingApplication.kt
> +    require(!roundCount.isNullOrBlank()) { IllegalArgumentException("잘못된 요청 입니다.") }
```suggestion
    RacingView.InputView.displayCarCount()
    val carCount: String = readln()
    require(carCount.isNotBlank()) { "잘못된 요청 입니다." }

    RacingView.InputView.displayRoundCount()
    val roundCount: String = readln()
    require(roundCount.isNotBlank()) { "잘못된 요청 입니다." }
```

kotlin 1.6부터는 readLine() 대신 readln()을 사용할 수 있습니다. 요번 기회에 readLine()과 readln()의 차이를 찾아보세요.😊 

<img width="728" alt="스크린샷 2022-05-12 오후 9 27 49" src="https://user-images.githubusercontent.com/50702723/168074608-953cf86f-c916-4060-949d-5205e9644ddf.png">

require는 맞지 않으면, IllegalArgumentException을 보냅니다! 🤩 추가로 에러 메시지는 상수로 관리해 주세요!

참고 
- [kotlin readln](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/readln.html)
- [kotlin 1.6.0 released](https://blog.jetbrains.com/ko/kotlin/2021/12/kotlin-1-6-0-is-released/)

2022-05-12 12:34 UTC, Flamme1004K commented on src/test/kotlin/racingcar/RacingTest.kt
> +internal class RacingTest {
자동차 결과에 대한 테스트도 추가해주셨으면 합니다! 🤩

2022-05-13 07:35 UTC, liquidjoo commented on src/main/kotlin/racingcar/Car.kt
> +
불변객체를 보장하기 위함이라고 생각을 했는데요~
현재 요구사항에서 각 단계별 자동차의 포지션을 보여주기 위해서는
각 단계 마다 포지션을 갖고 있는 자동차 객체가 있으면 좋을 것 같았어요
물론 움직이지 않으면 this 를 통해 현재 객체를 돌려주는 방안으로 택 했어요 

현재 move에 대한 테스트는 프로퍼티를 get 하는 형식으로 불러와 테스트를 해야할 것 같아서
객체 자체를 비교하는것이 더 좋을 것 같아서 현재 방식을 택했어요~

불변 객체가 가지는 단점 보다 장점이 더 많다고 생각해서 이렇게 설계를 해보았어요 :)
혹시 position 만 변하게 되면 어떤 장점이 있나요?

2022-05-13 07:38 UTC, liquidjoo commented on src/main/kotlin/racingcar/MoveStrategy.kt
> +@FunctionalInterface
습관적으로 .. 자바에서 람더 표현식을 사용하려고 했네요
이런 경우는 자바 인터페이스를 코틀린에서 사용할 수 있게 SAM 이라는 것이 있던데 지금은 필요 없을 것 같네요!

2022-05-13 07:45 UTC, liquidjoo commented on src/main/kotlin/racingcar/RacingApplication.kt
> +    require(!roundCount.isNullOrBlank()) { IllegalArgumentException("잘못된 요청 입니다.") }
자동차 요구사항 힌트에 있어서 사용해보았는데 readIn 구현체를 보니 제가 사용했던 것이 포함되어 있는 것 같네요~
?와 같은 연산자? 를 사용하지 않아도 되어서 좋네요 :)

2022-05-13 07:51 UTC, liquidjoo commented on src/main/kotlin/racingcar/Racing.kt
> +    fun result() = racing.toList()
방어적 복사를 컬렉션을 사용하지 않고 지원해줘서 좋은 것 같아요~
워낙 자바를 하다보니 이런 부분은 어색하면서 신기하네요 :)

2022-05-13 08:10 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +
제 생각이지만, 불변 객체를 보장하기 위함과 그리고 postion 만 변화게 한다라는 부분은 함수지향적으로 접근할 것인지, 객체지향적으로 접근할 것인지에 대한 차이인 것 같아요. 함수지향적으로 선택을 한다면, 결국 객체에 대해서 그리고 리스트에 대해서 항상 불변을 지켜줘야 하는 경우가 생기고, 객체지향적으로 선택을 한다면 car가 가변적인 position에 대해서도 관리를 할 수 있다고 봅니다.

이런 부분은 선택인 것 같아요. 예전에 저도 성주님 코드같이 모든 객체를 불변으로 지키기 위해서 함수마다 새로운 객체를 리턴하도록 만들었는데, 코틀린을 사용하다 보니, 외부에서는 불변으로 쓰되, 내부에서는 가변으로 움직이게 하는 게 더 유용할 때도 많고, 함수가 주려는 메시지가 명확해지는 경우가 많아서, 가변적인 데이터는 클래스 안에서 컨트롤하게 만들어주고 있습니다. 😅

그리고 때에 따라서 불변 객체를 꼭 지켜줘야하는 상황에 대해서는 data class의 copy()를 많이 사용하고 있어요. 현재 경우는 position만 있기 때문에 새로운 객체를 만들어줘도 되지만, 파라미터가 많아지고, 일부분만 변경이 필요할 때 제가 변경할 파라미터에 대해서 변경이 용이하기 때문이에요. 😊

2022-05-14 01:46 UTC, Flamme1004K approved these changes
안녕하세요! 

요번에도 많은 부분이 개선되었네요. 훌륭합니다! 🤩

다음 미션을 위하여 머지하도록 하겠습니다! 
추가적인 피드백에 대해서는 다음 미션에 반영해 주시면 되겠습니다🙌

화이팅입니다. 🥳

2022-05-14 01:46 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Cars.kt
> +    }
```suggestion
    fun move(moveStrategy: MoveStrategy): Cars {
        val newCars = cars.map { it.move(moveStrategy.isMove()) }
        return Cars(newCars)
    }
```

java에서는 `Stream API`의 `map`을 사용해야 가능하지만, 코틀린에는 `CollectionAPI`에 기본적으로 `map`이 있습니다.

`map`을 사용해서 새로운 리스트를 만들어주는 것도 좋아보이네요 😊

2022-05-14 01:46 UTC, Flamme1004K commented on src/main/kotlin/racingcar/RacingApplication.kt
> +    require(carCount.isNotBlank()) { "잘못된 요청 입니다." }
InputView에다가 다 넣어주면, 더 깔끔해지지 않을까요?🤔

2022-05-14 01:46 UTC, Flamme1004K commented on src/test/kotlin/racingcar/CarsTest.kt
> +        })
Test 케이스마다 moveStrategy가 성공하는 케이스의 코드가 중복이 되고 있다고 생각합니다.

해당 MoveStrategy를 Test 패키지에다가 SuccessMoveStrategy / FailMoveStrategy 를 만들어서, 테스트 케이스 내에서도 중복을 제거해 보는 건 어떨까요?🤔

2022-05-14 01:47 UTC, Flamme1004K commented on src/test/kotlin/racingcar/RacingTest.kt
> +        assertAll("", {
여기서 heading에 ""를 넣은 이유가 있을까요?

2022-05-14 01:47 UTC, merged

2022-05-15 15:07 UTC, liquidjoo commented on src/main/kotlin/racingcar/RacingApplication.kt
> +    require(carCount.isNotBlank()) { "잘못된 요청 입니다." }
InputView 를 단순 Dto 로 보아야할지 비지니스 로직을 갖고 있는 Vo 로 보아야할지 고민이 많이 되었어요!!

2022-05-15 15:07 UTC, liquidjoo commented on src/test/kotlin/racingcar/RacingTest.kt
> +        assertAll("", {
아! 저의 실수 입니다 😭