Step3 구현
next-step/kotlin-racingcar pull request #533
Opened 2022-05-13 12:20 UTC by jinwoo-k

2022-05-14 04:32 UTC, Laterality requested changes
안녕하세요!

3단계도 빠르게 구현해주셨네요 👍 

간단한 코멘트를 남겨드렸습니다. 확인 부탁드릴게요.

궁금하신 점은 언제든 DM 주세요 :)

2022-05-14 04:32 UTC, Laterality commented on src/main/kotlin/step3/Car.kt
> +    fun move(): Car = Car(position + 1)
불변 객체로 만드셨군요 👍 

도메인에 속하는 클래스로 보이는데, 중요한 속성 중 하나인 `position`을 외부에서 마음대로 지정해 인스턴스를 생성할 수 있네요.

`class Car private constructor(val position: Int)` 처럼 생성자를 private으로 만들고 `position`이 1로 초기화된 인스턴스를 생성하는 별도의 정적 팩토리 메서드를 제공하면 어떨까요? 

대신, data class에는 [`copy`](https://kotlinlang.org/docs/data-classes.html#copying)메서드가 내장돼 있기 때문에 이 경우 외부에서 `position`의 조작을 완전히 제한하려면 일반 class로 생성하는 것이 좋겠네요!

2022-05-14 04:32 UTC, Laterality commented on src/main/kotlin/step3/Car.kt
> +    override fun toString(): String = "-".repeat(position)
뷰의 출력에 사용되는 메서드로 보이네요. 도메인에서 뷰의 관심사를 분리해보면 어떨까요?

2022-05-14 04:32 UTC, Laterality commented on src/main/kotlin/step3/InputView.kt
> +    fun readInt(): Int {
내부에서만 호출되는 메서드라면 `private`으로 선언하면 어떨까요?

2022-05-14 04:32 UTC, Laterality commented on src/main/kotlin/step3/InputView.kt
> +        if (str.isNullOrEmpty() || !str.all { it.isDigit() }) {
[참고] `str?.toIntOrNull() == null` 같은 조건식을 사용할 수도 있겠네요!

2022-05-14 04:32 UTC, Laterality commented on src/main/kotlin/step3/MoveDecisionMaker.kt
> +    fun canMove(digit: Int = getRandomDigit()): Boolean = digit > 4
매직 넘버는 상수로 분리하면 어떨까요?

2022-05-14 05:07 UTC, jinwoo-k commented
@Laterality 리뷰 감사드립니다. 피드백 내용 수정했습니다.
Car 클래스의 경우 동등성 테스트에서 position 이 같으면 같은 객체로 판단하게 하기 위해 equals, hashcode 메서드 추가했습니다. 
다시 검토 부탁드립니다 :)

2022-05-17 13:45 UTC, Laterality requested changes
안녕하세요.

3단계도 빠르게 구현해주셨네요!

간단한 코멘트 남겨드렸는데, 확인 부탁드립니다.

다음 리뷰때 머지하도록 할게요!

2022-05-17 13:45 UTC, Laterality commented on src/main/kotlin/step3/Car.kt
> +    }
companion object는 클래스 본문의 가장 마지막에 위치시켜주세요! [참고: Kotlin - Coding conventions](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

2022-05-17 13:45 UTC, Laterality commented on src/main/kotlin/step3/Car.kt
> +    override fun equals(other: Any?): Boolean {
메서드 사이는 한 줄씩 띄우면 어떨까요?

2022-05-17 13:45 UTC, Laterality commented on src/main/kotlin/step3/MoveDecisionMaker.kt
> +        const val MOVE_DECISION_CRITERIA = 4
이 상수도 외부에서 사용되지 않는다면 `private`으로 선언할 수 있겠네요!

2022-05-17 13:45 UTC, Laterality commented on src/main/kotlin/step3/Race.kt
> +class Race(val cars: List<Car>, private val tries: Int, private val currentTries: Int = 1) {
내부에서만 쓰이는 생성자라면 `private`으로 선언하면 어떨까요?

2022-05-20 12:14 UTC, Laterality approved these changes
안녕하세요!

코드를 깔끔하게 정리해주셨네요 👍 

이번 단계는 이만 머지하도록 하겠습니다.

다음 단계 PR을 먼저 올려주셨네요. 다음 단계 리뷰 필요하신 시점에 다시 리뷰 요청 부탁드립니다.

고생 많으셨습니다!

2022-05-20 12:14 UTC, merged