Step4: 자동차 경주 (우승자)
next-step/kotlin-racingcar pull request #573
Opened 2022-05-15 13:34 UTC by aid95

말씀 주신 메뉴판 예시를 생각해봤을때 GameEngine은 run 메세지를 던지고 내부에서 처리하도록 변경해봤습니다 :> !!

2022-05-15 14:43 UTC, BeokBeok requested changes
이전 단계 피드백과 자동차 경주(우승자) 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2022-05-15 14:43 UTC, BeokBeok commented on src/main/kotlin/racing/model/Car.kt
> +data class Car constructor(private val position: Int, private val name: String = "unknown") : Comparable<Car> {
constructor는 생략하셔도 됩니다 😄

2022-05-15 14:43 UTC, BeokBeok commented on src/main/kotlin/racing/model/Car.kt
> +data class Car constructor(private val position: Int, private val name: String = "unknown") : Comparable<Car> {
Comparable 구현 👍

2022-05-15 14:43 UTC, BeokBeok commented on src/main/kotlin/racing/model/Car.kt
> +data class Car constructor(private val position: Int, private val name: String = "unknown") : Comparable<Car> {
```suggestion
data class Car(
    private val position: Int,
    private val name: String = "unknown"
) : Comparable<Car> {
```
두 개 이상의 프로퍼티를 캡슐화하는 경우에는 개행을 해주면 좀 더 보기 좋아져요

2022-05-15 14:43 UTC, BeokBeok commented on src/main/kotlin/racing/model/Car.kt
> +        fun spawnWithPositionAndName(position: Int, name: String) = Car(position, name)
기존에 private constructor를 사용함으로써 팩토리 메서드를 만들어주셨는데요.
private constructor를 제거하게 되면서, 이 두 함수는 불필요해보여요.

2022-05-15 14:43 UTC, BeokBeok commented on src/main/kotlin/racing/model/Cars.kt
> +            .map { it[0] }
Cars 객체가 우승자 관리에 대한 책임도 가지고 있네요.
Winner 라는 클래스를 별도로 구현해서, 해당 클래스에서 우승자를 관리하도록 하면 어떨까요?

2022-05-15 14:43 UTC, BeokBeok commented on src/main/kotlin/racing/model/Cars.kt
> +
위의 create 함수는 사용하지 않고 있는데, 제거해보면 어떨까요?

2022-05-15 14:43 UTC, BeokBeok commented on src/main/kotlin/racing/scene/InputScene.kt
>          setStageNumber()
start 함수를 분리한 것에 대한 이점이 없는 것 같아요.
run 함수에 합쳐도 될 것 같아요.

2022-05-15 14:43 UTC, BeokBeok commented on src/main/kotlin/racing/scene/PlayScene.kt
> +    }
on계열의 함수는 흔히 콜백 함수일 경우에는 앞에 on을 붙여줘요.
그런데 onDestroy는 콜백함수가 아니니, 일반 함수와 같이 동사구의 형태로 이름을 작성해보면 어떨까요?

2022-05-16 13:02 UTC, aid95 commented on src/main/kotlin/racing/model/Car.kt
> +data class Car constructor(private val position: Int, private val name: String = "unknown") : Comparable<Car> {
헛...😓 죄송합니닷...!!

2022-05-16 13:05 UTC, aid95 commented on src/main/kotlin/racing/model/Car.kt
> +        fun spawnWithPositionAndName(position: Int, name: String) = Car(position, name)
반복적으로 채워야 할 값이 있는 경우가 아닌 경우 팩터리 메서드를 만드는 건 필요성이 없군용..🤔

2022-05-16 13:06 UTC, aid95 commented on src/main/kotlin/racing/model/Cars.kt
> +            .map { it[0] }
헉 좋은 의견 감사합니당!! 가장 잘 알고 있는 객체라 Cars 내부에 만들었는데 말씀 주신 Winner에 위임하는 것이 더 적절하겠군용..!

2022-05-16 13:06 UTC, aid95 commented on src/main/kotlin/racing/model/Cars.kt
> +
👍🏻👍🏻👍🏻

2022-05-16 13:06 UTC, aid95 commented on src/main/kotlin/racing/scene/InputScene.kt
>          setStageNumber()
헛 구조를 변경하면서 놓친 부분이군용 감사합니다!!

2022-05-16 13:09 UTC, imdudu1 commented on src/main/kotlin/racing/scene/PlayScene.kt
> +    }
감사합니닷!! 이 부분은 start와 대칭적인 느낌으로 end로 지어봤습니닷!!😆

2022-05-16 15:57 UTC, BeokBeok commented on src/main/kotlin/racing/model/Car.kt
> +        fun spawnWithPositionAndName(position: Int, name: String) = Car(position, name)
기존 데이터를 유지하되 특정 값만 변경하고 싶으시면 copy 함수를 활용하시면 됩니다.
다만 copy 함수는 기본 타입에 대해서는 깊은 복사가 일어나지만 그 외의 타입은 얕은 복사가 일어나므로, 이런 경우에는 팩토리 함수를 만들어주시면 됩니다!

2022-05-16 16:08 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2022-05-16 16:08 UTC, BeokBeok commented on src/main/kotlin/racing/model/Car.kt
> +    private val name: String = "unknown"
"unknown" 이라는 문구도 매직 리터럴에 해당합니다.
상수로 정의해주시면 좋을 것 같아요.

2022-05-16 16:08 UTC, BeokBeok commented on src/main/kotlin/racing/model/Car.kt
> +        return Car(position + this.getStep(randomValue), name)
```suggestion
        return Car(position + getStep(randomValue), name)
```
this는 생략해주셔도 될 것 같아요.

2022-05-16 16:08 UTC, BeokBeok commented on src/main/kotlin/racing/model/Cars.kt
> +    fun getWinners(): Winner = Winner(cars)
Winner 클래스를 만들어서 잘 분리해주셨네요 👍 
하지만 결국 Car 클래스에서 Winner에 대한 책임을 가지고 있는 것은 동일해요.
Car 클래스를 통해서 Winner 객체를 생성하기보다는, 외부에서 Winner 객체를 생성하도록 변경해보면 어떨까요?

혹시 책임을 갖는 부분에 대한 판단이 어려우시다면, "XXX클래스가 XXX한다" 라는 문장을 만들어보시면 이해하기 쉬워요.
- 자동차들은 우승자들을 얻는다 (X)

2022-05-16 16:08 UTC, BeokBeok commented on src/main/kotlin/racing/model/Winner.kt
> +data class Winner(private val cars: List<Car>) {
Winner 클래스는 data class보다는 일반 class가 더 적합해보여요.
단순히 데이터를 wrapping하는 목적이 아니라, Winner 클래스만의 기능이 존재하니까요.

2022-05-16 16:08 UTC, BeokBeok commented on src/main/kotlin/racing/model/Winner.kt
> +    }
toString 함수에는 단순히 문자열로 변환해주는 것이라 이해가 되는데, 실제로는 우승자를 계산하는 로직이 들어있네요.
Winner 객체에 자동차 리스트들을 넣어서 생성했을 때, toString 함수를 호출하면 우승자를 알 수 있다는 점이 잘 예상이 되지 않네요.

다른 객체에서 Winner 객체에 메시지를 보내서 우승자를 알려주도록 변경해보면 어떨까요?

2022-05-16 16:08 UTC, merged