Step4 리뷰 요청 드려요~
next-step/kotlin-racingcar pull request #579
Opened 2022-05-15 17:17 UTC by liquidjoo

안녕하세요 리뷰어님

아직 부족함이 많이 있지만 코틀린 스럽게 최대한 진행해보았습니다.

이번에도 잘 부탁드리겠습니다 🙇

2022-05-16 11:53 UTC, Flamme1004K requested changes
안녕하세요!

전체적으로 구현 잘해주셨네요 💯

몇가지 코멘트를 남겼으니 확인 부탁드리겠습니다!

궁금하신 점에 대해서는 DM 부탁드립니다!! 확인 후 다시 리뷰 요청 부탁드립니다!

2022-05-16 11:53 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +    fun move(isMove: Boolean): Car = if (isMove) Car(this.name, position + PLUS_POSITION) else this
```suggestion
    fun move(isMove: Boolean): Car = if (isMove) {
        this.copy(position = position + PLUS_POSITION)
    } else {
        this
    }
```

- Postion이 변경 될 때마다 이름까지 모두 새로 넣는 것보다 data class의 copy()를 통하여 특정 부분만 변경해주는게 좋다고 생각합니다.
- if절에 대한 코드 블럭에 대해서는 저는 명확하게 표현해주고 있습니다.

2022-05-16 11:53 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +    fun isWinner(position: Int) = this.position == position
```suggestion
    fun isWinner(position: Int) : Boolean = (this.position == position)
```

리턴 값에 대해 명시해 주고, 비교에 대해 한번 감싸줘서 표현하면, 코드에 대한 가독성이 더 좋아지지 않을까요? 🤔

2022-05-16 11:53 UTC, Flamme1004K commented on src/main/kotlin/racingcar/CarSelector.kt
> +        get() = _names
`_names`에서 `split()`를 통하여 불변 리스트를 만들어주는데, 이를 다시 backingProperty를 통하여 전달해줘야하는 이유가 있을까요? 🤔

2022-05-16 11:53 UTC, Flamme1004K commented on src/main/kotlin/racingcar/README.md
> +[x] 우승자 화면 영역 추가
추가 요구 사항 👍👍

2022-05-16 11:53 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Racing.kt
> +
backing_property 사용 좋습니다 👍

2022-05-16 11:53 UTC, Flamme1004K commented on src/main/kotlin/racingcar/RacingView.kt
>      class InputView {
<img width="960" alt="스크린샷 2022-05-16 오후 8 38 05" src="https://user-images.githubusercontent.com/50702723/168584546-04c79d52-10da-4fcc-8d13-5ddd2a7c3ec2.png">

자바와 다르게 코틀린 파일은 함수도 넣을 수 있고, 값도 넣을 수 있고, 클래스도 넣을 수 있습니다.

이러한 장점을 이용하여 RacingView에다가 InputView, OutputView에 각각 class를 정의하는게 어떨까요? 🤔

2022-05-16 11:53 UTC, Flamme1004K commented on src/main/kotlin/racingcar/RacingView.kt
>          companion object {
InputView와 OutputView Class 모두 companion object를 사용하여 로직이 구현되고 있습니다. Object class로 변경해보는 건 어떨까요?

2022-05-16 11:53 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Winner.kt
> +        get() = _winner
코드를 개선 해볼까요? 🤔 

힌트 : init, 불변성

2022-05-16 11:53 UTC, Flamme1004K commented on src/test/kotlin/racingcar/WinnerTest.kt
> +    }
우승자가 한 명인 경우와 여러 명인 경우 테스트를 모두 해주셨군요 훌륭합니다 👍

2022-05-16 13:39 UTC, liquidjoo commented on src/main/kotlin/racingcar/Car.kt
> +    fun move(isMove: Boolean): Car = if (isMove) Car(this.name, position + PLUS_POSITION) else this
특정 부분만 변경할 수 있는 copy 가 자바에선 마치 부 생성자를 연상하게 하네요 :)
자바에서의 clone 과 copy가 유사하다고 생각했는데 오히려 생성자와 비슷한 느낌이네요 감사합니다~

2022-05-16 13:39 UTC, liquidjoo commented on src/main/kotlin/racingcar/Car.kt
> +    fun isWinner(position: Int) = this.position == position
코틀린 스럽게 표현하려고 표현식에서 타입을 추론할 수 있게 해보려고 했는데 오히려 이러면 유지보수 측에서 가독성이 떨어질 것 같네요~

2022-05-16 13:41 UTC, liquidjoo commented on src/main/kotlin/racingcar/CarSelector.kt
> +        get() = _names
split() 에서 불변 리스트를 만들어주는지 몰랐네요~ 내부 api 를 잘 확인해볼게요~

2022-05-16 13:45 UTC, liquidjoo commented on src/main/kotlin/racingcar/RacingView.kt
>          companion object {
상태 값(프로퍼티)이 없는 경우 object 를 활용해서 싱글톤으로 만들 수 있군요 :)
객체의 재사용성을 높일 수 있을 것 같아요~

2022-05-16 14:02 UTC, liquidjoo commented on src/main/kotlin/racingcar/Winner.kt
> +        get() = _winner
수정을 해보았는데요~ init 에서 map (collection api)을 통해 불변 객체를 반환을 하기에 백프로퍼티를 통해 리턴하는 책임은 제거 했습니다!

2022-05-17 12:50 UTC, Flamme1004K approved these changes
안녕하세요!

피드백 반영 감사합니다. 💯

그동안 step4 고생하셨습니다! 다음 단계를 위하여 merge 하도록 하겠습니다 🙌

몇 가지 코멘트를 남겼으니, step5 자동차 경주 진행하며, 같이 반영해주시면 되겠습니다.

궁금하신 점에 대해서는 DM 부탁드리겠습니다. 🙇🏻

다음 미션도 화이팅입니다! 🤩

2022-05-17 12:50 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +    }
```suggestion
    fun move(isMove: Boolean): Car = if (isMove) this.copy(position = position + PLUS_POSITION) else this
```

어제 if 절에 대한 코딩 컨벤션을 찾아봤는데요. 블록으로 감싸주지 않는 것도 허용을 하더군요! 이건 스타일의 차이인 것 같으니, 선택을 하시면 될 것 같습니다!

유식님은 어떤 스타일을 선호하시나요? 저는 블록으로 감싸주는 스타일을 선호하지만, 요번 같은 로직에 대해서는 블록으로 감싸주니, 코드가 지저분해 보이네요.

그렇다고, when 절로 true false로 변경하면 좋지 않을까? 라는 생각을 해봤는데, 코틀린 코딩 컨벤션에서 when 절은 3개 이상인 경우에만 쓰라고 되어있더군요!

참고 
- [if else versus when](https://kotlinlang.org/docs/coding-conventions.html#if-versus-when)

2022-05-17 12:50 UTC, Flamme1004K commented on src/main/kotlin/racingcar/RacingView.kt
> +        for (i in 0..distance) print(POSITION_VIEW)
```suggestion
        repeat(distance) { print(POSITION_VIEW) }
```

repeat로도 표현이 가능할 것 같아요! 😊

2022-05-17 12:50 UTC, Flamme1004K commented on src/test/kotlin/racingcar/RacingTest.kt
>              override fun isMove(): Boolean {
```suggestion
        val strategy = MoveStrategy { true }
```
전에 `@FunctionalInterface`를 이용하는 부분에 대한 피드백에서 SAM에 대해 언급하셔서 알아보았습니다!

MoveStartegy interface를 fun interface로 만들면 SAM을 사용하게 되면서, 코드가 더 간결해지더군요!

<img width="260" alt="스크린샷 2022-05-17 오전 7 30 35" src="https://user-images.githubusercontent.com/50702723/168692998-765fb1d0-14bd-4469-a554-cc1ae9f645a8.png">

참고
- [Functional (SAM) inteface](https://kotlinlang.org/docs/fun-interfaces.html)

2022-05-17 12:50 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Racing.kt
>      fun start(roundCount: Int, moveStrategy: MoveStrategy) {
`start()`의 `val racingCars = if (_racing.isNotEmpty()) _racing.last() else cars` 를  `val racingCars = _racing.lastOrNull() ?: cars` 로도 변경하면 더 간결해질 것 같습니다 😊

2022-05-17 13:42 UTC, merged

2022-05-19 02:09 UTC, liquidjoo commented on src/test/kotlin/racingcar/RacingTest.kt
>              override fun isMove(): Boolean {
아하 fun 이 붙었어야 하는 군요!!! 👍

2022-05-19 02:10 UTC, liquidjoo commented on src/main/kotlin/racingcar/Racing.kt
>      fun start(roundCount: Int, moveStrategy: MoveStrategy) {
else 예약어를 사용하는게 계속 맘에 걸렸는데 ?: 연산자를 활용해 보아야겠어요!