Step3 자동차 경주
next-step/kotlin-racingcar pull request #605
Opened 2022-05-17 08:18 UTC by nfreedom9

부끄러운 얘기지만,
실무에 자바를 사용했던게 8년 전이고,
코틀린은 이번에 처음 접했고,
5년 전부터는 거의 자바스크립트와 (class 를 사용하지 않고) 함수형 로직으로만 코딩을 하다보니
과제를 진행하는게 많이 낯설고 서툽니다.
(개인적으로는 함수형 프로그래밍을 좋아하고 익숙한 편입니다.)
 
근래 제가 해오던 패턴 때문에
객체 생성을 위한 class 사용이 적은 편이고,
object 나 enum class 의 companion object (일종의 static 메서드?!)를 많이 사용하고 있다는 생각이 들기도 합니다.
 
혹시 불필요하거나 더 좋은 방법이라 생각되는 부분 있으시면 피드백 부탁드립니다.
 
구현 방식에 대한 설명을 덧붙이자면,
1. Race
차량수(carCount)와 이동횟수(moveCount)를 기반으로
차량리스트(cars: List<Car>)와 이동단계리스트(steps: List<Int>)를 정의하고,
각각의 Car 에서는 step 에 따른 position 값을 반환하는 메소드를 구현하였습니다.
 
2. Car 
moveCount 를 size 로 하는 무작위 숫자(0~9) 배열(randomInts)을 만들고 (해당 로직은 RandomList 로 구현)
randomInts 을 전진 포인트 배열(drivingPoints)로 전환, ( map 함수와 enum class DrivingForce 로 구현)
drivingPoints 로부터 각 스텝의 포지션을 나타내는 배열(positions)로 전환.
결과적으로 Car 인스턴스는 각 moveCount 에 해당하는 각 스텝의 위치를 반환하는 함수만 public 메소드(positionBy)로 구현하였습니다.
 
3. DrivingForce
2단계 과제 리뷰를 통해 알게 된 enum class 를 사용하여
무작위 숫자로부터 전진값을 얻는 DrivingForce 를 구현하였습니다.
단순히 전진이냐 아니냐에 대한 boolean 값으로 로직을 구현할 수도 있지만,
차량의 전진/멈춤에 따라 결국 위치를 +1 혹은 +0 으로 해석할 수 있으며,
range 값에 따라 전진, 멈춤 뿐 아니라 1 보다 더 큰 숫자의 전진과 음수 덧셈을 통한 후퇴기능도 구현 가능하도록,
코드의 확장성도 함께 고려하였습니다.

2022-05-17 13:46 UTC, laco-dev requested changes
상황을 잘 알려주셔서 너무 감사합니다.

고민도 많고 힘드실텐데 노력하는 모습이 정말 아름답다고 생각합니다.
꼭 주어진 기간안에 해결하지 않아도 되니 다른 분들이 어떻게 작성하는지 PR을 살펴보시거나 강의 피드백 등을 통해서 천천히 해결 해 나가보면 좋겠습니다.

객체지향의 오해와 진실에서는
"객체지향의 세계는 협력하는 자율적인 객체들의 공동체"라고 표현을 하고는 합니다.

객체가 해야할 일은 무엇일까? 를 시작으로 접근을 해 보는 과정으로 본다면
```
자동차는 움직이는 존재인가?
자동차는 움직인 결과들을 가지는 리스트들인가?
자동차가 움직이게 하려면 누구에게 협력해야할까?
```

등 생각해볼 재미있는 내용들이 많아요.
다시한번 급하게 생각하지 않으셔도 되니 천천히 고민 해보도록 해요.

2022-05-17 13:46 UTC, laco-dev commented on src/main/kotlin/racingcar/car/Car.kt
> +    }
코틀린 코딩 컨벤션에서는 동반 객체를 가장 하단에 위치하도록 해요.
https://kotlinlang.org/docs/coding-conventions.html#class-layout

2022-05-17 13:46 UTC, laco-dev commented on src/main/kotlin/racingcar/view/InputView.kt
> +    }
ㅋㅋ 재미있는 재시도 로직이 있네요 😃

이 로직은 1 이상의 자연수를 받기 위한 로직이라고 볼 수 있는데요.
하지만 실제 Race로 넘겨주는 값은 Int 타입으로 넘겨주고 있어서 정말 1 이상의 값인가? 라는 의문을 가질 수가 있어요.
```kotlin
class Race(carCount: Int, val moveCount: Int) {
    // carCount > 0이 맞을까 과연?
    // moveCount > 0 이 맞을까 과연?
}
```

항상 자연수를 가지는 객체를 만들어 보면 어떨까요?
그러면 사용하는 곳에서 항상 신뢰할 수 있게 될 것 같아요.

```kotlin
class CarCount(count: Int) {
   init {
       // 숫자는 항상 0보다 커야 한다. 그렇지 않으면 오류 발생?
   } 
}

val carCount: CarCount = InputView.getCarcount()

class Race(carCount: CarCount, ...) { ... }
```

2022-05-17 13:46 UTC, laco-dev commented on src/main/kotlin/racingcar/view/ResultView.kt
> +        private fun stringBy(position: Int) = List(position) { "-" }.joinToString("")
코틀린에서 String.repeat(...) 함수가 제공되고 있어요.
위 로직을 대체할 수 있습니다

2022-05-17 13:46 UTC, laco-dev commented on src/main/kotlin/racingcar/view/ResultView.kt
> +        })
1. race.moveCount 만큼 반복하는 경우 repeat(count) { ... } 함수를 활용 할 수 있습니다!!
이 경우 steps를 정수로 만들어 주어야 하겠죠?
```kotlin
private val steps = race.moveCount
repeat(steps) { ... } // 이 경우 0부터 steps까지 1씩 증가하는 it가 사용됨
```
2. 함수형으로 사용할 경우에는 익명 함수를 만들지 않고 바로 람다로 생략하면서 전달이 가능해요.
```kotlin
steps.forEach { step -> 
   showPositionsBy(step)
   ...
}
```

2022-05-17 13:46 UTC, laco-dev commented on src/main/kotlin/racingcar/car/Car.kt
> +    }
자동차 라는 객체가 몇 번 이동한지에 대한 결과들을 가지는 것 보다
스스로 움직이는 자율적인 녀석이라고 생각 해 보면 어떨까요?

지금의 구조는 자동차라는 객체보다는 "움직인 결과" 라는 역할을 가진다고 느껴져요.

```kotlin
car.move()
car.move()
val position = car.position
```

오늘 강의에서 피드백 과정을 한번 천천히 보시면서 구조를 연습해 보도록 하죠!

2022-05-17 13:46 UTC, laco-dev commented on src/main/kotlin/racingcar/car/DrivingForce.kt
> +    RANGE1(4..9, 1);
RANGE, RANGE1 이라는 의미는 주행과는 다소 거리가 멀어보이는 의미라고 느껴지는데요.
`STOP`, `FORWARD` 처럼 잘 드러나도록 지어 볼 수 있을 것 같아요.

2022-05-17 13:46 UTC, laco-dev commented on src/main/kotlin/racingcar/car/DrivingForce.kt
> +        }
i 라는 의미가 무엇을 뜻할까요?
내가 아닌 남이 보기 위한 코드가 좋은 코드라고 생각이 들어요.

이 의미를 대체할만한 다른 이름으로 바꿔볼까요?

2022-05-17 13:46 UTC, laco-dev commented on src/main/kotlin/racingcar/car/DrivingForce.kt
> +        }
IntRange는 in 이라는 연산자를 제공 하는데요.
포함되어있는지를 비교하는 코드는 아래와 같이 나타낼 수 있어요
```kotlin
i in RANGE.range -> i 라는 값이 range 내에 포함이 되어 있다.
```

2022-05-17 13:49 UTC, laco-dev commented
4단계, 5단계는 이어서 자동차 경주 미션이기 때문에 3단계 미션인 이 PR에서 이야기를 마무리하고 
다음 단계 미션을 진행해야 할 것 같아요 ㅎ

2022-05-17 15:25 UTC, nfreedom9 commented on src/main/kotlin/racingcar/car/Car.kt
> +    }
앗.. 처음엔 range 변수를 companion object 가 아닌 멤버변수(용어가 정확한지 모르겠습니다.)로 구현하였다가
range 는 생성자의 매개변수에 의존하지 않기 때문에 companion object 로 변경하였습니다.
위치 수정하도록 하겠습니다.
 
비교적 적은 규모의 스타트업 회사에서 주로 일해오면서 컨벤션에 좀 무딘 편이었는데,
다른 분들과 함께 협업하는데 있어서 컨벤션이 중요하다는 것을 근래 많이 느끼고 있습니다.
 
궁금한점이 있습니다.
위의 range 변수처럼 생성자의 매개변수에 의존하지 않는 값을 클래스변수(static 변수)로 선언하여
해당 값을 인스턴스 생성 전에 미리 평가하고 재활용하는 효과가 있다고 알고 있습니다.
코틀린의 companion object 도 동일한 역할을 하는 것으로 알고 있는데,
얼마 전 얼핏 자바로 전환된 코드를 설명하면서 그 역할을 완벽하게 소화하지 못한다는 글을 본 것 같습니다.
해당 글이 영문이기도 했고 개인이 블로그에 작성했던 글이라...
제가 이해한게 맞는지 궁금합니다.
 
싱글스레드의 nodeJS 에서는 
원시 자료형에 대하여 동일한 값을 서로 다른 변수나 다른 장소에서 할당하여도
해당 변수가 참조하는 메모리상의 값은 동일하여 해당 값이 재활용되는 것으로 알고 있는데,
코틀린에서는 어떻게 동작하는지 궁금합니다.
 
가령 위에 선언한 range 변수를 멤버변수로 선언하면 인스턴스 생성시마다 서로 다른 메모리를 사용하게 되는건지,
자료형의 타입에 따라 동작 방식이 다른지,
(자바스크립트에서는 문자열의 경우 메모리에 있는 값을 재사용 하는 것으로 알고 있습니다.)

2022-05-18 15:52 UTC, nfreedom9 commented on src/main/kotlin/racingcar/view/InputView.kt
> +    }
위 내용을 참고하여 CarCount 와 moveCount 클래스를 구현하였습니다.
구현하다보니 자동차수와 이동횟수는 도메인 로직에 필요한 요소이자 동시에 입력값을 받는 InputView 에서도 필요한 요소이기 때문에,
GameBoard 라는 클래스를 두고, 요구되는 최소 자동차수와 최소 이동횟수를 GameBoard 로부터 전달받도록 구현하였습니다.

2022-05-18 16:08 UTC, nfreedom9 commented on src/main/kotlin/racingcar/view/ResultView.kt
> +        private fun stringBy(position: Int) = List(position) { "-" }.joinToString("")
오! 매우 유용한 함수네요. 감사합니다 :)

2022-05-18 16:11 UTC, nfreedom9 commented on src/main/kotlin/racingcar/view/ResultView.kt
> +        })
moveCount 로부터 repeat 을 사용할 경우 0부터 시작하기 때문에,
제가 구현한 로직대로라면 첫번째 이동 결과가 아닌, 초기(출발위치) 부터 출력되므로
1부터 시작되는 리스트인 steps 를 사용하였습니다.
 
익명함수는 람다로 변경하였습니다.

2022-05-18 17:45 UTC, nfreedom9 commented on src/main/kotlin/racingcar/car/Car.kt
> +    }
이 부분에 있어 저는 조금 다른 생각을 가지고 있습니다.
쇼트트랙처럼 여러 선수들이 함께 달리는 경기도 있지만,
스피드스케이팅처럼 선수들이 각자 정해진 구간을 달리고, 그 기록을 통해 우승자를 가리는 경기도 있습니다.
 
만약,
자동차가 이동하는데 있어 자동차간의 상호작용이 있거나
"출발선을 제외하고 이동 단계에서 모든 자동차가 동일선상에 위치할 경우 게임은 종료된다." 와 같이
이동횟수만큼 끝까지 완주하지 못할 조건이 있었다면,
저도 position 과 move 함수를 통해 구현했을 것입니다.
 
코드를 통해 로직을 구현하는 것은,
결국 주어진 데이터와 조건으로부터
`데이터의 흐름(변환과정)` 과 그로 인한 `부수효과` 를 구현하는 것이라 생각합니다.
 
저는 과제를 수행하는데 있어 화면 출력이라는 `부수효과`를 위해
이동 단계(`step`)에 따른 자동차의 위치(`position`)라는 `데이터`가 필요하다는 생각이 가장 먼저 들었고,
`positionBy(step)` 을 구현하는 것은 이동횟수`moveCount`로부터 시작된 `데이터의 흐름(변환과정)`이라 생각했습니다.
 
'자동차 인스턴스 생성 시점마다 이미 경주를 시작하고 그 결과까지 모두 구해버리는 것이 과연 좋은 것인가?'
라는 생각이 들기도 했지만,
위에 언급한 것처럼 일단 `moveCount` 가 주어지면 
다른 상호작용 없이 끝까지 완주하는 것이 확실하기 때문에
단계별 출력을 위한 "기록지"를 갖는 것도 좋은 방법이라고 생각했습니다.
 
저는 오히려 위와 같은 구현을 통해 (필요하다면) 자동차 각자가 이동한 히스토리를 알 수 있는 것도 장점이라 생각합니다.
만약 "현재 위치"를 의미하는 `position` 과 `move` 함수를 통해 `position`을 변화시키는 방식으로 구현했다면,
히스토리에 대한 요구사항이 생겼을 때,
그것을 기록하는 별도의 프로퍼티, 혹은 그 역할을 담당하는 별도의 클래스로 구현해야 할 것입니다.
 
어떤 기능을 구현하는데 있어 데이터와 로직을 구성하는 다양한 방법이 있는데,
메모리가 낭비되지 않고, 너무 무겁거나 복잡하지 않은 선에서,
유지보수와 확장성을 고려했을 때 활용 가치가 높은 형태로 구성하려고 노력합니다.
 
4단계 과제에서 요구하는 "우승자"를 선정하는 것도 현재 구현 방식으로 충분히 가능합니다.
만약, 애초에 단계별 출력 없이 최종 우승자를 선정하는 것이었다면
fold 함수를 통해 "기록지"가 아니라 "최종위치"를 구현하고, 그것만 public 프로퍼티로 구현했을 것입니다.

2022-05-18 18:01 UTC, nfreedom9 commented on src/main/kotlin/racingcar/car/DrivingForce.kt
> +    RANGE1(4..9, 1);
리뷰 요청 메시지에 남겼던 것처럼,
현재는 멈춤과 전진만 있지만, range 별로 전진하는 숫자를 얻는 것으로 생각하여 enum class 로 구현하였고,
"range 에 따른 전진수" 라는 의미로 저렇게 이름을 붙여버렸네요.
`STOP`, `FORWARD1` 로 수정하였습니다. (1은 한칸 전진이라는 의미로..)

2022-05-18 20:03 UTC, nfreedom9 commented on src/main/kotlin/racingcar/car/DrivingForce.kt
> +        }
i 라는 변수명을 drivingPoint 로 변경하다가,
Car 의 동반 객체 프로퍼티 range 와 DrivingForce 의 enum 에서 사용된 range 간에 의존성이 있다는 생각에,
(랜덤 숫자의 범위가 달라질 경우 DrivingForce 에서 사용되는 range 값도 함께 수정해야 하는 문제)
기존에 작성했던 코드에서 RandomList 와 DrivingForce 를 제거하고,
그 역할을 Car 클래스 내부로 변경하였습니다.
 
사실은 맨 처음 그렇게 구현했었는데,
RandomList 는 재사용을 고려하여,
Range 와 Int 로부터 랜덤리스트를 구성하는 유틸함수로,
DrivingForce 는 확장성을 고려하여,
Range 로부터 Int 를 반환하는 enum class 로 구현하였습니다.
(이전 과제에서 피드백 받았던 enum class 를 연습삼아 사용해보려는 의도도 있었습니다)
 
이번 과제를 진행하는데 있어
재사용을 위한 유틸함수를 얻는 것보다는 해당 로직을 필요로 하는 곳에 좀 더 직관적으로 구현하고,
의존성을 갖는 변수 처리를 위해 프로퍼티를 다른 클래스에 전달하는 방식보다 로직을 한군데 두는 것이 좋겠다는 생각에
위와 같이 변경하였습니다.

2022-05-19 00:32 UTC, nfreedom9 commented on src/main/kotlin/racingcar/view/InputView.kt
> +    }
위와 같이 init 을 통해 파라미터로 전달된 값을 검증하는 로직을 구현하였을 경우,
해당 값에 접근하는 방식을 carCount.value 와 같이 프로퍼티에 그 값을 두고 접근하도록 구현하면 되는 것인가요?
 
만약 그렇다면 위와 같은 형태의 타입으로 전달되는 값들에 대하여 
(검증을 통과한) 그 값에 접근할 때엔 value 와 같은 프로퍼티로 접근해야 하고, 
value 라는 프로퍼티 명은 개발자가 작성하기에 따라 달라지기 때문에,
혹시 다른 방식이 있나 해서 여쭤봅니다.

2022-05-19 01:51 UTC, nfreedom9 commented on src/main/kotlin/racingcar/GameBoard.kt
> +    fun showResult() = resultView.showResult()
기존의
```kotlin
fun showResult() {
    ResultView(race).showResult()
}
```
형태에서 ResultView 인스턴스를 싱글톤으로 변경하였습니다.

2022-05-19 12:13 UTC, nfreedom9 commented on src/main/kotlin/racingcar/view/InputView.kt
> +    }
결과적으로 CarCount 와 moveCount 는 매우 비슷한 형태를 갖게 되었고,
각 클래스에 대한 테스트 코드 역시 매우 흡사하고,
InputView 에서 입력값으로 부터 각각의 인스턴스를 생성하는 메소드 또한 매우 흡사한 형태를 갖게 되었습니다.
 
기존에 작성했던 것은 두 메소드가 입력을 위한 메시지를 제외하고 동일한 로직을 갖기 때문에
getCount 라는 추상 메소드를 만들고, getCarCount 와 getMoveCount 를 getCount 를 통해 구현하였는데,
반환 타입이 달라져서 비슷한 형태의 2 함수를 각각 구현하게 되었습니다.
 
제네릭, 인터페이스 등으로 개선할 수 있을 것 같은데,
좋은 방법 또는 참고할만한 자료가 있다면 알려주실 수 있을까요 ㅠ_ㅠ?

2022-05-19 12:28 UTC, nfreedom9 commented on src/main/kotlin/racingcar/car/DrivingForce.kt
> +        }
해당 변수명을 변경하려다가 
DrivingForce 라는 클래스가 지나치게 확장성을 고려한 오버스팩이라는 생각이 들어
drivingPointBy 라는 함수로 수정하고, 관련된 테스트 코드도 수정하였습니다.
 
더불어 object RamdomList 도 randomListBy 라는 하나의 함수로 수정하였고,
관련 테스트 코드도 수정하였습니다.

2022-05-19 12:29 UTC, nfreedom9 commented on src/main/kotlin/racingcar/car/DrivingForce.kt
> +        }
enum class 로 구현하였던 DrivingForce 를 drivingPointBy 함수로 변경하며 위 코드는 수정되었습니다.

2022-05-19 12:54 UTC, nfreedom9 commented
저는 Car 클래스로 생성되는 car 인스턴스의 역할을 
1. 위치 정보를 갖고 있고, 
2. 조건에 따라 위치를 이동할 수 있으며,
3. 현재 위치를 알려준다.

가 아니라
1. 이동횟수를 받아
2. 이동조건에 따라 경주를 마치고,
3. 이동단계별 위치를 알려준다.

로 생각했었습니다.
 
강의를 함께 듣는 회사 동료들과
역할과 책임을 고려한 좋은 구조가 어떤 것인지,
테스트 코드를 짜기 좋은 코드가 어떤 것인지 이야기를 나누는 시간을 가졌습니다.
 
저는 역할과 책임을 나누는데 있어 그것이 반드시 클래스여야 한다고 생각하지는 않습니다.
제가 구현한 코드에서 randomListBy, drivingPointBy 와 같은 개별 함수 역시 
역할과 책임에 충실하고, 테스트 코드를 짜기 좋은 한가지 방법이라고 생각합니다.
 
이전에 말씀드린대로 저는 꽤 오랫동안 객체지향이 아닌 함수형 프로그래밍을 해온 터라
제가 쉽게 떠올리고 구조를 잡는 것은
`순수 함수`, 기본 자료형을 매개변수로 갖는 `유틸리티 성격의 함수`,
그것들을 통한 `데이터의 흐름` 과 `부수효과`로 이루어질 때가 많습니다.
 
오래전 실무에서 다루었던 자바에 비해 코틀린은 좀 더 유연하고, 함수형을 지원하고 있는 것으로 알고 있습니다.
그래서인지 타입언어를 다루면서도 매우 즐겁게 과제와 공부를 진행하고 있습니다.
강의와 과제를 진행하는 동안 제가 가진 관습을 버리고,
객체지향 프로그래밍과 테스트코드에 대하여 좀 더 노력하도록 하겠습니다.

2022-05-19 15:34 UTC, laco-dev commented on src/main/kotlin/racingcar/car/Car.kt
> +    }
일부 원시 값은 어느정도 범위에 해당하는 풀에서 재활용을 하는 것으로 알고 있어요.
그 외의 일반적인 레퍼런스 타입은 주소 기반으로 동작을 합니다.

이쪽 내용은 제가 정확히 알고 있지 못하는 정보라, 추가적으로 알게되면 또 말씀드릴게요!

2022-05-19 16:50 UTC, nfreedom9 commented on src/main/kotlin/racingcar/car/Car.kt
> +    }
이 부분에 있어 저는 조금 다른 생각을 가지고 있습니다.
쇼트트랙처럼 여러 선수들이 함께 달리는 경기도 있지만,
스피드스케이팅처럼 선수들이 각자 정해진 구간을 달리고, 그 기록을 통해 우승자를 가리는 경기도 있습니다.
또한, 실행자 스스로가 기록지를 갖는 경우도 있습니다.
(체력장 혹은 신체검사를 할 때, 코스를 돌며 기록지를 작성하고, 맨 마지막에 기록지를 제출했던 것이 생각납니다.)

만약,
자동차가 이동하는데 있어 자동차간의 상호작용 또는 외부 요인이 있거나
"출발선을 제외하고 이동 단계에서 모든 자동차가 동일선상에 위치할 경우 게임은 종료된다." 와 같이
끝까지 완주하지 못할 조건이 있었다면,
저도 `position` 과 `move`로 구현했을 것입니다.

개발자가 코드를 통해 로직을 구현하는 것은,
결국 주어진 데이터와 요구사항들로부터
`데이터의 흐름(변환과정)` 을 효율적으로 구성하고,
요구사항에 알맞는 `부수효과` (출력, 데이터 저장, 호출 등)을 구현하는 것이라 생각합니다.

저는 과제를 수행하는데 있어 `각 단계별 자동차의 위치를 출력`하는 `부수효과`를 위해
각 자동차의 `이동 단계(step)에 따른 자동차의 위치(position)`라는 `데이터`가 필요하다 생각했고,
`positionBy(step)` 을 구현하는 것은
`이동횟수(moveCount)` 라는 `데이터`로부터 시작된 `흐름(변환과정)의 결과`라고 생각했습니다.
제가 그렇게 생각한데는
`자동차의 상태를 화면에 출력한다. "어느 시점에 출력할 것인지에 대한 제약은 없다."`
라는 과제의 요구 사항도 한 몫 했던 것 같습니다.
이동하는 단계마다 출력을 하는 것이 아니라, 기록지를 통해 결과물을 출력하는 것도 방법일 수 있기 때문입니다.

`'자동차 인스턴스 생성 시점에 이미 경주를 시작하고 그 결과를 모두 평가하는 것이 과연 좋은 것인가?'`
라는 생각이 들기도 했지만,
일단 `moveCount` 가 주어지면 끝까지 완주하는 것이 보장되기 때문에
단계별 출력을 위한 "기록지"를 갖는 것도 구현 방법이라 생각했습니다.

어떤 기능을 구현하는데 있어 `데이터(상태)`와 `로직(함수)`를 구성하는 다양한 방법이 있는데,
메모리가 낭비되지 않고, 너무 무겁거나 복잡하지 않은 선에서,
유지보수와 확장성을 고려했을 때 활용 가치가 높은 형태로 구성하려고 노력합니다.
조건에 따라 전진할 것인지 멈출 것인지
`condition ? move() : stop()` 형태가 아니라
조건에 따라 얼만큼 이동할 것인지
`move(pointByCondition)` 형태로 구현하려는 것도 그런 노력 중 하나입니다.

4단계 과제에서 요구하는 "우승자"를 선정하는 것도 현재 구현 방식으로 충분히 가능합니다.
여담입니다만, 애초에 단계별 출력 없이 최종 우승자를 선정하는 것만 필요했다면,
moveCount로부터 시작된 흐름(변환과정)의 최종 결과는
fold 함수를 통해 얻어지는 "기록지"가 아니라 
(List<Int> 에 그런 함수가 있는지는 모르겠지만) sum 함수를 통해 얻어지는 "최종위치" 였을 것 같습니다.

2022-05-20 11:51 UTC, laco-dev commented on src/main/kotlin/racingcar/view/InputView.kt
> +    }
어떻게 의미를 나누는가에 따라 다를 것 같아요!
```
차량 대수라는 명확한 CarCount 타입으로 바라보는 것.
이동 횟수라는 명확한 MoveCount 타입으로 바라보는 것.
```
이 두개는 실제 기능은 동일하다고 볼 수 있지만 타입 자체는 결국 다르다고 볼 수 있는데요.

어떻게 객체를 바라보는가에 따라 설계도 달라질 수 있는데,
위와 같은 경우 CarCount, MoveCount 모두 "숫자" 라는 정적인 타입이라고 판단한다면 하나의 타입으로만 구현을 해 볼 수 있을 것 같아요.

두개로만드는가 하나로 만드는가는 나중의 유지보수 과정에서의 트레이드 오프라고도 볼 수 있네요.

```kotlin
abstract class Count(val value: Int, minValue: Int)
class CarCount(value: Int) : Count(value, 0) // 차량 대수는  0대 이상이다?
class MoveCount(value: Int) : Count(value, 1) // 이동 횟수는 1회 이상이다?
```
저는 현재처럼 두 개로 나뉘어서 구현을 하는 방식도 좋다고 생각해요.

위에서 이야기 해본 추상화, 일반화는 앞으로 하게 될 미션들에서 다시 연습할 기회가 있으니 그때 또 도전 해 보시죠!

2022-05-20 11:52 UTC, laco-dev commented on src/main/kotlin/racingcar/view/InputView.kt
> +    }
코틀린에서는 이러한 값을 래핑한 경우 value class 라는 이름으로 부르기도 하는데,
타입처럼 선언하지만 실제로는 원시값 처럼 동작하는 좋은 기능이 있습니다.
https://kotlinlang.org/docs/inline-classes.html#members

2022-05-20 12:55 UTC, laco-dev requested changes
질문주신 내용들을 통해 
객체지향 주제로 조금 더 고민 해볼 수 있는 시간이 된 것 같습니다.

관련해서 조금 더 같이 생각 해 볼만한 내용들을 다시 남겨 보았습니다. 🙏

2022-05-20 12:55 UTC, laco-dev commented on src/main/kotlin/racingcar/count/CarCount.kt
> +}
CarCount의 최소 값을 받도록 만들어 주셨는데요.

`차량 대수가 가지는 원래의 의도는 1대 이상의 값을 보장한다.` 라는 조건이였습니다.
그런데 현재 구조에서는 `minCount`를 생성자로 받게 되면서 위 조건이 맞지 않게 되었어요! 🙏 

```
CarCount(-300, -20000)
```
위 Count를 넘겨받는 Race는 경주가 올바르게 진행된다고 판단할 수 있을까요!?
자동차 대수는 반드시 1대 이상이어야 한다.  라는 개념으로 우선 시작 해 봐도 좋을 것 같아요!

2022-05-20 12:55 UTC, laco-dev commented on src/main/kotlin/racingcar/count/MoveCount.kt
> +    }
코틀린의 require 를 이용해 간결하게 표현이 가능합니다!~
```kotlin
require(value >= minCount) { ... }
```

2022-05-20 12:55 UTC, laco-dev commented on src/main/kotlin/racingcar/view/InputView.kt
> +    }
오류의 불확실성이 있는 코드가 아니기 때문에 try & catch로 무조건 감싸는것은 좋지 않습니다.

하지만  IOException과 같은 변수도 고려해야 하기 때문에 사용하는 경우라면
코틀린에서는 runCatching { ... } 이라는 문법으로 함수형 코드를 지원하는 Result 타입을 만들기도 합니다.
```kotlin
private fun getMoveCount(askCount: Int): MoveCount = runCatching {
   ...
   readln().toIntOrNull()
}
.mapCatching { ... }
.getOrDefault(...)
```

지금 구조를 정확히 대체하지는 않을 수도 있는데, 참고 용으로 남겨 드려 보았어요.
https://github.com/Kotlin/KEEP/blob/master/proposals/stdlib/result.md

2022-05-20 12:55 UTC, laco-dev commented on src/main/kotlin/racingcar/view/InputView.kt
> +    val moveCount = getMoveCount()
이 두 개의 프로퍼티로서 있는 메리트가 부족 해 보입니다.
인스턴스가 초기화될 때 항상 두 개의 숫자를 같이 입력받아야 하는데 만약 CarCount를 먼저 가져온 뒤,
다른 행동을 하고 이어서 MoveCount를 가져와야 한다면 지금의 구조로는 어려워 보이는데요.

getCarCount(), getMoveCount()를 public으로 만들어 보면 어떨까요?

2022-05-20 12:55 UTC, laco-dev commented on src/test/kotlin/racingcar/car/randomListTest.kt
> +}
평소에도 Random 요소를 자주 테스트 하시는 편이신가요!?
불확실성 자체를 테스트 하기 위해 어떤 테스트 코드를 만들어야 하는지 항상 고민이 들기도 하고,,, 🤔 
도메인 로직의 테스트 검증으로는 불충분한 것일까? 라는 의문도 있어서요

2022-05-20 12:55 UTC, laco-dev commented on src/main/kotlin/racingcar/GameBoard.kt
> +}
이 객체의 역할은 도메인이라고 생각하시나요?
아니면 컨트롤러 라고 생각하시나요??

하나의 게임 보드가 하나의 어플리케이션 처럼 느껴지기도 해서 저는 컨트롤러라고 생각이 듭니다.
(게임보드가 만들어 진 순간 모든 것이 결정됨)
그런 관점이라면 입력을 받는 것부터 출력까지 모두 스스로 해야 하지 않을까요??

```kotlin
class GameResult(...) {
   ...

   init {
      showResult(...)
   }
}
```

2022-05-20 12:55 UTC, laco-dev commented on src/main/kotlin/racingcar/car/Car.kt
> +}
말씀주신 부분 잘 읽어봤습니다.
자동차가 누군가에게 협력을 하는 대신 생성하면서 모든 경주를 직접 달리고 결과를 가지고 있는 구조라고 느껴지네요.

이러한 관점에서 바라보는 설계가 저도 다소 어색하게는 느껴지지만 남겨주신 글 보고 공감을 조금씩 하게 되었습니다.
그러면 현실적인 관점에서 좋은 객체지향 설계란 무엇일까? 를 얘기 해 볼 수 있겠는데요.

저는 Car 라는 도메인을 어떻게 확장하고 테스트 할 수 있을까? 라는 의문에서 벗어나지 못하고 있습니다.
말씀 주신 것과 같이 하나 하나의 개별 함수들은 테스트가 가능할 수 있지만,
각 개별 함수를 모두 사용하고 있는 Car는 너무 많은 의존성을 가지고 있습니다.

1. 
우선 Car가 만들어진 순간 어느 위치에 도착해 있을지는 아무도 모릅니다. 
랜덤으로 결정되니까요.

2. 
다음으로 어떤 차는 시도횟수 두번에 무조건 한칸을 전진하는데, 어떤 차는 랜덤으로 전진할꺼야,
또 어떤 차는 연료가 많아서 시도횟수마다 전진할거야.
이 기능들을 대응하기 위해서 현재 구조는 더욱 많은 의존성을 가지거나 상속의 상속으로 만들어 질 지도 모릅니다.


3. 
자동차가 만들어진 순간 모든 컨텍스트가 휘발됩니다.
```kotlin
val car = Car(moveCount = 5)
car.positionBy(10)
```
Car가 이미 만들어진 이후라면, moveCount가 얼마의 값으로 만들어졌는지 아무도 모르게 됩니다.
자동차는 스스로 움직이지 않기 때문에 얼만큼 움직였는지를 모르기 때문입니다.

저도 많이 생각 해보면서 다른 분들에게도 한번 의견을 나눠보고 조금 더 말씀드려보도록 하겠습니다.
그래도 이 클래스가 불변을 유지한다는 점은 되게 매력적이긴 하네요 👍

2022-05-20 14:13 UTC, nfreedom9 commented on src/main/kotlin/racingcar/count/CarCount.kt
> +}
- 차량 대수가 1대 이상이어야 한다
- 이동 횟수는 반드시 1 이상이어야 한다

라는 요구사항은 없었습니다.
그것이 너무나도 당연한 것이기 때문에 
경주를 시작하기 위해 사용자로부터 입력받은 값이 1 이상인지 체크하여
잘못된 경우 다시 묻는 로직을 구현했던 것입니다.
 
리뷰를 통해 입력값에 대한 검증 로직을 위와 같은 방식으로 구현할 수 있다는 것을 알게 되었고,
이왕이면 단순히 입력값이 `1 이상의 자연수`를 검증하는 것이 아니라, 
한단계 더 나아가 `최소값 이상의 자연수`를 검증하는 것으로 구현해보고 싶었습니다.
 
게임에 필요한 최소한의 자동차 수와 이동횟수는 GameBoard 생성시 규정짓는 것으로 생각했습니다.
자동차는 최소 2대 이상이어야 하고, 이동횟수는 반드시 10번 이상이어야 하는 게임보드를 구성하고 싶다면,
`val gameBoard = GameBoard(2, 10)` 으로 진행할 수 있도록..
(다만, GameBoard 에서 두 파라미터의 기본값을 1로 정의하였습니다.)
 
CarCount 와 MoveCount 의 역할을 
입력값으로 부터 `1 이상의 자연수`를 보장하는 것이 아니라,
GameBoard 생성시 최소값을 얼마로 규정 지었느냐에 관계 없이
`규정된 최소값 이상의 숫자`를 보장하는 것으로 생각하였습니다.
 
그리고 여기서 표현된 `규정된 최소값`은 GameBoard 로부터 전달받도록 구현하였습니다.
 
타입이 CarCount 혹은 MoveCount 이면
`"(외부에서 접근할 수 없기 때문에) 규정된 최소값이 얼마였는지는 비밀인데, 나의 value 는 최소값 이상을 보장하고 있어"`
라고 말해주기 때문에 
inputView 로부터 전달받은 carCount 와 moveCount 는 `검증된 값`으로 해석할 수 있습니다.
 
그럼 `gameBoard 생성시 자연수가 아닌 값을 입력한 경우`는..
그건 사용자로부터 입력받는 것이 아니라 
어떤 최소조건으로 게임을 구성할지 "개발자가 구현한 코드" 로 이루어지기 때문에 크게 문제삼지 않았습니다.
이 게임을 최소한 -2 대의 자동차로 최소한 -5 번 움직여야 하는 조건으로 실행할 일은 없다고 봤기 때문입니다.
 
현재 제가 구현한 것은 두 값을 모두 1로 사용하고 있습니다.

2022-05-20 14:35 UTC, nfreedom9 commented on src/test/kotlin/racingcar/car/randomListTest.kt
> +}
부끄럽게도 저는 평소 위와 같은 "테스트 코드" 는 거의 작성하지 않았습니다. ㅠ_ㅠ;
다만, 개발하면서 제가 의도한대로 동작하는지 실행하며 로그로 점검하고,
필요하다면 실행값과 결과에 대해 비교연산자를 통해 boolean 값을 체크하며 로그를 찍는 스크립트 코드를 만들곤 했습니다.
 
랜덤값에 대한 테스트코드는 구현하기 어렵지만,
위와 같은 요구조건에 대한 예외케이스가 과연 발생하는지 매우 많은 횟수를 시도해보거나,
(0..9)로부터 랜덤값을 생성하는 함수를 10000 번 실행했을 때,
각각의 숫자가 정확히 1000번은 아니더라도 1000 에 수렴하는지 체크해보곤 합니다.
 
가령, 정육면체 주사위에 6이라는 숫자 대신 1 이 2개 들어있는 주사위처럼
1부터 5의 숫자 중 랜덤값을 리턴하되, 1이 나올 확률은 나머지 4개 숫자의 2배라고 했을 때,
주사위를 6만번정도 돌려서 1은 2만번, 나머지는 1만번 정도 나오는지, 눈으로 확인해보곤 합니다.

2022-05-21 12:51 UTC, nfreedom9 commented on src/test/kotlin/racingcar/car/randomListTest.kt
> +}
글을 작성하고 나니, "확률" 에 대한 테스트 코드는 별도의 좋은 방법이 있는지 궁금합니다.

2022-05-22 04:00 UTC, laco-dev commented on src/main/kotlin/racingcar/count/CarCount.kt
> +}
아하,, 네 구체적으로 1대 이상이어야 한다는 조건은 없었네요.
다만 자동차 경주 게임이라는 도메인 세계에서는 음수 대수를 가지는 개념이 논리적으로 맞지 않다고 생각을 하는게 옳지 않을까 해요.

사용하는 측 입장에서는 CarCount가 최솟값이 몇이였지? 라는 의문을 품을 수 밖에 없는데요.
결국 음수가 아닐경우에만 동작하도록 추가적인 방어 로직이 들어가야 할 수 있습니다.

두 값 모두 1로 사용한 것은 객체가 한 역할이 아니라, 개발자가 코드로 한 것이 아닐까요?
실제로는 일어날 수 없는 일이지만 값을 전달받는 객체 입장에서는 이 값이 몇으로 왔는지 개발자에게 의존해야 할 것 같습니다.

2022-05-22 15:22 UTC, nfreedom9 commented on src/main/kotlin/racingcar/view/InputView.kt
> +    }
오류 발생 여부가 readln() 을 통해 사용자로부터 입력받은 값에 의존하고 있기 때문에,
오류의 불확실성이 있다고 생각하였습니다.
 
runCatching.mapCatching 문법은 
내부 로직 실행시 발생되는 런타임 에러를 외부로 전달하지 않고,
로직 중간에 처리하기 위한 용도라는 생각이 들었습니다.
 
자바스크립트도 치면,
Promise().then().catch().then().then() 과 비슷한 느낌이 들었는데,
좀 더 자세히 공부한 뒤에 적용해보도록 하겠습니다.

2022-05-22 15:45 UTC, nfreedom9 commented on src/main/kotlin/racingcar/view/InputView.kt
> +    val moveCount = getMoveCount()
getCarCount 와 getMoveCount 메소드를 퍼블릭으로 만든다는 것은,
말씀하신대로 그 시점을 제어하기 위함일 것 같은데, 그건 제가 생각했던 것과 조금 다른 것 같습니다.
 
1. 게임보드에서 자동차 수와 이동횟수는 레이싱 게임을 시작하는 단계에서 단 한번만 묻게 됩니다.
2. 자동차 수와 이동횟수는 입력받아 결정되면 더 이상 변동되지 않고, 다시 물어보지도 않습니다.
 
그런 이유로 InputView 클래스의 역할을,
`자동차 수`와 `이동횟수`를 사용자에게 묻고 입력받아,
검증로직을 통해 필요에 따라 재귀 호출 함으로써
주어진 조건(`최소 자동차 수(minCarCount)`와 `최소 이동횟수(minMoveCount)`)에 부합하는
`자동차 수(carCount)`와 `이동횟수(moveCount)`를 알려주는 것으로 생각했습니다.
1. 입력값을 물어보는 것과 입력값에 대한 검증 및 다시 묻는 로직은 인스턴스 생성시 즉시 실행되고,
2. 인스턴스는 결정된 불변값을 알려주는 역할

2022-05-22 16:01 UTC, nfreedom9 commented on src/main/kotlin/racingcar/GameBoard.kt
> +}
저는 위에 제안해주신 것을 보고,
InputView 에서 carCount 와 moveCount 프로퍼티 대신 메소드를 public 으로 제안해주신 것이 떠올랐습니다.
 
가능성으로 치자면 getCarCount, getMoveCount 함수보다 showResult 함수가 실행시점을 제어할 필요성이 더 크다고 생각합니다.
 
현재는 main 함수에서 게임보드를 구성한 뒤
showResult 함수를 통해 결과를 보여주고 있지만,
필요에 따라서는 
getPositionsByCar, (특정 자동차의 이동내역)
getPositionsByStep, (특정 시점의 자동차들의 위치)
showPositionsByCar, (특정 자동차의 이동내역을 보여준다)
showPositionsByStep, (특정 시점의 자동차들의 위치를 보여준다)
getWinners, (우승자동차)
showWinners,  (우승자동차를 보여준다)
등 여러가지 기능이 게임보드에 추가될 수 있고, main 함수에서 원하는대로 사용할 수 있다고 생각했습니다.

2022-05-23 14:06 UTC, nfreedom9 commented
주말동안 책상 앞에 앉을 여건이 되지는 못했지만, 관련하여 저도 정말 많은 생각을 했습니다.
 
먼저는 `Car` 라는 클래스명이 잘못되었다는 생각이 들었습니다.
말씀해주신대로 제가 구현한 `Car` 인스턴스는, 
자기 위치`position`과 움직임`move()`을 갖는 자동차를 의미하지 않기 때문입니다.
오히려 주어진 이동횟수만큼 자동차를 움직이고 그 기록을 갖는 `Player` 라고 표현하는 것이 좀 더 자연스러울 것 같습니다.
 
제가 구현한 방식에서 `자동차`는 없었습니다.
각 `player` 는 자동차를 움직일 단서(이동 횟수와 각 스텝별 랜덤 수)와 로직(4 이상일 경우 전진, 아니면 멈춤)으로부터 경주 결과를 얻어옵니다.
함수형 프로그래밍을 주로 해오다보니, 유동성을 갖는 `position` 대신, 불변 데이터와 함수들의 조합으로 기능을 구현하게 된 것 같습니다.
저는 이번 과제를 진행하는데 있어 이런 구성이 문제가 되지 않는다고 생각하였습니다.
자동차가 이동하는 요구조건을 충분히 만족하며 경주 기록을 갖고,
요구조건에 해당하는 "결과출력"에 문제가 없기 때문입니다.
 
제가 프로그래밍을 처음 공부할 때에, 객체지향 프로그래밍을 배우면서,
구현해야 하는 것을 현실 세계에 빗대어, 마치 그것이 실존하는 사물처럼 생각하고,
각 사물들의 역할과 사물들 간의 상호작용에 대하여 생각해보라는 이야기를 들은 적이 있습니다.
 
저는 제가 구현한 것이 잘못된 것인가 심각하게 고민해봤습니다.
그런데 꼭 그렇지만도 않다는 생각도 해봤습니다.
 
- 데이터와 로직으로부터 결과를 도출하는 일은 현실 세계에서도 얼마든지 있는 일입니다.
  - `현재 시간이 11시 50분일 때 2시간 30분 뒤는 몇시 몇분인가요?` 라는 질문에
    1. 직접 시계의 시침과 분침을 옮겨가며 계산하는 것도 방법이고,
    2. 종이 위에 그림을 그려서 계산하는 것도 방법이고,
    3. 머릿속으로 상상하며 계산하는 것도 방법일 것입니다.
- 역할과 책임을 나누는 것이 꼭 클래스일 필요는 없다는 생각이 들었습니다.
  - 역할과 책임을 최대한 잘게 쪼개어 설계하다보면, 결국 기본 자료형과 로직을 담당하는 단일 함수로 쪼개진다고 생각합니다.
    - 제가 구현한 것에서 `randomListBy`, `drivingPointBy` 와 같은 단일 함수
  - 클래스보다 기본 자료형 중심으로 구현된 단일 함수는 테스트 하기에도 더 용이하고, 재사용성도 더 높다고 생각합니다.
    - 충분히 검증된 `randomListBy` 함수는 `0 이상 9 이하` 대신 다른 조건의 자동차가 종류가 생길 경우 유연하게 대응할 수 있게 해줍니다.
    - 자동차의 이동 조건이 전혀 다른 방식으로 변경된다면, `drivingForces` 를 `randomListBy` 가 아닌 다른 로직으로 구성하면 됩니다.
  - 다만 그런 데이터와 로직의 "집합체"가 필요한 경우, 그것을 묶어서 클래스로 구현한다고 생각했습니다.
    - 제가 구현한 것에서 `Car`, `GameBoard` 등
 
이후 강의 과정 중 이번 과제를 활용하여 진행되는 부분이 있어 혹시라도 발생할 이슈가 있다면, 요구 조건에 맞게 과제를 수정하도록 하겠습니다.

2022-05-23 14:31 UTC, nfreedom9 commented on src/main/kotlin/racingcar/car/Car.kt
> +}
1. `Car` 클래스를 `position` 과 `move()` 로 구현해도 도착위치를 모르는 것은 동일한 것 같습니다.
말씀하신 것처럼 랜덤으로 결정되기 때문입니다.
 
2. 말씀하신 조건들(두번에 한칸 전진, 랜덤 전진, 매번 전진)에 대한 요구사항이 있었다면, 
`drivingForces` 라는 변수를 `Car` 내부에서 `randomListBy` 함수를 통해 평가하지 않고, 
`Car` 생성시 전달받거나, 혹은 `randomListBy` 대신 `drivingForces` 평가를 위한 다른 함수를 주입받아 사용했을 것입니다.
그런 요구사항이 없더라도 "확장성을 고려"하여 그렇게 했어야 했다면,
`0 이상 9 이하` 라는 조건, `전진 기준이 4` 라는 조건, 
`전진(+1)` 과 `멈춤(+0)` 이외에 `후퇴`, 혹은 `+N 전진`까지,,
가능한 많은 것을 외부로부터 주입받는 형태로 구현하는게 꼭 좋은 것인지는 모르겠습니다.
과제의 요구사항을 구현하는 선에서, 혹시라도 발생할 변경사항, 혹은 요구 조건에 대해 충분히 대응할 수 있는 구조라고 생각합니다.
 
3. 말씀하신 휘발이 무엇을 의미하는지 잘 모르겠습니다. 
`moveCount` 가 얼마인지는 `positionsByStep.size` 로부터 유추할 수도 있고,
외부에서의 접근이 필요했다면 `moveCount` 를 public 변수로 선언했을 것입니다.
제가 구현한 방식에서의 `Car` 클래스가 가져야 할 public 프로퍼티(혹은 메소드?!)는 `positionBy` 만으로 충분했습니다.
moveCount 가 몇이었는지, 각 이동 단계의 "랜덤수" 가 무엇이었는지, 각 이동 단계에서 자동차의 위치는 어디였는지,
휘발되지 않고 모두 갖고 있으며, 
외부에서의 접근이 필요하다면 해당 변수를 public 으로 변경하거나, 적당한 메소드를 추가하면 됩니다.

2022-05-23 14:43 UTC, nfreedom9 commented on src/main/kotlin/racingcar/count/CarCount.kt
> +}
저는 제가 구현한 코드에서 게임보드 생성시
(그런 요구 사항은 없었지만) 최소값을 모두 1로 하였기 때문에 문제가 되지 않는다고 생각했습니다.
 
저 스스로 이번에 구현한 게임에서는 최소값을 모두 1로 정하였고,
최소값을 1이 아닌 다른 값으로도 설정 가능하도록 구현했지만,
그 값을 기획단계(요구조건)에서 1 미만의 숫자로 정할 일은 없다고 봤기 때문입니다.
 
단지, 사용자로부터 입력받는 CarCount 와 MoveCount 의 value 가,
이 게임에 `규정된 최소값` 이상인지를 체크하면 된다고 생각했습니다.
 
결국 요구사항에 맞는 코드를 작성하는 것은 개발자의 몫이고,
요구사항에 논리적 오류가 있는 것은 개발자가 구현해야 할 `기획`의 오류라고 생각합니다.
(예를들면, 0 이상 9 이하의 랜덤값 중, 그 값이 10 이상인 경우 자동차는 전진한다.)
 
"0" 이상 "9" 이하의 랜덤값 범위도, "4" 라는 전진 조건에 해당하는 숫자도,
모두 요구사항에 따라 개발자에 의해 작성된 코드(값)이고,
작성된 모든 코드는 개발자를 의존한다고 생각합니다.
 
말씀해주신게 어떤 취지이신지는 알 것 같아서, 
두 클래스 모두 최소값이 1 이상이어야 한다는 조건을 추가하였습니다.

2022-05-23 14:46 UTC, nfreedom9 commented on src/main/kotlin/racingcar/count/MoveCount.kt
> +    }
해당 내용 반영하여 수정하였습니다.

2022-05-23 15:20 UTC, nfreedom9 commented on src/test/kotlin/racingcar/car/randomListTest.kt
> +}
randomListBy 함수에 대한 테스트 코드를 수정하였습니다.

2022-05-23 15:43 UTC, nfreedom9 commented on src/test/kotlin/racingcar/car/randomListTest.kt
> +}
[슬랙의 스레드에 남긴 내용](https://nextstep-members.slack.com/archives/C03CB32ALKZ/p1653202686330359?thread_ts=1653140916.676589&cid=C03CB32ALKZ)을 이곳에도 첨부합니다.
 
```kotlin
(System.currentTimeMillis() % 10).toInt()
```
위의 코드를 비동기 반복문으로 실행해보거나,
충분히 많은 횟수(?!)를 반복 실행하여 결과를 살펴보면,
0 이상 9 이하의 정수를 랜덤으로 리턴한다고 오해할 수 있습니다.
참고로 100만번정도 실행하여 결과를 살펴보니 다음과 같았습니다.
```kotlin
val randomList = ArrayList<Int>()

repeat(1000000) { randomList.add((System.currentTimeMillis() % 10).toInt()) }

randomList.groupBy { it }.forEach { (i, list) -> println("$i - ${list.size}") }
 
// 실행결과 
5 - 100991
6 - 87072
7 - 88961
8 - 95279
9 - 92193
0 - 83428
1 - 94795
2 - 119123
3 - 122548
4 - 115610
```
저는 다른분들이 작성하신 자동차 경주 게임에서,
0 이상 9 이하의 랜덤 정수 부분을 위와 같이 `(System.currentTimeMillis() % 10).toInt()` 로 실행하였을 때,
작성하신 모든 테스트를 통과하는지,
그리고 이 게임의 실행 결과가 어떻게 나타나는지 궁금해졌습니다.
 
(랜덤값의 분포도에 대한 테스트 코드가 없다면..)
혹시 테스트 코드는 모두 통과하지만, 이상한 결과가 나오진 않을까요?
매우 높은 확률로 다 함께 공동우승을 하는, 평화로운 자동차 경주랄까..
 
이동 단계별로 모든 자동차가 다 함께 전진하거나 다 함께 멈추거나..
혹은 (제가 작성한 방식대로라면) 자동차가 이동횟수만큼 모든 단계에서 전진하거나, 한번도 전진하지 못하거나,

2022-05-23 17:05 UTC, nfreedom9 commented on src/main/kotlin/racingcar/GameBoard.kt
> +}
결과를 보여주는 로직을 GameBoard 에서 제거하고,
main 함수에서 gemaBoard 로부터 데이터를 받아 resultView 를 생성하여 메소드를 실행하는 방식으로 수정하였습니다.

2022-05-23 18:02 UTC, nfreedom9 commented on src/main/kotlin/racingcar/count/CarCount.kt
> +}
위에 표현한 것처럼 CarCount 와 MoveCount 가 최소값을 보장해주기 때문에 그것을 알 필요가 없다고 생각했습니다.
만약, 최소값이 몇이었지? 라는 의문을 품고, 그것을 필요로 하는 곳이 있으면 minCount 앞에 val 선언을 해주면 될 것 같습니다.
 
게임에 필요한 자동차수와 이동횟수는 
입력값을 묻고 요구조건에 부합하지 않을 경우 다시 묻는 `InputView` 와 
도메인 로직을 담당하는 `Race` 에서 모두 필요하기 때문에,
`CarCount`, `MoveCount` 클래스를 정의하고,
의존성을 갖게 된 `InputView` 와 `Race` 를 함께 다루는 `GameBoard` 클래스를 정의하였습니다.
결국 최소조건에 대한 정의는 `GameBoard` 내부에서 이뤄져야 하는데,
처음엔 내부에서 두 값 모두 1로 사용했다가,
그 값을 `GameBoard` 생성시 주입받도록 수정하였습니다.
 
기본값을 설정한 것은,
`GameBoard` 의 처음 구현당시 내부에서 두 값 모두 1로 정의 했던 것을,
인스턴스 생성 코드 변경 없이 수행하도록 생성자의 기본값을 설정한 것이고,
`CarCount` 와 `MoveCount` 역시 
최소값 기능 없이 구현되었을 당시의 테스트코드를 그대로 동작시켜 주려는 목적도 있었습니다.
 
`GameBoard` 의 기본값과, `CarCount`, `MoveCount` 에서의 기본값이 모두 1로 동일하지만, 
의미하는 바는 다르기 때문에 그 사이의 의존성이나 "누가 옳은 것이지?" 라는 의문을 가질 필요가 없다고 생각합니다.
 
`CarCount` 와 `MoveCount` 의 기본값을 각각 1로 두고,
`GameBoard` 의 `최소자동차수`와 `최소이동횟수`의 기본값을 각각 3과, 5로 하면,
이 게임에서 사용되는 자동차수`CarCount`와 이동횟수`MoveCount`에 대한 최소조건은 1을 기본값으로 갖지만,
자동차수와 이동횟수에 대한 최소조건이 따로 정의되지 않은 `GameBoard()` 에서의 기본값은 각각 3과 5가 됩니다.
 
여전히 기본값을 1로 갖는, 동일한 `CarCount` 와 `MoveCount` 클래스를 사용하지만, 
기본값이 다른 `class GameBoard_V2(minCarCount: Int = 2, minMoveCount: Int = 10)` 를 만들 수도 있고,
"자동차 부시기" 혹은 "말 달리기" 같은 전혀 다른 게임에서 필요하다면 `CarCount` 와 `MoveCount` 를 사용하는 것도 가능합니다.
 
요구사항에 없는 과도한 기능구현이라 생각되시면, 
`GameBoard` 내부에서 최소값 1로 정의하거나,
최소값과 관련된 유동성을 제거하고, `CarCount` 와 `MoveCount` 의 최소조건을 1로 고정하도록 하겠습니다. ㅠ_ㅠ;

2022-05-25 04:40 UTC, laco-dev requested changes
같이 생각하면서 정리를 공유하느라 추가 전달이 늦어지게 되었네요. 🙏 

지금은 자동차가 가진 책임을 서로 다른 여러개의 함수형 코드를 이용해 상태가 결정된다.
"자동차는 이동한 위치들을 가지고 결과를 나타내야 한다" 라는 책임을 가진다.
책임을 어떻게 바라보는가에 따라 구현해주신 방향도 충분히 나올 수 있는 설계라고 느껴집니다.

지금의 자동차는 결코 테스트와 확장에 유연한 구조라고 할 수 없는 것은 명확한 것 같습니다.
그렇기에 자동차가 가지는 "위치들"을 한번 분리 해 보고, 자동차를 테스트 할 수 있게 만들어 보도록 가이드를 같이 추가 해 보았습니다.

그래서 이번에 드린 피드백은 전체적인 구현 설계 자체는 유지하면서 수정 해 볼만한 내용들 위주로 남겨보았는데요.
한번 더 수정 해 보고 이후 4단계, 5단계 미션을 진행하면서 현재 설계가 가지는 특징을 조금 더 고민해보고 발전시켜 보도록 하시죠.

2022-05-25 04:40 UTC, laco-dev commented on src/main/kotlin/racingcar/car/Car.kt
> +    }
말씀주신 내용처럼 자동차의 의미 보다는 `이동한 위치들`을 가지는 하나의 개념이라고 생각을 합니다.
그렇다면 자동차 입장에서는 `이동한 위치들`이 어떻게 평가되는지는 `이동한 위치들`이 스스로 결정하는 방식은 어떨까요?

최소한 랜덤이라는 불확실성을 자동차에게서 떨어트려 볼 수 있을 것 같습니다.

2022-05-25 04:40 UTC, laco-dev commented on src/main/kotlin/racingcar/car/Car.kt
> +        private const val initPosition = 0
코틀린 컨벤션으로 상수는 대문자 스네이크 형태로 작성합니다.
https://kotlinlang.org/docs/coding-conventions.html#property-names

다른 곳에서도 같이 반영 해주세요 🙏

2022-05-25 04:40 UTC, laco-dev commented on src/main/kotlin/racingcar/car/Car.kt
> +    }
프로퍼티가 함수를 사용해서 반환을 할 경우에는 반환 타입을 명시 해 주시는것을 권장드립니다.
해당 함수가 어떤 타입을 반환하는지 알기 어렵습니다. 🙏 
```kotlin
private val drivingPoints: List<Int> = drivingForces.map { ... }
```

2022-05-25 04:40 UTC, laco-dev commented on src/main/kotlin/racingcar/car/drivingPoint.kt
> +fun drivingPointBy(drivingForce: Int) = if (drivingForce >= DATUM_POINT) FORWARD_POINT else 0
0도 같이 상수`STOP_POINT`로 만들어도 좋을 것 같아요.

2022-05-25 04:40 UTC, laco-dev commented on src/main/kotlin/racingcar/car/Car.kt
> +    private val initPositions = arrayListOf(initPosition)
위 세가지 프로퍼티는 positionsByStep을 만든 이후 더이상 사용되지 않아요.
프로퍼티로 만들지 않고 동일한 역할을 하도록 만들어 보면 어떨까요?

2022-05-25 04:40 UTC, laco-dev commented on src/main/kotlin/racingcar/view/InputView.kt
> +    val moveCount = getMoveCount()
> 덧붙여 혹시 위와 같은 상황,
즉 "파라미터 없이 호출되는 함수에서 언제나 동일한 값을 보장하는 constant 함수"를 표기하는 방법이
코틀린에 따로 있는지도 궁금합니다.

위 내용은 lazy property로 만들어 볼 수 있을 것 같습니다.
선언 시점이 아닌 실제 프로퍼티가 사용될 때 평가를 지연하는 방법입니다.

https://kotlinlang.org/docs/delegated-properties.html#lazy-properties

2022-05-25 04:40 UTC, laco-dev commented on src/main/kotlin/racingcar/view/ResultView.kt
> +    }
위 두 함수가 동반객체로 만들어진 이유가 무엇일까요?
ResultView의 인스턴스가 출력이라는 역할을 수행한 뒤에는 더이상 사용되지 않게 되는데,
클래스 영역에 함수를 항상 만들어 두는 메리트가 부족 해 보입니다.

2022-05-25 04:40 UTC, laco-dev commented on src/test/kotlin/racingcar/car/drivingPointTest.kt
> +    }
특정 기능을 확인할 때에는 반복문을 사용해서 테스트를 할 정도는 아닌 것 같습니다.
여러 케이스를 테스트 할 경우 `@ParameterizedTest`를 고려 해 볼수 있어요.

2022-05-25 04:40 UTC, laco-dev commented on src/main/kotlin/racingcar/view/ResultView.kt
> +class ResultView(private val cars: List<Car>, stepSize: Int) {
자동차마다 서로 다른 Step을 가지고 있을 때는 어떻게 할 수 있을까요?

2022-05-25 04:40 UTC, laco-dev commented on src/test/kotlin/racingcar/car/randomListTest.kt
> +        }
위 테스트도 반복문 보다는 `@ParameterizedTest`를 활용 해 보세요.

2022-05-25 04:40 UTC, laco-dev commented on src/test/kotlin/racingcar/car/randomListTest.kt
> +    }
랜덤 요소를 테스트 해보려는 시도 좋습니다. 👍 
저도 추가로 생각이 든 점은 결국 randomListBy는 내부적으로 IntRange.random() 이라는 함수를 사용하게 되는데 이 테스트에서 하고 싶은건 `IntRange.random()`이 정상적으로 동작하는가?

그뜻은 코틀린 라이브러리의 random이 테스트에서 충분히 검증되어 있다면 추가적으로 확인할 필요는 없지 않을까? 라는 생각도 드네요.
https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/test/random/RandomTest.kt

우리가 객체별로 역할을 나눠서 테스트 하는 것 처럼 랜덤 분포에 대한 테스트는 코틀린 RandomTest에서 수행하지 않았을까... 💭 

번외로 유닛 테스트 환경에서 랜덤을 테스트 하는것에 대한 글을 하나 발견해서 남겨봅니다. 🙏 
https://softwareengineering.stackexchange.com/questions/356456/testing-a-function-that-uses-random-number-generator

2022-05-25 04:40 UTC, laco-dev commented on src/test/kotlin/racingcar/race/CarCountTest.kt
> +    }
테스트 이름에 대해 ::
`@ParameterizedTest`의 name 기능을 이용하면 테스트 이름에서 파라미터를 표현할 수 있어요!
아래 처럼 만들면 테스트에 대한 기대값과 결과를 보다 직관적으로 전달할 수 있을 거에요
```kotlin
@ParameterizedTest(name = "CarCount의 {0} 값은 항상 {1}보다 크거나 같다")
```

이렇게 되면 테스트 검증문도 살짝 변경이 될 수도 있겠네요.
단순히 value를 가진다. 를 테스트 하는 것 보다 기능에 집중할 때 더욱 좋은 테스트가 만들어질 수 있습니다.

2022-05-25 04:40 UTC, laco-dev commented on src/test/kotlin/racingcar/race/RaceTest.kt
> +    }
위 테스트도 `@ParameterizedTest`를 활용 해 보면 어떨까요?

추가로 경주 입장에서는 cars가 만들어지는 방법은 내부적으로 결정하게 됩니다.
그래서 저는 수동이나 의존 형태로 작성되는 표현 보다는 상태 자체를 검증 하는 표현을 선호합니다. 
```
경주를 시작하면 {car_count}개의 자동차를 가진다.
경주를 시작하면 {move_count}개의 레일을 가진다.
```

2022-05-25 04:42 UTC, laco-dev commented
> 코틀린으로도 함수형 프로그래밍이 가능하기 때문에,
저는 두 페러다임을 적절히 조합하여 구현해보려고 했습니다.
이번 강의 (혹은 과제)가 TDD 뿐 아니라 객체지향을 지향하는 강의라면,
가능하면 함수형은 지양하도록 하겠습니다.

`수업에서는 큰 틀에서 OOP를, 세부 구현에는 FP를 권장합니다.`

객체 스스로 자율적으로 행동하며 협력으로 객체들의 관계를 결정하는 객체지향의 원칙을 가지면서
"불변"으로 구현을 만들어 보거나 함수형 처리를 이용해 디테일한 요소에서 이펙트를 줄이는 방향으로 권장을 드리는 것 같습니다.

2022-05-30 15:20 UTC, nfreedom9 commented
말씀해주신 내용들을 기반으로,
`Car` 클래스로부터 랜덤요소에 대한 의존성을 분리하기 위해,
전진 포인트를 제공하는 `Engine` 이라는 인터페이스를 정의하고,
과제물 구현을 위한 `RandomEngine` 과, `Car` 클래스에 대한 테스트 코드를 위한 `ConstantEngine` 을 구현하였습니다.
(진행 과정 중 불필요한 함수와 테스트 코드는 제거하였습니다. `drivingPoint`, `randomList`)
 
`Car` 클래스에 대하여 "스텝별 위치를 제공한다" 는 컨셉은 그대로 유지하였고,
`position` 과 같은 `var` 변수 사용을 지양하고자 Map 을 활용한 memoization 을 사용하였습니다.
자연스럽게(?!) 이동횟수에 대한 의존성은 `Car` 에서 분리되었고,
인스턴스 생성 즉시 `moveCount` 만큼 완주해버리는 일도 발생하지 않게 되었습니다.
 
제가 `Car` 클래스에 대하여 현재 위치를 의미하는 `position` 과 위치를 변화시키는 `move` 대신,
이동단계별 위치를 알려주는 `positionBy` 로 구현하고자 했던 것은,
`position` 값 자체를 변화시키면 지나간 기록들은 모두 휘발 되기 때문이었습니다.
과제물 구현에 있어서는 각 단계별 위치를 출력하는데 한번 사용하고나면 그만이지만,
필요하다면 [특정 자동차의 단계별 위치 출력]과 같이, 
각 자동차의 단계별 위치 기록을 사용할 수 있게 구현하는 것이 활용도가 더 높다고 봤기 때문입니다.

2022-05-30 16:29 UTC, nfreedom9 commented on src/test/kotlin/racingcar/car/randomListTest.kt
> +    }
`IntRange.random()` 이 정상적으로 동작하는지에 대한 테스트라기보다는,
특정 범위 내에서의 랜덤 Int 값을 얻는 방법은 다양한데,
그것이 균일한 분포도를 갖는지 테스트가 필요할 수도 있다는 의미에서 시도해봤습니다.
(구현 방식이 `IntRange.random()` 을 사용한 것이든, 다른 방법을 사용한 것이든,
구현 방식에 대한 테스트가 아니라 구현 결과에 대한 테스트)
 
이전에 언급했듯 `System.currentTimeMillis() % 10).toInt()` 를
`0 이상 9 이하의 랜덤수 반환` 으로 오해할 수도 있기 때문입니다.
 
구현 방식에 대한 신뢰도를 기반으로 테스트의 필요성이 달라진다면,
코드를 작성하는 사람의 언어 및 구현 방식에 대한 숙련도에 따라 그 대상이 달라질 것 같다는 생각도 듭니다.
(사실 저도 이번 강의와 과제를 진행하면서 그 부분이 가장 고민이 많이 되는 부분이기도 합니다.)

2022-06-02 11:57 UTC, laco-dev commented on src/test/kotlin/racingcar/car/randomListTest.kt
> +    }
네, 의견 감사합니다.
랜덤 테스트 관련해서는 정말 프로덕션에서도 적용하기 힘든 개념이라서 이렇게 고민하고 해보는것도 좋은 것 같네요. :)

2022-06-02 12:14 UTC, laco-dev approved these changes
안녕하세요!~

지금까지 많은 고민 해오면서 잘 따라와 주신 것 같아서 정말 고생 많으셨습니다. 🙏 
조금씩 객체지향에 대해 이해해보면서 얼마나 함수형을 활용할 수 있을지는 저도 그렇고 많은 분들이 고민을 하고 있는 주제 같습니다.

지금의 구현 설계로 4단계 진행 해보면서 조금 더 이야기 해 볼 수 있을 것 같습니다.
간단한 의견과 컨벤션 관련해서 남겨드렸는데 다음 단계에서 같이 반영 해 주시면 됩니다.

3단계 미션 종료하겠습니다 🙇

2022-06-02 12:14 UTC, laco-dev commented on src/main/kotlin/racingcar/car/Car.kt
> +        else position.getOrPut(moveCount) { positionBy(moveCount - 1) + engine.advancePoint() }
코틀린 컨벤션에서는 한 줄로 표현할 수 없는 간단하지 않은 if 컨디션은
항상 괄호를 열어서 표현하도록 하고 있어요.
https://kotlinlang.org/docs/control-flow.html

2022-06-02 12:14 UTC, laco-dev commented on src/main/kotlin/racingcar/car/Car.kt
> +    fun positionBy(moveCount: Int): Int =
MoveCount를 받도록 만들면 더욱 좋을 것 같아요~
MoveCount가 1보다 작은지는 MoveCount에게 물어볼 수도 있겠네요!

```kotlin
if (moveCount.isZeroOrNegative()) {
   INIT_POSITION
} else {
   ...
}
```

2022-06-02 12:14 UTC, merged