[Step4] 자동차 경주(우승자)
next-step/kotlin-racingcar pull request #609
Opened 2022-05-17 13:08 UTC by loadkrnis

- 1등을 판별해줄 심판(Referee)을 선언하였습니다.
 - `RacingTrack`에서 `ResultView`를 사용하고 있는데 사실 꽤나 마음에 들지 않습니다. 저는 `RacingTrack`이 `ResultView`를 알필요가 없다고 생각이 들었습니다. `Racing.kt`의 `main` 메소드만 `ResultView`를 알면 될 것 같은데 좋은 방법이 생각나지 않습니다..! 혹시 제가 필요 없는 걱정을 하는건 아닐까 생각도 들어서요! 의견 주시면 감사하겠습니다. 🙏

2022-05-17 15:16 UTC, hyunniiii requested changes
안녕하세요 민규님~!
몇가지 코멘트 남겼으니 확인 부탁드립니다!

2022-05-17 15:16 UTC, hyunniiii commented on README.md
>  - [x] 랜덤 숫자 생성 기능
👍 👍

2022-05-17 15:16 UTC, hyunniiii commented on src/main/kotlin/step3/racing/Car.kt
> +        private set
👍

2022-05-17 15:16 UTC, hyunniiii commented on src/main/kotlin/step3/racing/Car.kt
>  }
```kotlin
    fun move(input: Int) {
        if (input >= MOVING_CONDITION) distance += 1
    }
```
이렇게 바로 표현해줘도 괜찮을 것 같아요 ″̮

2022-05-17 15:16 UTC, hyunniiii commented on src/main/kotlin/step3/racing/InputView.kt
> +        require(!input.isNullOrBlank()) { "입력 값이 없습니다." }
입력값이 잘못 입력된 경우에 여기서 바로 검증해주면 어떨까요?
문자를 입력하면 바로 잘못된 입력이라는 것을 알도록하면 좋을 것 같습니다 ″̮

2022-05-17 15:16 UTC, hyunniiii commented on src/main/kotlin/step3/racing/Racing.kt
> +    println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).")
`, `가 없는 부분에 대한 검증과 테스트가 있으면 좋을 것 같습니다.

2022-05-17 15:16 UTC, hyunniiii commented on src/main/kotlin/step3/racing/RacingTrack.kt
>      }
```kotlin
val racers:List<Car> = racerNames.map { Car(it) }
```
이렇게 간결하게 표현도 가능합니다 ″̮

2022-05-17 15:16 UTC, hyunniiii commented on src/main/kotlin/step3/racing/Referee.kt
> +    }
우승자 조건에 대한 테스트도 있으면 좋을 것 같습니다.

2022-05-17 15:16 UTC, hyunniiii commented on src/main/kotlin/step3/racing/RacingTrack.kt
> +class RacingTrack(racerNames: List<String>, val times: Int) {
`RacingTrack`의 책임은 무엇일까요?
 `RacingTrack`의 책임이 모호한 것 같습니다.
 `List<Car>`를 가지고 있는 클래스를 생성하여 책임을 분배해보는건 어떨까요?

2022-05-17 15:16 UTC, hyunniiii commented on src/main/kotlin/step3/racing/RacingTrack.kt
> +            ResultView.showDistance(it.name, it.distance)
RacingTrack에서 ResultView를 가지고 있는 것은 다음 미션 요구사항과 연관되어 있습니다 ″̮ 
MVC 패턴을 참고해서 고민해보는건 어떨까요?
https://velog.io/@seongwon97/MVC-%ED%8C%A8%ED%84%B4%EC%9D%B4%EB%9E%80

2022-05-18 03:22 UTC, loadkrnis commented on src/main/kotlin/step3/racing/InputView.kt
> +        require(!input.isNullOrBlank()) { "입력 값이 없습니다." }
말씀해주신대로 수정한다면 `readLine()` 메소드를 `InputView`에서 사용해야할 것 같은데요.
그렇게되면 `readLine()` 때문에 테스트가 힘들어진다고 생각했는데.
혹시 제가 잘못이해한걸까요?
```kt
object InputView {
  fun getInt(): Int {
    println("시도할 횟수는 몇 회인가요?")
    val input = readLine()
    require(!input.isNullOrBlank()) { "입력 값이 없습니다." }
    return input.toIntOrThrow()
  }
}
```

2022-05-18 06:50 UTC, loadkrnis commented on src/main/kotlin/step3/racing/RacingTrack.kt
> +class RacingTrack(racerNames: List<String>, val times: Int) {
음 .. `List<Car>`를 꼭 빼야할 필요성을 잘 모르겠습니다 .. ! 🤔
하지만 `RacingTrack`의 역할이 많은 것으로 보여서 1등을 확인하는 작업은 온전히 `Referee`(심판)에게 위임하였습니다.

2022-05-18 13:38 UTC, hyunniiii commented on src/main/kotlin/step3/racing/InputView.kt
> +        require(!input.isNullOrBlank()) { "입력 값이 없습니다." }
아 제가 라인을 헷갈렸네요. 죄송합니다. 🙇 

getStringArray에서  `,`가 없는 경우의 대한 검증과 테스트가 필요할 것 같아서 남긴 리뷰였습니다!

2022-05-18 13:39 UTC, hyunniiii approved these changes
안녕하세요 민규님~!
다음 미션을 위해서 머지하겠습니다!
드디어 1단계 마지막 미션이네요 ″̮
MVC 패턴 기반으로 리팩토링 잘 부탁드립니다 🙇

2022-05-18 13:39 UTC, merged