Step3
next-step/kotlin-racingcar pull request #616
Opened 2022-05-17 15:47 UTC by glennsm

step2 추가 pr수정건과 step3 건입니다:)

2022-05-17 16:30 UTC, ohgillwhan requested changes
상민님 안녕하세요!

리뷰 반영 잘 해주셔서 감사합니다!! 💯 

몇가지의 코멘트를 남겼으니, 확인해주세요!

감사합니다!

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/calculator/Operation.kt
> +enum class Operation(val exp: String, val compute: (Int, Int) -> Int) {
`compute` good!

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/calculator/Operation.kt
> +        }.getOrElse { throw IllegalArgumentException() }
`.first {}`를 실행해서, 원하는 결과가 없으면 `NoSuchElementException`이 자동으로 발생하기 때문에, 
`values().first {}` 만으로도 충분합니다!

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Car.kt
> +    var progress: Boolean = false
`progress`는 테스트를 위해서 만들어진것 같네요!
최대한 테스트를 위한 코드는 제거하고, 프로그램 로직을 수행할 때 필요로한 데이터로 검증을 해볼까요?

테스트 코드에서는 `position`이 변경됬는지로 체크가 가능할꺼에요!

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Car.kt
> +    }
이 코드는 제거되어도 괜찮아 보이네요 :D

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Car.kt
> +    fun move(condition: Int) {
테스트 편의성 💯

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Car.kt
> +        return (0..9).random()
코틀린 스러움! 💯

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/RacincarApp.kt
> +    val tryCnt = InputView("시도할 횟수는 몇 회인가요?").value
```suggestion
    val inputView = InputView()
    val carCnt = inputView.readCarCount()
    val tryCnt = inputView.readTryCount()
```

위의 방식으로 바꾸는것도 고민해볼까요?
`.value`를 하면 변수를 읽는것 같지만, 실제로는 콘솔에서 데이터를 읽고 있어요.
`.value`를 자바 코드로 변경하면 `.getValue()`와 같은데, 이런 코드는 단순하게 변수를 가져오는것을 의미합니다.

`InputView`에게 너 ~~좀 해줘! 라고 명령하면(함수 호출), 다른 개발자도 이해하기 편할거에요.

다른 개발자가 보았을때도 명확한 코드면 좋겠죠?

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/RacincarApp.kt
> +    InputView("\n실행결과")
출력이 더 가까울것 같네요!

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/RacingGame.kt
> +    }
우리가 구현해야 할 핵심 로직은 `Car`와 `RacingGame` 입니다.
미션에서는 간단하게 하기 위해 콘솔을 통한 `In/Out`을 하고 있습니다. 하지만 이 코드가 전체적으로 `Spring`이나, `그래픽 프로그램`으로 넘어가게 된다면 어떨까요?

사용자와의 의사소통 방법이 바뀌었는데, 우리가 구현해야 할 핵심 로직도 변경해야 할까요?

화면에서 필요로 하는 데이터를 반환해주고, 함수를 호출한 부분에서 그 값을 받아서 `print` 해주는건 어떨까요?

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/ResultView.kt
> +class ResultView {
ResultView 클래스 분리! 💯

2022-05-17 16:30 UTC, ohgillwhan commented on src/test/kotlin/calculator/CalculationTest.kt
> +            .isThrownBy { Calculation(expr).run() }
전체적으로 리뷰 반영 잘 해주셨습니다!

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/Car.kt
> +    var position: Int = 0
위의 값은 생성자에 넣어도 충분하지 않을까요? 객체를 생성할 때 상태값만 확실하게 조건처리 한다면, 생성자는 풍부할 수록 좋습니다.

2022-05-17 16:30 UTC, ohgillwhan commented on src/test/kotlin/racingcar/CarTest.kt
> +        assertThat(car.progress).isEqualTo(true)
`progress` 는 테스트를 위한 프로퍼티로 보이네요! `position` 값으로 검사해도 괜찮습니다.

2022-05-17 16:30 UTC, ohgillwhan commented on src/test/kotlin/racingcar/CarTest.kt
> +        assertThat(car.progress).isEqualTo(false)
`progress` 는 테스트를 위한 프로퍼티로 보이네요! `position` 값으로 검사해도 괜찮습니다.

2022-05-17 16:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/RacingGame.kt
> +                it.move(it.generate())
`it.generate()`를 사용하게 된다면, 결국 `RacingGame`도 `랜덤`에 직접적인 연관이 생기게 되므로, 테스트도 어려워집니다.

이 방법을 해결하기 위해서는 `전략패턴`을 사용하면 됩니다.

https://victorydntmd.tistory.com/292

2022-05-19 08:31 UTC, glennsm commented
> `it.generate()`를 사용하게 된다면, 결국 `RacingGame`도 `랜덤`에 직접적인 연관이 생기게 되므로, 테스트도 어려워집니다.
> 
> 이 방법을 해결하기 위해서는 `전략패턴`을 사용하면 됩니다.
> 
> https://victorydntmd.tistory.com/292

전략패턴 대신 generate() 람다식으로 넘겨서 처리해보았습니다!

2022-05-20 04:30 UTC, ohgillwhan requested changes
안녕하세요!

전체적으로 잘 작성해주셨고, todolist 를 조금만 더 세분화 해도 좋아보여요.

확인부탁드립니다!

2022-05-20 04:30 UTC, ohgillwhan commented on src/main/kotlin/calculator/Operation.kt
> +        if (v2 == 0) throw IllegalArgumentException()
`require` 로 변경해볼까요

2022-05-20 04:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/RacincarApp.kt
> +    ResultView().execute(cars, tryCnt)
엔터를 통해서 코드의 블록을 나누면 가독성이 더 좋아집니다!

2022-05-20 04:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/domain/Car.kt
> +        if (condition in 4..9) {
`4..9`가 무엇을 의미하는것인지 상수화 해서 표현해도 좋겠네요!

2022-05-20 04:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/domain/Car.kt
> +class Car(var position: Int = 0) {
`position`을 public으로 해야할까요?

2022-05-20 04:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/ui/InputView.kt
> +        return readLine()!!.toInt()
`readLine()` 대신 `readln()`을 사용해봐요!

2022-05-20 04:30 UTC, ohgillwhan commented on src/main/kotlin/racingcar/domain/Car.kt
> +        histories.add(CarHistory(position, true))
자동차에게 `histories`를 알게해도 괜찮겠지만, 이렇게 되면 우리가 가장 중요하고 보호해야 할 도메인에 있는 변수를 직접 접근해야할것이고, 그러면 조금 위험하지 않을까 싶어요. 
그리고 `histories`의 타입은 `MutableList`라서 외부에서 `add`같은것도 작동할거에요.

이렇게 소중한 도메인을 보호하기 위해서는 `move`시 결과를 불변객체로 내려줘도 충분할거에요.

2022-05-21 06:56 UTC, ohgillwhan approved these changes
상민님 안녕하세요!

`step3`도 고생 많으셨습니다.

리뷰 남긴것은 다음 스텝에 적용 부탁드립니다!

2022-05-21 06:56 UTC, ohgillwhan commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +        return histories.toList()
코틀린에서는 거의 가변리스트를 잘 안만들어 보는 습관을 만드는게 좋습니다.
그게 가능한것은 `map`등의 함수가 잘 제공되기 떄문입니다.

그래서 위의 코드는 다음과 같이 리팩터링이 가능합니다.

```suggestion
return cars.map { it.move(method()) }
```

2022-05-21 06:56 UTC, ohgillwhan commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +    }
가변리스트를 제거해볼까요?

2022-05-21 06:56 UTC, ohgillwhan commented on src/main/kotlin/racingcar/domain/RacingGame.kt
> +    }
가변리스트를 제거해볼까요?

2022-05-21 06:56 UTC, merged