3단계 - 자동차 경주
next-step/kotlin-racingcar pull request #744
Opened 2022-11-04 14:02 UTC by harrisleesh

테스트를 먼저 짜려고 노력은 했는데 잘 안되네요 ㅎㅎ
비즈니스 로직이 많지는 않아서 테스트가 좀 부족하네요!

랜덤 전략으로 RacingCar가 움직이는데 이 의존성을 RacingCars나 RacingCarGame으로 전파하고 싶지 않았어요!
그러다보니 RacingCarGame의 테스트를 짜는게 어렵네요!

코드리뷰 부탁드립니다!! 감사해요 :)

2022-11-05 11:25 UTC, malibinYun requested changes
2단계 미션 고생 많으셨어요 :)
랜덤에 대한 주입을 상위로 노출하지 않으면, 결국 해당 클래스는 테스트하기 어려워집니다.
이런 전략들은 가장 최상위인 main까지 올려도 괜찮다고 생각해요. 그럼 모든 클래스가 테스트하기 용이해지기 때문이에요 :)
테스트 하지 않아도 되는 단계까지 적절히 추상화하는 것이 가장 어려운 일이란 생각이 드네요.

생각해보면 좋을 점들에 코멘트 달아두었어요!
피드백 반영하시고 다시 리뷰 요청 부탁드려요 😀

2022-11-05 11:25 UTC, malibinYun commented on src/test/kotlin/step2/StringCalculatorTest.kt
> +        assertThatExceptionOfType(IllegalArgumentException::class.java).isThrownBy { StringCalculator.calculate(input) }
assertAll을 사용하면 모든 테스트를 다 실행하고, 실패한 테스트가 무엇인지 알려주게 돼요.
사용하지 않으면, 실패한 테스트 라인 이후로는 코드를 실행하지 않아, 해당 라인 테스트를 고치더라도 아래 테스트에서 또 다시 fail이 나는 경우가 생길 수 있습니다.
테스트가 여러개라면 assertAll 사용을 권장드려요 :)

2022-11-05 11:25 UTC, malibinYun commented on src/main/kotlin/step2/StringCalculator.kt
> +            Operator.DIVIDE -> base / operand
operator가 계산하는 람다식을 갖게하는 것을 어떨까요?
그럼 아래와 같은 코드가 기대됩니다 :)
```kotlin
val operator = Operator.from(...)
val result = operator.calculate(leftValue, rightValue))
```

2022-11-05 11:25 UTC, malibinYun commented on src/main/kotlin/step2/Operator.kt
> +        }
$같은 문자를 넣으면 어떤 일이 발생할 수 있을까요?

2022-11-05 11:25 UTC, malibinYun commented on src/main/kotlin/game/racingcar/RacingCar.kt
> +    private val moveStrategy: MoveStrategy = RandomMoveStrategy(),
자동차의 움직임 전략을 외부로부터 주입해주셨네요! 👍👍

2022-11-05 11:25 UTC, malibinYun commented on src/main/kotlin/game/racingcar/RacingCarGame.kt
> +    fun play(): MutableList<List<Int>> {
MutableList보다는 List를 반환하는 것은 어떨까요?
처음 작성할 땐 불변으로, 필요할 때 가변으로 바꾸는 것을 추천드려요 :)

2022-11-05 11:25 UTC, malibinYun commented on src/main/kotlin/game/racingcar/RacingCarGame.kt
> +
locationSnapshot을 나타내는 List\<Int>를 클래스로 분리해보는 것은 어떨까요?

2022-11-05 11:25 UTC, malibinYun commented on src/main/kotlin/game/racingcar/RacingCars.kt
> +    }
moveAll의 결과로 snapshot을 반환해보는 것은 어떨까요?

2022-11-05 11:25 UTC, malibinYun commented on src/main/kotlin/game/racingcar/RacingCars.kt
> +    }
확장함수 체이닝으로 코드를 바꿔보는 것은 어떨까요?
힌트를 드리면,
```kotlin
(1..numberOfCars).map { ... } 
```
위처럼 숫자를 IntRange 객체로 만들 수 있습니다 :)

2022-11-05 11:25 UTC, malibinYun commented on src/test/kotlin/game/racingcar/RacingCarTest.kt
> +        assertThat(racingCar.location).isEqualTo(preLocation + 1)
테스트 코드의 검증부는 하드 코딩하는 것이 바람직합니다.

도메인 로직을 활용한 테스트의 방식은, 결국 프로덕션 코드를 copy & paste 한 결과와 다르지 않습니다.
가장 문제가 되는 점은, 해당 도메인 로직 자체에 버그가 존재하더라도 해당 테스트 코드는 통과하게 됩니다. 도메인 로직을 그대로 사용해서 비교하기 때문이에요.

그렇기에 Expression을 만들 때 내부 계산 로직을 활용하는 게 아닌, 결과 값을 직접 하드 코딩하는 것이 좋습니다.
검증부 하드 코딩에 대한 좋은 글을 공유드립니다. 꼭 읽어 보시길 바라요 :)
[https://jojoldu.tistory.com/615?category=1036934](https://jojoldu.tistory.com/615?category=1036934)

2022-11-05 12:28 UTC, harrisleesh commented on src/main/kotlin/step2/Operator.kt
> +        }
앗 예외를 처리해줘야 하겠네요!! 감사합니다 :)

2022-11-05 12:47 UTC, harrisleesh commented on src/main/kotlin/game/racingcar/RacingCars.kt
> +    }
엇!! 이부분은 좀 얘기하고 싶은데요!!
일부러 데이터를 변경하는 함수와 조회하는 함수를 분리했거든요 (CQRS의 일환으로)
혹시 이렇게 제안해주신 이유는 무엇인가요??

2022-11-05 12:49 UTC, harrisleesh commented on src/main/kotlin/game/racingcar/RacingCars.kt
> +    }
오오 감사합니다!! mutableList에서 List로 불변으로 바꿀 수 있게 되었네요!
이부분도 구현하면서 좀 찝찝했던 부분인데 덕분에 해결했습니다.

2022-11-05 12:55 UTC, harrisleesh commented on src/test/kotlin/game/racingcar/RacingCarTest.kt
> +        assertThat(racingCar.location).isEqualTo(preLocation + 1)
오오... 이부분은 처음 알았네요!!
결과값을 검증할 때에는 하드코딩으로 하는 것! 기억하겠습니다!

감사합니다

2022-11-05 13:16 UTC, harrisleesh commented
리뷰 감사해요!
추가적으로 https://github.com/next-step/kotlin-racingcar/pull/744#discussion_r1014621650 이 리뷰와 관련해서 댓글 남겼는데 확인 부탁드립니다.

나머지 내용 반영해서 다시 리뷰요청 보내드려요 :)

2022-11-06 02:01 UTC, malibinYun commented on src/main/kotlin/step2/Operator.kt
> +}
코틀린은 람다(함수)가 일급 시민 이어서 변수에 할당할 수 있어요.
```kotlin
enum class Operator(
    val sign: String,
    val calculate: (Int, Int) -> Int,
) {
    PLUS("+", { left, right -> left + right }),
    ...
```

또, enum class에서는 자신의 모든 enum 을 values() 라는 메서드를 통해 가져올 수 있답니다.
```kotlin
fun from(sign: String): Operator {
    return values().find { it.sign == sign }
        ?: throw ~~
}
```
이런 식으로 enum과 코틀린에서 제공해주는 함수들을 이용하면 if문을 모두 지워볼 수 있어요 😊

2022-11-06 02:01 UTC, malibinYun commented on src/main/kotlin/game/racingcar/RacingCarGame.kt
> +    }
이 구문도 메서드 체이닝으로 바꾸는 걸 연습해보는 건 어떨까요?

2022-11-06 02:01 UTC, malibinYun commented on src/main/kotlin/game/racingcar/RacingCars.kt
> +    }
CQRS의 일환으로 분리하는 것도 공감해요.
다만, moveAll()은 객체의 상태만 변경하는 사이드 이펙트를 발생 시키는 메서드예요.
메서드를 실행하면 무슨 일이 벌어지는 지 내부를 보지 않으면 알 수 없어요.
그렇기 때문에 값을 반환하면 메서드가 무슨 변화를 수행했는지 즉시 알 수 있는 장점이 있어요.

움직임 결과를 가져오기 위해서는 반드시 moveAll() 호출 후 locationSnapshot()을 호출해야 한다는 내부 규칙을 알아야만 사용할 수 있다는 단점도 있습니다.
play()를 호출하면 바로 결과를 가져올 수 있는 것 처럼, 비슷한 흐름이라고 생각해요!

또, 코틀린 확장함수들을 체이닝해서 한 줄 람다식으로 깔끔하게 작성할 수도 있는 장점이 있겠네요!

조회만 하는 것은 남겨도 좋고, CQRS를 지켜서 남겨둬도 괜찮다는 의견입니다.
사실 코딩에는 정답이란 게 없으니까요!

2022-11-06 02:01 UTC, malibinYun approved these changes
3단계 미션 피드백 반영 고생 많으셨어요!
코멘트 남겨두었으니 확인 부탁 바라요~
다음 미션을 위해 머지하겠습니다.
다음 미션도 화이팅이에요!! 💪

2022-11-06 02:01 UTC, merged

2022-11-06 03:30 UTC, harrisleesh commented on src/main/kotlin/game/racingcar/RacingCars.kt
> +    }
앗 그렇군요 ㅎㅎ 답변 감사합니다.
맹목적으로 분리하는 것보다 장단점을 잘 따져서 선택하는 연습을 해야겠군요!!
일단 제안해주신 대로 변경해보겠습니다!! 감사합니다!!

2022-11-06 03:48 UTC, harrisleesh commented on src/main/kotlin/step2/Operator.kt
> +}
와.. 감사합니다!!
함수형 프로그래밍이 익숙치가 않아서 이런 방법은 전혀 생각도 못했네요!!