3단계 - 자동차 경주
next-step/kotlin-racingcar pull request #751
Opened 2022-11-05 05:38 UTC by leedo1982

과제 3단계 구현해보았습니다

잘이해하고 작성했는지 모르겠네요 ;;

코드리뷰 감사드립니다

2022-11-05 23:40 UTC, namjackson requested changes
3단계 자동차 경주 미션 잘구현해주셨네요! 👍 
몇가지 고민해보실법한 포인트들 코멘트로 남겼으니, 확인해주세요!
이전단게 피드백도 함께 적용해주시면 좋을거 같아요!
변경사항 적용후, 다시 리뷰 요청해주시면 감사하겠습니다!

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/README.md
> +- InputView, ResultView 로 UI 분리, RacingCarMain 구현
요구사항 및 todo 정리 👍

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/RacingCarMain.kt
> +    racingCar.race()
Exception 처리도 필요할걱같아요!

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/model/Car.kt
> +    private var racingTimes: Int = 0
횟수를 의미하는 변수도 지정하셨군요 👍 
location, racingTimes등의 정보는 생성자에 주입받을수 있게하면 어떨까요?
객체 생성시, 커스텀된 프로퍼티로 조금 더 다양한 테스트하기 수월해질거 같아요! 
```kotlin
class Car(
    private var location: Int = 0
    private var racingTimes: Int = 0
)
```

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/model/Car.kt
> +    private var history: MutableMap<Int, Int> = mutableMapOf()
불필요한 경우라면 불변변수로 지정해주세요! `val`

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/model/Car.kt
> +    fun advance(randomDigit: Int) {
Car의 이동하는 기준에 대한 로직이 분산되어있는것 같아요.
randomDigit을 생성해주는곳은 호출부에서 이루어지고,
생성된 randomDigit에 대한 처리는 car에서 해주고 있네요! 

현재 구조에 대한 이해가 없다면, 헷갈릴거 같아요!
advance에 왜 랜덤숫자가 필요할까? 랜덤숫자를 입력한대로 이동할까?  등등의 의문이 생길걱같아요!

이부분에 대해서 고민해보시는게 좋을거 같아요!

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/model/Car.kt
> +        history[racingTimes] = location
요구사항에 없는 
history까지 관리하도록 구현하셨네요 👍 
단순 history관리라면 list로 관리해도 되지않을까요?

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/model/Car.kt
> +    fun history(): Map<Int, Int> = history.toMap()
`val location: Int get() = _location` 구조나
`getLocation()` 등의 함수명은 어떨ㄲ까요?

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/model/RacingCar.kt
> +    fun cars(): List<Car> = cars.toList()
방어적 복사 👍 👍 

마찬까지로 cars()라는 함수는 조금 어색한거같아요! 
`getCars()` 혹은 
`val cars get() = _cars.toList()`
은 어떨까요?

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/model/RacingCar.kt
> +        }
반복문이 중첩되네요! 함수로 분리하여 가독성을 개선해보면 어떨까요?

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/model/RacingCar.kt
> +        }
cars를 준비하는 함수를 만들어보는건 어떨까요?

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/view/InputView.kt
> +class InputView {
객체생성이 불필요하다면, object로 선언하셔도 좋을거 같아요!

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/view/InputView.kt
> +        fun input(): Pair<Int, Int> {
input이라는 이름은 너무 광범위한거 같아요.
조금더 구체적인 네이밍을 작성해보면 어떨까요?

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/view/InputView.kt
> +            val numberCars: String = readLine()!!
!! 사용은 지양하는 것이 좋습니다!
safe한 null처리 방법을 사용해주세요!

2022-11-05 23:40 UTC, namjackson commented on src/main/kotlin/study/step3/view/ResultView.kt
> +                cars.forEach {
forEach가 중첩되었네요, 
for문이 여러번 중첩된 경우, 코드도 복잡해지고, 가독성도 좋지 않은거 같아요!
함수를 분리해보면 어떨까요?

2022-11-05 23:40 UTC, namjackson commented on src/test/kotlin/study/step3/model/CarTest.kt
> +            assertThat(afterLocation - beforeLocation).isOne()
테스트 코드 블락에 Given , when, then의 범위를 나눠보면, 테스트 코드 가독성이 좋아집니다!
```kotlin
            // given 
            val car = Car()
            val beforeLocation = car.location()

            // when
            car.advance(it)

            // then 
            val afterLocation = car.location()
            assertThat(afterLocation - beforeLocation).isOne()
```

2022-11-05 23:40 UTC, namjackson commented on src/test/kotlin/study/step3/model/RacingCarTest.kt
> +internal class RacingCarTest : StringSpec({
RacingCar에서 랜덤함수를 사용하기 때문에, 구체적인 race 함수에 대한 테스트작성이 모호해진거같아요.
Random 함수를 사용하는 경우, 어떻게 테스트를 하면 좋을까요?

랜덤 숫자를 제공하는 인터페이스를 생성하고, 구현체를 주입받아 사용하는 구조는 어떨까요?

2022-11-06 01:02 UTC, leedo1982 commented on src/main/kotlin/study/step3/RacingCarMain.kt
> +    racingCar.race()
(자동차 경주시 발생하는 exception 을 처리해서, 사용자가 에러를 보지 못하게 하자는 의도가 맞으실까요?)
우선 전체에 try/catch 를 적용해서, 에러가 나더라도 사용자가 원인을 확인할 수 있게 print 시키도록 수정하였습니다

2022-11-06 01:05 UTC, leedo1982 commented on src/main/kotlin/study/step3/model/Car.kt
> +    private var racingTimes: Int = 0
Car 이 처음 생성될때, 외부에서 설정되면 안될것으로 생각하고, 내부에 정의해보았는데요
말씀해주신대로 적용해서  더 다양하게 확인해보겠습니다

2022-11-06 01:07 UTC, leedo1982 commented on src/main/kotlin/study/step3/model/Car.kt
> +    private var history: MutableMap<Int, Int> = mutableMapOf()
MutableMap 이어도 val 로 설정하여 처리가 가능하군요
이부분을 자주 오해했던거 같네요.
val 로 수정하겠습니다

2022-11-06 01:09 UTC, leedo1982 commented on src/main/kotlin/study/step3/model/Car.kt
> +    fun advance(randomDigit: Int) {
네 ,
전진할지 멈출지는 RacingCar에서 판단하고, car 은 전진하거나 멈추거나 하는 기능하는것으로 수정하겠습니다

2022-11-06 01:18 UTC, leedo1982 commented on src/main/kotlin/study/step3/model/Car.kt
> +        history[racingTimes] = location
결과출력을 한번에 처리하려면 history 가 유용한것으로 생각되어 만들어보았는데요.
list 로 고민하다가 list 의 index 가 시도횟수라는 의미를 가지고 있는 것 보다 
map 으로 "시도횟수 : 결과" 가 명확해보여 map 으로 해보았는데요~

list 로 변경해보겠습니다

2022-11-06 01:32 UTC, leedo1982 commented on src/main/kotlin/study/step3/model/Car.kt
> +    fun history(): Map<Int, Int> = history.toMap()
넵, 함수명을 수정하도록 하겠습니다

2022-11-06 01:33 UTC, leedo1982 commented on src/main/kotlin/study/step3/model/RacingCar.kt
> +    fun cars(): List<Car> = cars.toList()
넵 함수명 수정하겠습니다

2022-11-06 01:35 UTC, leedo1982 commented on src/main/kotlin/study/step3/model/RacingCar.kt
> +        }
넵, 함수를 분리하겠습니다

2022-11-06 01:35 UTC, leedo1982 commented on src/main/kotlin/study/step3/model/RacingCar.kt
> +        }
넵, 함수를 분리하겠습니다

2022-11-06 01:38 UTC, leedo1982 commented on src/main/kotlin/study/step3/view/InputView.kt
> +class InputView {
아하, 이런 경우 object 를 사용하면 되는군요

2022-11-06 01:39 UTC, leedo1982 commented on src/main/kotlin/study/step3/view/InputView.kt
> +        fun input(): Pair<Int, Int> {
넵, 수정하겠습니다

2022-11-06 01:42 UTC, leedo1982 commented on src/main/kotlin/study/step3/view/InputView.kt
> +            val numberCars: String = readLine()!!
네, !! 제거하겠습니다

2022-11-06 01:45 UTC, leedo1982 commented on src/main/kotlin/study/step3/view/ResultView.kt
> +                cars.forEach {
넵, 함수로 분리하겠습니다

2022-11-06 01:45 UTC, leedo1982 commented on src/test/kotlin/study/step3/model/CarTest.kt
> +            assertThat(afterLocation - beforeLocation).isOne()
넵,  범위 나눠보겠습니다

2022-11-06 02:08 UTC, leedo1982 commented on src/test/kotlin/study/step3/model/RacingCarTest.kt
> +internal class RacingCarTest : StringSpec({
RacingCar 에서 숫자를 제공하는 인터페이스를 주입받아 사용하고, 해당 구현체 활용하여 테스트 만들겠습니다

2022-11-06 12:57 UTC, namjackson reviewed
3단계 자동차 경주 미션 고생하셨습니다! 
변경사항 잘 적용해주셨네요 👍 👍 
몇가지 참고하실만한 내용 코멘트로 남겼으니, 확인해주세요! 
미션 진행을 위해 머지하겠습니다! 다음 미션도 화이팅입니다 ! 😄

2022-11-06 12:57 UTC, namjackson commented on src/main/kotlin/study/step3/RacingCarMain.kt
> +    try {
tryCatch문을 이용하여, 에러 메시지를 표시해주셧네요 👍  
코틀린에서  Result 클래스를 리턴해주는 같은 기능을 하는 runCatching을 제공해주는데요.
이런 부분을 활용하면, 좀더 가독성과 함수형스러운 코드를 작성할수 있는거 같아요!

```kotlin
       runCatching {
            // ..
        }.onSuccess { result ->
            // ..
        }.onFailure { error ->
            // ..
        }
```

2022-11-06 12:57 UTC, namjackson commented on src/main/kotlin/study/step3/util/DigitNumber.kt
> +    fun getDigit(): Int
숫자를 만들어주는 인터페이스를 작성해주셨네요 👍 👍 
다만 DigitNumber라는 이름은 숫자를 생성해준다기보다, 자료형에 가까운 이름인거같아요 
DigitGenerator, NumberGenerator 같은 네이밍은 어떨까요?

2022-11-06 12:57 UTC, namjackson commented on src/main/kotlin/study/step3/util/StaticDigit.kt
> +class StaticDigit(private val digit: Int) : DigitNumber {
테스트가 힘든 랜덤 함수를 대체할수 있는 구현체  👍 👍

2022-11-06 12:57 UTC, namjackson commented on src/main/kotlin/study/step3/model/RacingCar.kt
> +            }
( 개인적인 의견이니, 참고만 해주셔도 좋습니다! )
현재 구조는 RacingCar 클래스내에서 차를 이동시킬지, 멈출지에 대해 판단을 하고있는데요,
차가 움직이는 책임을 Car 클래스에 옮겨 보는건 어떨까요?

Racing클래스에서는 실제 Car가 어떤 기준으로 이동하고, 동작하는지에 대해 구체적으로 알필요는 없을거같단 생각이 드는데요.
Racing클래스의 경우는 경기를 진행하는 책임을, Car는 차가 이동하는 책임을 분리하고, 
서로 협력하게 하면 좀더 객체지향적일거 같단 생각이 들어요!

2022-11-06 12:57 UTC, namjackson commented on src/test/kotlin/study/step2/ExpressionTest.kt
> +class ExpressionTest : StringSpec({
기존에 calculator에 혼합되어 테스트 되었던, 
계산 + 문자열 검증 기능을 분리하여 검증하게 되었네요! 

검증기능의 테스트 뿐아니라, 기존  calculator의 계산 테스트의 신뢰도가 늘어난거 같아요!

2022-11-06 12:58 UTC, merged

2022-11-06 23:37 UTC, leedo1982 commented on src/main/kotlin/study/step3/RacingCarMain.kt
> +    try {
네, runCatching 사용해보겠습니다

2022-11-06 23:37 UTC, leedo1982 commented on src/main/kotlin/study/step3/util/DigitNumber.kt
> +    fun getDigit(): Int
네, 이름 변경하겠습니다

2022-11-06 23:44 UTC, leedo1982 commented on src/main/kotlin/study/step3/model/RacingCar.kt
> +            }
네, 차의 이동책임을 Car 로 옮기도록 하겠습니다