[2단계] - 문자열 계산기
next-step/kotlin-racingcar pull request #756
Opened 2022-11-05 13:07 UTC by SangHyunGil

안녕하세요 리뷰어님~! 😄
2단계 구현 완료 되어 리뷰 요청 드려요 ㅎㅎ

이번에 진행하면서, 일급 컬렉션을 이용해 Split으로 분리된 연산자와 피연산자를 관리하면서 계산을 하면 조금 더 깔끔한 방향으로 구현이 될 것 같아서 구현해 봤어요!
테스트 코드를 짜면서, Junit5의 ParameterizedTest와 같은 부분을 찾아보다가 kotest-framework-dataset의 withData를 발견해 적용해보았어요~!

요즘 급격히 날씨가 추워지고 있는데 감기조심하세요~!
바쁘신 와중에 감사드려요 ㅎㅎ

2022-11-05 17:24 UTC, ujusy requested changes
안녕하세요~ 문자열 계산기 구현해주시느라 고생하셨습니다! 
테스트를 너무 꼼꼼하게 작성해주셔서 코드를 파악하는데 도움이 많이 되었습니다 👍

몇 가지 고민해볼 부분을 코멘트를 남겼습니다. 
확인 후 다시 리뷰 요청 주세요 🙏

그리고 현재 계산기를 실행해 볼 수 있는 main 함수가 존재하지 않는데요, 실제로 콘솔에서 문자열 계산기를 실행해볼 수 있는 코드가 있으면 좋을 것 같습니다 🙂

2022-11-05 17:24 UTC, ujusy commented on README.md
> +예를 들어 "2 + 3 * 4 / 2"와 같은 문자열을 입력할 경우 2 + 3 * 4 / 2 실행 결과인 10을 출력해야 한다.
커밋을 잘 나누어 올려주신 부분 너무 좋습니다 👍
README.md에 단순히 미션에 있는 요구사항을 나열하는 것이 아니라 내가 실제로 구현해야 할 기능을 구체적으로 나열하면 더 좋을 것 같아요 :)
- [ ] 더하기 기능 구현
- [ ] 빼기 기능 구현
- [ ] 곱하기 기능 구현
- [ ] 나누기 기능 구현
  - [ ] 0으로 나눌 수 없다.
 .....

2022-11-05 17:24 UTC, ujusy commented on src/main/kotlin/calculator/Calculator.kt
> +        val tokenizeData = Parser.parse(rawString)
`tokenizeData` 가 어떤 타입인지 명시해보는 건 어떨까요?
IDE를 이용하면 쉽게 알 수 있지만 읽는 입장에서는 무슨 타입인지 알기 어려울 것 같아요 :)
코드를 항상 IDE에서 읽지 않는 다는 점을 고려해서 작성해보시면 더 좋을 것 같아요!

2022-11-05 17:24 UTC, ujusy commented on src/main/kotlin/calculator/Expression.kt
> +        require(isCorrectExpression()) { "수식이 올바르지 않습니다." }
만족해야 하는 조건을 별도의 함수로 분리해 적절한 이름을 붙여 명확하게 표현한 부분 너무 좋습니다 👍
이렇게 조건을 함수로 분리한다면 `require` 문 자체를 함수 내로 옮겨 가독성을 높이는 건 어떨까요?

2022-11-05 17:24 UTC, ujusy commented on src/main/kotlin/calculator/Expression.kt
> +            .drop(1)
한 줄에 하나의 함수 씩 체이닝되어 코드가 간결해보이네요 👍

2022-11-05 17:24 UTC, ujusy commented on src/main/kotlin/calculator/Expression.kt
> +    private fun isMoreThanMinimumSize() = rawExpression.size > 2
전체적으로 매직 넘버가 많이 사용되고 있는데 이를  정적이고 변경 불가능한 상수로 선언하여 사용해보는게 어떨까요? 
상수로 선언하면 어떤 의도로 사용되는지 좀 더 수월하게 파악할 수 있을거에요 :)

2022-11-05 17:24 UTC, ujusy commented on src/main/kotlin/calculator/Operator.kt
> +        override fun invoke(a: Double, b: Double): Double = a.plus(b)
`enum class`를 사용 💯 , 그리고 `invoke`를 `override`하여 `enum` 값을 바로 호출할 수 있도록 한 부분도 너무 인상깊습니다. 👍
그러나 여기에서는 `a+b` 표현해도 되는 것을 `a.plus(b)`와 같이 표현해서 얻을 수 있는 이점이 무엇일까요? 🧐

2022-11-05 17:24 UTC, ujusy commented on src/main/kotlin/calculator/Operator.kt
> +        fun from(op: String) = Operator.values().find { it.op == op } ?: throw IllegalArgumentException("올바른 연산자를 입력해주세요.")
엘비스 연산자 사용 👍

2022-11-05 17:24 UTC, ujusy commented on src/main/kotlin/calculator/util/StringExtensions.kt
> +fun String.isNumeric() = this.all { it.isDigit() }
확장함수 사용 👍

2022-11-05 17:24 UTC, ujusy commented on src/test/kotlin/calculator/CalculatorTest.kt
> +                "5 * 4 / 4" to 5.0
Data Driven Testing 활용한 부분 좋습니다 👍

2022-11-05 17:24 UTC, ujusy commented on src/test/kotlin/calculator/ExpressionTest.kt
> +                listOf("4", "/", "2", "+", "1")
대부분의 테스트가 `data driven testing` 을 사용하고있는데, [`property based testing`](https://kotest.io/docs/proptest/property-based-testing.html) 를 사용하여 무작위로 생성된 다양한 케이스에 대해서 테스트를 해보는 건 어떨까요?

2022-11-05 17:24 UTC, ujusy commented on src/test/kotlin/calculator/ExpressionTest.kt
> +        ) { (data, result) ->
이 케이스는` 4 / 0 + 1`이 `3.0`의 결과가 `3.0`이 아니니 굳이 `data driven testing`을 활용하지 않았어도 되었을 것 같네요 :)

2022-11-05 17:24 UTC, ujusy commented on src/test/kotlin/calculator/ExpressionTest.kt
> +    context("올바르지 않은 데이터는 검증에 실패한다.") {
어떠한 상황에 검증에 실패하는지 테스트가 좀 더 명확하면 좋을 것 같습니다 :) `Expression.kt`를 보면 총 3가지 로직을 모두 검증하는 테스트로 보여요. 하나에 init 블록 하나에 묶여있더라도 로직이 다르면 개별 검증하는 것이 좋아보입니다. 꼭 이 부분이 아니더라도 항목 별로 개별 검증하는 것이 추후 테스트를 유지 보수 하시는데 도움이 될 거에요 :)

2022-11-06 07:49 UTC, SangHyunGil reviewed
안녕하세요~ 리뷰어님!
말씀해주신 부분들 관련해서 의견달고 반영했어요!
Kotest를 이번에 처음 써보는데 Property-Based-Test를 사용하면 다양한 랜덤 케이스에 대해서도 테스트할 수 있어 편리하네요~!
다만, 오히려 예상치 못한 케이스가 걸릴 수도 있을 것 같다는 생각이 들기도 하네요 😵‍💫

2022-11-06 07:49 UTC, SangHyunGil commented on README.md
> +예를 들어 "2 + 3 * 4 / 2"와 같은 문자열을 입력할 경우 2 + 3 * 4 / 2 실행 결과인 10을 출력해야 한다.
다음에는 요구사항뿐 아니라, 기능을 구체적으로 나열하면서 하면 좋을 것 같네요~!
반영해두었고 다음 미션부터에서도 반영해둘게요~!

2022-11-06 07:49 UTC, SangHyunGil commented on src/main/kotlin/calculator/Operator.kt
> +        override fun invoke(a: Double, b: Double): Double = a.plus(b)
추후에 사칙연산을 진행할 때, 특정 로그를 찍는다던지에 대한 부분을 추가할 수도 있다고 생각했어요.
그래서 오버로딩이 가능한 구조로 미리 짜놓으려고 해당 부분을 다음과 같이 구현했어요 😄

2022-11-06 07:49 UTC, SangHyunGil commented on src/test/kotlin/calculator/ExpressionTest.kt
> +                listOf("4", "/", "2", "+", "1")
해당 부분을 사용해보면 조금 더 다양한 테스트를 진행해볼 수 있겠네요~!

2022-11-06 07:49 UTC, SangHyunGil commented on src/test/kotlin/calculator/ExpressionTest.kt
> +    context("올바르지 않은 데이터는 검증에 실패한다.") {
맞아요~! 추후 테스트가 깨지더라도 어떤 예외로 인해 깨졌는지를 명확하게 알 수 있을 것 같아요!
해당 부분 반영해볼게요!

2022-11-06 07:49 UTC, SangHyunGil commented on src/main/kotlin/calculator/Calculator.kt
> +        val expression: Expression = Parser.parse(rawString)
조금 더 명시적으로 하기 위해 네이밍도 변경해보았어요~!

2022-11-06 07:49 UTC, SangHyunGil commented on src/main/kotlin/calculator/const/CalculatorException.kt
> +object CalculatorException {
메시지를 상수화해서 조금 더 명시적으로 하고 관리도 용이하도록 수정해보았어요!

2022-11-06 07:49 UTC, SangHyunGil commented on src/main/kotlin/calculator/util/ListExtensions.kt
> +fun <T> List<T>.isOddSize() = this.size % 2 == 1
홀수사이즈인지를 확인하는 확장함수를 추가해 조금 더 명시적으로 보이도록 수정해보았어요!

2022-11-06 07:49 UTC, SangHyunGil commented on src/test/kotlin/calculator/ExpressionTest.kt
> +    context("올바른 데이터는 검증에 성공한다. [Property-Based-Test]") {
Property-Based-Test를 통해 더 다양한 케이스를 테스트를 진행해볼 수 있도록 해보았어요~!

2022-11-06 07:49 UTC, SangHyunGil commented on src/test/kotlin/calculator/ExpressionTest.kt
> +        ) { (data, result) ->
맞아요~! 해당 부분을 놓친 것 같네요 감사해요 👍

2022-11-06 07:50 UTC, SangHyunGil commented on src/main/kotlin/calculator/Expression.kt
> +    private fun isMoreThanMinimumSize() = rawExpression.size > 2
drop이나 chunk에서 사용되는 부분에서는 일부러 매직넘버로 살려두었어요.
이유는 drop이나 chunk에서 사용되는 파라미터값이 너무 명시적이라고 생각되고 오히려 상수값으로 관리하면 명시적이지 못할 수도 있을 것 같다는 느낌이 들어서였어요!
그런데 생각해보면 네이밍만 적절하다면 더 명시적으로 보일 수도 있다는 생각이 드네요~! 감사해요 👍

2022-11-06 07:51 UTC, SangHyunGil commented on src/main/kotlin/calculator/Expression.kt
> +        require(isCorrectExpression()) { "수식이 올바르지 않습니다." }
init 블럭만 보고 해당 조건이 맞지 않는다면, IllegalArgumentException을 던진다는 부분을 알 수 있게 해당 부분을 위와 같이 구현했었어요.
그런데 함수 자체로 옮기면 가독성이 조금 더 올라갈 것 같다는 생각이 드네요!
해당 부분도 반영해볼게요~! 👍

2022-11-06 11:10 UTC, ujusy approved these changes
안녕하세요, 상현님 🙌

피드백 반영 너무 잘해주셨습니다 💯💯
피드백 드린 것 외에도 개선 해주신 부분 인상깊었습니다 :)
새로 추가해주신 main 함수에 한 가지 코멘트 남겼으니 확인부탁드려요 🙏

다음 단계인 자동자 경주 미션도 화이팅입니다 💪💪

2022-11-06 11:10 UTC, ujusy commented on src/main/kotlin/calculator/CalculatorApplication.kt
> +    val input = sc.nextLine()
`Kotlin`에서는 `Scanner`를 생성해주지 않고 [`readLine`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/read-line.html)을 사용하여 입력값을 읽을 수 있어요. :)

2022-11-06 11:10 UTC, merged