🚀 2단계 - 문자열 계산기
next-step/kotlin-racingcar pull request #778
Opened 2022-11-06 15:10 UTC by shinseongsu

제가 코틀린은 처음이라;; 문법이 맞게 사용했는지 확인해주시면 감사하겠습니다 🙇

2022-11-07 11:34 UTC, ujusy requested changes
안녕하세요, 성수님 😊

문자열 계산기 구현해주시느라 고생하셨습니다!
전체적으로 깔끔하게 작성해주셨어요 👍

추가로 고민해볼 몇 가지 코멘트를 남겨두었어요!
확인 후 다시 리뷰 요청 주세요 🙌

그리고 현재 `lint` 적용이 안되어있는 듯 합니다 :) `lint` 설정을 확인해주세요 🙏

2022-11-07 11:34 UTC, ujusy commented on src/main/kotlin/calculator/Runner.kt
> +fun main(args: Array<String>) {
`args` 인수는 사용되지 않는 것 같은데, 사용되지 않는 인수는 없애주는게 좋을 것 같습니다.
또한 코틀린의 경우 자바와 다르게 메인 함수에 `args`를 제거해도 됩니다 :)

2022-11-07 11:34 UTC, ujusy commented on src/main/kotlin/calculator/application/StringCalculator.kt
> +const val SPACE_DELIMITER = " "
상수화 너무 좋습니다 👍

2022-11-07 11:34 UTC, ujusy commented on src/main/kotlin/calculator/domain/Calculable.kt
> +interface Calculable {
`Calculable`을 구현하는 곳은 `Operator enum` 뿐인데 그렇다면 `Calculable` 인터페이스를 만드는 대신 `enum` 안에 위치시키는 건 어떨까요? :) 
[kotlin enum class](https://kotlinlang.org/docs/enum-classes.html#anonymous-classes) 를 참고해보세요!

2022-11-07 11:34 UTC, ujusy commented on src/main/kotlin/calculator/domain/Calculator.kt
> +    init {
init 블록 사용 좋습니다 👍

2022-11-07 11:34 UTC, ujusy commented on src/main/kotlin/calculator/domain/Calculator.kt
> +            val operator = Operator.from(inputs[i])
`operator` 는 `Kotlin`에서 예약어로 사용되고있습니다 :) 
예약어가 아닌 다른 변수명을 활용해보는건 어떨까요?
https://kotlinlang.org/docs/keyword-reference.html

2022-11-07 11:34 UTC, ujusy commented on src/main/kotlin/calculator/domain/Operand.kt
> +    companion object {
`kotlin class coding convention` 에 따르면 `companion object`는 마지막으로 가야합니다.
아래 링크 참고부탁드려요 :) 
https://kotlinlang.org/docs/coding-conventions.html#class-layout

2022-11-07 11:34 UTC, ujusy commented on src/main/kotlin/calculator/domain/Operand.kt
> +            }
`java.lang`의 `NumberFormatException`가 아닌 코틀린 `NumberFormatException`을 사용하거나 `toDoubleOrNull()`과 `elvis(?:)` 연산자를 사용할 수 있습니다 :)

2022-11-07 11:34 UTC, ujusy commented on src/main/kotlin/calculator/domain/Operator.kt
> +            return Operand(number1.plus(number2))
`Value Object(Operand)` 를 정의한 의도는 좋습니다 👍
하지만 별 다른 제약 조건이 없고, 실제로 `Double` 을 사용해서 연산하는 것과 차이가 없으므로 `Operand` 클래스를 굳이 정의하지 않고 `Operator.kt`에 정의해보는 건 어떨까요?
아래 링크를 참고해보세요 :)
https://kotlinlang.org/docs/enum-classes.html#anonymous-classes

2022-11-07 11:34 UTC, ujusy commented on src/main/kotlin/calculator/ui/View.kt
> +    return Scanner(input).nextLine()
`Kotlin`에서는 [`readline`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/read-line.html) 을 지원하고있습니다 :)

2022-11-07 11:34 UTC, ujusy commented on src/test/kotlin/calculator/domain/CalculatorTest.kt
> +            .isThrownBy { Calculator(Lists.newArrayList("1", "+")) }
`assertj`에서 제공하는게 아닌 `kotlin`에서 제공하는 [`listOf`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/list-of.html)를 사용해 볼 수 있을 것 같아요! 😃

2022-11-07 11:34 UTC, ujusy commented on src/test/kotlin/calculator/domain/OperandTest.kt
> +            .withMessage("올바르지 않은 피연산자 타입입니다")
한 라인에 함수 하나씩 체이닝 한 부분 좋습니다 👍

2022-11-07 21:13 UTC, shinseongsu commented on src/main/kotlin/calculator/Runner.kt
> +fun main(args: Array<String>) {
아하 그렇군요 ㅎㅎ 👍

2022-11-07 21:18 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/Calculator.kt
> +            val operator = Operator.from(inputs[i])
코틀린에서 override가 operator로 사용되는군요

2022-11-07 21:19 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/Operand.kt
> +            }
코틀린에서는 에러를 처리할 수 있는 메소드들이 추가가 되었군요 👍

2022-11-07 21:28 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/Operator.kt
> +            return Operand(number1.plus(number2))
Operator에는 연산에만 집중해야하고 Operand 연관 안되게 재구성해보겠습니다

2022-11-07 21:46 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/Operand.kt
> +    companion object {
Java에서 static 를 쓰듯이 쓰면 되는군요 👍

2022-11-07 22:28 UTC, shinseongsu commented
## 수정사항

1. lint 맞추기

![스크린샷 2022-11-08 오전 7 24 18](https://user-images.githubusercontent.com/24979159/200428380-785f4ec7-d19c-4627-b358-ce84f229a734.png)

2. 실행함수에서 args 빼기
3. Operator enum에 BinaryOperator 적용하였습니다.
4. elvis(?:) 사용하여 try ~ catch 삭제
5. java 라이브러리 scanner 말고 readLine 사용
6. newArrayList -> listOf 사용

2022-11-08 04:17 UTC, ujusy approved these changes
안녕하세요 성수님 😊

피드백 반영 너무 잘해주셨습니다 💯 
한 가지 더 고민해볼만한 코멘트를 남겼으니 확인부탁드려요 :) 

빠른 미션 진행을 위해 머지하겠습니다!
step3 자동차 경주 미션도 화이팅입니다! 💪💪

2022-11-08 04:17 UTC, ujusy commented on src/main/kotlin/calculator/domain/Operator.kt
> +        override fun apply(number1: Double, number2: Double): Double = number1.minus(number2)
아래 `MULTIPLE`과 `DIVIDE`는 산술 연산자를 사용하고있는데 통일성을 가져가보는게 어떨까요? :) 
참고 링크: https://kotlinlang.org/docs/operator-overloading.html#arithmetic-operators

2022-11-08 04:18 UTC, ujusy approved these changes

2022-11-08 04:19 UTC, merged

2022-11-08 04:51 UTC, shinseongsu commented on src/main/kotlin/calculator/domain/Operator.kt
> +        override fun apply(number1: Double, number2: Double): Double = number1.minus(number2)
아하~ 제가 plus랑 minus만 메소드를 이용하였군요 😢 
다음 미션떄 같이 수정하겠습니다