step3 자동차 경주입니다.
next-step/kotlin-racingcar pull request #796
Opened 2022-11-08 03:54 UTC by shinaaaa

step2 과제랑 비슷하게 구현하려고 했는데 맞는지 확신이 없네요.

2022-11-08 13:23 UTC, laco-dev requested changes
자동차 경주 시작 고생 많으셨습니다.

클래스를 분리하면서 역할을 나눠보는 경험을 해보셨네요. 👍🏻 
다만 각각의 객체가 해야하는 역할과 협력하는 대상이 적절한가에 대한 고민을 해 볼 수 잇겠습니다.

위 내용 포함해서 몇가지 피드백을 같이 남겼습니다.

2022-11-08 13:23 UTC, laco-dev commented on src/test/kotlin/racingcar/RaceTest.kt
> +    }
기능을 작은 단위의 시나리오로 분리해서 정의 해주신 점 좋습니다.

다만 이 작업이 포함된 커밋은 `feat: 참가할 자동차 목록 생성`로 되어 있는데,
자동차 수가 없는 경우 오류가 발생할 것이라는 예측이 어려울 수 있어요.

테스트 코드의 이름을 그대로 커밋으로 작성 해보셔도 좋습니다!
"feat: 자동차의 수는 0대일 수 없다"

이러한 방법은 2주차 미션 이후의 TDD를 연습해보는 과정에서 다시 해 볼 기회가 있으니, 지금은 참고만 해 주시면 되겠습니다.

2022-11-08 13:23 UTC, laco-dev commented on docs/racingcar.md
> +- [ ] 후진 조건일 경우 자동차의 현재 위치 고정
구현이 되었으니 체크박스 표시를!? 해주시죠!

2022-11-08 13:23 UTC, laco-dev commented on src/main/kotlin/racingcar/application/Race.kt
> +class Race {
Race는 바퀴, 혹은 경주라는 이름의 도메인 모델로 사용될 수도 있을 것 같아요.
메인 함수를 가지는 클래스로 Application이라는 이름을 그대로 지어봐도 좋아요!

2022-11-08 13:23 UTC, laco-dev commented on src/main/kotlin/racingcar/view/InputView.kt
> +class InputView {
정적 함수만 제공하는 경우, object 를 이용해 선언하는 것이 좋습니다.
슬랙 DM으로 드렸던 내용과 같습니다.

코틀린의 object와 companion object와 같은 특징을 학습 해보셔도 좋아요

```kotlin
object InputView { ... }
```

2022-11-08 13:23 UTC, laco-dev commented on src/main/kotlin/racingcar/view/InputView.kt
> +        }
register(...) set(...)와 같은 함수 이름은 값을 반환하는 의미와 살짝 거리가 있는 것 같아요. 🤔

2022-11-08 13:23 UTC, laco-dev commented on src/main/kotlin/racingcar/common/RandomNumber.kt
> +}
범위에 대한 랜덤 기능인 RandomNumber가 코틀린 표준 함수를 이용한 random()과 비교했을때 클래스로 만들어진 장점이 드러나지 않는 것 처럼 보여요.

아래와 같은 방법 두 가지가 있다면 표준 함수를 사용한 2번이 더 친숙하게 느껴집니다
```kotlin
1. RandomNumber(0..10).generate()
2. (0..10).random()
```

2022-11-08 13:23 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Car.kt
> +    var currentPosition: Int = 0
var로 되어있으면 외부에서 접근을 해서 수정이 가능하게 됩니다.

```kotlin
val car: Car
car.currentPosition = 10
```

코틀린은에서 getter, setter가 만들어지는 규칙에 따라 setter를 private으로 숨길 수 있습니다.
https://kotlinlang.org/docs/properties.html#getters-and-setters

2022-11-08 13:23 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Car.kt
> +        }
결국 반환값이 Array이기 때문에 사용하는측에서 비어있는지 아닌지를 다시 한번 고민을 해야 할 수 있어요.

0대인 경우 게임을 할 수 없는 것은 Car의 역할일지 게임을 진행하는 컨트롤러가 판단할 역할인지 고민해볼 필요가 있습니다.

2022-11-08 13:23 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Gear.kt
> +    abstract fun move(car: Car)
이동을 하는 것은 기어의 역할일까요? 자동차의 역할일까요?
저는 기어 자체는 자동차와 직접적인 관계가 없다고 느껴집니다.

자동차가 어떤 기어인지 확인을 하고, 기어에 따라 전진 후진을 주도적으로 수행하도록 하면 어떨까요?
외부에서 자동차의 상태를 변경하는 것을 줄일 수 있을 것 같아요.

```kotlin
// Car
fun move(gear: Gear) { ... }
```

2022-11-08 13:23 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Gear.kt
> +        }
도메인 모델에서는 가급적 랜덤과 같은 불확실성을 사용하는 것은 지양하는게 좋습니다.
테스트가 불가능하거나 억지로 해야 할 수도 있고, 적절한 협력을 통한 객체지향 설계와 방향성이 다소 멀어진다고 생각이 듭니다.
아래 형태와 비교 해 본다면 어떤 방법이 괜찮아 보이시나요?

```kotlin
val currentGear = getCurrentGear(...)
car.drive(gear)
```

2022-11-08 13:23 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Move.kt
> +}
이동이라는 인터페이스가 전진, 정지를 했을때 반환하는 값이 무엇일까요?

역할과 상태를 포함한다면 이런 인터페이스로 사용이 될 수는 있어 보여요
하지만, 기어와 자동차의 관계를 보면 Move라는 인터페이스가 하는 역할이 애매해 질 수도 있을 것 같아서 참고만 해 주세요
```kotlin
interface Moveable {
   val position: Int
   fun go(): Moveable
   fun stop(): Moveable
}
```

2022-11-08 13:23 UTC, laco-dev commented on src/test/kotlin/racingcar/RaceTest.kt
> +class RaceTest {
RaceTest라는 것에 모든 케이스가 포함되어 있기 때문에
적절한 클래스에게 역할을 부여 해 주셨다면 해당 클래스에 대한 테스트를 작성 해 주시는 것이 좋습니다.
```
CarTest
GearTest
...
```

2022-11-09 00:28 UTC, shinaaaa commented on src/main/kotlin/racingcar/application/Race.kt
> +class Race {
`class Application {} ` 그냥 이렇게요?

2022-11-09 00:30 UTC, shinaaaa commented on src/main/kotlin/racingcar/view/InputView.kt
> +class InputView {
그러면 `class InputView {}`  이거 없이 그냥 비어있는 파일에 `object InputView { ... }` 이렇게 작성하시라는 거죠? 나머지 ResultVIew object 로 만들면 될까요?

2022-11-09 00:32 UTC, shinaaaa commented on src/main/kotlin/racingcar/view/InputView.kt
> +        }
반환하는 함수를 별도로 만드는게 적절할 수도 있겠네요

2022-11-09 00:36 UTC, shinaaaa commented on src/main/kotlin/racingcar/domain/Move.kt
> +}
이름 짓는게 어렵네요,ㅜㅜ

2022-11-09 00:37 UTC, shinaaaa commented on src/main/kotlin/racingcar/domain/Car.kt
> +        }
입력하는 쪽에서 검증하는 것으로 바꾸겠습니다.

2022-11-09 00:38 UTC, shinaaaa commented on src/main/kotlin/racingcar/domain/Gear.kt
> +    abstract fun move(car: Car)
주체가 무엇인지 다시 생각해보겠습니다.

2022-11-09 00:40 UTC, shinaaaa commented on src/main/kotlin/racingcar/common/RandomNumber.kt
> +}
그러면 범위에 대한 변화가 있을 것이라는 거는 고려 하지않아도 되는거죠?

2022-11-09 04:29 UTC, shinaaaa commented
리뷰 해주신 내용을 토대로 최대한 하려고 노력했습니다. ㅜㅜ

2022-11-09 14:18 UTC, laco-dev approved these changes
피드백 반영 고생 많으셨습니다.

많은 고민을 하신 흔적이 보여서 좋았습니다.
지금의 구현 방식이 고민하신 방향과 다를 수도 있고 같을 수도 있습니다.

남겨드린 피드백은 다음 미션을 진행하면서 같이 고려 하고 반영 해 보시면 되겠습니다.
지금의 설계 방식이 이후의 미션에서 어떻게 적용될지 같이 발전시켜 보시죠. 👍🏻

2022-11-09 14:18 UTC, laco-dev commented on src/main/kotlin/racingcar/common/RandomNumber.kt
> +}
RandomNumber를 사용하는 측에서 결국 몇부터 몇까지의 범위를 가지는지 알 수 없어서 신뢰성의 문제라고도 생각을 했네요. 🤔

2022-11-09 14:18 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Car.kt
> +    fun getCurrentPosition() = currentPosition
코틀린에서는  getter() 함수 대신 private setter를 활용 해보세요.
아래 코드가 자바로 컴파일 되면 어떻게 되는지 비교 해 보실 수 있습니다.

```kotlin
var currentPosition: Int = 0
   private set
```

2022-11-09 14:18 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Car.kt
> +        currentPosition
따로 아무 동작이 없어서 별도의 코드를 추가하지 않아도 괜찮을 것 같습니다!

2022-11-09 14:18 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Car.kt
> +        }
이 함수가 Car의 메소드가 아닌 정적 메소드로 만들어진 이유는 무엇일까요~?

2022-11-09 14:18 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Gear.kt
> +        fun getGear(ran: Int): Gear {
ran 이라는 값은 랜덤값이 들어올 것이라고 예측하는 것으로 볼 수 있어서 
명확한 이름으로 만들어도 괜찮습니다!

2022-11-09 14:18 UTC, laco-dev commented on src/main/kotlin/racingcar/view/InputView.kt
> +    }
set()으로 값을 변경하게 되면 InputView를 사용하는 다른 곳에서 각각 다른값이 나올 수 있어서 사이드 이펙트의 문제를 가질 수 있겠습니다.

getParticipant(), getNumberOfTimes() 함수가 출력을 위한 처리를 같이 해도 문제는 없습니다.
명시적으로 요구사항을 이름으로 담는다면 이런식으로도 작성을 해 볼수는 있습니다.

```kotlin
object InputView {
   fun register(): RegisterResult { 
      val participant = ...
      val numberOfTimes = ...
      return RegisterResult(...)
   }
}
```

2022-11-09 14:18 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Gear.kt
> +enum class Gear(var range: IntRange) {
기어의 범위를 외부에서 수정하는 것은 어떤 의미를 가지나요?

전진 조건의 범위 4 ~ 9
정지의 범위 0 ~ 3

으로 명확하게 정해진 요구사항을 변경시키는 위험에 빠지지는 않을까요?

2022-11-09 14:18 UTC, laco-dev commented on src/test/kotlin/racingcar/CarTest.kt
> +        cars.first().drive(RandomGear.getGear())
단순히 전진조건이라면 drive(Gear.FORWARD)라고 명시적으로 넣어도 될 것 같아요!

2022-11-09 14:18 UTC, laco-dev commented on src/test/kotlin/racingcar/InputViewTest.kt
> +class InputViewTest {
입출력 기능에 대한 테스트가 필수는 아니지만, 잘 해주셨네요 :)  좋습니다

2022-11-09 14:18 UTC, laco-dev commented on src/main/kotlin/racingcar/domain/Gear.kt
> +        fun getGear(ran: Int): Gear {
`정해진 값이 N일 경우 기어는 OO이다.` 라는 테스트를 만들어 볼수 있겟죠?

2022-11-09 14:18 UTC, merged

2022-11-09 14:22 UTC, shinaaaa commented on src/main/kotlin/racingcar/domain/Car.kt
> +        }
사실 있어서 한번 해봤어요 .ㅋㅋㅋㅋ

2022-11-09 14:24 UTC, shinaaaa commented on src/main/kotlin/racingcar/domain/Gear.kt
> +        fun getGear(ran: Int): Gear {
축약 보다 명확이 더 좋은 변수 명이라고 인지하겠습니다.

2022-11-09 14:25 UTC, shinaaaa commented on src/test/kotlin/racingcar/CarTest.kt
> +        cars.first().drive(RandomGear.getGear())
아 맞아요 ㅎㅎㅎㅎ

2022-11-09 14:26 UTC, shinaaaa commented on src/main/kotlin/racingcar/domain/Gear.kt
> +enum class Gear(var range: IntRange) {
첨에는 음 뭔가 변경이 이루어 질 수도 있겠다는 생각을 했었는데 지금 요구사항과는 거리가 먼 것 같아요. ㅜㅜ

2022-11-09 14:26 UTC, shinaaaa commented on src/test/kotlin/racingcar/InputViewTest.kt
> +class InputViewTest {
테스트를 나눠서 하려다 보니 파일이 많이 안나와서 해봤는데 감사합니다.

2022-11-09 14:27 UTC, shinaaaa commented on src/main/kotlin/racingcar/domain/Gear.kt
> +        fun getGear(ran: Int): Gear {
새로운 테스트 케이스 감사합니다.

2022-11-09 14:28 UTC, shinaaaa commented
처음에 리뷰해주신 내용과 굉장히 많은 코드를 변경했는데 꼼꼼히 해주셔서 감사합니다. 😀

2022-11-09 14:30 UTC, shinaaaa commented on src/main/kotlin/racingcar/domain/Car.kt
> +    fun getCurrentPosition() = currentPosition
조언 감사합니다.

2022-11-10 05:18 UTC, shinaaaa commented on src/main/kotlin/racingcar/view/InputView.kt
> +    }
```
fun register(): RegisterResult {
        println("자동차 대수는 몇 대인가요 ?")
        val participant = readLine()!!.toInt()
        require(InputView.participant != 0) { "0대의 차로는 시작할 수 없습니다." }

        println("시도할 횟수는 몇 회인가요?")
        val times = readLine()!!.toInt()
        require(InputView.times != 0) { "0번의 횟수를 시도할 수 없습니다." }

        return RegisterResult(participant, times)
    }
```

이렇게 하라는 말씀이신가요?