🚀 3단계 - 자동차 경주
next-step/kotlin-racingcar pull request #797
Opened 2022-11-08 08:55 UTC by chayoung-choi

🚀 3단계 - 자동차 경주
- [X] 몇 대의 자동차로 몇 번의 이동을 할 것인지를 입력 받는다.
- [X] 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
    - [X] 위치와 이동 처리할 수 있는 자동차를 만든다.
- [X] 0에서 9 사이에서 무작위 값을 구한 후 무작위 값이 4 이상일 경우 전진한다.
    - [X] 랜덤 이동 전략 패턴(기본 이동 전략)
    - [X] 기준치 이상일 때 전진 처리
- [X] 자동차의 상태를 화면에 출력한다.

위와 같이 3단계 자동차 경주를 구현해보았습니다.
부족한 점이 많지만, 많은 가르침 부탁드립니다. 감사합니다! 🫡

2022-11-08 16:35 UTC, ujusy requested changes
안녕하세요, 차영님 😊

step3 자동차 경주 미션 구현하시느라 고생많으셨어요! 🙌
step2 계산기 미션도 많이 개선해주셨네요 👍 

고민해볼 몇 가지 코멘트 남겨두었습니다 :) 
확인 후 다시 리뷰 요청 주세요! 🙏

2022-11-08 16:35 UTC, ujusy commented on README.md
> +- [X] 몇 대의 자동차로 몇 번의 이동을 할 것인지를 입력 받는다.
요구 사항 정리 잘해주셨습니다 💯

2022-11-08 16:35 UTC, ujusy commented on src/main/kotlin/racing/domain/strategy/MovingStrategy.kt
> +interface MovingStrategy {
전략 패턴 사용 좋습니다 👍

2022-11-08 16:35 UTC, ujusy commented on src/main/kotlin/racing/domain/Car.kt
> +    }
`kotlin class coding convention` 에 따르면 `companion object`는 마지막으로 가야합니다!
아래 링크 참고부탁드려요 :)
https://kotlinlang.org/docs/coding-conventions.html#class-layout

2022-11-08 16:35 UTC, ujusy commented on src/main/kotlin/racing/domain/Car.kt
> +    fun getPosition(): Int = position
`private property` 를 만들고 `getter` 함수를 만드는 것도 좋지만 `public property`를 만들고 `setter`를 `private`으로 바꾸는것은 어떨까요? 🧐

2022-11-08 16:35 UTC, ujusy commented on src/main/kotlin/racing/domain/Car.kt
> +    }
`move` 라는 함수가 이동 여부를 반환해야할지 고민해보면 좋을 것 같아요 :)
조회하거나 명령하거나 둘 중에 하나의 역할만 할 수 없을까요?

2022-11-08 16:35 UTC, ujusy commented on src/main/kotlin/racing/domain/Car.kt
> +    fun getPositionMark(): String = POSITION_MARK.repeat(position)
차가 자신이 움직인 위치를 어떻게 표현할 것인가에 대해서 알 필요가 있을지 고민해보면 좋을 것 같아요:)  
어떤 형식으로 표현하는지에 대한 것은 `View`의 역할이 아닐까요?

2022-11-08 16:35 UTC, ujusy commented on src/main/kotlin/racing/domain/strategy/RandomMovingStrategy.kt
> +        const val MOVING_POINT = 4
매직 넘버 상수화 좋습니다 👍  
하지만 네이밍을 조금 더 고민해보는 건 어떨까요?
`MOVING_POINT`만 보았을 때는 4칸을 움직인다는 의미로 해석될 여지가 있어보입니다 :)

2022-11-08 16:35 UTC, ujusy commented on src/main/kotlin/racing/domain/strategy/RandomMovingStrategy.kt
> +    override fun move(): Boolean = Random().nextInt(MOVING_RANGE_MAX) >= MOVING_POINT
`kotlin.random.Random` 도 제공하니 참고해주세요 :)

2022-11-08 16:35 UTC, ujusy commented on src/main/kotlin/racing/view/GameInputView.kt
> +        val team = readLine()!!.toInt()
자동차 수를 받는 변수인데 `team` 이라는 변수명은 조금 어색한 것 같아요 :) 
좀 더 구체적인 변수명으로 변경해보는게 어떨까요?

2022-11-08 16:35 UTC, ujusy commented on src/main/kotlin/racing/view/GameResultView.kt
> +            }
뷰들이 직접 게임을 생성하거나 게임을 수행하고 있는 것으로 보여집니다:)
한 번에 너무 많은 일을 하고있는게 아닐까요? 
하나의 객체가 하나의 역할과 책임을 가지도록 개선해보는 건 어떨까요? 😊

2022-11-08 16:35 UTC, ujusy commented on src/test/kotlin/racing/domain/CarTest.kt
> +    fun `자동차 최초 정상 움직임`() {
지금 테스트는 자동차가 움직여야 할 상황에 움직이는지를 테스트하는지 혹은 랜덤 생성이 정상적으로 잘 작동하는지를 테스트하는지 모호한 것 같아요,,! `Car`의 `move`를 테스트하고싶다면 랜덤 테스트와 분리하는 것이 좋아보입니다:)

2022-11-08 16:35 UTC, ujusy commented on src/test/kotlin/racing/domain/CarTest.kt
> +        (0..10).forEach { _ -> car.move() }
```suggestion
        (0..10).forEach { car.move() }  
```
이렇게 작성하거나 [`repeat`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/repeat.html) 을 이용해 볼 수도 있을 것 같아요 :)

2022-11-09 05:57 UTC, chayoung-choi commented on src/main/kotlin/racing/view/GameInputView.kt
> +        val team = readLine()!!.toInt()
항상 변수명을 짓는 게 제일 어려운 것 같은데 리뷰어님은 참고하는 것이나 특별한 원칙이 있으실까요? 🤔

2022-11-09 16:18 UTC, ujusy commented on src/main/kotlin/racing/view/GameInputView.kt
> +        val team = readLine()!!.toInt()
저도 변수명 지을 때 많은 고민을 합니다..ㅜㅜ 
비즈니스 용어, 해당 값이 사용되는 형태 등을 고려해서 의미를 가장 잘 나타낼 수 있는 단어를 찾아보는 것 같아요!
실무에서는 팀 내에서 사용하는 용어를 기준으로 변수명을 작성하고 있습니다.
또한 영어로 변수명을 짓기 때문에 문법을 지켜서 자연스럽게 읽히도록 하려고 합니다 :) 
위와 같이 자동차 대 수를 받을 때는 `자동차` + `개수` 가 들어가도록 변수명을 지어보는 건 어떨까요?
ex. `numCar` , `countOfCar` 등등.. 의미를 담아 다양하게 지을 수 있을 것 같아요!

2022-11-09 16:47 UTC, ujusy approved these changes
안녕하세요, 차영님 😊

전체적으로 피드백 반영 너무 잘해주셨습니다 💯 
살짝 아쉬운 부분 몇 가지 코멘트를 남겨두었어요! 

다음 단계 진행해주시면서 같이 반영해주시면 좋을 것 같아요 :) 
다음 단계도 화이팅입니다 !💪💪

2022-11-09 16:47 UTC, ujusy commented on src/main/kotlin/racing/domain/Game.kt
> +        }
단순 반복으로 보여지는데 [`repeat`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/repeat.html) 사용은 어떨까요? :)

2022-11-09 16:47 UTC, ujusy commented on src/main/kotlin/racing/domain/Game.kt
> +    private fun race() {
`play`, `race`  명령이 값을 반환하지 않도록 구현 👍

2022-11-09 16:47 UTC, ujusy commented on src/main/kotlin/racing/domain/Game.kt
> +        private val gameOutputView = GameOutputView()
하나의 인스턴스를 재사용하고자 한다면 class 대신 명시적으로 object로 선언해보면 어떨까요?  재사용되는 인스턴스는(싱글톤이라던가..) 공유되는 상태를 가지지 않도록 주의해야 하는데 Object로 선언해 이 클래스가 싱글톤임을 명시적으로 알 수 있게 한다면 주의해서 구현하는데 도움이 될 것 같습니다 :)

2022-11-09 16:47 UTC, ujusy commented on src/main/kotlin/racing/view/GameInputView.kt
> +        return Game(racingCarCount, round)
`View`가  한결 가벼워진 것 같지만 여전히 게임을 직접 생성하는 책임까지 가지고 있는 것으로 보여요! 게임을 직접 생성하는 책임도 분리해줄 수 없을까요?

2022-11-09 16:47 UTC, ujusy commented on src/main/kotlin/racing/domain/Car.kt
> +        private set
리뷰 반영 잘 해주셨네요 !👍

2022-11-09 16:47 UTC, ujusy commented on src/main/kotlin/racing/view/GameOutputView.kt
> +    }
함수들의 이름이 마치 `GameOutputView`가 게임을 시작하거나 다음 라운드로 넘어가게 해줄 것 같이 해줄 것처럼 해석됩니다.
다른 함수들처럼 출력을 한다는 것을 명확하게 드러내는 네이밍으로 변경해보면 어떨까요? :)

2022-11-09 16:47 UTC, merged