5단계 - 리팩토링
next-step/kotlin-racingcar pull request #809
Opened 2022-11-09 15:40 UTC by harrisleesh

Domain과 View를 분리!
- 기존에 코드들이 이미 분리되어있어서 크게 변경한 부분은 많지 않습니다.
- domain 패키지를 만들어서 코드를 안에 넣어주었구요!
- RacingCarMain 파일을 만들어서 실행하는 부분을 분리했습니다.
- 리뷰 부탁드려요!! 감사합니다 :)

2022-11-10 14:26 UTC, malibinYun requested changes
5단계 미션 고생 많으셨어요~!
이번 미션의 완주가 코 앞에 있네요! 😀
이미 뷰와 도메인 로직이 잘 분리되어 있어서 크게 변경된 부분은 없어 보이네요 👍
생각해보면 좋을점들에 코멘트 남겨두었어요.
피드백 반영하시고 리뷰 요청 부탁드릴게요!
마지막 까지 화이팅입니다 💪🔥

2022-11-10 14:26 UTC, malibinYun commented on src/main/kotlin/game/racingcar/domain/RacingCar.kt
> +
이제 location을 외부에서 변경할 수 없겠네요! 👍

초기 location값을 생성자로 받아보는 건 어떨까요? 어떤 장점이 생길 수 있을까요?

2022-11-10 14:26 UTC, malibinYun commented on src/main/kotlin/game/racingcar/domain/RacingCar.kt
> +    }
`isNotBlank()`를 활용해보는 것은 어떨까요?

2022-11-10 14:26 UTC, malibinYun commented on src/main/kotlin/game/racingcar/domain/RacingCarGame.kt
> +) {
저번 리뷰 중, RacingCarGame에 MoveStrategy의 전파가 걱정되셨다는 것이 떠올랐는데요,
RacingCarGame이니, 움직임 전략과 자동차 이름을 각각 받는 것이 아니라, 완성된 자동차의 목록을 받아보는 것은 어떨까요?
그러면 RacingCarGame은 MoveStrategy에 대한 의존성이 제거되겠네요 :)

2022-11-10 14:26 UTC, malibinYun commented on src/main/kotlin/game/racingcar/domain/RacingCarGame.kt
> +            .let { RacingCarPlayResult(it, racingCars.pickWinners()) }
가끔 저는 it가 무엇을 가리키는 지 한 번에 눈에 들어오지 않을 때가 있는데요.
이럴 때는 it 말고 명시적으로 파라미터명을 써보는 것은 어떨까요?

`.map { snapShots -> ~~ }`

2022-11-10 14:26 UTC, malibinYun commented on src/main/kotlin/game/racingcar/domain/RacingCars.kt
> +) {
이 부분도 움직임 전략에 대한 의존성을 제거해볼 수 있겠네요 :)

2022-11-10 14:26 UTC, malibinYun commented on src/main/kotlin/game/racingcar/domain/RacingCars.kt
> +    private fun carsIn(maxLocation: Int) = racingCars.filter { it.location == maxLocation }.map { it.name }
메서드 체이닝을 하면서 .은 한 줄에 하나만 작성하는 것이 바람직해요.
만약, filter{} 혹은 map{} 에서 Exception이 발생한다면, 로그에는 어떻게 나타날까요?

2022-11-10 14:26 UTC, malibinYun commented on src/main/kotlin/game/racingcar/view/OutputView.kt
>                  val (name, location) = snapshot
data class는 람다 내에서 이렇게 구조 분해할 수 있어요 :)
```suggestion
            locationOfCars.locations.forEach { (name, location) ->
   
```

2022-11-10 14:26 UTC, malibinYun commented on src/test/kotlin/game/racingcar/RacingCarGameTest.kt
> +                assertThat(carLocation.location).isEqualTo(expected + 1)
테스트 코드에서 반복문 등 로직의 포함을 지양하는 것은 어떨까요?
테스트 코드는 하나의 설명서처럼 한 번에 눈으로 쭉 읽고 내용을 파악할 수 있어야 하는데,
반복문 등의 로직이 들어가면 생각을 하면서 코드를 보아야 해서 가독성을 해칠 수 있게 되어요 :)

2022-11-11 14:05 UTC, harrisleesh commented on src/main/kotlin/game/racingcar/domain/RacingCar.kt
> +
음 이부분은 잘 모르겠어요!! 생성자를 통해 location 값을 받으면 명확하게 0의 위치에서 차가 생성됨을 알 수 있을 것 같은데요!
딱히 테스트나 다른 면에서 이점이 있는지 모르겠습니다..!

2022-11-11 14:10 UTC, harrisleesh commented on src/main/kotlin/game/racingcar/domain/RacingCar.kt
> +    }
오 덕분에 Blank와 Empty의 차이를 명확하게 알았습니다! 감사합니다

2022-11-11 14:19 UTC, harrisleesh commented on src/main/kotlin/game/racingcar/domain/RacingCarGame.kt
> +) {
오오..!! 감사합니다.
생성자도 고민하면서 만들어 봐야겠어요!!

2022-11-11 14:37 UTC, harrisleesh commented on src/main/kotlin/game/racingcar/domain/RacingCars.kt
> +    private fun carsIn(maxLocation: Int) = racingCars.filter { it.location == maxLocation }.map { it.name }
filter나 map에서 Exception이 발생하면 해당 exception이 발생한 위치에서부터 내역이 로그에 나타날 것 같은데요!
질문의 의도를 파악하지 못했어요! 이게 같은 줄이라면 어떤 부분인지 파악하기가 어려우니 개행하라는 의미이신가요??

2022-11-11 14:47 UTC, harrisleesh commented on src/test/kotlin/game/racingcar/RacingCarGameTest.kt
> +                assertThat(carLocation.location).isEqualTo(expected + 1)
오 네넵 생각해보니까 맞는 말인것 같아요! 감사합니다

2022-11-12 15:12 UTC, malibinYun requested changes
자동차 경주 미션 완주 정말 고생 많으셨어요!! 🔥🎉
미션을 진행해주시면서 굉장히 코드가 깔끔해졌다는 것이 느껴졌어요.
리뷰이님께서도 처음과 비교했을 때 더 나아졌음을 느끼셨으면 좋겠네요 😊

미션을 잘 구현해주셔서 크게 변경할 점들은 없어 보이네요 :)
생각해보면 좋을 점들에 코멘트 남겨두었으니 확인 부탁드릴게요!
더 구현해보고 싶으시면 반영 후 리뷰 요청 부탁드리고, 이만 미션을 마무리 짓고 싶으시다면 슬랙 DM 부탁드릴게요 🙂

다른 미션들도 끝까지 완주하시길 응원할게요! 화이팅입니다~ 💪🔥

2022-11-12 15:12 UTC, malibinYun commented on src/main/kotlin/game/racingcar/RacingCarMain.kt
> +    val racingCars = RacingCars(carNames.map { RacingCar(it, RandomMoveStrategy()) })
RacingCar를 만드는 일을 다른 객체로 분리해보는 것은 어떨까요?
다른 부분들은 모두 값을 받아서 생성만 하고 있는데,
이 부분만 자동차 경주의 중요한 로직을 담당하고 있는 것 처럼 보이네요!!

2022-11-12 15:12 UTC, malibinYun commented on src/main/kotlin/game/racingcar/domain/RacingCarGame.kt
> +) {
코틀린 1.4 버전 부터 trailing comma를 지원하기 시작했는데요,
이때부터 코틀린 컨벤션에도 등록이 되었답니다 :)
자세한 내용과 이점에 대해서는 아래 문서를 읽어주세요! 
https://kotlinlang.org/docs/coding-conventions.html#trailing-commas

2022-11-12 15:12 UTC, malibinYun commented on src/main/kotlin/game/racingcar/domain/RacingCars.kt
> +    private fun getMaxLocation() = racingCars.maxOf { it.location }
https://github.com/next-step/kotlin-racingcar/pull/763#discussion_r1015511506
이 리뷰를 참고해서 리턴 타입을 명시해보는 것은 어떨까요?

2022-11-12 15:12 UTC, malibinYun commented on src/test/kotlin/game/racingcar/RacingCarGameTest.kt
> +        assertThat(locationSnapshots.carLocationSnapshots[0].locations[2]).isEqualTo(CarLocation("huris", 1))
https://github.com/next-step/kotlin-racingcar/pull/744#discussion_r1014620854
이 리뷰를 참고해서 assertAll을 활용해보는 것은 어떨까요?

2022-11-12 15:12 UTC, malibinYun commented on src/test/kotlin/game/racingcar/RacingCarGameTest.kt
> +        assertThat(locationSnapshots.carLocationSnapshots[0].locations[2]).isEqualTo(CarLocation("huris", 1))
변수명이 너무 길어서, locationSnapshots.carLocationSnapshots 까지는 then 절 직후에 변수에 따로 담아도 괜찮다는 생각이 드네요 :)

2022-11-12 15:12 UTC, malibinYun commented on src/test/kotlin/game/racingcar/RacingCarTest.kt
> +            .hasMessage("이름은 빈 문자열일 수 없습니다.")
공백문자열은 여러 케이스를 테스트 해야해요 :)
\n, \t, " " 등, 다양한 공백 문자에 대해 Parameterized 테스트 해보는 것은 어떨까요?

Junit의 `@EmptySource`도 같이 활용해보시면 좋겠네요 :)

2022-11-12 15:12 UTC, malibinYun commented on src/test/kotlin/game/racingcar/RacingCarsTest.kt
> +        val racingCars = RacingCars(listOf("haris", "horis", "huris").map { RacingCar(it, AlwaysMoveStrategy()) })
RacingCar를 만들때, 초기 location을 생성자로 설정할 수 있게 되었어요.
이를 활용해서 RacingCar 객체를 만들 때 위치가 서로 다른 자동차를 의도적으로 배치하고,
그 상태에서 우승자를 가져오는 테스트를 진행해보는 것은 어떨까요?

좀 더 명확한 테스트를 작성할 수 있을 것으로 기대되네요 😊

2022-11-12 15:14 UTC, malibinYun commented on src/main/kotlin/game/racingcar/domain/RacingCar.kt
> +
초기 location을 받게 되면 테스트를 할 때 move등을 일일이 호출하지 않아도,
원하는 위치의 자동차를 의도적으로 생성해낼 수 있는 장점이 생겨요 :)
마지막 리뷰 내용 중 포함되어있으니 테스트를 한 번 짜보시는 것을 추천드릴게요!

2022-11-12 15:14 UTC, malibinYun commented on src/main/kotlin/game/racingcar/domain/RacingCars.kt
> +    private fun carsIn(maxLocation: Int) = racingCars.filter { it.location == maxLocation }.map { it.name }
네!! 맞아요!
Exception이 발생하면 로그 창에는 모두 같은 라인에서 발생했다고 나타나서 디버그하기 어려워지게 됩니다 :)

2022-11-13 04:20 UTC, harrisleesh commented on src/main/kotlin/game/racingcar/RacingCarMain.kt
> +    val racingCars = RacingCars(carNames.map { RacingCar(it, RandomMoveStrategy()) })
넵!! 이부분은 RacingCars의 스태틱 메서드로 분리해봤는데요!
팩토리 클래스를 만드는게 나을지 고민되네요 ㅎㅎ

2022-11-13 04:23 UTC, harrisleesh commented on src/main/kotlin/game/racingcar/domain/RacingCarGame.kt
> +) {
오 이 내용은 처음이네요!! 
항상 의문이 있었거든요! 콤마로 끝나도되고 콤마로 안끝나도 되는데 이게 컨벤션이 있었군요!!
감사합니다!

2022-11-13 04:34 UTC, harrisleesh commented on src/test/kotlin/game/racingcar/RacingCarTest.kt
> +            .hasMessage("이름은 빈 문자열일 수 없습니다.")
오오.. 감사합니다!!

2022-11-13 13:49 UTC, malibinYun approved these changes
자동차 경주 미션 완주 다시 한 번 축하드려요~🎉
피드백을 잘 반영해주셔서 크게 리뷰 드릴 게 없었네요 :)
이번 미션은 이만 마무리 짓겠습니다.
더 어려운 미션들이 기다리고 있지만, 차근히 진행하시다보면 전부 완수해낼 수 있을거예요!
다른 미션들도 모두 완주하시길 바라요 :) 응원할게요! 💪

2022-11-13 13:50 UTC, merged