Step3
next-step/kotlin-racingcar pull request #833
Opened 2022-11-11 23:51 UTC by relkimm

2022-11-12 00:47 UTC, relkimm commented on src/main/kotlin/step3/Store.kt
> +}
요부분은 UI 화면에서 사용하는 데이터를 편하게 공유하기 위해서 만들어 보았어요🙆‍♂️

2022-11-12 00:47 UTC, relkimm commented on src/main/kotlin/step3/Store.kt
> +}
`pub/sub` 구조면 더 좋을텐데 아직 한 곳에서만 조회하고 있어서 간단하게 구현해 보았습니다.

2022-11-12 00:47 UTC, relkimm commented on src/main/kotlin/step3/component/Component.kt
> +}
리액트 클래스형 컴포넌트 느낌을 살려서 UI 들을 구현해 보았습니다.🙇‍♂️
괜찮은지는... 잘 모르겠네요... 😅😄

2022-11-12 15:17 UTC, YooInKeun requested changes
2단계 반영하시고 3단계까지 진행하시느라 고생 많으셨습니다 👍 
몇가지 피드백 남겼으니 확인해주시고 재요청 부탁드려요~ 🙇‍♂️
항상 응원하고 있습니다~ 좀 더 화이팅입니다!!

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/Car.kt
> +    var position = 0
객체지향 생활체조 원칙을 적용해보기 위해 position 프로퍼티를 클래스 형태로 관리해보는 것은 어떨까요?

**객체지향 생활체조 원칙**
```
3. 모든 원시 값과 문자열을 포장한다.
```

원시값이 하나인 경우 코틀린의 inline class인 value class 를 활용하면 객체 생성 비용을 줄일 수 있어요~
한 번 적용해보시는 것도 좋을 거 같습니다!
https://kotlinlang.org/docs/inline-classes.html

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/Car.kt
> +    private fun canMove(oil: Oil): Boolean {
oil 에게 메세지 형태로 물어보는 형태가 객체 지향적으로 좋을 거 같은데 어떨까요?

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/Car.kt
> +    fun move(oil: Oil) {
car를 이동시키는 요소를 외부에서 주입해주셨군요 👍 👍 
덕분에 테스트하기 좋은 구조가 됐네요~

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/Oil.kt
> +data class Oil(val amount: Int) {
`data class` 로 선언한 이유가 있을까요~?

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/Oil.kt
> +    operator fun compareTo(oil: Oil): Int {
연산자 오버로딩을 사용해주셨군요 👍

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/OilStation.kt
> +    private val randomRange = (0..9)
상수 표기법을 따라주는 게 좋겠네요~
```suggestion
    private val RANDOM_RANGE = (0..9)
```

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/component/DistanceComponent.kt
> +        (1..position).forEach { _ ->
코틀린의 `repeat` 기능을 사용하면 좀 더 간결하게 표현 가능할 거 같습니다!
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/repeat.html

2022-11-12 15:17 UTC, YooInKeun commented on src/test/kotlin/step3/CarTest.kt
> +                val 충분한_연료 = Oil(amount = 4)
경계값을 잘 테스트 해주셨네요 👍

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/OilStation.kt
> +    fun getOilRandomly(): Oil {
`OilStation` 이 갖고 있는 `Oil` 을 반환하는 것이 아니라 새로운 `Oil` 을 생성해주는 기능이라, getXXX 보다는 generateXXX, createXXX 와 같은 네이밍이 좀 더 어울릴 거 같은데 어떨까요?

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/README.md
> +초간단 자동차 경주 게임을 구현한다.
미션 설명에 있는 기능 요구 사항을 그대로를 사용하는 것보다, 커밋을 기능별로 자세하게 잘 작성해주신 것처럼 요구 사항을 기능별로 자세하게 나눠보시는 것도 좋을 거 같습니다!

수정해주실 필요는 없지만 참고차 코멘트 드립니다~ 🙇‍♂️

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/RoundResult.kt
> +    data class CarPosition(
생성자에 대한 접근 제어자도 신경 써주시면 좋을 거 같아요~

```suggestion
    data class CarPosition private constructor(
```

2022-11-12 15:17 UTC, YooInKeun commented on src/main/kotlin/step3/component/Component.kt
> +}
프론트 영역은 자세히 몰라서 말씀드리기 조심스럽습니다만
`render()` 메소드를 구현하고 있는 여러 클래스를 보면 입력하거나 출력하거나 아니면 2개를 한 번에 하는 등 기능이 섞여 있는 거 같아서, 헷갈리지 않도록 인터페이스나 메소드를 정확히 정의하거나 그게 쉽지 않으면 구조 자체를 좀 더 심플하게 가져가는 것도 고려해볼 수 있을 거 같습니다!

ex) input 을 담당하는 class 와 output 을 담당하는 class 2가지로 나눔

2022-11-13 10:36 UTC, relkimm commented on src/main/kotlin/step3/OilStation.kt
> +    fun getOilRandomly(): Oil {
네네 완전 좋은 것 같아요!! 특히 `generate` 네이밍 너무 마음에 드네요.☺️

2022-11-13 10:41 UTC, relkimm commented on src/main/kotlin/step3/OilStation.kt
> +    private val randomRange = (0..9)
확실히 상수 표기법 따르는 편이 구분 잘되고 좋네요~👍

2022-11-13 11:16 UTC, relkimm commented on src/main/kotlin/step3/Car.kt
> +    private fun canMove(oil: Oil): Boolean {
음 조금 고민이 되는 부분이 있어요!  
혹시나 자동차마다 `move` 하는데 필요한 연료가 다르다면 (`Truck` `Oil >= 6`)자동차 내부에서 판단하는게 좋지 않을까 싶기도 하고 
`Oil` 이 최대한 자동차를 모르는 편이 좋지 않을까 싶기도 하네요~ (비행기에서도 `Oil` 을 사용한다고 가정을 하면!)

차라리 `Oil` 대신 `MovePolicy` 를 인자로 받고 `MovePolicy` 에게 `canMove` 를 물어보는 형태는 어떨까 싶기도 합니다~

최대한 자동차 `move` 에 대한 테스트를 편하게 짜려고 하다 보니, 설계를 뭔가 잘못했나? 싶기도 하네요.😭😇 

아래와 같이 코드를 짜면, `canMove` 에 대한 테스트가 어려워진다는 단점이 있을 것 같아요~

``` kotlin
fun move(movePolicy: MovePolicy) {
    if (movePolicy.canMove()) {
        this.position++
    }
}

class RandomPolicy(
    private val oilStation: OilStation,
): MovePolicy {
    override fun canMove(): Boolean {
        val oil = oilStation.generateOilRandomly()
        return oil >= Oil(amount = 4)
    }
}

```

2022-11-13 11:20 UTC, relkimm commented on src/main/kotlin/step3/Oil.kt
> +data class Oil(val amount: Int) {
헉 무지성으로 data class 선언해 버렸네요.🥲 
한가지 궁금한 점이 있는데! 혹시 인근님은 data class 를 보통 어떠한 경우에 선언하시는 편일까요?

2022-11-13 11:25 UTC, relkimm commented on src/main/kotlin/step3/component/DistanceComponent.kt
> +        (1..position).forEach { _ ->
우와 인근님 요런 기능 찾고 있었는데... 너무 감사합니다. 덕분에 앞으로도 잘 쓸 것 같아요! https://github.com/next-step/kotlin-racingcar/pull/833/commits/6ea5ef8e29e43518faafe99762dad996058ce650

2022-11-13 11:28 UTC, relkimm commented on src/main/kotlin/step3/README.md
> +초간단 자동차 경주 게임을 구현한다.
코멘트 감사합니다~! 다음 단계에서는 기능 별로 조금 더 자세히 나눠 볼게요.🙆‍♂️🙆‍♂️

2022-11-13 11:36 UTC, relkimm commented on src/main/kotlin/step3/RoundResult.kt
> +    data class CarPosition(
와!! 확실히 `private constructor` 가 맞겠네요~ 아무래도 `CarPosition` 이 자동차에 대한 위치 정보니까 
정적 팩터리 메서드 `from(car: Car)` 통해서만 생성 될 것 같아요!
코멘트 감사합니다.👍👍

2022-11-13 11:53 UTC, relkimm commented on src/main/kotlin/step3/Car.kt
> +    var position = 0
value class 는 처음인데! 요긴하게 쓸 것 같네요.☺️
덕분에 하나 또 잘 배웠습니다.🙇‍♂️ https://github.com/next-step/kotlin-racingcar/pull/833/commits/471aa1d5efb3104951195c4d87e979e08aa13b5c Oil 클래스에도 적용해 보았어요~ https://github.com/next-step/kotlin-racingcar/pull/833/commits/e2ea742b9fe92bab0206b2dedab768d8e91b501c

2022-11-13 12:42 UTC, relkimm commented on src/main/kotlin/step3/component/Component.kt
> +}
아! `Component` 를 여러 UI 를 묶은 하나의 단위 라고 본다면 
`Input` 과 `Span` 은 컴포넌트라기 보단 `input/output` 을 담당하는 기본 UI 단위라고 볼 수 있겠네요!
`Component` 와 `Input/Span` 은 구별하는게 좋겠다는 생각이 듭니다☺️

그리고 `InputComponent` 내부가 확실히 `output/input` 두가지 기능이 섞여 있네요!
`label` 을 `placeholder` 느낌으로 표현해 보았는데 분리하는 것도 좋은 것 같아요.

우선 요렇게 구성해 보았습니다🙆‍♂️🙆‍♂️ https://github.com/next-step/kotlin-racingcar/pull/833/commits/432ae8374a33826be5cf20ec1a38d875078d875c

2022-11-13 12:44 UTC, relkimm commented
이번에도 새로운 주제 많이 알려주셔서 많이 배웠네요!
감사합니다 인근님👍👍 우선 수정한 부분 리뷰 재요청 드립니다.🙇‍♂️

2022-11-14 04:07 UTC, YooInKeun commented on src/main/kotlin/step3/Car.kt
> +    private fun canMove(oil: Oil): Boolean {
먼저 `MovePolicy` 의 구조에 대해 고민해주시고 예시 코드까지 첨부해주셔서 감사합니다 👍 
`move()` 메소드가 인터페이스에 의존하게 되면서 유연해지고 테스트가 용이해지는 거 같아서 좋은 거 같아요

이때 `canMove()` 에 대한 테스트가 어려워지는 이유는 랜덤한 오일을 생성하는 메소드인 `generateOilRandomly()` 가 메소드 안에 있기 때문인 거 같은데요~ 차라리 외부에서 generateOilRandomly() 를 호출하고 그 결과인 oil을 파라미터 형태로 받으면 테스트가 가능한 구조가 될 거 같은데 어떨까요? ex) `canMove(oil: Oil)`

그리고 개인적으로 `Oil`, `OilStation` 이라는 도메인이 당장 필요한지 잘 모르겠는데요~ 🤔 
Oil 도메인을 봤을 때 XP 원칙에서 말하는 YAGNI 가 떠오르긴 했습니다만 동구님은 어떠실까요?
미션 진행은 동구님의 생각대로 계속 진행하셔도 무방할 거 같습니다! 🙏 

> YAGNI(You aren't gonna need it): 필요하다고 간주할 때까지 기능을 추가하지 않는 것이 좋다

2022-11-14 04:07 UTC, YooInKeun commented on src/main/kotlin/step3/component/DistanceComponent.kt
> +        (1..position).forEach { _ ->
피드백 잘 반영해주시고 의견주셔서 제가 감사합니다~ 🙇‍♂️

2022-11-14 04:07 UTC, YooInKeun commented on src/main/kotlin/step3/Oil.kt
> +data class Oil(val amount: Int) {
`data class` 는 `toString()`, `hashCode()`, `equals()`, `copy()` 메소드를 구현해줘서 저는 이 기능들이 필요할 때 사용하고 있는데요~

2022-11-14 11:43 UTC, relkimm commented on src/main/kotlin/step3/Car.kt
> +    private fun canMove(oil: Oil): Boolean {
네~ 저도 공감합니다☺️ `Oil` 은 사실 지금 필요한 요소는 아닌 것 같아요.
재밌게 하려다 보니, 상상의 나래를 조금 펼쳐본 것 같기도 하네요.😁😁

인근님 말씀대로 `MovePolicy` 의 `canMove` 가 `Oil` 을 받는 구조가 되면 
테스트할 수 있을 것 같은데 한가지 고민이 되는 부분이 있었어요~
결국 지금 구조에서 아래와 같이 `car` 내부에서 `movePolicy` 의 `canMove` 를 호출해야 하는데
Oil 을 `canMove` 가 받으려면 `move` 의 인자로 Oil 을 받는 구조가 되어야 할 것 같아요.😭

아니면 `RandomPolicy` 가 생성될 때 생성자로 `Oil` 을 받을 수도 있을 것 같네요!

지금 단계에서 답을 정하긴 어려운 것 같은데 이런 저런 고민하는 것 자체가 너무 재밌네요~🥲☺️😁


``` kotlin
// client code
val oil = OilStation.generateOilRandomly()
val randomPolicy = RandomPolicy()
car.move(movePolicy = randomPolicy, oil = oil)

// Car Class
fun move(movePolicy: MovePolicy, oil: Oil) {
if (movePolicy.canMove(oil = oil)) {
..
}
}
```

``` kotlin
val oil = OilStation.generateOilRandomly()
val randomPolicy = RandomPolicy(oil = oil)
car.move(movePolicy = randomPolicy)

fun move(movePolicy: MovePolicy) {
if (movePolicy.canMove()) {
..
}
}
```

2022-11-14 14:18 UTC, YooInKeun commented on src/main/kotlin/step3/Car.kt
> +    private fun canMove(oil: Oil): Boolean {
Oil 도메인을 제거해보거나 말씀주신 방법 중에 괜찮은 방법으로 4단계에 적용해주시면 같이 확인해볼게요~ ㅎㅎ

2022-11-14 14:29 UTC, YooInKeun commented on src/main/kotlin/step3/Oil.kt
> +data class Oil(val amount: Int) {
저는 `toString(), hashCode(), equals(), copy()` 메소드 기능이 필요한 클래스거나
데이터 전달 역할을 하는 DTO 를 생성할 때, `data class` 로 선언해서 사용하곤 합니다!

2022-11-14 14:34 UTC, YooInKeun approved these changes
3단계 진행하시느라 정말 고생많으셨습니다~ 👍 👍 
질문 주신 내용에 대해선 코멘트 남겼으니 4단계 하실 때 참고 부탁드려요~ 🙇‍♂️ 
그럼 4단계도 화이팅입니다!! 💪

2022-11-14 14:34 UTC, merged