Step2
next-step/kotlin-racingcar pull request #840
Opened 2022-11-12 10:01 UTC by Cafemug

## 구현사항
- 문자열 validation과 계산로직을 Calculator 클래스 구현
- 사칙연산을 하는 Operator 클래스 구현
- 공통함수(숫자 판별, 연산자 판별, 중위 표기식 -> 후위 표기식 변환)를 위한 utils 클래스 구현
- 에러 메세지를 한 곳에서 처리 하기 위한 ExceptionCode 클래스 구현
- ExceptionCode클래스를 제외한 모든 클래스 테스트코드 작성

## 질문사항 및 논의사항
1. 중위 표기식 -> 후위 표기식 변환 함수는 예외처리를 어떻게 해야할지 고민입니다.(하려면 무수히 할수 있지만 얼마나까지 해야하나?) 
이 함수만 negative 시나리오 테스트 케이스가 없습니다

2. Calculator에서 when으로 + - * / 를 판단하는 구문에 주석으로 적힌 것 처럼 이미 validation에서 걸러진 예외처리를 when이 else가 필요하다고 이렇게 처리하는 게 맞는지(/를 굳이 안쓰고 else로 해도 되지만 가독성때문에 /도 넣었습니다)

3. Operator 클래스 같은 경우 사실 맨처음에는 private fun으로 Calculator 클래스가 같이 있었는데 다른 데서도 쓸 수 있을까봐 인터페이스화와 클래스 분리를 하였는데 이게 굳이 필요했을까 고민입니다

2022-11-13 04:39 UTC, namjackson requested changes
안녕하세요 가빈님 2단계 미션 코드 고생하셨습니다! 
몇가지 참고하실만한 포인트들 코멘트 남겼으니 확인해주세요! 
변경사항 적용 후, 다시 리뷰요청해주세요!

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/Calculator.kt
> +        println(postFix)
불필요한 코드는 삭제해주세요!

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/Calculator.kt
> +        postFix.map { it ->
map은 반환값이 존재하는데요,
반환값을 사용하지 않는다면, forEach가 적절해보여요!

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/Calculator.kt
> +                        else -> throw IllegalArgumentException(ExceptionCode.NOT_MATCHED_OPERATOR.getMessage())
> Calculator에서 when으로 + - * / 를 판단하는 구문에 주석으로 적힌 것 처럼 이미 validation에서 걸러진 예외처리를 when이 else가 필요하다고 이렇게 처리하는 게 맞는지(/를 굳이 안쓰고 else로 해도 되지만 가독성때문에 /도 넣었습니다)

가빈님의 생각대로, 가독성 측면에서도 그렇고, 
validation이 변경되거나, 연산자가 추가되는 등의 변경에도 좀더 명시적으로 사용하는 편이 좋을거 같다는 생각이 듭니다!

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/Calculator.kt
> +    private fun inputValidation(input: String?): List<String> {
Calculator에서 계산로직을 제외하고, validation체크만 테스트하고 싶다면 어떻게 해야할까요?
private 함수를 테스트해야한다면, 해당 클래스의 여러책임이 결합되어있어 클래스 분리의 신호로 볼수 있습니다!

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/Calculator.kt
> +        if (input.isNullOrBlank()) {
코틀린에서는 require이라는 키워드도 지원해주니 참고해주세요!

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/Calculator.kt
> +                        "/" -> stack.add(operator.divide(firstNum, secondNum))
연산자에 대한 문자열을 operator에서 따로 관리하는 방법을 고민해보면 어떨까요?

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/Operator.kt
> +class OperatorImpl : Operator {
> Operator 클래스 같은 경우 사실 맨처음에는 private fun으로 Calculator 클래스가 같이 있었는데 다른 데서도 쓸 수 있을까봐 인터페이스화와 클래스 분리를 하였는데 이게 굳이 필요했을까 고민입니다

미션과정에서는 interface가 불필요 해보이긴합니다! 
인터페이스를 분리하여, 여러종류의 타입에 해당하는 operator를 따로 구현할수도 있을거 같지만,
현재 Operator인터페이스는 제너릭하지 않기때문에, 재활용하기도 어렵다는 생각이 들어요! 

또한 Impl라는 접미사는 사용을 지양하는것이 좋아요! 
interface의 이름은 추상화된 이름을, 구현체에서는 추상화요소에 구체화된 이름을 고민해보시면서 
interface의 필요성을 고민해보셔도 좋을거같습니다!

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/common/ExceptionCode.kt
> +enum class ExceptionCode(
Exception을 따로 관리하도록 하셨군요 👍

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/common/Utils.kt
> +    fun isOperator(str: String) = str.all { it in charArrayOf('+', '-', '*', '/') }
코틀린의 확장함수를 사용해보셔도 좋을거같아요! 
`fun String.isOperator() = this.all { it in charArrayOf('+', '-', '*', '/') }`

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/common/Utils.kt
> +        input.map {
위의 리뷰와 마찬가지로 반환값을 사용하지않는다면 forEach를 사용해주세요!

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/common/Utils.kt
> +class Utils {
Utils라는 클래스는 너무 광범위한 이름을 가진 네이밍이라 생각이 들어요!
해당 클래스의 맞는 이름으로 변경해보면 어떨까여?

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/common/Utils.kt
> +        }
반복문과 if/else 또다시 while문이 혼재되어있어 
가독성이 좋지않은거 같아요. 적절하게 함수를 분리해서 가독성에 대한 고민해보셔도 좋을거같아요!

2022-11-13 04:39 UTC, namjackson commented on src/test/kotlin/calculator/CalculatorTest.kt
> +        }.isInstanceOf(IllegalArgumentException::class.java).hasMessageContaining(ExceptionCode.NOT_DIVIDE_ZERO.getMessage())
여러종류의 같은 테스트를 반복해야한다면,
@ParameterizedTest라는 기능을 제공해줍니다! 
참고해주셔도 좋을거같아요!

2022-11-13 04:39 UTC, namjackson commented on src/test/kotlin/calculator/CalculatorTest.kt
> +    @DisplayName("숫자 위치에 숫자가 아니면 에러를 낸다")
테스트케이스에 대한 규칙을 정해보는건 어떨까요?
실무의 복잡한 케이스들과, 많은 테스트 케이스가 추가된다면
관리하기가 복잡해질수 있어요! 
Given, When, Then 표기법을 활용해보시는것을 추천드립니다!

2022-11-13 04:39 UTC, namjackson commented on src/test/kotlin/calculator/common/UtilsTest.kt
> +    }
> 중위 표기식 -> 후위 표기식 변환 함수는 예외처리를 어떻게 해야할지 고민입니다.(하려면 무수히 할수 있지만 얼마나까지 해야하나?)
> 이 함수만 negative 시나리오 테스트 케이스가 없습니다
구체적인 시나리오가 없다면, 후위표기 변환되는 결과를 확인하는정도도 괜찮을거 같습니다!

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/Calculator.kt
> +        val postFix = utils.infixToPostFix(inputList)
중위표현식을 후위표현식으로 변환하여 처리하는 방법이 인상적이네요 👍 👍 👍

2022-11-13 04:39 UTC, namjackson commented on src/main/kotlin/calculator/Calculator.kt
> +                else -> {
else문보다는 명시적으로 isOperator 로 표기해주시는게 좋을거같아요!

2022-11-14 10:13 UTC, Cafemug commented on src/main/kotlin/calculator/Calculator.kt
> +                        "/" -> stack.add(operator.divide(firstNum, secondNum))
리뷰 감사합니다 enum class로 변경해보았습니다

2022-11-14 10:13 UTC, Cafemug commented on src/main/kotlin/calculator/Calculator.kt
> +        if (input.isNullOrBlank()) {
리뷰 감사합니다 require로 변경하였습니다

2022-11-14 10:13 UTC, Cafemug commented on src/main/kotlin/calculator/Calculator.kt
> +    private fun inputValidation(input: String?): List<String> {
리뷰 감사합니다 class로 새로 만들어서 적용하고 테스트코드도 작성하였습니다
분리의 신호의 기준을 알려주셔서 감사합니다

2022-11-14 10:14 UTC, Cafemug commented on src/main/kotlin/calculator/Calculator.kt
> +                        else -> throw IllegalArgumentException(ExceptionCode.NOT_MATCHED_OPERATOR.getMessage())
고민을 많이 했는데 명쾌한 해답 감사합니다

2022-11-14 10:14 UTC, Cafemug commented on src/main/kotlin/calculator/Calculator.kt
> +        postFix.map { it ->
이 부분도 명심하도록 하겠습니다

2022-11-14 10:14 UTC, Cafemug commented on src/main/kotlin/calculator/Calculator.kt
> +        println(postFix)
제가 까먹고 디버깅용 코드를 지우지 않았네요 다음부터는 잘 확인하도록 하겠습니다

2022-11-14 10:14 UTC, Cafemug commented on src/main/kotlin/calculator/Operator.kt
> +class OperatorImpl : Operator {
class명을 SimpleOperator라고 변경해보았습니다

2022-11-14 10:15 UTC, Cafemug commented on src/main/kotlin/calculator/common/Utils.kt
> +    fun isOperator(str: String) = str.all { it in charArrayOf('+', '-', '*', '/') }
확장함수에 대해서 알게되었습니다 감사합니다. 이 부분은 좀 더 추후에 적용해보도록 하겠습니다

2022-11-14 10:15 UTC, Cafemug commented on src/main/kotlin/calculator/common/Utils.kt
> +class Utils {
OperatorHelper로 바꾸어보았습니다

2022-11-14 10:15 UTC, Cafemug commented on src/main/kotlin/calculator/common/Utils.kt
> +        }
while문이 반복되어서 fun으로 뺐는데 얕은 복사의 위험성이 있을지 궁금합니다

2022-11-14 10:16 UTC, Cafemug commented on src/test/kotlin/calculator/CalculatorTest.kt
> +        }.isInstanceOf(IllegalArgumentException::class.java).hasMessageContaining(ExceptionCode.NOT_DIVIDE_ZERO.getMessage())
넵넵 null이랑 빈 문자열 테스트에만 @ParameterizedTest를 사용하였습니다

2022-11-14 10:16 UTC, Cafemug commented on src/test/kotlin/calculator/CalculatorTest.kt
> +    @DisplayName("숫자 위치에 숫자가 아니면 에러를 낸다")
이 부분도 참고하여 step3부터 적용해보도록 하겠습니다

2022-11-14 10:16 UTC, Cafemug commented on src/main/kotlin/calculator/Calculator.kt
> +                else -> {
명시적으로 표기하였습니다

2022-11-14 10:16 UTC, Cafemug commented
@namjackson 재 리뷰 요청드립니다

2022-11-14 13:32 UTC, namjackson approved these changes
안녕하세요 가빈님 문자열 계산기 고생많으셨습니다! 
몇가지 참고하실만한 코멘트 남겼으니, 확인해주세요! 
변경사항은 다음미션중에 적용해주시면 됩니다! 
빠른진행을위해 머지하겠습니다!
이제 본격적으로 자동차 경주 미션 진행해주세요 😸

2022-11-14 13:32 UTC, namjackson commented on src/main/kotlin/calculator/enums/ArithmeticOperator.kt
> +    }
operator 변수를 불변으로 선언하셔서 getter 함수를 만드는것보다, 
`val operator: String`를 열어주는게 좀더 코틀린스러운거같아요! 😸

2022-11-14 13:32 UTC, namjackson commented on src/main/kotlin/calculator/enums/ArithmeticOperator.kt
> +enum class ArithmeticOperator(private val operator: String) {
enum을 추가해주셨군요 👍 
반면에 연산자에 관한 로직이 Operator 와 enum 클래스에서 분산된거같아요! 
해당 연산자에 맞는 연산 로직도 이곳에서 관리하도록하면 어떨까요?

https://kotlinlang.org/docs/enum-classes.html

2022-11-14 13:32 UTC, namjackson commented on src/main/kotlin/calculator/Calculator.kt
> +        postFix.forEach { it ->
반복문 / when / when 
뎁스가 길어질수록, 가독성이 나빠지고, 실수하기가 쉬워집니다! 
뎁스가 길어지지않도록, 함수로 분리해보면 어떨까요?

2022-11-14 13:32 UTC, namjackson commented on src/test/kotlin/calculator/CalculatorTest.kt
> +        }.isInstanceOf(IllegalArgumentException::class.java).hasMessageContaining(ExceptionCode.NOT_DIVIDE_ZERO.getMessage())
다른 부분도 ParameterizedTest를 사용해도 좋을거같아요! 😸

2022-11-14 13:33 UTC, merged

2022-12-24 08:08 UTC, Cafemug commented on src/main/kotlin/calculator/enums/ArithmeticOperator.kt
> +    }
이 부분을 #957 에 반영했는데 기대하신 게 맞는지 체크부탁드려요

2022-12-24 08:09 UTC, Cafemug commented on src/main/kotlin/calculator/enums/ArithmeticOperator.kt
> +enum class ArithmeticOperator(private val operator: String) {
제가 의도하신바를 이해를 못해서 여쭤보려고 하는데 이 enum클래스에 기존 operator를 다 넣으시라는 말씀이신건가요?

2022-12-24 08:10 UTC, Cafemug commented on src/main/kotlin/calculator/Calculator.kt
> +        postFix.forEach { it ->
이 부분은 조금 더 고민후에 고쳐보도록 하겠습니다!