Step4 자동차 경주(우승자)
next-step/kotlin-racingcar pull request #852
Opened 2022-11-13 05:18 UTC by dk-ko

미리 작업했더니 일부 계산기 코드가 포함되었네요
나름 Application에 모여 있는 로직을 분산하려 했는데
Service 같은 클래스를 따로 만드는게 좋을지 고민됩니다 🤔 
이번에도 잘 부탁드립니다 🙇

2022-11-15 14:17 UTC, Flamme1004K requested changes
안녕하세요!

전체적으로 구현 잘해주셨네요 💯

몇가지 코멘트를 남겼으니 확인 부탁드리겠습니다!

궁금하신 점에 대해서는 DM 부탁드립니다!!

확인 후 다시 리뷰 요청 부탁드립니다!

2022-11-15 14:17 UTC, Flamme1004K commented on src/main/kotlin/calcualator/Operator.kt
> +    DIV("/", { a, b -> a.div(b) });
한 단계 더 리팩토링 하셨군요!  리팩토링 하시는 모습 너무 훌륭하세요! 👍👍

2022-11-15 14:17 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +    var status: Int = 0,
현재 `status`는 외부에서도 수정이 가능해보여요! 어떻게 해야 외부에서 수정이 불가능하도록 할 수 있을까요~? 🤔

2022-11-15 14:17 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +        if (name.length > NAME_LENGTH_CONDITION)
kotlin에서는 `require` 함수를 통해서 `IllegalArgumentException`을 처리할 수 있습니다!

참고
- [Kotlin 예외처리](https://seosh817.tistory.com/155)

2022-11-15 14:17 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +    }
`result`를 만드는 로직은 뷰 로직이 아닐까요~?

2022-11-15 14:17 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +        const val NAME_LENGTH_CONDITION = 5
`MOVE_CONDITION`과 `NAME_LENGTH_CONDITION`은 `Car`에서만 사용하고 있는 것 같은데, 이 경우에는 외부에서 사용 불가능하도록 만드는 것이 괜찮지 않을까요?

2022-11-15 14:17 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Cars.kt
> +class Cars(var cars: List<Car>) {
일급 컬렉션 사용 👍

2022-11-15 14:17 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Cars.kt
> +            it.move((RANDOM_NUMBER_RANGE).random())
랜덤한 요소가 있다면, `cars`에 대한 테스트가 힘들다고 생각해요. 변경 해볼까요~?

2022-11-15 14:17 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Cars.kt
> +    }
```suggestion
    fun findMaxStatusValue(): Int = cars.maxOf { it.status }
```

kotlin의 `maxOf`를 사용하면 깔끔하게 리팩토링이 가능해보여요!

`maxOf`에 대해서 알아볼까요~? 

링크
- [maxOf](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.comparisons/max-of.html)

2022-11-15 14:17 UTC, Flamme1004K commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +    for (i in 1..tryNumber) {
`repeat`를 사용하는 방법도 있어보여요! 한번 해볼까요!?

링크
- [Kotlin Repeat](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/repeat.html)

2022-11-15 14:17 UTC, Flamme1004K commented on src/main/kotlin/racingcar/RacingCarApplication.kt
>      }
자동차 게임을 시작하는 것과 결과를 내어주는 것은 자동차 게임이라는 하나의 클래스가 만들어질 수 있다고 생각해요. 해당 부분에 대해서 어떻게 생각하시나요? 🤔

2022-11-15 14:17 UTC, Flamme1004K commented on src/test/kotlin/racingcar/CarTest.kt
>  class CarTest {
저는 모든 도메인 클래스에 대한 테스트는 필수라고 생각을 합니다.

`cars`에 대한 테스트도 필요하지 않을까요?

2022-11-17 11:30 UTC, dk-ko commented on src/main/kotlin/racingcar/Car.kt
> +        if (name.length > NAME_LENGTH_CONDITION)
@Flamme1004K `require`을 사용하려면 
```kotlin
require (name.length < NAME_LENGTH_CONDITION) {
    ("자동자 이름은 ${NAME_LENGTH_CONDITION}자를 넘을 수 없습니다.")
}
```
위와 같은 형태가 되어야 하는데 이게 오히려 의미상 직관적이지 않은 것 같아요~
이번의 경우 if 문을 쓰는게 좀 더 와닿을 것 같습니다

2022-11-17 11:49 UTC, dk-ko commented on src/main/kotlin/racingcar/RacingCarApplication.kt
>      }
@Flamme1004K 지금 생각해보니 InputView와 ResultView의 역할로 충분하지 않나 싶긴합니다. 더 쪼갠다면 MVC 형태로 데이터를 받는 컨트롤러 형태의 클래스는 만들어도 괜찮을 것 같아요

2022-11-18 12:22 UTC, Flamme1004K approved these changes
안녕하세요!

step4 미션 고생하셨습니다! 이만 머지하도록 하겠습니다!

몇 가지 코멘트를 남겼으니, 5단계 자동차 경주 진행하며, 같이 반영해 주시면 되겠습니다.

마지막 step5도 화이팅입니다! 응원하겠습니다! 🥳🥳🥳

2022-11-18 12:22 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +    private val _name: String,
`backingProperty`는 어느 순간에 사용하는 걸까요~?

2022-11-18 12:22 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Car.kt
> +        }
```suggestion
    val name: String = _name
```

커스텀 getter를 사용하지 않고 바로 할당이 가능합니다 😊

2022-11-18 12:22 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Cars.kt
> +data class Cars(var cars: List<Car>) {
`var`는 외부에서도 수정이 가능해요! 도메인 내부에서만 수정이 가능하도록 해야하지 않을까요?

2022-11-18 12:22 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Cars.kt
> +    }
자동차의 상태가 변경이 되고 있는데, 과연 `of`를 리턴을 해줘야할까요?

2022-11-18 12:22 UTC, Flamme1004K commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +        val movedCars = cars.move { (RANDOM_NUMBER_RANGE).random() }
움직임의 조건에 대해서는 따로 클래스로 빼서 관리하는게 좋지 않을까요~?

2022-11-18 12:22 UTC, Flamme1004K commented on src/main/kotlin/racingcar/ResultView.kt
> +class ResultView {
뷰 로직이 훨씬 좋아졌군요~

2022-11-18 12:22 UTC, Flamme1004K commented on src/test/kotlin/racingcar/CarsTest.kt
> +internal class CarsTest {
`Cars`에 대한 테스트 좋습니다!

2022-11-18 12:22 UTC, merged

2022-11-19 07:20 UTC, dk-ko commented on src/main/kotlin/racingcar/Cars.kt
> +    }
@Flamme1004K 뷰로직에서 출력문을 만들 때 사용하고 있어요

2022-11-19 07:21 UTC, dk-ko commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +        val movedCars = cars.move { (RANDOM_NUMBER_RANGE).random() }
@Flamme1004K 이게 무슨 의미신지 이해가 안가네요 ! 🧐

2022-11-19 09:06 UTC, hyoungjune-kurly commented on src/main/kotlin/racingcar/Cars.kt
> +    }
뷰 로직에서 출력문을 만들때 사용한다면, of 대신에 상태가 변경 된 cars를 사용해도 괜찬지 않을까요?

2022-11-19 09:10 UTC, Flamme1004K commented on src/main/kotlin/racingcar/Cars.kt
> +    }
뷰 로직을 위하여 사용한다면 of 대신에 내부 로직으로 인해 상태가 변경 된 cars를 사용해도 괜찮지 않을까요?

2022-11-19 09:15 UTC, Flamme1004K commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +        val movedCars = cars.move { (RANDOM_NUMBER_RANGE).random() }
자동차 요구 사항을 보면 ‘전진하는 조건은 0에서 9 사이에서 무작위 값을 구한 후 무작위 값이 4 이상일 경우이다.’ 이라는 요구 사항이 있어요. 

무작위 값을 구하는 요구 사항에 대해서는 정책으로 만들어서 클래스화 시키면 추후 정책이  바뀐다면 변경에 용이하지 않을까요?

2022-11-19 23:08 UTC, dk-ko commented on src/main/kotlin/racingcar/Cars.kt
> +    }
cars를 val로 바꾸고 car에서 복사한 값으로 새 객체를 받아서 넘기도록 수정했어요! 일관적이게 여기서도 받은 객체를 새 리스트로 만들어서 반환하게 되었습니다 😄

2022-11-19 23:09 UTC, dk-ko commented on src/main/kotlin/racingcar/Car.kt
> +    private val _name: String,
backingProperty를 완전히 이해하지 못한 것 같아서 제외했습니다! 다음 단계 미션 진행하며 적용해 볼 생각입니다