[Step4] 자동차 경주(우승자)
next-step/kotlin-racingcar pull request #859
Opened 2022-11-13 13:14 UTC by misudev

안녕하세요 리뷰어님!
4단계 리뷰도 잘 부탁드립니다 🙏

2022-11-14 14:27 UTC, kyucumber requested changes
안녕하세요 몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-11-14 14:27 UTC, kyucumber commented on src/main/kotlin/racing/Cars.kt
> +        fun init(listOfNames: List<String>, moveStrategy: MoveStrategy): Cars {
개인적인 의견일 수 있는데 `List<String>`이라는 타입에서 list임이 나타나기 때문에 `names: List<String>`으로 표기해도 좋다고 생각해요.

2022-11-14 14:27 UTC, kyucumber commented on src/main/kotlin/racing/Cars.kt
> +            .maxByOrNull { it.key }!!.value
max가 나오지 않는 경우에 NPE가 발생한다면 어떤 사유로 예외가 발생했는지 인지하기 어렵지 않을까요?

null safe operator(?)와 Elvis operator(?:)를 이용해 예외를 던지거나 혹은 기본 값을 반환하는 처리를 해주시면 좋을 것 같아요.

2022-11-14 14:27 UTC, kyucumber commented on src/main/kotlin/racing/Name.kt
> +data class Name private constructor(val name: String) {
value class(이전 기준 inline)의 사용을 고려해보셔도 좋겠네요. 자세한 내용은 아래 글을 참고해보세요.

- https://kotlinlang.org/docs/inline-classes.html

- [이펙티브 코틀린 아이템 47. 인라인 클래스의 사용을 고려하라](https://kyucumber.github.io/posts/book/effective-kotlin/effective-kotlin-item-47)

2022-11-14 14:27 UTC, kyucumber commented on src/main/kotlin/racing/Cars.kt
> +    fun getDistancesWithNames(): List<Pair<Name, Int>> {
지금과 같이 타입이 명확히 나뉜 경우라면 Pair를 사용하는것도 괜찮겠지만 만약 이후에 Int, Int와 같은 타입이라면 Pair나 Triple의 사용은 지양해주세요~

여기서는 반영하실 부분은 없습니다. 이후 과정에 참고하시라고 코멘트 남겼어요. 아래 글도 한번 참고 부탁드립니다.

[튜플 대신 데이터 클래스 활용하기](https://kyucumber.github.io/posts/book/effective-kotlin/effective-kotlin-item-37#%ED%8A%9C%ED%94%8C-%EB%8C%80%EC%8B%A0-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%81%B4%EB%9E%98%EC%8A%A4-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)

2022-11-14 14:27 UTC, kyucumber commented on src/main/kotlin/racing/Cars.kt
> +            .maxByOrNull { it.key }!!.value
groupBy를 사용하지 않아도 maxBy에서 distance를 기준으로 걸고 최종적으로 나온 값의 name에 대해 map 연산을 수행해도 되지 않을까요?

2022-11-15 11:05 UTC, misudev commented on src/main/kotlin/racing/Cars.kt
> +            .maxByOrNull { it.key }!!.value
음.. 우승자가 여러명일 경우 처리를 위해, groupBy를 사용했는데요!
아래처럼 처리하는 방식을 말씀하신걸까요?.?
```
        val maxValue = cars.maxOf(Car::distance)
        return cars
            .filter { it.distance == maxValue }
            .map(Car::name)
```

2022-11-15 11:07 UTC, misudev commented on src/main/kotlin/racing/Cars.kt
> +    fun getDistancesWithNames(): List<Pair<Name, Int>> {
타입이 동일할 때는 구분이 어렵겠네요! 🤭

2022-11-15 12:34 UTC, kyucumber commented on src/main/kotlin/racing/Cars.kt
> +            .maxByOrNull { it.key }!!.value
아이고 코멘트를 이상하게 남겼네요. 무시하셔도 됩니다. 😭

2022-11-17 11:23 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

다음 단계 진행을 위해 머지할게요

2022-11-17 11:23 UTC, merged