[Step5] 자동차 경주(리팩터링) PR 요청드립니다.
next-step/kotlin-racingcar pull request #875
Opened 2022-11-14 12:39 UTC by dajeong

형준님 안녕하세요! 🌞
드디어.. 5단계네요!
4단계 피드백 주신 내용도 반영해서 올렸습니다.
간단한 프로그램이지만 패키지를 분리해보았는데요. 잘 나눠진건지 잘 모르겠네요 ㅎㅎ
이번에도 잘 부탁드립니다! 🙏 
그리고 패키지명에 카멜케이스도 가능하다고 문서에서 봐서 적용해봤는데 보통 그렇게 잘쓰는지도 궁금하네요.

2022-11-15 14:44 UTC, Flamme1004K commented
> 패키지명에 카멜케이스도 가능하다고 문서에서 봐서 적용해봤는데 보통 그렇게 잘쓰는지도 궁금하네요.

확실히 이 부분에 대해서는 자신이 속해있는 조직에서 컨벤션을 어떻게 가져가는지에 따라서 다를 것 같긴하네요. 저는 둘다 사용을 해봤는데 딱히 차이점을 못 느꼇습니다. 🥲

다른 이야기이지만, 추가로 코틀린 파일 명도 카멜 케이스로도 가능합니다! 한번 읽어보시죠! 재밌는 글입니다! [링크](https://jojoldu.tistory.com/671)

> paramterized test를 통하여 보통 forAll로 사용?

확실히 저도 forall이 많으면 가독성에 좋지 않다고 생각을 합니다. 저는 가독성이 문제라고 생각되어지면 kotest에 대한 기본 Spec이 아닌, Junit도 사용하여 짜고는 있습니다.

2022-11-15 14:58 UTC, Flamme1004K requested changes
안녕하세요!

벌써 마지막 미션이군요! 리팩터링 고생하셨습니다! 잘 나눠주셨습니다 👍

몇 가지 코멘트를 남겼으니, 확인 부탁드립니다.

마지막까지 화이팅입니다! 🤩

2022-11-15 14:58 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
>      private val turnCount: Int,
`indicatorGenerator`, `turnCount`는 게임 시작 시에 한번만 사용할 것 같은데 계속 가지고 있어야할까요?

2022-11-15 14:58 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
>      private var maxDistance = 0
과연 `maxDistance`를 항상 갱신해줘야할까요?

2022-11-15 14:58 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
> +            this.records.add(TurnRecord(turn + 1, turnRecord))
`+1`은 무엇을 뜻하는걸까요~?

2022-11-15 14:58 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
>              .map { it.car }
우승자를 가지고 오는 로직은 `TurnRecord`에 있어도 되지 않을까요?

2022-11-15 14:58 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/carRacing/dto/CarRecord.kt
> +package racingcar.domain.carRacing.dto
`CarRecord`가 `dto`인 이유가 궁금합니다.

2022-11-15 14:58 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/carRacing/dto/TurnRecord.kt
> +package racingcar.domain.carRacing.dto
`TurnRecord`가 `dto`인 이유가 궁금합니다.

2022-11-15 14:58 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/carRacing/dto/CarRacingResult.kt
> +package racingcar.domain.carRacing.dto
도메인 패키지에 `dto` 패키지가 있는지 궁금해요!

2022-11-19 02:52 UTC, dajeong commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
>      private val turnCount: Int,
처음엔 재사용할 목적으로 가지고 있게하였는데
start(), result() 함수로 나눠지면서 가지면 안될것 같아요!

2022-11-20 11:34 UTC, dajeong commented on src/main/kotlin/racingcar/domain/carRacing/dto/CarRecord.kt
> +package racingcar.domain.carRacing.dto
요 애플리케이션에서는 출력을 위한 데이터를 담고 있는 역할만해서 DTO로 분류하였어요. 도메인 클래스 라고 생각하시는걸까요?

2022-11-20 11:34 UTC, dajeong commented on src/main/kotlin/racingcar/domain/carRacing/dto/TurnRecord.kt
> +package racingcar.domain.carRacing.dto
위와 동일합니다.

2022-11-20 11:35 UTC, dajeong commented on src/main/kotlin/racingcar/domain/carRacing/dto/CarRacingResult.kt
> +package racingcar.domain.carRacing.dto
제가 잘 몰라서 그러는데 dto 를 패키지로 보통 나누긴하는지 궁금합니다.

2022-11-20 11:35 UTC, dajeong commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
> +            this.records.add(TurnRecord(turn + 1, turnRecord))
의미 있는 메서드로 분리하도록 하겠습니다~!

2022-11-20 13:52 UTC, dajeong commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
>      private var maxDistance = 0
마지막에 탐색하는걸 제외하려고 매번 갱신했는데
결과 생성시 구하는것도 가능할것 같아요~

2022-11-20 14:00 UTC, dajeong commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
>              .map { it.car }
TurnRecord는 각 턴마다 기록을 저장해놓은 객체인데요~
마지막 record에서 우승자를 가지고오고 있는데 요 로직이 TurnRecord에 들어가는게 잘 이해가안갑니다 ㅠ

2022-11-20 16:11 UTC, hyoungjune-kurly commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
>              .map { it.car }
턴마다 레코드를 기록한다면, 마지막 턴이나 현재 턴에 대해서 기록을 가지고 오는 메서드를 만들 수 있지 않을까 했습니다. 왜냐하면 마지막 기록을 가지고 carRacing 도메인에서 직접 우승자에 대한 결과를 만들어 버리면 CarRacing에 기록에 대한 책임까지 주는게 아닐까요?

2022-11-20 16:12 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
>              .map { it.car }
턴마다 레코드를 기록한다면, 마지막 턴이나 현재 턴에 대해서 기록을 가지고 오는 메서드를 만들 수 있지 않을까 했습니다. 왜냐하면 마지막 기록을 가지고 carRacing 도메인에서 직접 우승자에 대한 결과를 만들어 버리면 CarRacing에 기록에 대한 책임까지 주는게 아닐까요?

2022-11-20 16:16 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/carRacing/dto/CarRecord.kt
> +package racingcar.domain.carRacing.dto
네! 기록을 위한 클래스도 하나의 도메인 클래스가 된다고 생각했어요.

2022-11-20 16:23 UTC, Flamme1004K commented on src/main/kotlin/racingcar/domain/carRacing/dto/CarRacingResult.kt
> +package racingcar.domain.carRacing.dto
저는 보통 DTO를 애플리케이션에다가 두고 있습니다. 
그 이유는 DTO는 말 그대로 도메인을 보내야할 곳에 맞게 형식을 바꿔 데이터 전송하기 위한 도구라고 생각하기 때문입니다. 변환 지점이 가장 자연스러운 계층인 애플리케이션에 두어 도메인과 뷰의 중간을 이어주기 위해서 사용합니다.

2022-11-20 16:40 UTC, dajeong commented on src/main/kotlin/racingcar/domain/carRacing/CarRacing.kt
>              .map { it.car }
아 우승자를 가지고 오는 로직이 아니라 현재 턴에대한 기록을 가져오는 메서드라는 말씀이시군요~!
이해했습니다 설명 감사합니다 😄

2022-11-20 16:49 UTC, dajeong commented on src/main/kotlin/racingcar/domain/carRacing/dto/CarRacingResult.kt
> +package racingcar.domain.carRacing.dto
설명 감사합니다 !

2022-11-20 16:49 UTC, dajeong commented on src/main/kotlin/racingcar/domain/carRacing/dto/CarRecord.kt
> +package racingcar.domain.carRacing.dto
설명 감사합니다!

2022-11-20 23:18 UTC, Flamme1004K approved these changes
안녕하세요!
피드백 반영 감사합니다! 그리고 그동안 자동차 경주 미션 고생하셨습니다! 🤩

피드백에 대해 긍정적으로 따라와 주시고, 결국에는 답을 찾아오시는 것을 보고 항상 뿌듯했습니다!
열심히 하시는 모습을 보고, 저도 자극받게 되었고, 저도 같이 성장할 수 있었습니다.😊

그동안 감사했습니다!🙇🏻 그리고 고생하셨습니다! 앞으로 있을 미션 화이팅입니다!🙌

2022-11-20 23:18 UTC, merged