🚀 4단계 - 자동차 경주(우승자)
next-step/kotlin-racingcar pull request #920
Opened 2022-11-21 18:25 UTC by shinseongsu

## 기능 구현 🚀 4단계 - 자동차 경주(우승자)

- [x] 각 자동차에 이름을 부여할 수 있다
  - [x] 자동차 이름은 5자를 초과할 수 없다.
  - [x] 빈값을 넣을 수 없다.
- [x] 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
- [x] 자동차 이름은 쉼표(,)를 기준으로 구분한다.
- [x] 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한 명 이상일 수 있다.

2022-11-22 10:57 UTC, ujusy commented
@shinseongsu 
안녕하세요 성수님 :) 

현재 ktlint가 깨지고있는 것 같아요. 다음과 같이 설정해서 커밋 전 lint적용이 잘 되었는지 확인할 수 있도록 설정해보면 어떨까요?
![image](https://user-images.githubusercontent.com/49120090/203297055-c97ea57c-c2c8-41ee-b4ec-ae2cc143cf04.png)

2022-11-22 12:39 UTC, shinseongsu commented
![스크린샷 2022-11-22 오후 9 37 48](https://user-images.githubusercontent.com/24979159/203315947-3c4ffb35-8b4e-471b-b084-2e7d3f368367.png)

린트에 맞게 다시 커밋했습니다
계속 린트에 발목이 잡히네요 죄송합니다... 😓

2022-11-22 17:05 UTC, ujusy requested changes
안녕하세요 , 성수님 👋

4단계 미션 진행하시느라 고생하셨습니다 :)
점점 코드가 깔끔해지는게 느껴집니다 👍 
고민해볼 몇 가지 코멘트를 남겼습니다.
확인 후 다시 요청 주세요! 💪

2022-11-22 17:05 UTC, ujusy commented on src/main/kotlin/racing/domain/CarName.kt
> +class CarName(
원시값 포장 👍

2022-11-22 17:05 UTC, ujusy commented on src/main/kotlin/racing/application/RacingGame.kt
> +    val carNames: List<String>
`List<CarName>` 으로 전달받아 애플리케이션과 도메인에서 VO만을 사용하게 해보는건 어떨까요?

2022-11-22 17:05 UTC, ujusy commented on src/main/kotlin/racing/domain/Position.kt
> +class Position(
Position VO 좋습니다 👍 
그런데 자동차의 위치에는 아무런 제약도 없는 것일까요?

2022-11-22 17:05 UTC, ujusy commented on src/main/kotlin/racing/ui/OutputView.kt
> +        cars.cars.forEach {
`cars.cars` 는 자동차들의 자동차들..? 이렇게 이해하기 어려운 코드가 될 것 같아요.
이런 자동차 명과 포지션들의 정보를 `cars` 가 생성하도록 하는건 어떨까요? 
예를 들면 `cars.roundInfo`와 같이 명확하게 표현할 수 있을 것 같아요. :) 
또 다른 쉬운 방법으로는 `Cars`의 `cars` 가 아닌 `value`등.. 다른 이름으로 변경하면 조금 더 직관적일 것 같아요!

2022-11-23 00:38 UTC, shinseongsu commented on src/main/kotlin/racing/application/RacingGame.kt
> +    val carNames: List<String>
넵 알겠습니다 👍

2022-11-23 00:39 UTC, shinseongsu commented on src/main/kotlin/racing/domain/Position.kt
> +class Position(
set을 금지시켜 직접 데이터를 넣는것을 막도록 하겠습니다 😄

2022-11-23 00:41 UTC, shinseongsu commented on src/main/kotlin/racing/ui/OutputView.kt
> +        cars.cars.forEach {
이름이 중복되어서 이해하기 어려운 코드가 되어 버렸네요
좀 더 이해하기 편하게 수정하도록하겠습니다

2022-11-23 01:17 UTC, shinseongsu commented
## 수정사항

- position private set으로 제약 두기
- 일급객체 이름 수정
- 입력값 List<CarName>으로 반환값 수정

2022-11-23 15:42 UTC, ujusy approved these changes
안녕하세요, 성수님! 👋

리뷰 반영 너무 잘해주셨어요 💯 
미션이 진행될수록 코드가 훨씬 깔끔해지는게 보입니다! 
자동차 경주 미션이 거의 끝나가는데요,
마지막 미션도 화이팅입니다 !! 💪💪

2022-11-23 15:42 UTC, ujusy commented on src/test/kotlin/racing/domain/CarNameTest.kt
> +            }
5글자를 초과할 경우와 반값일 경우 모두 RuntimeException을 던지기 때문에 메시지도 검증해보면 좋을 것 같아요 :)

2022-11-23 15:42 UTC, ujusy commented on src/test/kotlin/racing/domain/CarNameTest.kt
> +class CarNameTest : FreeSpec({
혹시 `FreeSpec` 으로 변경하신 이유가 있나요?! 단순 궁금증입니다!!

2022-11-23 15:43 UTC, merged

2022-11-23 23:21 UTC, shinseongsu commented on src/test/kotlin/racing/domain/CarNameTest.kt
> +            }
아하 그렇군요 예외 나오는지만 테스트 해서 무슨에러인지 체크가 명확하게 안되는군요 😄

2022-11-23 23:23 UTC, shinseongsu commented on src/test/kotlin/racing/domain/CarNameTest.kt
> +class CarNameTest : FreeSpec({
kotest에서 여러 spec들이 있어서 모두다 익숙하기에는 시간이 빠듯해서 실무에서 제일 많이 쓰는 spec으로 테스트를 진행하고 싶었습니다.
그래서 @ujusy 멘토님께도 여쭤보고 lotto 미션도 같이 진행중인데 여기 멘토님께서도 FreeSpec을 많이 쓰신다고 하셔서 여기 스펙으로 공부를 진행 하고 싶어서 변경하였습니다~