5단계 - 자동차 경주(리팩터링)
next-step/kotlin-racingcar pull request #930
Opened 2022-11-25 17:24 UTC by yuuuzzzin

## Summary
- 자동차 경주(리팩터링)를 구현하였습니다.
- 이전 리뷰를 반영했습니다.

## Describe changes

### 이전 리뷰 반영 내용
1. RacingCarGame에서 우승자를 판별하는 책임을 제거하고, Judges 클래스가 그 책임을 하도록 수정했습니다.
2. 매직 넘버 숫자 5를 상수로 변경했습니다.
3. Action이라는 자동차의 액션을 관리하는 클래스가 너무 과하게 책임을 분리해 만들어진 느낌이 들어 이를 제거하고, Car 클래스가 Action에 대한 타입과 그에 따른 동작을 할 수 있도록 수정하였습니다.
4. 불필요한 함수 분리를 제거하고 이를 주생성자로 받도록 하였습니다. (게임에 대한 정보를 받아 게임을 시작한다는 흐름상 더 자연스러운 것 같았습니다 !)

### 새로 구현한 내용
- 리팩터링 요구사항인 MVC 패턴에 맞게 패키지를 분리하였습니다.
- 책임을 적절히 분배하려 했고, 과도하게 분리한 부분은 수정하였습니다.

-> 이를 통해 더 적절한 테스트 코드를 구성할 수 있었습니다 ! 🙇‍♀️
1. CarTest : 액션을 행하는 주체로서 액션 타입에 따라 전진하는지, 멈춰 있는지 테스트
2. RacingCarTest : 게임을 진행하는 주체로서 게임 진행과 관련된 테스트
3. JudgesTest : 우승자를 선정하는 심판으로서 우승자 선정에 대한 테스트

## 남겨주신 리뷰에 대한 생각

> 만약 아래와 같이 이름을 5글자 초과하는 객체를 만들게 된다면 어떻게 될까요?
> 
> ```kotlin
> Car(name = "가나다라마바사아")
> ```
> 
> 그리고 이 것을 방지하려면 어떻게 하면 좋을까요?

- 이전 리뷰에서 위와 같이 남겨주셨는데, 입력 조건이 충족되는지는 이미 InputView에서 자동차 이름이 5자를 초과할 시에 Exception을 던지고 있어 `이름이 5글자 초과하는 객체`가 만들어질 일이 없기 때문에 저는 **추가로 방지하지 않아도 괜찮지 않을까** 하는 의견입니다 !
- 회원가입 시 아이디 비밀번호 조건을 확인하는 상황과 비슷하다고 생각했는데, 조건이 충족하는지를 입력받는 곳에서 확인하는 것이 회원 정보 객체 내부에서 확인하는 것 보다 더 자연스럽다고 생각하여 InputView에서 검사하게 되었습니다 !

------------------------
현석님 덕분에 어떤 것들을 고려하면서 코드를 짜야하는지를 배울 수 있었던 것 같습니다 🙏 
그동안 PR 봐주셔서 감사했습니다 🙂

2022-11-26 12:16 UTC, BeokBeok requested changes
이전 단계 피드백과 자동차 경주(리팩터링) 미션하시느라 고생하셨습니다. 👍 
구조를 잘 잡아주신 덕분에, 이번 미션에서 드릴 피드백이 적네요. 💯 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2022-11-26 12:16 UTC, BeokBeok commented on src/main/kotlin/racingcar/domain/RacingCarGame.kt
> +import racingcar.view.ResultView
프로그래밍 요구사항 중에서, 아래와 같은 내용이 있습니다.
> domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현한다.

위 요구사항을 준수해보면 어떨까요?

2022-11-26 12:16 UTC, BeokBeok commented on src/main/kotlin/racingcar/domain/RacingCarGame.kt
> +class RacingCarGame(
RacingCarGame 클래스를 잘 만들어주셨네요.
하지만 RacingCarGame 클래스는 게임에 대한 전반에 대한 책임을 가지고 있는 것으로 보여요. (게임 시작, 결과 보기, 우승자 보여주기 등)
그래서 RacingCarGame 클래스는 domain이 아닌 컨트롤러의 느낌이 들기도 해요.
RacingCarGame 클래스를 하나의 책임만 갖도록 개선해보면 어떨까요?

2022-11-26 12:27 UTC, BeokBeok commented
> 이전 리뷰에서 위와 같이 남겨주셨는데, 입력 조건이 충족되는지는 이미 InputView에서 자동차 이름이 5자를 초과할 시에 Exception을 던지고 있어 이름이 5글자 초과하는 객체가 만들어질 일이 없기 때문에 저는 추가로 방지하지 않아도 괜찮지 않을까 하는 의견입니다 !

A. 유진님이 말씀하신대로, InputView에서 검증을 하고 있으니 지금 미션에서는 문제가 되지 않습니다.
하지만, 이름을 관리하는 주체가 어디인지 고민해보시면 좋을 것 같아요.
지금은 단순히 이름이 5글자 초과하지 않도록 하는 요구사항이 있지만, 이 요구사항이 추가가 되거나 변경이 된다면 어떻게 될까요?
지금과 같은 구조라면 InputView를 변경해야 합니다.
자동차 이름에만 영향이 가도록 변경이 되어야 하지만, InputView를 변경하게 되므로 자동차 이름 뿐만 아니라 다른 Input 조건에도 영향을 미치게 될 가능성이 높습니다.

추가로 테스트 코드는 비즈니스 검증을 하는 목적도 있지만, 문서화의 목적도 있습니다.
자동차 이름 유효성 체크를 InputView에서 하게 되면, 정작 자동차를 관리하는 Car 클래스에는 자동차 이름과 관련된 테스트 코드를 작성할 수 없습니다.
동료가 테스트 코드만 보았을 때, 이 클래스에는 어떤 비즈니스 로직을 가지고 있는지 한눈에 파악하기 쉬워지기도 합니다. 😅

2022-11-26 12:32 UTC, BeokBeok commented
> 회원가입 시 아이디 비밀번호 조건을 확인하는 상황과 비슷하다고 생각했는데, 조건이 충족하는지를 입력받는 곳에서 확인하는 것이 회원 정보 객체 내부에서 확인하는 것 보다 더 자연스럽다고 생각하여 InputView에서 검사하게 되었습니다 !

A. 아이디와 비밀번호의 조건의 상황과 비슷하게 보실 수도 있습니다.
오히려 객체 내부에서 확인하지 않고, 입력하는 곳에서 확인하기 때문에 예외처리가 많이 생기게 됩니다.
그렇기 때문에, 대부분 로그인 화면개발 시 관련 코드가 굉장히 복잡하고 예외처리가 많습니다. 😅 
추후에 일급객체에 대해서 학습해보시고 나면, 아마 지금 제가 드린 말씀이 조금은 공감이 되지 않을까 싶습니다. 🙏

2022-11-26 12:34 UTC, BeokBeok commented
텍스트로 적어서 아마 이해가 잘 안되실 것 같습니다.
만약 이해가 잘 안되신다면 편하게 DM주세요! 😄

2022-11-27 02:04 UTC, BeokBeok commented
> 각 자동차에 이름을 부여할 수 있다. 자동차 이름은 5자를 초과할 수 없다.

위의 로직이 View의 로직인지 Domain의 로직인지 고민해보시면 좋을 것 같아요! 🙏

2022-12-03 12:40 UTC, yuuuzzzin commented on src/main/kotlin/racingcar/domain/RacingCarGame.kt
> +class RacingCarGame(
그렇네요ㅠㅠ 완전히 컨트롤러의 역할을 하고 있는 것 같아
[9165afe](https://github.com/next-step/kotlin-racingcar/pull/930/commits/9165afed4eee6f3d35811b8a2a26eeac428fbbdf), [560e984](https://github.com/next-step/kotlin-racingcar/pull/930/commits/560e984e6dc36ad6626d49cf89f34560040fdc43), [560e984](https://github.com/next-step/kotlin-racingcar/pull/930/commits/560e984e6dc36ad6626d49cf89f34560040fdc43)에서 Race 클래스를 새로 생성해 레이스를 진행하는 책임을 갖도록 했고, 전반적인 게임 진행은 컨트롤러인 CarRacingGameApplication에서 담당하도록 수정하였습니다 !

2022-12-03 12:40 UTC, yuuuzzzin commented on src/main/kotlin/racingcar/domain/RacingCarGame.kt
> +import racingcar.view.ResultView
아래 코멘트 반영하면서 요구사항에 맞게 수정하였습니다 !

2022-12-03 13:10 UTC, yuuuzzzin commented
텍스트였지만 상세하게 코멘트 남겨주셔서 이해가 되었습니다 ! 
처음엔 이해가 잘 되지 않았는데, 이런 저런 케이스와 고민해보면 좋을 점도 같이 언급해주셔서 공감이 되었던 것 같습니다 🙏 너무너무 감사합니다 ㅎㅎ

[e8e1154](https://github.com/next-step/kotlin-racingcar/pull/930/commits/e8e1154c9f3b04bf8b9750fdbc4cf1a2ae253236), [884deb5](https://github.com/next-step/kotlin-racingcar/pull/930/commits/884deb54b30fcbb5a2c4e9ad6e8d51b24541b28f)에서 차의 이름을 관리하는 Name클래스를 생성하고, 클래스 내부에서 유효성 체크를 하도록 수정했습니다 !

+) 추가로 질문드릴 점이 있습니다..!
Name클래스 안에서 유효성 체크를 하는 부분이 companion object block 안에 포함이 되어야 할지, 아니면 init block에서 체크하는 것이 더 바람직한지 고민이 되었는데..🤔 리뷰어님은 이러한 유효성 체크를 해야하는 상황에서 companion object를 이용하시는지, 클래스 내의 init 을 이용하시는지 궁금합니다 !

2022-12-03 13:52 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
유진님과 미션하면서 저 또한 성장하게 된 것 같습니다. 😄 
좋은 개발자가 되기 위한 소중한 경험이 되었길 바랍니다. 💪

2022-12-03 13:52 UTC, merged

2022-12-03 13:54 UTC, BeokBeok commented
> Name클래스 안에서 유효성 체크를 하는 부분이 companion object block 안에 포함이 되어야 할지, 아니면 init block에서 체크하는 것이 더 바람직한지 고민이 되었는데..🤔 리뷰어님은 이러한 유효성 체크를 해야하는 상황에서 companion object를 이용하시는지, 클래스 내의 init 을 이용하시는지 궁금합니다 !

A. 유효성체크는 init 블록에서 해주시는 것이 좋습니다. 😄 
ref. https://kotlinlang.org/docs/inline-classes.html#members

2022-12-03 15:12 UTC, yuuuzzzin commented
오호 참고할만한 문서까지 감사합니다 👍
항상 정성스러운 코멘트 남겨주셔서 도움이 많이 되었습니다 🙂
그동안 감사했습니다 현석님 😭 👍