refactor : Cars 로 우승자구하는 로직 이동
next-step/kotlin-racingcar pull request #952
Opened 2022-12-18 09:23 UTC by mia6111

안녕하세요, PR 요청 드립니다

2022-12-19 12:42 UTC, ddaaac requested changes
안녕하세요 미현님 👋 

5단계 미션까지 구현 잘 해주셨어요 👍 

몇 가지 코멘트를 남겼으니 확인 부탁드립니다~

2022-12-19 12:42 UTC, ddaaac commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    }
지금 로직도 훌륭하지만 조금 더 극단적인 훈련을 해볼 수 있을 것 같아요. getter 없이 이 로직을 작성할 수 있을까요?
Car는 currentPosition이라는 상태를 갖고 있는데요, 외부에서 currentPosition이라는 상태를 모른채로 우승자를 구할 수 있다면 객체가 온전히 캡슐화되었다고 얘기할 수 있을 것 같습니다.
isWin, isDraw 등의 함수가 있다면 getter 없이도 우승자를 구해볼 수 있을 것 같습니다. 한 번 도전해보셔도 좋을 것 같아요!

2022-12-19 12:42 UTC, ddaaac commented on src/test/kotlin/racingcar/domain/CarsTest.kt
> +        val result = cars.move(FixedNumberProvider())
FixedNumberProvider라는 이름을 보면 전진을 해야할지 하지 말아야할지 한 눈에 읽기 어려워보여요!

의미있는 이름을 부여해보는 건 어떨까요?

+) 이름을 부여해보면 느끼시겠지만 오직 전진하는 경우에 대한 테스트만 있습니다. 전진하지 않는 경우에 대한 테스트도 있으면 좋을 것 같아요 :)

2022-12-19 12:42 UTC, ddaaac commented on src/test/kotlin/racingcar/domain/CarsTest.kt
> +        cars.getWinnersOfGame() shouldContainExactly listOf("test2")
우승자 구하는 테스트 잘 작성해주셨어요!

여기서는 `getWinnersOfGame`의 반환 타입에 대해서 얘기해볼 수 있을 것 같아요. 만약 Car에 id와 같은 프로퍼티들이 추가되고, id와 이름을 모두 View에서 사용해야한다면 여기 코드가 어떻게 수정될까요?
지금의 코드는 콘솔 View와 밀접한 관계를 갖는 코드라고도 얘기할 수 있을 것 같아요. 여기서 winners를 반환하는만큼 List<Car> 또는 Cars를 반환하고 View에서 필요한 값들을 가져다 사용하는 건 어떨까요?

2022-12-19 12:42 UTC, ddaaac commented on src/test/kotlin/racingcar/domain/CarsTest.kt
> +        )
position을 0이 아닌 값을 생성자로 받을 수 있게 구현해주셨어요. 이를 활용해서 여기 테스트에 다양한 경우를 넣어볼 수 있을 것 같습니다 😄

2022-12-31 07:36 UTC, mia6111 commented on src/test/kotlin/racingcar/domain/CarsTest.kt
> +        cars.getWinnersOfGame() shouldContainExactly listOf("test2")
아.. 처음에 뷰에서 Car 를 직접 접근하지 않게 하려고 했는데, 괜히 그렇게 했네요

2022-12-31 07:37 UTC, mia6111 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    }
"차는 위치 순으로 비교 가능하다"고 가정하고 Comparable 을 구현하도록 변경해봤습니다

2022-12-31 07:38 UTC, mia6111 commented
안녕하세요 리뷰반영했습니다 :) 연말 따뜻하게 보내세요~

2023-01-01 13:38 UTC, ddaaac approved these changes
안녕하세요 미현님 👋 

리뷰 반영 잘 해주셨습니다~ 

자동차 게임 미션 진행하시는 동안 정말 고생 많으셨습니다!
다른 미션들도 모두 파이팅해서 완주하세요 💪 💪 💪

2023-01-01 13:38 UTC, ddaaac commented on src/main/kotlin/racingcar/domain/Cars.kt
> +        val winner = cars.sorted().first()
```suggestion
        val winner = cars.minOf { it }
```
Comparable을 구현할거라면 조금 더 적극적으로 사용해봐도 좋을 것 같습니다 😄

2023-01-01 13:38 UTC, ddaaac commented on src/test/kotlin/racingcar/domain/FixedNumberProvider.kt
> +class NeverMoveConditionProvider : FixedNumberProvider(1)
상속구조를 사용해야할 이유가 있을까요? 특별한 이유가 없다면 각자 구현해도 좋을 것 같아요 😄

2023-01-01 13:38 UTC, merged